; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: clang -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define i16 @bswapi16(i16 %a) {
; CHECK-LABEL: bswapi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 258
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call i16 @llvm.bswap.i16(i16 %a)
  ret i16 %res
}

define i32 @bswapi32(i32 %a) {
; CHECK-LABEL: bswapi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1020408
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call i32 @llvm.bswap.i32(i32 %a)
  ret i32 %res
}

define i64 @bswapi64(i64 %a) {
; CHECK-LABEL: bswapi64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x102040810204080
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call i64 @llvm.bswap.i64(i64 %a)
  ret i64 %res
}

define <2 x i16> @bswapv2i16(<2 x i16> %a) {
; CHECK-LABEL: bswapv2i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x4080102
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call <2 x i16> @llvm.bswap.v2i16(<2 x i16> %a)
  ret <2 x i16> %res
}

define <4 x i16> @bswapv4i16(<4 x i16> %a) {
; CHECK-LABEL: bswapv4i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x4080102004080102
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call <4 x i16> @llvm.bswap.v4i16(<4 x i16> %a)
  ret <4 x i16> %res
}

define <2 x i32> @bswapv2i32(<2 x i32> %a) {
; CHECK-LABEL: bswapv2i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1020408001020408
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call <2 x i32> @llvm.bswap.v2i32(<2 x i32> %a)
  ret <2 x i32> %res
}

define <2 x i64> @bswapv2i64(<2 x i64> %a) {
; CHECK-LABEL: bswapv2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x102040810204080
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x102040810204080
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call <2 x i64> @llvm.bswap.v2i64(<2 x i64> %a)
  ret <2 x i64> %res
}

define <4 x i32> @bswapv4i32(<4 x i32> %a) {
; CHECK-LABEL: bswapv4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1020408001020408
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1020408001020408
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call <4 x i32> @llvm.bswap.v4i32(<4 x i32> %a)
  ret <4 x i32> %res
}

define <4 x i64> @bswapv4i64(<4 x i64> %a) {
; CHECK-LABEL: bswapv4i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r2 = $r2, 0x102040810204080
; CHECK-NEXT:    sbmm8 $r3 = $r3, 0x102040810204080
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x102040810204080
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x102040810204080
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %res = call <4 x i64> @llvm.bswap.v4i64(<4 x i64> %a)
  ret <4 x i64> %res
}
declare i16 @llvm.bswap.i16(i16)
declare i32 @llvm.bswap.i32(i32)
declare i64 @llvm.bswap.i64(i64)
declare <2 x i16> @llvm.bswap.v2i16(<2 x i16>)
declare <2 x i32> @llvm.bswap.v2i32(<2 x i32>)
declare <2 x i64> @llvm.bswap.v2i64(<2 x i64>)
declare <4 x i16> @llvm.bswap.v4i16(<4 x i16>)
declare <4 x i32> @llvm.bswap.v4i32(<4 x i32>)
declare <4 x i64> @llvm.bswap.v4i64(<4 x i64>)
