; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -o - %s | FileCheck %s --check-prefixes=CHECK,CV1
; RUN: llc -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefixes=CHECK,CV2
; RUN: clang -march=kv3-1 -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define i8 @cttzi8(i8 %a) {
; CHECK-LABEL: cttzi8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    iorw $r0 = $r0, 256
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    ctzw $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %res = call i8 @llvm.cttz.i8(i8 %a)
  ret i8 %res
}

define i16 @cttzi16(i16 %a) {
; CHECK-LABEL: cttzi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    iorw $r0 = $r0, 0x10000
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    ctzw $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %res = call i16 @llvm.cttz.i16(i16 %a)
  ret i16 %res
}

define i32 @ctzw(i32 %a) {
; CHECK-LABEL: ctzw:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ctzw $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call i32 @llvm.cttz.i32(i32 %a)
  ret i32 %res
}

define i64 @ctzd(i64 %a) {
; CHECK-LABEL: ctzd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ctzd $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call i64 @llvm.cttz.i64(i64 %a)
  ret i64 %res
}

define <2 x i8> @cttzv2i8(<2 x i8> %a) {
; CHECK-LABEL: cttzv2i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x200000001
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    iord $r0 = $r0, 256.@
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    ctzwp $r0 = $r0
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 3)
  %res = call <2 x i8> @llvm.cttz.v2i8(<2 x i8> %a)
  ret <2 x i8> %res
}

define <2 x i16> @cttzv2i16(<2 x i16> %a) {
; CHECK-LABEL: cttzv2i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x80400000201
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    iord $r0 = $r0, 0x10000.@
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    ctzwp $r0 = $r0
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x100001
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 3)
  %res = call <2 x i16> @llvm.cttz.v2i16(<2 x i16> %a)
  ret <2 x i16> %res
}

define <2 x i32> @ctzwp(<2 x i32> %a) {
; CHECK-LABEL: ctzwp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ctzwp $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call <2 x i32> @llvm.cttz.v2i32(<2 x i32> %a)
  ret <2 x i32> %res
}

define <2 x i64> @cttzv2i64(<2 x i64> %a) {
; CHECK-LABEL: cttzv2i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ctzd $r0 = $r0
; CHECK-NEXT:    ctzd $r1 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call <2 x i64> @llvm.cttz.v2i64(<2 x i64> %a)
  ret <2 x i64> %res
}

define <4 x i8> @cttzv4i8(<4 x i8> %a) {
; CHECK-LABEL: cttzv4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x200000001
; CHECK-NEXT:    sbmm8 $r1 = $r0, 0x800000004
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    iord $r0 = $r0, 256.@
; CHECK-NEXT:    iord $r1 = $r1, 256.@
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    ctzwp $r0 = $r0
; CHECK-NEXT:    ctzwp $r1 = $r1
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 4)
  %res = call <4 x i8> @llvm.cttz.v4i8(<4 x i8> %a)
  ret <4 x i8> %res
}

define <4 x i16> @cttzv4i16(<4 x i16> %a) {
; CHECK-LABEL: cttzv4i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x80400000201
; CHECK-NEXT:    sbmm8 $r1 = $r0, 0x804000002010
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    iord $r0 = $r0, 0x10000.@
; CHECK-NEXT:    iord $r1 = $r1, 0x10000.@
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    ctzwp $r0 = $r0
; CHECK-NEXT:    ctzwp $r1 = $r1
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x100001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x100001
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 4)
  %res = call <4 x i16> @llvm.cttz.v4i16(<4 x i16> %a)
  ret <4 x i16> %res
}

define <4 x i32> @cttzwq(<4 x i32> %a) {
; CHECK-LABEL: cttzwq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ctzwp $r0 = $r0
; CHECK-NEXT:    ctzwp $r1 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call <4 x i32> @llvm.cttz.v4i32(<4 x i32> %a)
  ret <4 x i32> %res
}

define <4 x i64> @cttzv4i64(<4 x i64> %a) {
; CHECK-LABEL: cttzv4i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ctzd $r0 = $r0
; CHECK-NEXT:    ctzd $r1 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    ctzd $r2 = $r2
; CHECK-NEXT:    ctzd $r3 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %res = call <4 x i64> @llvm.cttz.v4i64(<4 x i64> %a)
  ret <4 x i64> %res
}

define <8 x i8> @cttzv8i8(<8 x i8> %a) {
; CV1-LABEL: cttzv8i8:
; CV1:       # %bb.0:
; CV1-NEXT:    sbmm8 $r1 = $r0, 0x8000000040
; CV1-NEXT:    sbmm8 $r2 = $r0, 0x2000000010
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    sbmm8 $r0 = $r0, 0x200000001
; CV1-NEXT:    iord $r1 = $r1, 256.@
; CV1-NEXT:    sbmm8 $r3 = $r0, 0x800000004
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    iord $r0 = $r0, 256.@
; CV1-NEXT:    ctzwp $r1 = $r1
; CV1-NEXT:    iord $r2 = $r2, 256.@
; CV1-NEXT:    iord $r3 = $r3, 256.@
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    ctzwp $r2 = $r2
; CV1-NEXT:    ctzwp $r3 = $r3
; CV1-NEXT:    ;; # (end cycle 3)
; CV1-NEXT:    ctzwp $r0 = $r0
; CV1-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CV1-NEXT:    ;; # (end cycle 4)
; CV1-NEXT:    sbmm8 $r2 = $r2, 0x1001
; CV1-NEXT:    sbmm8 $r3 = $r3, 0x1001
; CV1-NEXT:    ;; # (end cycle 5)
; CV1-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CV1-NEXT:    insf $r2 = $r1, 31, 16
; CV1-NEXT:    ;; # (end cycle 6)
; CV1-NEXT:    insf $r0 = $r3, 31, 16
; CV1-NEXT:    ;; # (end cycle 7)
; CV1-NEXT:    insf $r0 = $r2, 63, 32
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 8)
;
; CV2-LABEL: cttzv8i8:
; CV2:       # %bb.0:
; CV2-NEXT:    sbmm8 $r1 = $r0, 0x8000000040
; CV2-NEXT:    sbmm8 $r2 = $r0, 0x2000000010
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    sbmm8 $r0 = $r0, 0x200000001
; CV2-NEXT:    iord $r1 = $r1, 256.@
; CV2-NEXT:    sbmm8 $r3 = $r0, 0x800000004
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    iord $r0 = $r0, 256.@
; CV2-NEXT:    ctzwp $r1 = $r1
; CV2-NEXT:    iord $r2 = $r2, 256.@
; CV2-NEXT:    iord $r3 = $r3, 256.@
; CV2-NEXT:    ;; # (end cycle 2)
; CV2-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CV2-NEXT:    ctzwp $r2 = $r2
; CV2-NEXT:    ctzwp $r3 = $r3
; CV2-NEXT:    ;; # (end cycle 3)
; CV2-NEXT:    ctzwp $r0 = $r0
; CV2-NEXT:    sbmm8 $r2 = $r2, 0x1001
; CV2-NEXT:    sbmm8 $r3 = $r3, 0x1001
; CV2-NEXT:    ;; # (end cycle 4)
; CV2-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CV2-NEXT:    insf $r2 = $r1, 31, 16
; CV2-NEXT:    ;; # (end cycle 5)
; CV2-NEXT:    insf $r0 = $r3, 31, 16
; CV2-NEXT:    ;; # (end cycle 6)
; CV2-NEXT:    insf $r0 = $r2, 63, 32
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 7)
  %res = call <8 x i8> @llvm.cttz.v8i8(<8 x i8> %a)
  ret <8 x i8> %res
}

define <8 x i16> @cttzv8i16(<8 x i16> %a) {
; CV1-LABEL: cttzv8i16:
; CV1:       # %bb.0:
; CV1-NEXT:    sbmm8 $r0 = $r0, 0x80400000201
; CV1-NEXT:    sbmm8 $r2 = $r0, 0x804000002010
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    sbmm8 $r1 = $r1, 0x80400000201
; CV1-NEXT:    iord $r2 = $r2, 0x10000.@
; CV1-NEXT:    sbmm8 $r3 = $r1, 0x804000002010
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    iord $r0 = $r0, 0x10000.@
; CV1-NEXT:    iord $r1 = $r1, 0x10000.@
; CV1-NEXT:    ctzwp $r2 = $r2
; CV1-NEXT:    iord $r3 = $r3, 0x10000.@
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    ctzwp $r0 = $r0
; CV1-NEXT:    ctzwp $r3 = $r3
; CV1-NEXT:    ;; # (end cycle 3)
; CV1-NEXT:    ctzwp $r1 = $r1
; CV1-NEXT:    sbmm8 $r2 = $r2, 0x100001
; CV1-NEXT:    ;; # (end cycle 4)
; CV1-NEXT:    sbmm8 $r0 = $r0, 0x100001
; CV1-NEXT:    sbmm8 $r3 = $r3, 0x100001
; CV1-NEXT:    ;; # (end cycle 5)
; CV1-NEXT:    insf $r0 = $r2, 63, 32
; CV1-NEXT:    sbmm8 $r1 = $r1, 0x100001
; CV1-NEXT:    ;; # (end cycle 6)
; CV1-NEXT:    insf $r1 = $r3, 63, 32
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 7)
;
; CV2-LABEL: cttzv8i16:
; CV2:       # %bb.0:
; CV2-NEXT:    sbmm8 $r0 = $r0, 0x80400000201
; CV2-NEXT:    sbmm8 $r2 = $r0, 0x804000002010
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    sbmm8 $r1 = $r1, 0x80400000201
; CV2-NEXT:    iord $r2 = $r2, 0x10000.@
; CV2-NEXT:    sbmm8 $r3 = $r1, 0x804000002010
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    iord $r0 = $r0, 0x10000.@
; CV2-NEXT:    iord $r1 = $r1, 0x10000.@
; CV2-NEXT:    ctzwp $r2 = $r2
; CV2-NEXT:    iord $r3 = $r3, 0x10000.@
; CV2-NEXT:    ;; # (end cycle 2)
; CV2-NEXT:    ctzwp $r0 = $r0
; CV2-NEXT:    sbmm8 $r2 = $r2, 0x100001
; CV2-NEXT:    ctzwp $r3 = $r3
; CV2-NEXT:    ;; # (end cycle 3)
; CV2-NEXT:    sbmm8 $r0 = $r0, 0x100001
; CV2-NEXT:    ctzwp $r1 = $r1
; CV2-NEXT:    sbmm8 $r3 = $r3, 0x100001
; CV2-NEXT:    ;; # (end cycle 4)
; CV2-NEXT:    insf $r0 = $r2, 63, 32
; CV2-NEXT:    sbmm8 $r1 = $r1, 0x100001
; CV2-NEXT:    ;; # (end cycle 5)
; CV2-NEXT:    insf $r1 = $r3, 63, 32
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 6)
  %res = call <8 x i16> @llvm.cttz.v8i16(<8 x i16> %a)
  ret <8 x i16> %res
}

define <8 x i32> @cttzwo(<8 x i32> %a) {
; CHECK-LABEL: cttzwo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ctzwp $r0 = $r0
; CHECK-NEXT:    ctzwp $r1 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    ctzwp $r2 = $r2
; CHECK-NEXT:    ctzwp $r3 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %res = call <8 x i32> @llvm.cttz.v8i32(<8 x i32> %a)
  ret <8 x i32> %res
}

declare i8 @llvm.cttz.i8(i8)
declare i16 @llvm.cttz.i16(i16)
declare i32 @llvm.cttz.i32(i32)
declare i64 @llvm.cttz.i64(i64)
declare <2 x i8> @llvm.cttz.v2i8(<2 x i8>)
declare <2 x i16> @llvm.cttz.v2i16(<2 x i16>)
declare <2 x i32> @llvm.cttz.v2i32(<2 x i32>)
declare <2 x i64> @llvm.cttz.v2i64(<2 x i64>)
declare <4 x i8> @llvm.cttz.v4i8(<4 x i8>)
declare <4 x i16> @llvm.cttz.v4i16(<4 x i16>)
declare <4 x i32> @llvm.cttz.v4i32(<4 x i32>)
declare <4 x i64> @llvm.cttz.v4i64(<4 x i64>)
declare <8 x i8> @llvm.cttz.v8i8(<8 x i8>)
declare <8 x i16> @llvm.cttz.v8i16(<8 x i16>)
declare <8 x i32> @llvm.cttz.v8i32(<8 x i32>)
