; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -o - %s -mtriple=kvx-kalray-cos | FileCheck %s --check-prefixes=ALL,KV1
; RUN: llc -mcpu=kv3-2 -o - %s -mtriple=kvx-kalray-cos | FileCheck %s --check-prefixes=ALL,KV2
; RUN: clang -march=kv3-1 -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define float @ffmaw(float %a, float %b, float %c) {
; ALL-LABEL: ffmaw:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmaw $r2 = $r0, $r1
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    copyd $r0 = $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
  %res = call float @llvm.fma.f32(float %a, float %b, float %c)
  ret float %res
}

define float @ffmaw_i(float %a, float %b) {
; KV1-LABEL: ffmaw_i:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmaw $r1 = $r0, 0x3dcccccd
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    copyd $r0 = $r1
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 4)
;
; KV2-LABEL: ffmaw_i:
; KV2:       # %bb.0:
; KV2-NEXT:    make $r2 = 0x3dcccccd
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmaw $r1 = $r0, $r2
; KV2-NEXT:    ;; # (end cycle 1)
; KV2-NEXT:    copyd $r0 = $r1
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 5)
  %res = call float @llvm.fma.f32(float %a, float 0x3FB99999A0000000, float %b)
  ret float %res
}

define double @ffmad(double %a, double %b, double %c) {
; ALL-LABEL: ffmad:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmad $r2 = $r0, $r1
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    copyd $r0 = $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
  %res = call double @llvm.fma.f64(double %a, double %b, double %c)
  ret double %res
}

define double @ffmad_i(double %a, double %b) {
; KV1-LABEL: ffmad_i:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmad $r1 = $r0, 0x3fb99999a0000000
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    copyd $r0 = $r1
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 4)
;
; KV2-LABEL: ffmad_i:
; KV2:       # %bb.0:
; KV2-NEXT:    make $r2 = 0x3fb99999a0000000
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmad $r1 = $r0, $r2
; KV2-NEXT:    ;; # (end cycle 1)
; KV2-NEXT:    copyd $r0 = $r1
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 5)
  %res = call double @llvm.fma.f64(double %a, double 0x3FB99999A0000000, double %b)
  ret double %res
}

define <2 x float> @ffmawp(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; ALL-LABEL: ffmawp:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmawp $r2 = $r0, $r1
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    copyd $r0 = $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
  %res = call <2 x float> @llvm.fma.v2f32(<2 x float> %a, <2 x float> %b, <2 x float> %c)
  ret <2 x float> %res
}

define half @ffmaf16(half %a, half %b, half %c) {
; KV1-LABEL: ffmaf16:
; KV1:       # %bb.0:
; KV1-NEXT:    zxhd $r1 = $r1
; KV1-NEXT:    zxhd $r3 = $r0
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    zxhd $r0 = $r2
; KV1-NEXT:    ;; # (end cycle 1)
; KV1-NEXT:    ffmahq $r0 = $r3, $r1
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 2)
;
; KV2-LABEL: ffmaf16:
; KV2:       # %bb.0:
; KV2-NEXT:    zxhd $r0 = $r2
; KV2-NEXT:    zxhd $r1 = $r1
; KV2-NEXT:    zxhd $r3 = $r0
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmahq $r0 = $r3, $r1
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
  %res = call half @llvm.fma.f16(half %a, half %b, half %c)
  ret half %res
}

define half @ffmahq_v1_rr(half %a, half %b, half %c) {
; KV1-LABEL: ffmahq_v1_rr:
; KV1:       # %bb.0:
; KV1-NEXT:    zxhd $r1 = $r1
; KV1-NEXT:    zxhd $r2 = $r2
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    zxhd $r0 = $r0
; KV1-NEXT:    ;; # (end cycle 1)
; KV1-NEXT:    ffmahq $r0 = $r1, $r2
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 2)
;
; KV2-LABEL: ffmahq_v1_rr:
; KV2:       # %bb.0:
; KV2-NEXT:    zxhd $r0 = $r0
; KV2-NEXT:    zxhd $r1 = $r1
; KV2-NEXT:    zxhd $r2 = $r2
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmahq $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
  %mul = fmul fast half %b, %c
  %add = fadd fast half %mul, %a
  ret half %add
}

define half @ffmahq_v1_ri(half %a, half %b) {
; KV1-LABEL: ffmahq_v1_ri:
; KV1:       # %bb.0:
; KV1-NEXT:    zxhd $r0 = $r0
; KV1-NEXT:    zxhd $r1 = $r1
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmahq $r0 = $r1, 0x4300
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: ffmahq_v1_ri:
; KV2:       # %bb.0:
; KV2-NEXT:    zxhd $r0 = $r0
; KV2-NEXT:    zxhd $r1 = $r1
; KV2-NEXT:    make $r2 = 0x4300
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmahq $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
  %mul = fmul fast half 3.5, %b
  %add = fadd fast half %a, %mul
  ret half %add
}

define <2 x half> @ffmahq1(<2 x half> %a, <2 x half> %b, <2 x half> %c) {
; ALL-LABEL: ffmahq1:
; ALL:       # %bb.0:
; ALL-NEXT:    zxwd $r0 = $r2
; ALL-NEXT:    zxwd $r1 = $r1
; ALL-NEXT:    zxwd $r3 = $r0
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    ffmahq $r0 = $r3, $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 1)
  %res = call <2 x half> @llvm.fma.v2f16(<2 x half> %a, <2 x half> %b, <2 x half> %c)
  ret <2 x half> %res
}

define <4 x half> @ffmahq(<4 x half> %a, <4 x half> %b, <4 x half> %c) {
; ALL-LABEL: ffmahq:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmahq $r2 = $r0, $r1
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    copyd $r0 = $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
  %res = call <4 x half> @llvm.fma.v4f16(<4 x half> %a, <4 x half> %b, <4 x half> %c)
  ret <4 x half> %res
}

define <2 x double> @ffmav2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c) {
; ALL-LABEL: ffmav2f64:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmad $r5 = $r1, $r3
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    ffmad $r4 = $r0, $r2
; ALL-NEXT:    ;; # (end cycle 1)
; ALL-NEXT:    copyd $r0 = $r4
; ALL-NEXT:    copyd $r1 = $r5
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 5)
  %res = call <2 x double> @llvm.fma.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c)
  ret <2 x double> %res
}

define float @fma32_not(float %a, float %b, float %c) {
; ALL-LABEL: fma32_not:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    fmulw $r1 = $r1, $r2
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    faddw $r0 = $r1, $r0
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
entry:
  %mul = fmul float %b, %c
  %add = fadd float %mul, %a
  ret float %add
}

define double @fma64_not(double %a, double %b, double %c) {
; ALL-LABEL: fma64_not:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    fmuld $r1 = $r1, $r2
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    faddd $r0 = $r1, $r0
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
entry:
  %mul = fmul double %b, %c
  %add = fadd double %mul, %a
  ret double %add
}

define float @fma32_rr(float %a, float %b, float %c) {
; ALL-LABEL: fma32_rr:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmaw $r0 = $r2, $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast float %c, %b
  %add = fadd fast float %mul, %a
  ret float %add
}

define double @fma64_rr(double %a, double %b, double %c)  {
; ALL-LABEL: fma64_rr:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmad $r0 = $r2, $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast double %c, %b
  %add = fadd fast double %mul, %a
  ret double %add
}

define float @fma32_neg(float %a, float %b, float %c) {
; ALL-LABEL: fma32_neg:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    fnegw $r2 = $r2
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    ffmaw $r2 = $r0, $r1
; ALL-NEXT:    ;; # (end cycle 1)
; ALL-NEXT:    copyd $r0 = $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 5)
entry:
  %mul = fmul fast float %a, %b
  %sub = fsub fast float %mul, %c
  ret float %sub
}

define double @fma64_neg(double %a, double %b, double %c) {
; ALL-LABEL: fma64_neg:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    fnegd $r2 = $r2
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    ffmad $r2 = $r0, $r1
; ALL-NEXT:    ;; # (end cycle 1)
; ALL-NEXT:    copyd $r0 = $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 5)
entry:
  %mul = fmul fast double %a, %b
  %sub = fsub fast double %mul, %c
  ret double %sub
}

define float @fma32_contract(float %a, float %b, float %c) {
; ALL-LABEL: fma32_contract:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmaw $r0 = $r2, $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul contract float %c, %b
  %add = fadd contract float %mul, %a
  ret float %add
}

define double @fma64_contract(double %a, double %b, double %c)  {
; ALL-LABEL: fma64_contract:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmad $r0 = $r2, $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul contract double %c, %b
  %add = fadd contract double %mul, %a
  ret double %add
}

define float @fms32_not(float %a, float %b, float %c) {
; ALL-LABEL: fms32_not:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    fmulw $r1 = $r1, $r2
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    fsbfw $r0 = $r1, $r0
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
entry:
  %mul = fmul float %b, %c
  %sub = fsub float %a, %mul
  ret float %sub
}

define double @fms64_not(double %a, double %b, double %c) {
; ALL-LABEL: fms64_not:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    fmuld $r1 = $r1, $r2
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    fsbfd $r0 = $r1, $r0
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
entry:
  %mul = fmul double %b, %c
  %sub = fsub double %a, %mul
  ret double %sub
}

define float @fms32_rr(float %a, float %b, float %c) {
; ALL-LABEL: fms32_rr:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmsw $r0 = $r1, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast float %c, %b
  %sub = fsub fast float %a, %mul
  ret float %sub
}

; We can't tell difference of fms or fma for immediates
define float @fms32_ri(float %a, float %b) {
; KV1-LABEL: fms32_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmaw $r0 = $r1, 0xc0600000
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 0)
;
; KV2-LABEL: fms32_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    make $r2 = 0xc0600000
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmaw $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast float 3.5, %b
  %sub = fsub fast float %a, %mul
  ret float %sub
}

; We can't tell difference of fms or fma for immediates
define float @fma32_ri(float %a, float %b) {
; KV1-LABEL: fma32_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmaw $r0 = $r1, 0x40600000
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 0)
;
; KV2-LABEL: fma32_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    make $r2 = 0x40600000
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmaw $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast float 3.5, %b
  %sub = fadd fast float %a, %mul
  ret float %sub
}


define double @fms64_rr(double %a, double %b, double %c)  {
; ALL-LABEL: fms64_rr:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmsd $r0 = $r1, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast double %c, %b
  %sub = fsub fast double %a, %mul
  ret double %sub
}

define double @fms64_ri(double %a, double %b)  {
; KV1-LABEL: fms64_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmad $r0 = $r1, 0xc00c000000000000
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 0)
;
; KV2-LABEL: fms64_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    make $r2 = 0xc00c000000000000
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmad $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast double %b, 3.5
  %sub = fsub fast double %a, %mul
  ret double %sub
}

define double @fma64_ri(double %a, double %b)  {
; KV1-LABEL: fma64_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmad $r0 = $r1, 0x400c000000000000
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 0)
;
; KV2-LABEL: fma64_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    make $r2 = 0x400c000000000000
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmad $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast double %b, 3.5
  %sub = fadd fast double %a, %mul
  ret double %sub
}


define float @fms32_contract(float %a, float %b, float %c) {
; ALL-LABEL: fms32_contract:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmsw $r0 = $r1, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul contract float %c, %b
  %sub = fsub contract float %a, %mul
  ret float %sub
}

define double @fms64_contract(double %a, double %b, double %c)  {
; ALL-LABEL: fms64_contract:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmsd $r0 = $r1, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul contract double %c, %b
  %sub = fsub contract double %a, %mul
  ret double %sub
}

define float @fms32_2(float %a, float %b, float %c, float %d) {
; ALL-LABEL: fms32_2:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    fmulw $r0 = $r0, $r1
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    ffmsw $r0 = $r2, $r3
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
entry:
  %mul = fmul fast float %a, %b
  %mul1 = fmul fast float %c, %d
  %sub = fsub fast float %mul, %mul1
  ret float %sub
}

define double @fms64_2(double %a, double %b, double %c, double %d) {
; ALL-LABEL: fms64_2:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    fmuld $r0 = $r0, $r1
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    ffmsd $r0 = $r2, $r3
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
entry:
  %mul = fmul fast double %a, %b
  %mul1 = fmul fast double %c, %d
  %sub = fsub fast double %mul, %mul1
  ret double %sub
}

define <4 x float> @fmawp_x2(<4 x float> %a, <4 x float> %b, <4 x float> %c) {
; KV1-LABEL: fmawp_x2:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmawp $r1 = $r5, $r3
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmawp $r0 = $r4, $r2
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: fmawp_x2:
; KV2:       # %bb.0:
; KV2-NEXT:    ffmawq $r0r1 = $r4r5, $r2r3
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 0)
  %1 = fmul fast <4 x float> %c, %b
  %2 = fadd fast <4 x float> %a, %1
ret <4 x float> %2
}

define <4 x float> @not_fmawp_x2(<4 x float> %a, <4 x float> %b, <4 x float> %c) {
; ALL-LABEL: not_fmawp_x2:
; ALL:       # %bb.0:
; ALL-NEXT:    fmulwq $r0r1 = $r4r5, $r2r3
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    faddwq $r0r1 = $r0r1, $r4r5
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
  %1 = fmul <4 x float> %c, %b
  %2 = fadd <4 x float> %1, %c
ret <4 x float> %2
}

define <4 x float> @fmawp_x2_int(<4 x float> %a, <4 x float> %b, <4 x float> %c) {
; KV1-LABEL: fmawp_x2_int:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmawp $r1 = $r3, $r5
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmawp $r0 = $r2, $r4
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: fmawp_x2_int:
; KV2:       # %bb.0:
; KV2-NEXT:    ffmawq $r0r1 = $r2r3, $r4r5
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 0)
  %res = call <4 x float> @llvm.fma.v4f32(<4 x float> %b, <4 x float> %c, <4 x float> %a)
  ret <4 x float> %res
}

define <8 x float> @fmawp_x4(<8 x float> %a, <8 x float> %b, <8 x float> %c) {
; KV1-LABEL: fmawp_x4:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmawp $r3 = $r11, $r7
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmawp $r2 = $r10, $r6
; KV1-NEXT:    ;; # (end cycle 1)
; KV1-NEXT:    ffmawp $r1 = $r9, $r5
; KV1-NEXT:    ;; # (end cycle 2)
; KV1-NEXT:    ffmawp $r0 = $r8, $r4
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 3)
;
; KV2-LABEL: fmawp_x4:
; KV2:       # %bb.0:
; KV2-NEXT:    ffmawq $r2r3 = $r10r11, $r6r7
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmawq $r0r1 = $r8r9, $r4r5
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
%1 = fmul fast <8 x float> %c, %b
%2 = fadd fast <8 x float> %1, %a
ret <8 x float> %2
}

define <8 x float> @not_fmawp_x4(<8 x float> %a, <8 x float> %b, <8 x float> %c) {
; ALL-LABEL: not_fmawp_x4:
; ALL:       # %bb.0:
; ALL-NEXT:    fmulwq $r0r1 = $r10r11, $r6r7
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    fmulwq $r4r5 = $r8r9, $r4r5
; ALL-NEXT:    ;; # (end cycle 1)
; ALL-NEXT:    faddwq $r2r3 = $r0r1, $r10r11
; ALL-NEXT:    ;; # (end cycle 4)
; ALL-NEXT:    faddwq $r0r1 = $r4r5, $r8r9
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 5)
%1 = fmul <8 x float> %c, %b
%2 = fadd <8 x float> %1, %c
ret <8 x float> %2
}

define <8 x float> @int_fmawp_x4(<8 x float> %a, <8 x float> %b, <8 x float> %c) {
; KV1-LABEL: int_fmawp_x4:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmawp $r3 = $r7, $r11
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmawp $r2 = $r6, $r10
; KV1-NEXT:    ;; # (end cycle 1)
; KV1-NEXT:    ffmawp $r1 = $r5, $r9
; KV1-NEXT:    ;; # (end cycle 2)
; KV1-NEXT:    ffmawp $r0 = $r4, $r8
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 3)
;
; KV2-LABEL: int_fmawp_x4:
; KV2:       # %bb.0:
; KV2-NEXT:    ffmawq $r2r3 = $r6r7, $r10r11
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmawq $r0r1 = $r4r5, $r8r9
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
  %res = call <8 x float> @llvm.fma.v8f32(<8 x float> %b, <8 x float> %c, <8 x float> %a)
  ret <8 x float> %res
}

define <4 x float> @fmswp_x2(<4 x float> %a, <4 x float> %b, <4 x float> %c) {
; KV1-LABEL: fmswp_x2:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmswp $r1 = $r5, $r3
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmswp $r0 = $r4, $r2
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: fmswp_x2:
; KV2:       # %bb.0:
; KV2-NEXT:    ffmswq $r0r1 = $r4r5, $r2r3
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 0)
  %1 = fmul fast <4 x float> %c, %b
  %2 = fsub fast <4 x float> %a, %1
  ret <4 x float> %2
}

define <4 x float> @not_fmswp_x2(<4 x float> %a, <4 x float> %b, <4 x float> %c) {
; ALL-LABEL: not_fmswp_x2:
; ALL:       # %bb.0:
; ALL-NEXT:    fmulwq $r0r1 = $r4r5, $r2r3
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    fsbfwq $r0r1 = $r4r5, $r0r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
  %1 = fmul <4 x float> %c, %b
  %2 = fsub <4 x float> %1, %c
ret <4 x float> %2
}

define <8 x float> @fmswp_x4(<8 x float> %a, <8 x float> %b, <8 x float> %c) {
; KV1-LABEL: fmswp_x4:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmswp $r3 = $r11, $r7
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmswp $r2 = $r10, $r6
; KV1-NEXT:    ;; # (end cycle 1)
; KV1-NEXT:    ffmswp $r1 = $r9, $r5
; KV1-NEXT:    ;; # (end cycle 2)
; KV1-NEXT:    ffmswp $r0 = $r8, $r4
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 3)
;
; KV2-LABEL: fmswp_x4:
; KV2:       # %bb.0:
; KV2-NEXT:    ffmswq $r2r3 = $r10r11, $r6r7
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmswq $r0r1 = $r8r9, $r4r5
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
%1 = fmul fast <8 x float> %c, %b
%2 = fsub fast <8 x float> %a, %1
ret <8 x float> %2
}

define <8 x float> @not_fmswp_x4(<8 x float> %a, <8 x float> %b, <8 x float> %c) {
; ALL-LABEL: not_fmswp_x4:
; ALL:       # %bb.0:
; ALL-NEXT:    fmulwq $r6r7 = $r10r11, $r6r7
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    fmulwq $r4r5 = $r8r9, $r4r5
; ALL-NEXT:    ;; # (end cycle 1)
; ALL-NEXT:    fsbfwq $r2r3 = $r2r3, $r6r7
; ALL-NEXT:    ;; # (end cycle 4)
; ALL-NEXT:    fsbfwq $r0r1 = $r0r1, $r4r5
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 5)
%1 = fmul <8 x float> %c, %b
%2 = fsub <8 x float> %1, %a
ret <8 x float> %2
}

declare half @llvm.fma.f16(half, half, half)
declare float @llvm.fma.f32(float, float, float)
declare double @llvm.fma.f64(double, double, double)
declare <2 x half> @llvm.fma.v2f16(<2 x half>, <2 x half>, <2 x half>)
declare <2 x float> @llvm.fma.v2f32(<2 x float>, <2 x float>, <2 x float>)
declare <4 x half> @llvm.fma.v4f16(<4 x half>, <4 x half>, <4 x half>)
declare <2 x double> @llvm.fma.v2f64(<2 x double>, <2 x double>, <2 x double>)
declare <4 x float> @llvm.fma.v4f32(<4 x float>, <4 x float>, <4 x float>)
declare <8 x float> @llvm.fma.v8f32(<8 x float>, <8 x float>, <8 x float>)

define <2 x float> @fmswp_rr(<2 x float> %a, <2 x float> %b, <2 x float> %c) {
; ALL-LABEL: fmswp_rr:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmswp $r0 = $r1, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast <2 x float> %c, %b
  %sub = fsub fast <2 x float> %a, %mul
  ret <2 x float> %sub
}

define float @fmsw_ri(float %a, float %b) {
; KV1-LABEL: fmsw_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmaw $r0 = $r1, 0xc0400000
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 0)
;
; KV2-LABEL: fmsw_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    make $r2 = 0xc0400000
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmaw $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast float 3.0, %b
  %sub = fsub fast float %a, %mul
  ret float %sub
}


define <2 x float> @fmawp_ri(<2 x float> %a, <2 x float> %b) {
; KV1-LABEL: fmawp_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmawp $r0 = $r1, 0xc040000040400000
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 0)
;
; KV2-LABEL: fmawp_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    make $r2 = 0xc040000040400000
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmawp $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast <2 x float> <float -3.0, float 3.0>, %b
  %sub = fsub fast <2 x float> %a, %mul
  ret <2 x float> %sub
}

define <4 x half> @fmshq_rr(<4 x half> %a, <4 x half> %b, <4 x half> %c) {
; ALL-LABEL: fmshq_rr:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmshq $r0 = $r1, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast <4 x half> %c, %b
  %sub = fsub fast <4 x half> %a, %mul
  ret <4 x half> %sub
}

define <4 x half> @fmshq_ri(<4 x half> %a, <4 x half> %b) {
; KV1-LABEL: fmshq_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmahq $r0 = $r1, 0x5fd0dfd03c00bc00
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 0)
;
; KV2-LABEL: fmshq_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    make $r2 = 0x5fd0dfd03c00bc00
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmahq $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast <4 x half> %b, <half 1.0, half -1.0, half 500.0, half -500.0>
  %sub = fsub fast <4 x half> %a, %mul
  ret <4 x half> %sub
}

define <4 x half> @fmahq_ri(<4 x half> %a, <4 x half> %b) {
; KV1-LABEL: fmahq_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmahq $r0 = $r1, 0xdfd05fd0bc003c00
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 0)
;
; KV2-LABEL: fmahq_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    make $r2 = 0xdfd05fd0bc003c00
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmahq $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast <4 x half> %b, <half 1.0, half -1.0, half 500.0, half -500.0>
  %sub = fadd fast <4 x half> %a, %mul
  ret <4 x half> %sub
}

define <2 x half> @fmshq_v2_rr(<2 x half> %a, <2 x half> %b, <2 x half> %c) {
; ALL-LABEL: fmshq_v2_rr:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmshq $r0 = $r2, $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast <2 x half> %c, %b
  %sub = fsub fast <2 x half> %a, %mul
  ret <2 x half> %sub
}

define <2 x half> @fmshq_v2_ri(<2 x half> %a, <2 x half> %b) {
; KV1-LABEL: fmshq_v2_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    zxwd $r0 = $r0
; KV1-NEXT:    zxwd $r1 = $r1
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmahq $r0 = $r1, 0x5fd0bc00
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: fmshq_v2_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    zxwd $r0 = $r0
; KV2-NEXT:    zxwd $r1 = $r1
; KV2-NEXT:    make $r2 = 0x5fd0bc00
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmahq $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast <2 x half> %b, <half 1.0, half -500.0>
  %sub = fsub fast <2 x half> %a, %mul
  ret <2 x half> %sub
}

define <2 x half> @fmahq_v2_ri(<2 x half> %a, <2 x half> %b) {
; KV1-LABEL: fmahq_v2_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    zxwd $r0 = $r0
; KV1-NEXT:    zxwd $r1 = $r1
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmahq $r0 = $r1, 0xffffffffdfd03c00
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: fmahq_v2_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    zxwd $r0 = $r0
; KV2-NEXT:    zxwd $r1 = $r1
; KV2-NEXT:    make $r2 = 0xffffffffdfd03c00
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmahq $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast <2 x half> %b, <half 1.0, half -500.0>
  %sub = fadd fast <2 x half> %a, %mul
  ret <2 x half> %sub
}

define half @fmshq_v1_rr(half %a, half %b, half %c) {
; ALL-LABEL: fmshq_v1_rr:
; ALL:       # %bb.0: # %entry
; ALL-NEXT:    ffmshq $r0 = $r2, $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast half %c, %b
  %sub = fsub fast half %a, %mul
  ret half %sub
}

define half @fmshq_v1_ri(half %a, half %b) {
; KV1-LABEL: fmshq_v1_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    zxhd $r0 = $r0
; KV1-NEXT:    zxhd $r1 = $r1
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmahq $r0 = $r1, 0xdfd0
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: fmshq_v1_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    zxhd $r0 = $r0
; KV2-NEXT:    zxhd $r1 = $r1
; KV2-NEXT:    make $r2 = 0xdfd0
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmahq $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast half %b, 500.0
  %sub = fsub fast half %a, %mul
  ret half %sub
}

define half @fmahq_v1_ri(half %a, half %b) {
; KV1-LABEL: fmahq_v1_ri:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    zxhd $r0 = $r0
; KV1-NEXT:    zxhd $r1 = $r1
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmahq $r0 = $r1, 0x5fd0
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: fmahq_v1_ri:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    zxhd $r0 = $r0
; KV2-NEXT:    zxhd $r1 = $r1
; KV2-NEXT:    make $r2 = 0x5fd0
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmahq $r0 = $r1, $r2
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
entry:
  %mul = fmul fast half %b, 500.0
  %sub = fadd fast half %a, %mul
  ret half %sub
}

define float @ffmahw_rr(float %0, half %1, half %2) {
; ALL-LABEL: ffmahw_rr:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmahw $r0 = $r2, $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %4 = fpext half %1 to float
  %5 = fpext half %2 to float
  %6 = fmul fast float %5, %4
  %7 = fadd fast float %6, %0
  ret float %7
}

define <4 x float> @ffmahwq_rr(<4 x float> %0, <4 x half> %1, <4 x half> %2) {
; ALL-LABEL: ffmahwq_rr:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmahwq $r0r1 = $r3, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %4 = fpext <4 x half> %1 to <4 x float>
  %5 = fpext <4 x half> %2 to <4 x float>
  %6 = fmul fast <4 x float> %5, %4
  %7 = fadd fast <4 x float> %6, %0
  ret <4 x float> %7
}

define <2 x double> @ffmawdp_rr(<2 x double> %0, <2 x float> %1, <2 x float> %2) {
; ALL-LABEL: ffmawdp_rr:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmawdp $r0r1 = $r3, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %4 = fpext <2 x float> %1 to <2 x double>
  %5 = fpext <2 x float> %2 to <2 x double>
  %6 = fmul fast <2 x double> %5, %4
  %7 = fadd fast <2 x double> %6, %0
  ret <2 x double> %7
}

define float @ffmshw_rr(float %0, half %1, half %2) {
; ALL-LABEL: ffmshw_rr:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmshw $r0 = $r2, $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %4 = fpext half %1 to float
  %5 = fpext half %2 to float
  %6 = fmul fast float %5, %4
  %7 = fsub fast float %0, %6
  ret float %7
}

define <4 x float> @ffmshwq_rr(<4 x float> %0, <4 x half> %1, <4 x half> %2) {
; ALL-LABEL: ffmshwq_rr:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmshwq $r0r1 = $r3, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %4 = fpext <4 x half> %1 to <4 x float>
  %5 = fpext <4 x half> %2 to <4 x float>
  %6 = fmul fast <4 x float> %5, %4
  %7 = fsub fast <4 x float> %0, %6
  ret <4 x float> %7
}

define <2 x double> @ffmswdp_rr(<2 x double> %0, <2 x float> %1, <2 x float> %2) {
; ALL-LABEL: ffmswdp_rr:
; ALL:       # %bb.0:
; ALL-NEXT:    ffmswdp $r0r1 = $r3, $r2
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %4 = fpext <2 x float> %1 to <2 x double>
  %5 = fpext <2 x float> %2 to <2 x double>
  %6 = fmul fast <2 x double> %5, %4
  %7 = fsub fast <2 x double> %0, %6
  ret <2 x double> %7
}

define float @fmulhw(half %0, half %1) {
; ALL-LABEL: fmulhw:
; ALL:       # %bb.0:
; ALL-NEXT:    fmulhw $r0 = $r1, $r0
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %3 = fpext half %0 to float
  %4 = fpext half %1 to float
  %5 = fmul fast float %4, %3
  ret float %5
}

define <4 x float> @fmulhwq(<4 x half> %0, <4 x half> %1) {
; ALL-LABEL: fmulhwq:
; ALL:       # %bb.0:
; ALL-NEXT:    fmulhwq $r0r1 = $r1, $r0
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %3 = fpext <4 x half> %0 to <4 x float>
  %4 = fpext <4 x half> %1 to <4 x float>
  %5 = fmul fast <4 x float> %4, %3
  ret <4 x float> %5
}

define <2 x double> @fmulwdp_rr(<2 x float> %0, <2 x float> %1) {
; ALL-LABEL: fmulwdp_rr:
; ALL:       # %bb.0:
; ALL-NEXT:    fmulwdp $r0r1 = $r1, $r0
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %3 = fpext <2 x float> %0 to <2 x double>
  %4 = fpext <2 x float> %1 to <2 x double>
  %5 = fmul fast <2 x double> %4, %3
  ret <2 x double> %5
}

declare <8 x half> @llvm.fma.v8f16(<8 x half>, <8 x half>, <8 x half>)

define <8 x half> @ffmaho0(<8 x half> %a, <8 x half> %b, <8 x half> %c) {
; KV1-LABEL: ffmaho0:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmahq $r0 = $r4, $r2
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmahq $r1 = $r5, $r3
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: ffmaho0:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    ffmaho $r0r1 = $r4r5, $r2r3
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast <8 x half> %c, %b
  %acc = fadd fast <8 x half> %a, %mul
  ret <8 x half> %acc
}

define <8 x half> @ffmsho0(<8 x half> %a, <8 x half> %b, <8 x half> %c) {
; KV1-LABEL: ffmsho0:
; KV1:       # %bb.0: # %entry
; KV1-NEXT:    ffmshq $r0 = $r2, $r4
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmshq $r1 = $r3, $r5
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 1)
;
; KV2-LABEL: ffmsho0:
; KV2:       # %bb.0: # %entry
; KV2-NEXT:    ffmsho $r0r1 = $r2r3, $r4r5
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 0)
entry:
  %mul = fmul fast <8 x half> %c, %b
  %acc = fsub fast <8 x half> %a, %mul
  ret <8 x half> %acc
}

define <8 x half> @ffmaho1(<8 x half> %a, <8 x half> %b, <8 x half> %c) {
; KV1-LABEL: ffmaho1:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmahq $r4 = $r0, $r2
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmahq $r5 = $r1, $r3
; KV1-NEXT:    ;; # (end cycle 1)
; KV1-NEXT:    copyd $r0 = $r4
; KV1-NEXT:    ;; # (end cycle 4)
; KV1-NEXT:    copyd $r1 = $r5
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 5)
;
; KV2-LABEL: ffmaho1:
; KV2:       # %bb.0:
; KV2-NEXT:    ffmaho $r4r5 = $r0r1, $r2r3
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    copyd $r0 = $r4
; KV2-NEXT:    copyd $r1 = $r5
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 4)
  %res = call <8 x half> @llvm.fma.v8f16(<8 x half> %a, <8 x half> %b, <8 x half> %c)
  ret <8 x half> %res
}

define <8 x half> @ffmsho1(<8 x half> %a, <8 x half> %b, <8 x half> %c) {
; KV1-LABEL: ffmsho1:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmshq $r4 = $r2, $r0
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmshq $r5 = $r3, $r1
; KV1-NEXT:    ;; # (end cycle 1)
; KV1-NEXT:    copyd $r0 = $r4
; KV1-NEXT:    ;; # (end cycle 4)
; KV1-NEXT:    copyd $r1 = $r5
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 5)
;
; KV2-LABEL: ffmsho1:
; KV2:       # %bb.0:
; KV2-NEXT:    ffmsho $r4r5 = $r2r3, $r0r1
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    copyd $r0 = $r4
; KV2-NEXT:    copyd $r1 = $r5
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 4)
  %nega = fneg <8 x half> %a
  %res = call <8 x half> @llvm.fma.v8f16(<8 x half> %nega, <8 x half> %b, <8 x half> %c)
  ret <8 x half> %res
}

define <8 x half> @ffmsho2(<8 x half> %a, <8 x half> %b, <8 x half> %c) {
; KV1-LABEL: ffmsho2:
; KV1:       # %bb.0:
; KV1-NEXT:    ffmshq $r4 = $r2, $r0
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    ffmshq $r5 = $r3, $r1
; KV1-NEXT:    ;; # (end cycle 1)
; KV1-NEXT:    copyd $r0 = $r4
; KV1-NEXT:    ;; # (end cycle 4)
; KV1-NEXT:    copyd $r1 = $r5
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 5)
;
; KV2-LABEL: ffmsho2:
; KV2:       # %bb.0:
; KV2-NEXT:    ffmsho $r4r5 = $r2r3, $r0r1
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    copyd $r0 = $r4
; KV2-NEXT:    copyd $r1 = $r5
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 4)
  %negb = fneg <8 x half> %b
  %res = call <8 x half> @llvm.fma.v8f16(<8 x half> %a, <8 x half> %negb, <8 x half> %c)
  ret <8 x half> %res
}

define <8 x half> @avoidFneg(<8 x half> %a, <8 x half> %b, <8 x half> %c) {
; KV1-LABEL: avoidFneg:
; KV1:       # %bb.0:
; KV1-NEXT:    fmulhq $r0 = $r0, $r2
; KV1-NEXT:    ;; # (end cycle 0)
; KV1-NEXT:    fmulhq $r1 = $r1, $r3
; KV1-NEXT:    ;; # (end cycle 1)
; KV1-NEXT:    ffmshq $r0 = $r4, $r2
; KV1-NEXT:    ;; # (end cycle 4)
; KV1-NEXT:    ffmshq $r1 = $r5, $r3
; KV1-NEXT:    ret
; KV1-NEXT:    ;; # (end cycle 5)
;
; KV2-LABEL: avoidFneg:
; KV2:       # %bb.0:
; KV2-NEXT:    fmulho $r0r1 = $r0r1, $r2r3
; KV2-NEXT:    ;; # (end cycle 0)
; KV2-NEXT:    ffmsho $r0r1 = $r4r5, $r2r3
; KV2-NEXT:    ret
; KV2-NEXT:    ;; # (end cycle 1)
  %mul = fmul fast <8 x half> %c, %b
  %neg = fneg <8 x half> %mul
  %res = call <8 x half> @llvm.fma.v8f16(<8 x half> %a, <8 x half> %b, <8 x half> %neg)
  ret <8 x half> %res
}
