; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s | FileCheck %s --check-prefixes=CHECK,CV1
; RUN: llc -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefixes=CHECK,CV2
; RUN: clang -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

declare half @llvm.maxnum.f16(half, half)

define half @fmaxh(half %a, half %b) {
; CV1-LABEL: fmaxh:
; CV1:       # %bb.0:
; CV1-NEXT:    sllhqs $r2 = $r0, 1
; CV1-NEXT:    fcompnhq.olt $r3 = $r0, $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    compnhq.gtu $r2 = $r2, 0xf800
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    orw $r2 = $r3, $r2
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    cmovehq.odd $r2 ? $r0 = $r1
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 3)
;
; CV2-LABEL: fmaxh:
; CV2:       # %bb.0:
; CV2-NEXT:    fmaxhq $r0 = $r0, $r1
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 0)
  %res = call half @llvm.maxnum.f16(half %a, half %b)
  ret half %res
}

define half @fmaxh_fast(half %a, half %b) {
; CHECK-LABEL: fmaxh_fast:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmaxhq $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call fast half @llvm.maxnum.f16(half %a, half %b)
  ret half %res
}

define float @fmaxw(float %a, float %b) {
; CV1-LABEL: fmaxw:
; CV1:       # %bb.0:
; CV1-NEXT:    sllw $r2 = $r0, 1
; CV1-NEXT:    fcompw.olt $r3 = $r0, $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    compw.gtu $r2 = $r2, 0xff000000
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    orw $r2 = $r3, $r2
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    cmoved.odd $r2 ? $r0 = $r1
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 3)
;
; CV2-LABEL: fmaxw:
; CV2:       # %bb.0:
; CV2-NEXT:    fmaxw $r0 = $r0, $r1
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 0)
  %res = call float @llvm.maxnum.f32(float %a, float %b)
  ret float %res
}

define float @fmaxw_fast(float %a, float %b) {
; CHECK-LABEL: fmaxw_fast:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmaxw $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call fast float @llvm.maxnum.f32(float %a, float %b)
  ret float %res
}

declare float @llvm.maxnum.f32(float, float)

define double @fmaxd(double %a, double %b) {
; CV1-LABEL: fmaxd:
; CV1:       # %bb.0:
; CV1-NEXT:    slld $r2 = $r0, 1
; CV1-NEXT:    fcompd.olt $r3 = $r0, $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    compd.gtu $r2 = $r2, 0xffe0000000000000
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    ord $r2 = $r3, $r2
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    cmoved.odd $r2 ? $r0 = $r1
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 3)
;
; CV2-LABEL: fmaxd:
; CV2:       # %bb.0:
; CV2-NEXT:    fmaxd $r0 = $r0, $r1
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 0)
  %res = call double @llvm.maxnum.f64(double %a, double %b)
  ret double %res
}

define double @fmaxd_fast(double %a, double %b) {
; CHECK-LABEL: fmaxd_fast:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmaxd $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %res = call fast double @llvm.maxnum.f64(double %a, double %b)
  ret double %res
}

declare double @llvm.maxnum.f64(double, double)
