; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: clang -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-sqrt"

define float @sqrtf32(float %x) {
; CHECK-LABEL: sqrtf32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    goto sqrtf
; CHECK-NEXT:    ;;
  %tmp = call float @llvm.sqrt.f32(float %x)
  ret float %tmp
}

define float @sqrtf32_fast(float %x) {
; CHECK-LABEL: sqrtf32_fast:
; CHECK:       # %bb.0:
; CHECK-NEXT:    frsrw $r1 = $r0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fmulw $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 11)
  %tmp = call fast float @llvm.sqrt.f32(float %x)
  ret float %tmp
}

define double @sqrtf64(double %x) {
; CHECK-LABEL: sqrtf64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    goto sqrt
; CHECK-NEXT:    ;;
  %tmp = call double @llvm.sqrt.f64(double %x)
  ret double %tmp
}

define <2 x float> @sqrtv2f32(<2 x float> %x) {
; CHECK-LABEL: sqrtv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 8[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 8[$r12]
; CHECK-NEXT:    insf $r0 = $r19, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;; # (end cycle 6)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %tmp = call <2 x float> @llvm.sqrt.v2f32(<2 x float> %x)
  ret <2 x float> %tmp
}

define <2 x double> @sqrtv2f64(<2 x double> %x) {
; CHECK-LABEL: sqrtv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sd 8[$r12] = $r18
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    call sqrt
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call sqrt
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r20
; CHECK-NEXT:    copyd $r1 = $r0
; CHECK-NEXT:    ld $r18 = 8[$r12]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;; # (end cycle 7)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %tmp = call <2 x double> @llvm.sqrt.v2f64(<2 x double> %x)
  ret <2 x double> %tmp
}

declare float @llvm.sqrt.f32(float)
declare double @llvm.sqrt.f64(double)
declare <2x float> @llvm.sqrt.v2f32(<2 x float>)
declare <2x double> @llvm.sqrt.v2f64(<2 x double>)
