; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define i64 @f_5_quadpack(i64* nocapture readonly %v){
; CHECK-LABEL: f_5_quadpack:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lo $r4r5r6r7 = 0[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    ld $r0 = 32[$r0]
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    addd $r1 = $r5, $r4
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    addd $r1 = $r1, $r6
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    addd $r1 = $r1, $r7
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    addd $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 6)
entry:
  %0 = load i64, i64* %v, align 8
  %arrayidx1 = getelementptr inbounds i64, i64* %v, i64 1
  %1 = load i64, i64* %arrayidx1, align 8
  %arrayidx2 = getelementptr inbounds i64, i64* %v, i64 2
  %2 = load i64, i64* %arrayidx2, align 8
  %arrayidx3 = getelementptr inbounds i64, i64* %v, i64 3
  %3 = load i64, i64* %arrayidx3, align 8
  %arrayidx4 = getelementptr inbounds i64, i64* %v, i64 4
  %4 = load i64, i64* %arrayidx4, align 8
  %add = add nsw i64 %1, %0
  %add5 = add nsw i64 %add, %2
  %add6 = add nsw i64 %add5, %3
  %add7 = add nsw i64 %add6, %4
  ret i64 %add7
}

