; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --disable-kvx-loadstore-packing=false -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc --disable-kvx-loadstore-packing=false -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: clang -mllvm --disable-kvx-loadstore-packing=false -c -o /dev/null %s
; RUN: clang -mllvm --disable-kvx-loadstore-packing=false -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define i64 @f2(ptr nocapture readonly %a) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lq $r0r1 = 0[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    addd $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 3)
entry:
  %0 = load i64, ptr %a, align 8
  %arrayidx1 = getelementptr inbounds i64, ptr %a, i64 1
  %1 = load i64, ptr %arrayidx1, align 8
  %add = add nsw i64 %1, %0
  ret i64 %add

}

define i64 @f4(ptr nocapture readonly %a) {
; CHECK-LABEL: f4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lo $r0r1r2r3 = 0[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    addd $r0 = $r1, $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    addd $r0 = $r0, $r2
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    addd $r0 = $r0, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 5)
entry:
  %0 = load i64, ptr %a, align 8
  %arrayidx1 = getelementptr inbounds i64, ptr %a, i64 1
  %1 = load i64, ptr %arrayidx1, align 8
  %add = add nsw i64 %1, %0
  %arrayidx2 = getelementptr inbounds i64, ptr %a, i64 2
  %2 = load i64, ptr %arrayidx2, align 8
  %add3 = add nsw i64 %add, %2
  %arrayidx4 = getelementptr inbounds i64, ptr %a, i64 3
  %3 = load i64, ptr %arrayidx4, align 8
  %add5 = add nsw i64 %add3, %3
  ret i64 %add5

}

define i64 @f2_2(ptr nocapture readonly %a, ptr nocapture readonly %b) {
; CHECK-LABEL: f2_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lq $r2r3 = 0[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r0r1 = 0[$r1]
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    addd $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    addx2d $r1 = $r2, $r1
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    addd $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 6)
entry:
  %arrayidx = getelementptr inbounds i64, ptr %a, i64 1
  %0 = load i64, ptr %arrayidx, align 8
  %1 = load i64, ptr %a, align 8
  %arrayidx2 = getelementptr inbounds i64, ptr %b, i64 1
  %2 = load i64, ptr %arrayidx2, align 8
  %3 = load i64, ptr %b, align 8
  %factor = shl i64 %1, 1
  %add3 = add i64 %2, %0
  %add5 = add i64 %add3, %factor
  %add7 = add i64 %add5, %3
  ret i64 %add7


}

define i64 @force(i64 %a, i64 %b, i64 %c, i64 %d) {
; CHECK-LABEL: force:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addd $r0 = $r1, $r0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    addd $r0 = $r0, $r2
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    addd $r0 = $r0, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
entry:
  %add = add nsw i64 %b, %a
  %add1 = add nsw i64 %add, %c
  %add2 = add nsw i64 %add1, %d
  ret i64 %add2
}

define i64 @f4_force(ptr nocapture readonly %a) {
; CHECK-LABEL: f4_force:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lo $r0r1r2r3 = 0[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    addd $r0 = $r1, $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    addd $r0 = $r0, $r2
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    addd $r0 = $r0, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 5)
entry:
  %0 = load i64, ptr %a, align 8
  %arrayidx1 = getelementptr inbounds i64, ptr %a, i64 1
  %1 = load i64, ptr %arrayidx1, align 8
  %arrayidx2 = getelementptr inbounds i64, ptr %a, i64 2
  %2 = load i64, ptr %arrayidx2, align 8
  %arrayidx3 = getelementptr inbounds i64, ptr %a, i64 3
  %3 = load i64, ptr %arrayidx3, align 8
  %add.i = add nsw i64 %1, %0
  %add1.i = add nsw i64 %add.i, %2
  %add2.i = add nsw i64 %add1.i, %3
  ret i64 %add2.i

}
