; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -kvx-conditional-tailcalls -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -kvx-conditional-tailcalls -o - %s | FileCheck %s --check-prefixes=CHECK

target triple = "kvx-kalray-cos"

define void @foo(i64 %0, i64 %1, i64 %2) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cb.dnez $r0 ? A
; CHECK-NEXT:    ;;
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    cb.dnez $r1 ? B
; CHECK-NEXT:    ;;
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    goto C
; CHECK-NEXT:    ;;
  %4 = icmp eq i64 %0, 0
  br i1 %4, label %6, label %5

5:
  tail call void @A()
  br label %10

6:
  %7 = icmp eq i64 %1, 0
  br i1 %7, label %9, label %8

8:
  tail call void @B()
  br label %10

9:
  tail call void @C()
  br label %10

10:
  ret void
}

declare void @A()

declare void @B()

declare void @C()

