; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -O2 -o - %s | FileCheck %s --check-prefixes=ALL
; RUN: llc -mcpu=kv3-2 -O2 -o - %s | FileCheck %s --check-prefixes=ALL
; RUN: clang -O2 -march=kv3-1 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <4 x i32> @cat128(<2 x i32> %0, <2 x i32> %1) {
; ALL-LABEL: cat128:
; ALL:       # %bb.0:
; ALL-NEXT:    copyd $r0 = $r1
; ALL-NEXT:    copyd $r1 = $r0
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %3 = shufflevector <2 x i32> %1, <2 x i32> %0, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %3
}

define <8 x i32> @cat256(<4 x i32> %0, <4 x i32> %1) {
; ALL-LABEL: cat256:
; ALL:       # %bb.0:
; ALL-NEXT:    copyd $r0 = $r2
; ALL-NEXT:    copyd $r1 = $r3
; ALL-NEXT:    copyd $r2 = $r0
; ALL-NEXT:    copyd $r3 = $r1
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 0)
  %3 = shufflevector <4 x i32> %1, <4 x i32> %0, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x i32> %3
}

define void @cat512(<16 x i32>* noalias nocapture sret(<16 x i32>) align 32 %0, <8 x i32> %1, <8 x i32> %2) {
; ALL-LABEL: cat512:
; ALL:       # %bb.0:
; ALL-NEXT:    so 32[$r15] = $r0r1r2r3
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    so 0[$r15] = $r4r5r6r7
; ALL-NEXT:    copyd $r0 = $r15
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 1)
  %4 = shufflevector <8 x i32> %2, <8 x i32> %1, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  store <16 x i32> %4, <16 x i32>* %0
  ret void
}
