; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-2 -O2 -o - %s | FileCheck %s --check-prefix=ALL
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define void @fencev() {
; ALL-LABEL: fencev:
; ALL:       # %bb.0:
; ALL-NEXT:    fence
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    fence
; ALL-NEXT:    ;; # (end cycle 1)
; ALL-NEXT:    fence.w
; ALL-NEXT:    ;; # (end cycle 2)
; ALL-NEXT:    fence.r
; ALL-NEXT:    ;; # (end cycle 3)
; ALL-NEXT:    fence.wa
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 4)
  tail call void @llvm.kvx.fence(i32 0)
  tail call void @llvm.kvx.fence(i32 0)
  tail call void @llvm.kvx.fence(i32 1)
  tail call void @llvm.kvx.fence(i32 2)
  tail call void @llvm.kvx.fence(i32 3)
  ret void
}

declare void @llvm.kvx.fence(i32)

