; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-2 -O2 -o - %s | FileCheck %s --check-prefix=V2
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <4 x float> @ffdmdawq(<8 x float> %0, <8 x float> %1, <4 x float> %2) {
; V2-LABEL: ffdmdawq:
; V2:       # %bb.0:
; V2-NEXT:    ffdmdawq $r8r9 = $r0r1r2r3, $r4r5r6r7
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r0 = $r8
; V2-NEXT:    copyd $r1 = $r9
; V2-NEXT:    ret
; V2-NEXT:    ;;
  %4 = tail call <4 x float> @llvm.kvx.ffdmda.v4f32(<8 x float> %0, <8 x float> %1, <4 x float> %2, i32 7, i32 0)
  ret <4 x float> %4
}

declare <4 x float> @llvm.kvx.ffdmda.v4f32(<8 x float>, <8 x float>, <4 x float>, i32, i32)

define <4 x float> @ffdmdawq_rn_s(<8 x float> %0, <8 x float> %1, <4 x float> %2) {
; V2-LABEL: ffdmdawq_rn_s:
; V2:       # %bb.0:
; V2-NEXT:    ffdmdawq.rn.s $r8r9 = $r0r1r2r3, $r4r5r6r7
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r0 = $r8
; V2-NEXT:    copyd $r1 = $r9
; V2-NEXT:    ret
; V2-NEXT:    ;;
  %4 = tail call <4 x float> @llvm.kvx.ffdmda.v4f32(<8 x float> %0, <8 x float> %1, <4 x float> %2, i32 0, i32 1)
  ret <4 x float> %4
}

