; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefix=CV2
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <8 x half> @ffmsho(<8 x half> %0, <8 x half> %1, <8 x half> %2) {
; CV2-LABEL: ffmsho:
; CV2:       # %bb.0:
; CV2-NEXT:    ffmsho.ru.s $r4r5 = $r0r1, $r2r3
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    copyd $r0 = $r4
; CV2-NEXT:    copyd $r1 = $r5
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 4)
  %4 = tail call <8 x half> @llvm.kvx.ffms.v8f16(<8 x half> %0, <8 x half> %1, <8 x half> %2, i32 1, i32 1)
  ret <8 x half> %4
}

declare <8 x half> @llvm.kvx.ffms.v8f16(<8 x half>, <8 x half>, <8 x half>, i32, i32)

define <16 x half> @ffmshx(<16 x half> %0, <16 x half> %1, <16 x half> %2) {
; CV2-LABEL: ffmshx:
; CV2:       # %bb.0:
; CV2-NEXT:    ffmsho.ru.s $r8r9 = $r0r1, $r4r5
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    ffmsho.ru.s $r10r11 = $r2r3, $r6r7
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    copyd $r0 = $r8
; CV2-NEXT:    copyd $r1 = $r9
; CV2-NEXT:    ;; # (end cycle 4)
; CV2-NEXT:    copyd $r2 = $r10
; CV2-NEXT:    copyd $r3 = $r11
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 5)
  %4 = shufflevector <16 x half> %0, <16 x half> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %5 = shufflevector <16 x half> %1, <16 x half> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %6 = shufflevector <16 x half> %2, <16 x half> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %7 = tail call <8 x half> @llvm.kvx.ffms.v8f16(<8 x half> %4, <8 x half> %5, <8 x half> %6, i32 1, i32 1)
  %8 = shufflevector <16 x half> %0, <16 x half> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %9 = shufflevector <16 x half> %1, <16 x half> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %10 = shufflevector <16 x half> %2, <16 x half> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %11 = tail call <8 x half> @llvm.kvx.ffms.v8f16(<8 x half> %8, <8 x half> %9, <8 x half> %10, i32 1, i32 1)
  %12 = shufflevector <8 x half> %7, <8 x half> %11, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x half> %12
}
