; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK,CV1
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK,CV2
; RUN: clang -O2 -march=kv3-1 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define double @fnegd(double %0) {
; CHECK-LABEL: fnegd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fnegd $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %2 = tail call double @llvm.kvx.fneg.f64(double %0)
  ret double %2
}

declare double @llvm.kvx.fneg.f64(double)

define <2 x double> @fnegdp(<2 x double> %0) {
; CHECK-LABEL: fnegdp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fnegd $r0 = $r0
; CHECK-NEXT:    fnegd $r1 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %2 = extractelement <2 x double> %0, i64 0
  %3 = tail call double @llvm.kvx.fneg.f64(double %2)
  %4 = extractelement <2 x double> %0, i64 1
  %5 = tail call double @llvm.kvx.fneg.f64(double %4)
  %6 = insertelement <2 x double> undef, double %3, i32 0
  %7 = insertelement <2 x double> %6, double %5, i32 1
  ret <2 x double> %7
}

define <4 x double> @fnegdq(<4 x double> %0) {
; CV1-LABEL: fnegdq:
; CV1:       # %bb.0:
; CV1-NEXT:    fnegd $r0 = $r0
; CV1-NEXT:    fnegd $r1 = $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    fnegd $r2 = $r2
; CV1-NEXT:    fnegd $r3 = $r3
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 1)
;
; CV2-LABEL: fnegdq:
; CV2:       # %bb.0:
; CV2-NEXT:    fnegd $r0 = $r0
; CV2-NEXT:    fnegd $r1 = $r1
; CV2-NEXT:    fnegd $r2 = $r2
; CV2-NEXT:    fnegd $r3 = $r3
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 0)
  %2 = extractelement <4 x double> %0, i64 0
  %3 = tail call double @llvm.kvx.fneg.f64(double %2)
  %4 = extractelement <4 x double> %0, i64 1
  %5 = tail call double @llvm.kvx.fneg.f64(double %4)
  %6 = extractelement <4 x double> %0, i64 2
  %7 = tail call double @llvm.kvx.fneg.f64(double %6)
  %8 = extractelement <4 x double> %0, i64 3
  %9 = tail call double @llvm.kvx.fneg.f64(double %8)
  %10 = insertelement <4 x double> undef, double %3, i32 0
  %11 = insertelement <4 x double> %10, double %5, i32 1
  %12 = insertelement <4 x double> %11, double %7, i32 2
  %13 = insertelement <4 x double> %12, double %9, i32 3
  ret <4 x double> %13
}

define half @fnegh(half %0) {
; CHECK-LABEL: fnegh:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fneghq $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %2 = tail call half @llvm.kvx.fneg.f16(half %0)
  ret half %2
}

declare half @llvm.kvx.fneg.f16(half)

define <8 x half> @fnegho(<8 x half> %0) {
; CHECK-LABEL: fnegho:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fneghq $r0 = $r0
; CHECK-NEXT:    fneghq $r1 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %2 = shufflevector <8 x half> %0, <8 x half> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %3 = tail call <4 x half> @llvm.kvx.fneg.v4f16(<4 x half> %2)
  %4 = shufflevector <8 x half> %0, <8 x half> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %5 = tail call <4 x half> @llvm.kvx.fneg.v4f16(<4 x half> %4)
  %6 = shufflevector <4 x half> %3, <4 x half> %5, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x half> %6
}

declare <4 x half> @llvm.kvx.fneg.v4f16(<4 x half>)

define <2 x half> @fneghp(<2 x half> %0) {
; CHECK-LABEL: fneghp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fneghq $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %2 = tail call <2 x half> @llvm.kvx.fneg.v2f16(<2 x half> %0)
  ret <2 x half> %2
}

declare <2 x half> @llvm.kvx.fneg.v2f16(<2 x half>)

define <4 x half> @fneghq(<4 x half> %0) {
; CHECK-LABEL: fneghq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fneghq $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %2 = tail call <4 x half> @llvm.kvx.fneg.v4f16(<4 x half> %0)
  ret <4 x half> %2
}

define <16 x half> @fneghx(<16 x half> %0) {
; CV1-LABEL: fneghx:
; CV1:       # %bb.0:
; CV1-NEXT:    fneghq $r0 = $r0
; CV1-NEXT:    fneghq $r1 = $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    fneghq $r2 = $r2
; CV1-NEXT:    fneghq $r3 = $r3
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 1)
;
; CV2-LABEL: fneghx:
; CV2:       # %bb.0:
; CV2-NEXT:    fneghq $r0 = $r0
; CV2-NEXT:    fneghq $r1 = $r1
; CV2-NEXT:    fneghq $r2 = $r2
; CV2-NEXT:    fneghq $r3 = $r3
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 0)
  %2 = shufflevector <16 x half> %0, <16 x half> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %3 = tail call <4 x half> @llvm.kvx.fneg.v4f16(<4 x half> %2)
  %4 = shufflevector <16 x half> %0, <16 x half> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %5 = tail call <4 x half> @llvm.kvx.fneg.v4f16(<4 x half> %4)
  %6 = shufflevector <16 x half> %0, <16 x half> undef, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
  %7 = tail call <4 x half> @llvm.kvx.fneg.v4f16(<4 x half> %6)
  %8 = shufflevector <16 x half> %0, <16 x half> undef, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
  %9 = tail call <4 x half> @llvm.kvx.fneg.v4f16(<4 x half> %8)
  %10 = shufflevector <4 x half> %3, <4 x half> %5, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %11 = shufflevector <4 x half> %7, <4 x half> %9, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %12 = shufflevector <8 x half> %10, <8 x half> %11, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x half> %12
}

define float @fnegw(float %0) {
; CHECK-LABEL: fnegw:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fnegw $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %2 = tail call float @llvm.kvx.fneg.f32(float %0)
  ret float %2
}

declare float @llvm.kvx.fneg.f32(float)

define <8 x float> @fnegwo(<8 x float> %0) {
; CV1-LABEL: fnegwo:
; CV1:       # %bb.0:
; CV1-NEXT:    fnegwp $r0 = $r0
; CV1-NEXT:    fnegwp $r1 = $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    fnegwp $r2 = $r2
; CV1-NEXT:    fnegwp $r3 = $r3
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 1)
;
; CV2-LABEL: fnegwo:
; CV2:       # %bb.0:
; CV2-NEXT:    fnegwp $r0 = $r0
; CV2-NEXT:    fnegwp $r1 = $r1
; CV2-NEXT:    fnegwp $r2 = $r2
; CV2-NEXT:    fnegwp $r3 = $r3
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 0)
  %2 = shufflevector <8 x float> %0, <8 x float> undef, <2 x i32> <i32 0, i32 1>
  %3 = tail call <2 x float> @llvm.kvx.fneg.v2f32(<2 x float> %2)
  %4 = shufflevector <8 x float> %0, <8 x float> undef, <2 x i32> <i32 2, i32 3>
  %5 = tail call <2 x float> @llvm.kvx.fneg.v2f32(<2 x float> %4)
  %6 = shufflevector <8 x float> %0, <8 x float> undef, <2 x i32> <i32 4, i32 5>
  %7 = tail call <2 x float> @llvm.kvx.fneg.v2f32(<2 x float> %6)
  %8 = shufflevector <8 x float> %0, <8 x float> undef, <2 x i32> <i32 6, i32 7>
  %9 = tail call <2 x float> @llvm.kvx.fneg.v2f32(<2 x float> %8)
  %10 = shufflevector <2 x float> %3, <2 x float> %5, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %11 = shufflevector <2 x float> %7, <2 x float> %9, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %12 = shufflevector <4 x float> %10, <4 x float> %11, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  ret <8 x float> %12
}

declare <2 x float> @llvm.kvx.fneg.v2f32(<2 x float>)

define <2 x float> @fnegwp(<2 x float> %0) {
; CHECK-LABEL: fnegwp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fnegwp $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %2 = tail call <2 x float> @llvm.kvx.fneg.v2f32(<2 x float> %0)
  ret <2 x float> %2
}

define <4 x float> @fnegwq(<4 x float> %0) {
; CHECK-LABEL: fnegwq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fnegwp $r0 = $r0
; CHECK-NEXT:    fnegwp $r1 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %2 = shufflevector <4 x float> %0, <4 x float> undef, <2 x i32> <i32 0, i32 1>
  %3 = tail call <2 x float> @llvm.kvx.fneg.v2f32(<2 x float> %2)
  %4 = shufflevector <4 x float> %0, <4 x float> undef, <2 x i32> <i32 2, i32 3>
  %5 = tail call <2 x float> @llvm.kvx.fneg.v2f32(<2 x float> %4)
  %6 = shufflevector <2 x float> %3, <2 x float> %5, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x float> %6
}

