; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -O2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -O2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O2 -march=kv3-1 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <2 x i32> @high64(<4 x i32> %0) {
; CHECK-LABEL: high64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = shufflevector <4 x i32> %0, <4 x i32> poison, <2 x i32> <i32 2, i32 3>
  ret <2 x i32> %2
}

define <4 x i32> @high128(<8 x i32> %0) {
; CHECK-LABEL: high128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = shufflevector <8 x i32> %0, <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  ret <4 x i32> %2
}

define <8 x i32> @high256(<16 x i32>* nocapture readonly %0) {
; CHECK-LABEL: high256:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lo $r0r1r2r3 = 32[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = load <16 x i32>, <16 x i32>* %0
  %3 = shufflevector <16 x i32> %2, <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <8 x i32> %3
}

