; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s

target triple = "kvx-kalray-cos"

define <4 x i32> @mm212w(<2 x i32> %0, <2 x i32> %1) {
; CHECK-LABEL: mm212w:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mm212w $r0r1 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %3 = tail call <4 x i32> @llvm.kvx.mm212w(<2 x i32> %0, <2 x i32> %1)
  ret <4 x i32> %3
}

declare <4 x i32> @llvm.kvx.mm212w(<2 x i32>, <2 x i32>)

define <4 x i32> @mma212w(<4 x i32> %0, <2 x i32> %1, <2 x i32> %2) {
; CHECK-LABEL: mma212w:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mma212w $r0r1 = $r2, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %4 = tail call <4 x i32> @llvm.kvx.mma212w(<2 x i32> %1, <2 x i32> %2, <4 x i32> %0)
  ret <4 x i32> %4
}

declare <4 x i32> @llvm.kvx.mma212w(<2 x i32>, <2 x i32>, <4 x i32>)

define <4 x i32> @mms212w(<4 x i32> %0, <2 x i32> %1, <2 x i32> %2) {
; CHECK-LABEL: mms212w:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mms212w $r0r1 = $r2, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %4 = tail call <4 x i32> @llvm.kvx.mms212w(<2 x i32> %1, <2 x i32> %2, <4 x i32> %0)
  ret <4 x i32> %4
}

declare <4 x i32> @llvm.kvx.mms212w(<2 x i32>, <2 x i32>, <4 x i32>)

