; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -o - %s | FileCheck %s --check-prefixes=CHECK,CV1
; RUN: llc -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefixes=CHECK,CV2
; RUN: clang -O2 -march=kv3-1 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <8 x i8> @shiftbo_one(<8 x i8> %0, i8 %1) {
; CHECK-LABEL: shiftbo_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r0 = $r0, 8
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 63, 56
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <8 x i8> undef, i8 %1, i64 0
  %4 = shufflevector <8 x i8> %3, <8 x i8> %0, <8 x i32> <i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0>
  ret <8 x i8> %4
}

define <8 x i8> @shiftbo_last(<8 x i8> %0, i8 %1) {
; CHECK-LABEL: shiftbo_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 7, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x101010101010180
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <8 x i8> undef, i8 %1, i64 0
  %4 = shufflevector <8 x i8> %3, <8 x i8> %0, <8 x i32> <i32 15, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <8 x i8> %4
}

define <16 x i8> @shiftbx_one(<16 x i8> %0, i8 %1) {
; CHECK-LABEL: shiftbx_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r0 = $r0, 8
; CHECK-NEXT:    srld $r1 = $r1, 8
; CHECK-NEXT:    zxbd $r3 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r3, 63, 56
; CHECK-NEXT:    insf $r1 = $r2, 63, 56
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <16 x i8> undef, i8 %1, i64 0
  %4 = shufflevector <16 x i8> %3, <16 x i8> %0, <16 x i32> <i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 0>
  ret <16 x i8> %4
}

define <16 x i8> @shiftbx_last(<16 x i8> %0, i8 %1) {
; CHECK-LABEL: shiftbx_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r1 = $r2, 7, 0
; CHECK-NEXT:    sbmm8 $r3 = $r2, 0x1010101.@
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r1, 0x101010101010180
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <16 x i8> undef, i8 %1, i64 0
  %4 = shufflevector <16 x i8> %3, <16 x i8> %0, <16 x i32> <i32 31, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <16 x i8> %4
}

define <32 x i8> @shiftbv_one(<32 x i8> %0, i8 %1) {
; CV1-LABEL: shiftbv_one:
; CV1:       # %bb.0:
; CV1-NEXT:    srld $r0 = $r0, 8
; CV1-NEXT:    srld $r1 = $r1, 8
; CV1-NEXT:    zxbd $r5 = $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    insf $r0 = $r5, 63, 56
; CV1-NEXT:    srld $r2 = $r2, 8
; CV1-NEXT:    zxbd $r5 = $r2
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    insf $r1 = $r5, 63, 56
; CV1-NEXT:    srld $r3 = $r3, 8
; CV1-NEXT:    zxbd $r5 = $r3
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    insf $r2 = $r5, 63, 56
; CV1-NEXT:    insf $r3 = $r4, 63, 56
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 3)
;
; CV2-LABEL: shiftbv_one:
; CV2:       # %bb.0:
; CV2-NEXT:    srld $r0 = $r0, 8
; CV2-NEXT:    srld $r1 = $r1, 8
; CV2-NEXT:    zxbd $r5 = $r1
; CV2-NEXT:    zxbd $r6 = $r2
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    insf $r0 = $r5, 63, 56
; CV2-NEXT:    srld $r2 = $r2, 8
; CV2-NEXT:    srld $r3 = $r3, 8
; CV2-NEXT:    zxbd $r7 = $r3
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    insf $r1 = $r6, 63, 56
; CV2-NEXT:    insf $r2 = $r7, 63, 56
; CV2-NEXT:    insf $r3 = $r4, 63, 56
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <32 x i8> undef, i8 %1, i64 0
  %4 = shufflevector <32 x i8> %3, <32 x i8> %0, <32 x i32> <i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 0>
  ret <32 x i8> %4
}

define <32 x i8> @shiftbv_last(<32 x i8> %0, i8 %1) {
; CHECK-LABEL: shiftbv_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r1 = $r4, 0x1010101.@
; CHECK-NEXT:    insf $r3 = $r4, 7, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r3, 0x101010101010180
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <32 x i8> undef, i8 %1, i64 0
  %4 = shufflevector <32 x i8> %3, <32 x i8> %0, <32 x i32> <i32 63, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <32 x i8> %4
}

define void @shiftbt_one(<64 x i8>* noalias nocapture sret(<64 x i8>) align 32 %0, <64 x i8>* nocapture readonly %1, i8 %2) {
; CV1-LABEL: shiftbt_one:
; CV1:       # %bb.0:
; CV1-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    lo $r32r33r34r35 = 0[$r0]
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    zxbd $r0 = $r6
; CV1-NEXT:    zxbd $r2 = $r5
; CV1-NEXT:    zxbd $r3 = $r7
; CV1-NEXT:    srld $r9 = $r5, 8
; CV1-NEXT:    ;; # (end cycle 3)
; CV1-NEXT:    zxbd $r0 = $r34
; CV1-NEXT:    zxbd $r5 = $r33
; CV1-NEXT:    insf $r9 = $r0, 63, 56
; CV1-NEXT:    srld $r33 = $r33, 8
; CV1-NEXT:    ;; # (end cycle 4)
; CV1-NEXT:    zxbd $r0 = $r35
; CV1-NEXT:    srld $r8 = $r4, 8
; CV1-NEXT:    insf $r33 = $r0, 63, 56
; CV1-NEXT:    srld $r34 = $r34, 8
; CV1-NEXT:    ;; # (end cycle 5)
; CV1-NEXT:    srld $r10 = $r6, 8
; CV1-NEXT:    srld $r11 = $r7, 8
; CV1-NEXT:    srld $r32 = $r32, 8
; CV1-NEXT:    insf $r34 = $r0, 63, 56
; CV1-NEXT:    ;; # (end cycle 6)
; CV1-NEXT:    zxbd $r0 = $r4
; CV1-NEXT:    insf $r8 = $r2, 63, 56
; CV1-NEXT:    insf $r32 = $r5, 63, 56
; CV1-NEXT:    srld $r35 = $r35, 8
; CV1-NEXT:    ;; # (end cycle 7)
; CV1-NEXT:    insf $r10 = $r3, 63, 56
; CV1-NEXT:    insf $r11 = $r1, 63, 56
; CV1-NEXT:    ;; # (end cycle 8)
; CV1-NEXT:    so 32[$r15] = $r8r9r10r11
; CV1-NEXT:    insf $r35 = $r0, 63, 56
; CV1-NEXT:    ;; # (end cycle 9)
; CV1-NEXT:    so 0[$r15] = $r32r33r34r35
; CV1-NEXT:    copyd $r0 = $r15
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 10)
;
; CV2-LABEL: shiftbt_one:
; CV2:       # %bb.0:
; CV2-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    lo $r32r33r34r35 = 0[$r0]
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    zxbd $r0 = $r6
; CV2-NEXT:    zxbd $r2 = $r5
; CV2-NEXT:    zxbd $r3 = $r7
; CV2-NEXT:    srld $r9 = $r5, 8
; CV2-NEXT:    ;; # (end cycle 3)
; CV2-NEXT:    zxbd $r0 = $r34
; CV2-NEXT:    zxbd $r5 = $r33
; CV2-NEXT:    insf $r9 = $r0, 63, 56
; CV2-NEXT:    srld $r33 = $r33, 8
; CV2-NEXT:    ;; # (end cycle 4)
; CV2-NEXT:    zxbd $r0 = $r35
; CV2-NEXT:    srld $r8 = $r4, 8
; CV2-NEXT:    insf $r33 = $r0, 63, 56
; CV2-NEXT:    srld $r34 = $r34, 8
; CV2-NEXT:    ;; # (end cycle 5)
; CV2-NEXT:    srld $r10 = $r6, 8
; CV2-NEXT:    srld $r11 = $r7, 8
; CV2-NEXT:    srld $r32 = $r32, 8
; CV2-NEXT:    insf $r34 = $r0, 63, 56
; CV2-NEXT:    ;; # (end cycle 6)
; CV2-NEXT:    zxbd $r0 = $r4
; CV2-NEXT:    insf $r8 = $r2, 63, 56
; CV2-NEXT:    insf $r32 = $r5, 63, 56
; CV2-NEXT:    srld $r35 = $r35, 8
; CV2-NEXT:    ;; # (end cycle 7)
; CV2-NEXT:    insf $r10 = $r3, 63, 56
; CV2-NEXT:    insf $r11 = $r1, 63, 56
; CV2-NEXT:    insf $r35 = $r0, 63, 56
; CV2-NEXT:    ;; # (end cycle 8)
; CV2-NEXT:    so 32[$r15] = $r8r9r10r11
; CV2-NEXT:    ;; # (end cycle 9)
; CV2-NEXT:    so 0[$r15] = $r32r33r34r35
; CV2-NEXT:    copyd $r0 = $r15
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 10)
  %4 = load <64 x i8>, <64 x i8>* %1
  %5 = insertelement <64 x i8> undef, i8 %2, i64 0
  %6 = shufflevector <64 x i8> %5, <64 x i8> %4, <64 x i32> <i32 65, i32 66, i32 67, i32 68, i32 69, i32 70, i32 71, i32 72, i32 73, i32 74, i32 75, i32 76, i32 77, i32 78, i32 79, i32 80, i32 81, i32 82, i32 83, i32 84, i32 85, i32 86, i32 87, i32 88, i32 89, i32 90, i32 91, i32 92, i32 93, i32 94, i32 95, i32 96, i32 97, i32 98, i32 99, i32 100, i32 101, i32 102, i32 103, i32 104, i32 105, i32 106, i32 107, i32 108, i32 109, i32 110, i32 111, i32 112, i32 113, i32 114, i32 115, i32 116, i32 117, i32 118, i32 119, i32 120, i32 121, i32 122, i32 123, i32 124, i32 125, i32 126, i32 127, i32 0>
  store <64 x i8> %6, <64 x i8>* %0
  ret void
}

define void @shiftbt_last(<64 x i8>* noalias nocapture sret(<64 x i8>) align 32 %0, <64 x i8>* nocapture readonly %1, i8 %2) {
; CHECK-LABEL: shiftbt_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld $r0 = 56[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 7, 0
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1010101.@
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x101010101010180
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    copyd $r4 = $r1
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    so 0[$r15] = $r0r1r2r3
; CHECK-NEXT:    copyd $r5 = $r1
; CHECK-NEXT:    copyd $r6 = $r1
; CHECK-NEXT:    copyd $r7 = $r1
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    so 32[$r15] = $r4r5r6r7
; CHECK-NEXT:    copyd $r0 = $r15
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 6)
  %4 = load <64 x i8>, <64 x i8>* %1
  %5 = insertelement <64 x i8> undef, i8 %2, i64 0
  %6 = shufflevector <64 x i8> %5, <64 x i8> %4, <64 x i32> <i32 127, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  store <64 x i8> %6, <64 x i8>* %0
  ret void
}

define <4 x i16> @shifthq_one(<4 x i16> %0, i16 %1) {
; CHECK-LABEL: shifthq_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r0 = $r0, 16
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 63, 48
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <4 x i16> undef, i16 %1, i64 0
  %4 = shufflevector <4 x i16> %3, <4 x i16> %0, <4 x i32> <i32 5, i32 6, i32 7, i32 0>
  ret <4 x i16> %4
}

define <4 x i16> @shifthq_last(<4 x i16> %0, i16 %1) {
; CHECK-LABEL: shifthq_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 15, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x201020102018040
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <4 x i16> undef, i16 %1, i64 0
  %4 = shufflevector <4 x i16> %3, <4 x i16> %0, <4 x i32> <i32 7, i32 0, i32 0, i32 0>
  ret <4 x i16> %4
}

define <8 x i16> @shiftho_one(<8 x i16> %0, i16 %1) {
; CHECK-LABEL: shiftho_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r0 = $r0, 16
; CHECK-NEXT:    srld $r1 = $r1, 16
; CHECK-NEXT:    zxhd $r3 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r3, 63, 48
; CHECK-NEXT:    insf $r1 = $r2, 63, 48
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <8 x i16> undef, i16 %1, i64 0
  %4 = shufflevector <8 x i16> %3, <8 x i16> %0, <8 x i32> <i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0>
  ret <8 x i16> %4
}

define <8 x i16> @shiftho_last(<8 x i16> %0, i16 %1) {
; CHECK-LABEL: shiftho_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r1 = $r2, 15, 0
; CHECK-NEXT:    sbmm8 $r3 = $r2, 0x2010201.@
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r1, 0x201020102018040
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <8 x i16> undef, i16 %1, i64 0
  %4 = shufflevector <8 x i16> %3, <8 x i16> %0, <8 x i32> <i32 15, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <8 x i16> %4
}

define <16 x i16> @shifthx_one(<16 x i16> %0, i16 %1) {
; CV1-LABEL: shifthx_one:
; CV1:       # %bb.0:
; CV1-NEXT:    srld $r0 = $r0, 16
; CV1-NEXT:    srld $r1 = $r1, 16
; CV1-NEXT:    zxhd $r5 = $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    insf $r0 = $r5, 63, 48
; CV1-NEXT:    srld $r2 = $r2, 16
; CV1-NEXT:    zxhd $r5 = $r2
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    insf $r1 = $r5, 63, 48
; CV1-NEXT:    srld $r3 = $r3, 16
; CV1-NEXT:    zxhd $r5 = $r3
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    insf $r2 = $r5, 63, 48
; CV1-NEXT:    insf $r3 = $r4, 63, 48
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 3)
;
; CV2-LABEL: shifthx_one:
; CV2:       # %bb.0:
; CV2-NEXT:    srld $r0 = $r0, 16
; CV2-NEXT:    srld $r1 = $r1, 16
; CV2-NEXT:    zxhd $r5 = $r1
; CV2-NEXT:    zxhd $r6 = $r2
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    insf $r0 = $r5, 63, 48
; CV2-NEXT:    srld $r2 = $r2, 16
; CV2-NEXT:    srld $r3 = $r3, 16
; CV2-NEXT:    zxhd $r7 = $r3
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    insf $r1 = $r6, 63, 48
; CV2-NEXT:    insf $r2 = $r7, 63, 48
; CV2-NEXT:    insf $r3 = $r4, 63, 48
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <16 x i16> undef, i16 %1, i64 0
  %4 = shufflevector <16 x i16> %3, <16 x i16> %0, <16 x i32> <i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 0>
  ret <16 x i16> %4
}

define <16 x i16> @shifthx_last(<16 x i16> %0, i16 %1) {
; CHECK-LABEL: shifthx_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r1 = $r4, 0x2010201.@
; CHECK-NEXT:    insf $r3 = $r4, 15, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r3, 0x201020102018040
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <16 x i16> undef, i16 %1, i64 0
  %4 = shufflevector <16 x i16> %3, <16 x i16> %0, <16 x i32> <i32 31, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <16 x i16> %4
}

define void @shifthv_one(<32 x i16>* noalias nocapture sret(<32 x i16>) align 32 %0, <32 x i16>* nocapture readonly %1, i8 %2) {
; CV1-LABEL: shifthv_one:
; CV1:       # %bb.0:
; CV1-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV1-NEXT:    sxbd $r16 = $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    lo $r8r9r10r11 = 0[$r0]
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    zxhd $r0 = $r6
; CV1-NEXT:    srld $r1 = $r5, 16
; CV1-NEXT:    zxhd $r2 = $r5
; CV1-NEXT:    ;; # (end cycle 3)
; CV1-NEXT:    zxhd $r0 = $r10
; CV1-NEXT:    insf $r1 = $r0, 63, 48
; CV1-NEXT:    srld $r32 = $r8, 16
; CV1-NEXT:    srld $r33 = $r9, 16
; CV1-NEXT:    ;; # (end cycle 4)
; CV1-NEXT:    srld $r0 = $r4, 16
; CV1-NEXT:    zxhd $r3 = $r9
; CV1-NEXT:    insf $r33 = $r0, 63, 48
; CV1-NEXT:    srld $r34 = $r10, 16
; CV1-NEXT:    ;; # (end cycle 5)
; CV1-NEXT:    insf $r0 = $r2, 63, 48
; CV1-NEXT:    srld $r2 = $r6, 16
; CV1-NEXT:    insf $r32 = $r3, 63, 48
; CV1-NEXT:    srld $r35 = $r11, 16
; CV1-NEXT:    ;; # (end cycle 6)
; CV1-NEXT:    zxhd $r3 = $r7
; CV1-NEXT:    zxhd $r4 = $r4
; CV1-NEXT:    ;; # (end cycle 7)
; CV1-NEXT:    insf $r2 = $r3, 63, 48
; CV1-NEXT:    zxhd $r3 = $r11
; CV1-NEXT:    ;; # (end cycle 8)
; CV1-NEXT:    srld $r3 = $r7, 16
; CV1-NEXT:    insf $r34 = $r3, 63, 48
; CV1-NEXT:    insf $r35 = $r4, 63, 48
; CV1-NEXT:    ;; # (end cycle 9)
; CV1-NEXT:    so 0[$r15] = $r32r33r34r35
; CV1-NEXT:    insf $r3 = $r16, 63, 48
; CV1-NEXT:    ;; # (end cycle 10)
; CV1-NEXT:    so 32[$r15] = $r0r1r2r3
; CV1-NEXT:    copyd $r0 = $r15
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 11)
;
; CV2-LABEL: shifthv_one:
; CV2:       # %bb.0:
; CV2-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV2-NEXT:    sxbd $r16 = $r1
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    lo $r8r9r10r11 = 0[$r0]
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    zxhd $r0 = $r6
; CV2-NEXT:    srld $r1 = $r5, 16
; CV2-NEXT:    zxhd $r2 = $r5
; CV2-NEXT:    zxhd $r3 = $r7
; CV2-NEXT:    ;; # (end cycle 3)
; CV2-NEXT:    zxhd $r0 = $r10
; CV2-NEXT:    insf $r1 = $r0, 63, 48
; CV2-NEXT:    zxhd $r5 = $r9
; CV2-NEXT:    srld $r9 = $r9, 16
; CV2-NEXT:    ;; # (end cycle 4)
; CV2-NEXT:    srld $r0 = $r4, 16
; CV2-NEXT:    srld $r8 = $r8, 16
; CV2-NEXT:    insf $r9 = $r0, 63, 48
; CV2-NEXT:    srld $r10 = $r10, 16
; CV2-NEXT:    ;; # (end cycle 5)
; CV2-NEXT:    insf $r0 = $r2, 63, 48
; CV2-NEXT:    srld $r2 = $r6, 16
; CV2-NEXT:    zxhd $r4 = $r4
; CV2-NEXT:    insf $r8 = $r5, 63, 48
; CV2-NEXT:    ;; # (end cycle 6)
; CV2-NEXT:    insf $r2 = $r3, 63, 48
; CV2-NEXT:    zxhd $r3 = $r11
; CV2-NEXT:    srld $r11 = $r11, 16
; CV2-NEXT:    ;; # (end cycle 7)
; CV2-NEXT:    srld $r3 = $r7, 16
; CV2-NEXT:    insf $r10 = $r3, 63, 48
; CV2-NEXT:    insf $r11 = $r4, 63, 48
; CV2-NEXT:    ;; # (end cycle 8)
; CV2-NEXT:    so 0[$r15] = $r8r9r10r11
; CV2-NEXT:    insf $r3 = $r16, 63, 48
; CV2-NEXT:    ;; # (end cycle 9)
; CV2-NEXT:    so 32[$r15] = $r0r1r2r3
; CV2-NEXT:    copyd $r0 = $r15
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 10)
  %4 = load <32 x i16>, <32 x i16>* %1
  %5 = sext i8 %2 to i16
  %6 = insertelement <32 x i16> undef, i16 %5, i64 0
  %7 = shufflevector <32 x i16> %6, <32 x i16> %4, <32 x i32> <i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 0>
  store <32 x i16> %7, <32 x i16>* %0
  ret void
}

define void @shifthv_last(<32 x i16>* noalias nocapture sret(<32 x i16>) align 32 %0, <32 x i16>* nocapture readonly %1, i8 %2) {
; CHECK-LABEL: shifthv_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld $r0 = 56[$r0]
; CHECK-NEXT:    sxbd $r1 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 15, 0
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x2010201.@
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x201020102018040
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    copyd $r4 = $r1
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    so 0[$r15] = $r0r1r2r3
; CHECK-NEXT:    copyd $r5 = $r1
; CHECK-NEXT:    copyd $r6 = $r1
; CHECK-NEXT:    copyd $r7 = $r1
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    so 32[$r15] = $r4r5r6r7
; CHECK-NEXT:    copyd $r0 = $r15
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 6)
  %4 = load <32 x i16>, <32 x i16>* %1
  %5 = sext i8 %2 to i16
  %6 = insertelement <32 x i16> undef, i16 %5, i64 0
  %7 = shufflevector <32 x i16> %6, <32 x i16> %4, <32 x i32> <i32 63, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  store <32 x i16> %7, <32 x i16>* %0
  ret void
}

define <2 x i32> @shiftwp_one(<2 x i32> %0, i32 %1) {
; CHECK-LABEL: shiftwp_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r0, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <2 x i32> undef, i32 %1, i64 0
  %4 = shufflevector <2 x i32> %3, <2 x i32> %0, <2 x i32> <i32 3, i32 0>
  ret <2 x i32> %4
}

define <4 x i32> @shiftwq_one(<4 x i32> %0, i32 %1) {
; CHECK-LABEL: shiftwq_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 31, 0
; CHECK-NEXT:    srad $r3 = $r1, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x804020180402010
; CHECK-NEXT:    insf $r3 = $r2, 63, 32
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <4 x i32> undef, i32 %1, i64 0
  %4 = shufflevector <4 x i32> %3, <4 x i32> %0, <4 x i32> <i32 5, i32 6, i32 7, i32 0>
  ret <4 x i32> %4
}

define <4 x i32> @shiftwq_last(<4 x i32> %0, i32 %1) {
; CHECK-LABEL: shiftwq_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r1, 32
; CHECK-NEXT:    copyd $r3 = $r2
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r3, 63, 32
; CHECK-NEXT:    insf $r3 = $r3, 63, 32
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <4 x i32> undef, i32 %1, i64 0
  %4 = shufflevector <4 x i32> %3, <4 x i32> %0, <4 x i32> <i32 7, i32 0, i32 0, i32 0>
  ret <4 x i32> %4
}

define <8 x i32> @shiftwo_one(<8 x i32> %0, i32 %1) {
; CV1-LABEL: shiftwo_one:
; CV1:       # %bb.0:
; CV1-NEXT:    insf $r0 = $r1, 31, 0
; CV1-NEXT:    insf $r1 = $r2, 31, 0
; CV1-NEXT:    srad $r5 = $r3, 32
; CV1-NEXT:    copyd $r6 = $r2
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    insf $r5 = $r4, 63, 32
; CV1-NEXT:    insf $r6 = $r3, 31, 0
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    sbmm8 $r0 = $r0, 0x804020180402010
; CV1-NEXT:    sbmm8 $r2 = $r6, 0x804020180402010
; CV1-NEXT:    copyd $r3 = $r5
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    sbmm8 $r1 = $r1, 0x804020180402010
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 3)
;
; CV2-LABEL: shiftwo_one:
; CV2:       # %bb.0:
; CV2-NEXT:    insf $r0 = $r1, 31, 0
; CV2-NEXT:    insf $r1 = $r2, 31, 0
; CV2-NEXT:    srad $r5 = $r3, 32
; CV2-NEXT:    copyd $r6 = $r2
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    sbmm8 $r0 = $r0, 0x804020180402010
; CV2-NEXT:    sbmm8 $r1 = $r1, 0x804020180402010
; CV2-NEXT:    insf $r5 = $r4, 63, 32
; CV2-NEXT:    insf $r6 = $r3, 31, 0
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    sbmm8 $r2 = $r6, 0x804020180402010
; CV2-NEXT:    copyd $r3 = $r5
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <8 x i32> undef, i32 %1, i64 0
  %4 = shufflevector <8 x i32> %3, <8 x i32> %0, <8 x i32> <i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0>
  ret <8 x i32> %4
}

define <8 x i32> @shiftwo_last(<8 x i32> %0, i32 %1) {
; CHECK-LABEL: shiftwo_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r3, 32
; CHECK-NEXT:    copyd $r1 = $r4
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    insf $r1 = $r1, 63, 32
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <8 x i32> undef, i32 %1, i64 0
  %4 = shufflevector <8 x i32> %3, <8 x i32> %0, <8 x i32> <i32 15, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <8 x i32> %4
}

define void @shiftwx_one(<16 x i32>* noalias nocapture sret(<16 x i32>) align 32 %0, <16 x i32>* nocapture readonly %1, i16 %2) {
; CV1-LABEL: shiftwx_one:
; CV1:       # %bb.0:
; CV1-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV1-NEXT:    sxhd $r16 = $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    lo $r8r9r10r11 = 0[$r0]
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    srld $r0 = $r4, 32
; CV1-NEXT:    srld $r1 = $r5, 32
; CV1-NEXT:    srld $r2 = $r6, 32
; CV1-NEXT:    srld $r3 = $r7, 32
; CV1-NEXT:    ;; # (end cycle 3)
; CV1-NEXT:    srld $r32 = $r8, 32
; CV1-NEXT:    srld $r33 = $r9, 32
; CV1-NEXT:    srld $r34 = $r10, 32
; CV1-NEXT:    srld $r35 = $r11, 32
; CV1-NEXT:    ;; # (end cycle 4)
; CV1-NEXT:    insf $r0 = $r5, 63, 32
; CV1-NEXT:    insf $r34 = $r11, 63, 32
; CV1-NEXT:    ;; # (end cycle 5)
; CV1-NEXT:    insf $r1 = $r6, 63, 32
; CV1-NEXT:    insf $r35 = $r4, 63, 32
; CV1-NEXT:    ;; # (end cycle 6)
; CV1-NEXT:    insf $r2 = $r7, 63, 32
; CV1-NEXT:    insf $r32 = $r9, 63, 32
; CV1-NEXT:    ;; # (end cycle 7)
; CV1-NEXT:    insf $r3 = $r16, 63, 32
; CV1-NEXT:    insf $r33 = $r10, 63, 32
; CV1-NEXT:    ;; # (end cycle 8)
; CV1-NEXT:    so 32[$r15] = $r0r1r2r3
; CV1-NEXT:    ;; # (end cycle 9)
; CV1-NEXT:    so 0[$r15] = $r32r33r34r35
; CV1-NEXT:    copyd $r0 = $r15
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 10)
;
; CV2-LABEL: shiftwx_one:
; CV2:       # %bb.0:
; CV2-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV2-NEXT:    sxhd $r16 = $r1
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    lo $r8r9r10r11 = 0[$r0]
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    srld $r0 = $r4, 32
; CV2-NEXT:    srld $r1 = $r5, 32
; CV2-NEXT:    srld $r2 = $r6, 32
; CV2-NEXT:    srld $r3 = $r7, 32
; CV2-NEXT:    ;; # (end cycle 3)
; CV2-NEXT:    srld $r32 = $r8, 32
; CV2-NEXT:    srld $r33 = $r9, 32
; CV2-NEXT:    srld $r34 = $r10, 32
; CV2-NEXT:    srld $r35 = $r11, 32
; CV2-NEXT:    ;; # (end cycle 4)
; CV2-NEXT:    insf $r0 = $r5, 63, 32
; CV2-NEXT:    insf $r1 = $r6, 63, 32
; CV2-NEXT:    insf $r34 = $r11, 63, 32
; CV2-NEXT:    insf $r35 = $r4, 63, 32
; CV2-NEXT:    ;; # (end cycle 5)
; CV2-NEXT:    insf $r2 = $r7, 63, 32
; CV2-NEXT:    insf $r3 = $r16, 63, 32
; CV2-NEXT:    insf $r32 = $r9, 63, 32
; CV2-NEXT:    insf $r33 = $r10, 63, 32
; CV2-NEXT:    ;; # (end cycle 6)
; CV2-NEXT:    so 32[$r15] = $r0r1r2r3
; CV2-NEXT:    ;; # (end cycle 7)
; CV2-NEXT:    so 0[$r15] = $r32r33r34r35
; CV2-NEXT:    copyd $r0 = $r15
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 8)
  %4 = load <16 x i32>, <16 x i32>* %1
  %5 = sext i16 %2 to i32
  %6 = insertelement <16 x i32> undef, i32 %5, i64 0
  %7 = shufflevector <16 x i32> %6, <16 x i32> %4, <16 x i32> <i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 0>
  store <16 x i32> %7, <16 x i32>* %0
  ret void
}

define void @shiftwx_last(<16 x i32>* noalias nocapture sret(<16 x i32>) align 32 %0, <16 x i32>* nocapture readonly %1, i16 %2) {
; CHECK-LABEL: shiftwx_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sxhd $r1 = $r1
; CHECK-NEXT:    ld $r3 = 56[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srld $r0 = $r3, 32
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    insf $r1 = $r1, 63, 32
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    copyq $r4r5 = $r2, $r3
; CHECK-NEXT:    ;; # (end cycle 6)
; CHECK-NEXT:    so 0[$r15] = $r0r1r2r3
; CHECK-NEXT:    copyq $r6r7 = $r2, $r3
; CHECK-NEXT:    ;; # (end cycle 7)
; CHECK-NEXT:    so 32[$r15] = $r4r5r6r7
; CHECK-NEXT:    copyd $r0 = $r15
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 8)
  %4 = load <16 x i32>, <16 x i32>* %1
  %5 = sext i16 %2 to i32
  %6 = insertelement <16 x i32> undef, i32 %5, i64 0
  %7 = shufflevector <16 x i32> %6, <16 x i32> %4, <16 x i32> <i32 31, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  store <16 x i32> %7, <16 x i32>* %0
  ret void
}

define <2 x i64> @shiftdp_one(<2 x i64> %0, i64 %1) {
; CHECK-LABEL: shiftdp_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    copyd $r1 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %3 = insertelement <2 x i64> undef, i64 %1, i64 0
  %4 = shufflevector <2 x i64> %3, <2 x i64> %0, <2 x i32> <i32 3, i32 0>
  ret <2 x i64> %4
}

define <4 x i64> @shiftdq_one(<4 x i64> %0, i64 %1) {
; CHECK-LABEL: shiftdq_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    copyd $r1 = $r2
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    copyd $r3 = $r4
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %3 = insertelement <4 x i64> undef, i64 %1, i64 0
  %4 = shufflevector <4 x i64> %3, <4 x i64> %0, <4 x i32> <i32 5, i32 6, i32 7, i32 0>
  ret <4 x i64> %4
}

define <4 x i64> @shiftdq_last(<4 x i64> %0, i64 %1) {
; CHECK-LABEL: shiftdq_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r3
; CHECK-NEXT:    copyd $r1 = $r4
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <4 x i64> undef, i64 %1, i64 0
  %4 = shufflevector <4 x i64> %3, <4 x i64> %0, <4 x i32> <i32 7, i32 0, i32 0, i32 0>
  ret <4 x i64> %4
}

define <4 x half> @shiftfhq_one(<4 x half> %0, half %1) {
; CHECK-LABEL: shiftfhq_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r0 = $r0, 16
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 63, 48
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <4 x half> undef, half %1, i64 0
  %4 = shufflevector <4 x half> %3, <4 x half> %0, <4 x i32> <i32 5, i32 6, i32 7, i32 0>
  ret <4 x half> %4
}

define void @shiftdo_one(<8 x i64>* noalias nocapture sret(<8 x i64>) align 32 %0, <8 x i64>* nocapture readonly %1, double %2) {
; CHECK-LABEL: shiftdo_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CHECK-NEXT:    fixedd.rz $r3 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lo $r8r9r10r11 = 0[$r0]
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r0 = $r5
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    copyd $r1 = $r6
; CHECK-NEXT:    copyd $r8 = $r9
; CHECK-NEXT:    copyd $r9 = $r10
; CHECK-NEXT:    copyd $r10 = $r11
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r2 = $r7
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    so 32[$r15] = $r0r1r2r3
; CHECK-NEXT:    copyd $r11 = $r4
; CHECK-NEXT:    ;; # (end cycle 6)
; CHECK-NEXT:    so 0[$r15] = $r8r9r10r11
; CHECK-NEXT:    copyd $r0 = $r15
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 7)
  %4 = load <8 x i64>, <8 x i64>* %1
  %5 = fptosi double %2 to i64
  %6 = insertelement <8 x i64> undef, i64 %5, i64 0
  %7 = shufflevector <8 x i64> %6, <8 x i64> %4, <8 x i32> <i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0>
  store <8 x i64> %7, <8 x i64>* %0
  ret void
}

define void @shiftdo_last(<8 x i64>* noalias nocapture sret(<8 x i64>) align 32 %0, <8 x i64>* nocapture readonly %1, double %2) {
; CHECK-LABEL: shiftdo_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld $r0 = 56[$r0]
; CHECK-NEXT:    fixedd.rz $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    copyd $r4 = $r1
; CHECK-NEXT:    copyd $r5 = $r1
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    so 0[$r15] = $r0r1r2r3
; CHECK-NEXT:    copyd $r6 = $r1
; CHECK-NEXT:    copyd $r7 = $r1
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    so 32[$r15] = $r4r5r6r7
; CHECK-NEXT:    copyd $r0 = $r15
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 6)
  %4 = load <8 x i64>, <8 x i64>* %1
  %5 = fptosi double %2 to i64
  %6 = insertelement <8 x i64> undef, i64 %5, i64 0
  %7 = shufflevector <8 x i64> %6, <8 x i64> %4, <8 x i32> <i32 15, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  store <8 x i64> %7, <8 x i64>* %0
  ret void
}

define <4 x half> @shiftfhq_last(<4 x half> %0, half %1) {
; CHECK-LABEL: shiftfhq_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 15, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x201020102018040
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <4 x half> undef, half %1, i64 0
  %4 = shufflevector <4 x half> %3, <4 x half> %0, <4 x i32> <i32 7, i32 0, i32 0, i32 0>
  ret <4 x half> %4
}

define <8 x half> @shiftfho_one(<8 x half> %0, half %1) {
; CHECK-LABEL: shiftfho_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r0 = $r0, 16
; CHECK-NEXT:    srld $r3 = $r1, 16
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 63, 48
; CHECK-NEXT:    insf $r3 = $r2, 63, 48
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <8 x half> undef, half %1, i64 0
  %4 = shufflevector <8 x half> %3, <8 x half> %0, <8 x i32> <i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0>
  ret <8 x half> %4
}

define <8 x half> @shiftfho_last(<8 x half> %0, half %1) {
; CHECK-LABEL: shiftfho_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r1 = $r2, 15, 0
; CHECK-NEXT:    sbmm8 $r3 = $r2, 0x2010201.@
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r1, 0x201020102018040
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <8 x half> undef, half %1, i64 0
  %4 = shufflevector <8 x half> %3, <8 x half> %0, <8 x i32> <i32 15, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <8 x half> %4
}

define <16 x half> @shiftfhx_one(<16 x half> %0, half %1) {
; CV1-LABEL: shiftfhx_one:
; CV1:       # %bb.0:
; CV1-NEXT:    srld $r0 = $r0, 16
; CV1-NEXT:    srld $r5 = $r3, 16
; CV1-NEXT:    srld $r6 = $r2, 16
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    srld $r3 = $r1, 16
; CV1-NEXT:    insf $r5 = $r4, 63, 48
; CV1-NEXT:    insf $r6 = $r3, 63, 48
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    insf $r0 = $r1, 63, 48
; CV1-NEXT:    insf $r3 = $r2, 63, 48
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    copyd $r1 = $r3
; CV1-NEXT:    copyd $r2 = $r6
; CV1-NEXT:    copyd $r3 = $r5
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 3)
;
; CV2-LABEL: shiftfhx_one:
; CV2:       # %bb.0:
; CV2-NEXT:    srld $r0 = $r0, 16
; CV2-NEXT:    srld $r5 = $r3, 16
; CV2-NEXT:    srld $r6 = $r2, 16
; CV2-NEXT:    srld $r7 = $r1, 16
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    insf $r0 = $r1, 63, 48
; CV2-NEXT:    insf $r5 = $r4, 63, 48
; CV2-NEXT:    insf $r6 = $r3, 63, 48
; CV2-NEXT:    insf $r7 = $r2, 63, 48
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    copyd $r1 = $r7
; CV2-NEXT:    copyd $r2 = $r6
; CV2-NEXT:    copyd $r3 = $r5
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <16 x half> undef, half %1, i64 0
  %4 = shufflevector <16 x half> %3, <16 x half> %0, <16 x i32> <i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 0>
  ret <16 x half> %4
}

define <16 x half> @shiftfhx_last(<16 x half> %0, half %1) {
; CHECK-LABEL: shiftfhx_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r1 = $r4, 0x2010201.@
; CHECK-NEXT:    insf $r3 = $r4, 15, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r3, 0x201020102018040
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <16 x half> undef, half %1, i64 0
  %4 = shufflevector <16 x half> %3, <16 x half> %0, <16 x i32> <i32 31, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <16 x half> %4
}

define void @shiftfhv_one(<32 x half>* noalias nocapture sret(<32 x half>) align 32 %0, <32 x half>* nocapture readonly %1, i8 %2) {
; CV1-LABEL: shiftfhv_one:
; CV1:       # %bb.0:
; CV1-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV1-NEXT:    sxbd $r1 = $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    lo $r0r1r2r3 = 0[$r0]
; CV1-NEXT:    floatw.rn $r8 = $r1, 0
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    extfz $r9 = $r4, 47, 32
; CV1-NEXT:    srld $r11 = $r4, 48
; CV1-NEXT:    extfz $r16 = $r5, 47, 32
; CV1-NEXT:    srlw $r32 = $r4, 16
; CV1-NEXT:    ;; # (end cycle 3)
; CV1-NEXT:    insf $r11 = $r5, 31, 16
; CV1-NEXT:    insf $r32 = $r9, 31, 16
; CV1-NEXT:    srld $r33 = $r2, 48
; CV1-NEXT:    srld $r34 = $r3, 48
; CV1-NEXT:    ;; # (end cycle 4)
; CV1-NEXT:    srlw $r10 = $r2, 16
; CV1-NEXT:    srlw $r11 = $r3, 16
; CV1-NEXT:    insf $r32 = $r11, 63, 32
; CV1-NEXT:    insf $r34 = $r4, 31, 16
; CV1-NEXT:    ;; # (end cycle 5)
; CV1-NEXT:    extfz $r4 = $r3, 47, 32
; CV1-NEXT:    srld $r17 = $r5, 48
; CV1-NEXT:    srld $r35 = $r0, 48
; CV1-NEXT:    fnarrowwh.rn $r36 = $r8
; CV1-NEXT:    ;; # (end cycle 6)
; CV1-NEXT:    srld $r4 = $r7, 48
; CV1-NEXT:    extfz $r8 = $r2, 47, 32
; CV1-NEXT:    insf $r11 = $r4, 31, 16
; CV1-NEXT:    srld $r37 = $r6, 48
; CV1-NEXT:    ;; # (end cycle 7)
; CV1-NEXT:    srlw $r8 = $r0, 16
; CV1-NEXT:    srlw $r9 = $r1, 16
; CV1-NEXT:    insf $r10 = $r8, 31, 16
; CV1-NEXT:    insf $r33 = $r3, 31, 16
; CV1-NEXT:    ;; # (end cycle 8)
; CV1-NEXT:    extfz $r3 = $r0, 47, 32
; CV1-NEXT:    insf $r11 = $r34, 63, 32
; CV1-NEXT:    srlw $r34 = $r6, 16
; CV1-NEXT:    ;; # (end cycle 9)
; CV1-NEXT:    extfz $r0 = $r6, 47, 32
; CV1-NEXT:    insf $r35 = $r1, 31, 16
; CV1-NEXT:    ;; # (end cycle 10)
; CV1-NEXT:    srld $r0 = $r1, 48
; CV1-NEXT:    insf $r8 = $r3, 31, 16
; CV1-NEXT:    insf $r34 = $r0, 31, 16
; CV1-NEXT:    ;; # (end cycle 11)
; CV1-NEXT:    insf $r8 = $r35, 63, 32
; CV1-NEXT:    insf $r10 = $r33, 63, 32
; CV1-NEXT:    srlw $r33 = $r5, 16
; CV1-NEXT:    srlw $r35 = $r7, 16
; CV1-NEXT:    ;; # (end cycle 12)
; CV1-NEXT:    insf $r0 = $r2, 31, 16
; CV1-NEXT:    extfz $r3 = $r7, 47, 32
; CV1-NEXT:    ;; # (end cycle 13)
; CV1-NEXT:    extfz $r2 = $r1, 47, 32
; CV1-NEXT:    insf $r33 = $r16, 31, 16
; CV1-NEXT:    ;; # (end cycle 14)
; CV1-NEXT:    insf $r17 = $r6, 31, 16
; CV1-NEXT:    insf $r37 = $r7, 31, 16
; CV1-NEXT:    ;; # (end cycle 15)
; CV1-NEXT:    insf $r4 = $r36, 31, 16
; CV1-NEXT:    insf $r35 = $r3, 31, 16
; CV1-NEXT:    ;; # (end cycle 16)
; CV1-NEXT:    insf $r9 = $r2, 31, 16
; CV1-NEXT:    insf $r33 = $r17, 63, 32
; CV1-NEXT:    ;; # (end cycle 17)
; CV1-NEXT:    insf $r34 = $r37, 63, 32
; CV1-NEXT:    insf $r35 = $r4, 63, 32
; CV1-NEXT:    ;; # (end cycle 18)
; CV1-NEXT:    so 32[$r15] = $r32r33r34r35
; CV1-NEXT:    insf $r9 = $r0, 63, 32
; CV1-NEXT:    ;; # (end cycle 19)
; CV1-NEXT:    so 0[$r15] = $r8r9r10r11
; CV1-NEXT:    copyd $r0 = $r15
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 20)
;
; CV2-LABEL: shiftfhv_one:
; CV2:       # %bb.0:
; CV2-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV2-NEXT:    sxbd $r1 = $r1
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    lo $r8r9r10r11 = 0[$r0]
; CV2-NEXT:    floatw.rn $r3 = $r1, 0
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    srlw $r0 = $r4, 16
; CV2-NEXT:    srld $r1 = $r4, 48
; CV2-NEXT:    extfz $r2 = $r4, 47, 32
; CV2-NEXT:    srld $r16 = $r5, 48
; CV2-NEXT:    ;; # (end cycle 3)
; CV2-NEXT:    insf $r0 = $r2, 31, 16
; CV2-NEXT:    insf $r1 = $r5, 31, 16
; CV2-NEXT:    srld $r2 = $r10, 48
; CV2-NEXT:    srld $r32 = $r11, 48
; CV2-NEXT:    ;; # (end cycle 4)
; CV2-NEXT:    extfz $r4 = $r11, 47, 32
; CV2-NEXT:    extfz $r17 = $r10, 47, 32
; CV2-NEXT:    insf $r32 = $r4, 31, 16
; CV2-NEXT:    srlw $r34 = $r10, 16
; CV2-NEXT:    ;; # (end cycle 5)
; CV2-NEXT:    insf $r0 = $r1, 63, 32
; CV2-NEXT:    srlw $r1 = $r5, 16
; CV2-NEXT:    insf $r2 = $r11, 31, 16
; CV2-NEXT:    srlw $r35 = $r11, 16
; CV2-NEXT:    ;; # (end cycle 6)
; CV2-NEXT:    srld $r4 = $r6, 48
; CV2-NEXT:    extfz $r5 = $r5, 47, 32
; CV2-NEXT:    insf $r34 = $r17, 31, 16
; CV2-NEXT:    insf $r35 = $r4, 31, 16
; CV2-NEXT:    ;; # (end cycle 7)
; CV2-NEXT:    insf $r1 = $r5, 31, 16
; CV2-NEXT:    extfz $r5 = $r8, 47, 32
; CV2-NEXT:    insf $r34 = $r2, 63, 32
; CV2-NEXT:    insf $r35 = $r32, 63, 32
; CV2-NEXT:    ;; # (end cycle 8)
; CV2-NEXT:    srlw $r2 = $r6, 16
; CV2-NEXT:    insf $r4 = $r7, 31, 16
; CV2-NEXT:    extfz $r11 = $r6, 47, 32
; CV2-NEXT:    srlw $r32 = $r8, 16
; CV2-NEXT:    ;; # (end cycle 9)
; CV2-NEXT:    insf $r2 = $r11, 31, 16
; CV2-NEXT:    srld $r5 = $r8, 48
; CV2-NEXT:    insf $r16 = $r6, 31, 16
; CV2-NEXT:    insf $r32 = $r5, 31, 16
; CV2-NEXT:    ;; # (end cycle 10)
; CV2-NEXT:    insf $r2 = $r4, 63, 32
; CV2-NEXT:    srld $r4 = $r7, 48
; CV2-NEXT:    insf $r5 = $r9, 31, 16
; CV2-NEXT:    fnarrowwh.rn $r6 = $r3
; CV2-NEXT:    ;; # (end cycle 11)
; CV2-NEXT:    srlw $r3 = $r7, 16
; CV2-NEXT:    insf $r4 = $r6, 31, 16
; CV2-NEXT:    extfz $r7 = $r7, 47, 32
; CV2-NEXT:    insf $r32 = $r5, 63, 32
; CV2-NEXT:    ;; # (end cycle 12)
; CV2-NEXT:    insf $r3 = $r7, 31, 16
; CV2-NEXT:    srld $r5 = $r9, 48
; CV2-NEXT:    extfz $r6 = $r9, 47, 32
; CV2-NEXT:    srlw $r33 = $r9, 16
; CV2-NEXT:    ;; # (end cycle 13)
; CV2-NEXT:    insf $r1 = $r16, 63, 32
; CV2-NEXT:    insf $r3 = $r4, 63, 32
; CV2-NEXT:    insf $r5 = $r10, 31, 16
; CV2-NEXT:    insf $r33 = $r6, 31, 16
; CV2-NEXT:    ;; # (end cycle 14)
; CV2-NEXT:    so 32[$r15] = $r0r1r2r3
; CV2-NEXT:    insf $r33 = $r5, 63, 32
; CV2-NEXT:    ;; # (end cycle 15)
; CV2-NEXT:    so 0[$r15] = $r32r33r34r35
; CV2-NEXT:    copyd $r0 = $r15
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 16)
  %4 = load <32 x half>, <32 x half>* %1
  %5 = sitofp i8 %2 to half
  %6 = insertelement <32 x half> undef, half %5, i64 0
  %7 = shufflevector <32 x half> %6, <32 x half> %4, <32 x i32> <i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63, i32 0>
  store <32 x half> %7, <32 x half>* %0
  ret void
}

define void @shiftfhv_last(<32 x half>* noalias nocapture sret(<32 x half>) align 32 %0, <32 x half>* nocapture readonly %1, i8 %2) {
; CHECK-LABEL: shiftfhv_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sxbd $r1 = $r1
; CHECK-NEXT:    ld $r3 = 56[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    floatw.rn $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    srld $r0 = $r3, 48
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    fnarrowwh.rn $r1 = $r1
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x2010201.@
; CHECK-NEXT:    ;; # (end cycle 6)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x804080408040201
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ;; # (end cycle 7)
; CHECK-NEXT:    copyq $r4r5 = $r2, $r3
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    so 0[$r15] = $r0r1r2r3
; CHECK-NEXT:    copyq $r6r7 = $r2, $r3
; CHECK-NEXT:    ;; # (end cycle 9)
; CHECK-NEXT:    so 32[$r15] = $r4r5r6r7
; CHECK-NEXT:    copyd $r0 = $r15
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 10)
  %4 = load <32 x half>, <32 x half>* %1
  %5 = sitofp i8 %2 to half
  %6 = insertelement <32 x half> undef, half %5, i64 0
  %7 = shufflevector <32 x half> %6, <32 x half> %4, <32 x i32> <i32 63, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  store <32 x half> %7, <32 x half>* %0
  ret void
}

define <2 x float> @shiftfwp_one(<2 x float> %0, float %1) {
; CHECK-LABEL: shiftfwp_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r0, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <2 x float> undef, float %1, i64 0
  %4 = shufflevector <2 x float> %3, <2 x float> %0, <2 x i32> <i32 3, i32 0>
  ret <2 x float> %4
}

define <4 x float> @shiftfwq_one(<4 x float> %0, float %1) {
; CHECK-LABEL: shiftfwq_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 31, 0
; CHECK-NEXT:    srad $r3 = $r1, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x804020180402010
; CHECK-NEXT:    insf $r3 = $r2, 63, 32
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <4 x float> undef, float %1, i64 0
  %4 = shufflevector <4 x float> %3, <4 x float> %0, <4 x i32> <i32 5, i32 6, i32 7, i32 0>
  ret <4 x float> %4
}

define <4 x float> @shiftfwq_last(<4 x float> %0, float %1) {
; CHECK-LABEL: shiftfwq_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r1, 32
; CHECK-NEXT:    copyd $r3 = $r2
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r3, 63, 32
; CHECK-NEXT:    insf $r3 = $r3, 63, 32
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <4 x float> undef, float %1, i64 0
  %4 = shufflevector <4 x float> %3, <4 x float> %0, <4 x i32> <i32 7, i32 0, i32 0, i32 0>
  ret <4 x float> %4
}

define <8 x float> @shiftfwo_one(<8 x float> %0, float %1) {
; CV1-LABEL: shiftfwo_one:
; CV1:       # %bb.0:
; CV1-NEXT:    insf $r0 = $r1, 31, 0
; CV1-NEXT:    insf $r1 = $r2, 31, 0
; CV1-NEXT:    srad $r5 = $r3, 32
; CV1-NEXT:    copyd $r6 = $r2
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    insf $r5 = $r4, 63, 32
; CV1-NEXT:    insf $r6 = $r3, 31, 0
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    sbmm8 $r0 = $r0, 0x804020180402010
; CV1-NEXT:    sbmm8 $r2 = $r6, 0x804020180402010
; CV1-NEXT:    copyd $r3 = $r5
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    sbmm8 $r1 = $r1, 0x804020180402010
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 3)
;
; CV2-LABEL: shiftfwo_one:
; CV2:       # %bb.0:
; CV2-NEXT:    insf $r0 = $r1, 31, 0
; CV2-NEXT:    insf $r1 = $r2, 31, 0
; CV2-NEXT:    srad $r5 = $r3, 32
; CV2-NEXT:    copyd $r6 = $r2
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    sbmm8 $r0 = $r0, 0x804020180402010
; CV2-NEXT:    sbmm8 $r1 = $r1, 0x804020180402010
; CV2-NEXT:    insf $r5 = $r4, 63, 32
; CV2-NEXT:    insf $r6 = $r3, 31, 0
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    sbmm8 $r2 = $r6, 0x804020180402010
; CV2-NEXT:    copyd $r3 = $r5
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <8 x float> undef, float %1, i64 0
  %4 = shufflevector <8 x float> %3, <8 x float> %0, <8 x i32> <i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0>
  ret <8 x float> %4
}

define <8 x float> @shiftfwo_last(<8 x float> %0, float %1) {
; CHECK-LABEL: shiftfwo_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r3, 32
; CHECK-NEXT:    copyd $r1 = $r4
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    insf $r1 = $r1, 63, 32
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %3 = insertelement <8 x float> undef, float %1, i64 0
  %4 = shufflevector <8 x float> %3, <8 x float> %0, <8 x i32> <i32 15, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  ret <8 x float> %4
}

define void @shiftfwx_one(<16 x float>* noalias nocapture sret(<16 x float>) align 32 %0, <16 x float>* nocapture readonly %1, i16 %2) {
; CV1-LABEL: shiftfwx_one:
; CV1:       # %bb.0:
; CV1-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV1-NEXT:    sxhd $r1 = $r1
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    lo $r8r9r10r11 = 0[$r0]
; CV1-NEXT:    floatw.rn $r16 = $r1, 0
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    srld $r0 = $r4, 32
; CV1-NEXT:    srld $r1 = $r5, 32
; CV1-NEXT:    srld $r2 = $r6, 32
; CV1-NEXT:    srld $r3 = $r7, 32
; CV1-NEXT:    ;; # (end cycle 3)
; CV1-NEXT:    srld $r32 = $r8, 32
; CV1-NEXT:    srld $r33 = $r9, 32
; CV1-NEXT:    srld $r34 = $r10, 32
; CV1-NEXT:    srld $r35 = $r11, 32
; CV1-NEXT:    ;; # (end cycle 4)
; CV1-NEXT:    insf $r0 = $r5, 63, 32
; CV1-NEXT:    insf $r34 = $r11, 63, 32
; CV1-NEXT:    ;; # (end cycle 5)
; CV1-NEXT:    insf $r1 = $r6, 63, 32
; CV1-NEXT:    insf $r35 = $r4, 63, 32
; CV1-NEXT:    ;; # (end cycle 6)
; CV1-NEXT:    insf $r2 = $r7, 63, 32
; CV1-NEXT:    insf $r32 = $r9, 63, 32
; CV1-NEXT:    ;; # (end cycle 7)
; CV1-NEXT:    insf $r3 = $r16, 63, 32
; CV1-NEXT:    insf $r33 = $r10, 63, 32
; CV1-NEXT:    ;; # (end cycle 8)
; CV1-NEXT:    so 32[$r15] = $r0r1r2r3
; CV1-NEXT:    ;; # (end cycle 9)
; CV1-NEXT:    so 0[$r15] = $r32r33r34r35
; CV1-NEXT:    copyd $r0 = $r15
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 10)
;
; CV2-LABEL: shiftfwx_one:
; CV2:       # %bb.0:
; CV2-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CV2-NEXT:    sxhd $r1 = $r1
; CV2-NEXT:    ;; # (end cycle 0)
; CV2-NEXT:    lo $r8r9r10r11 = 0[$r0]
; CV2-NEXT:    floatw.rn $r16 = $r1, 0
; CV2-NEXT:    ;; # (end cycle 1)
; CV2-NEXT:    srld $r0 = $r4, 32
; CV2-NEXT:    srld $r1 = $r5, 32
; CV2-NEXT:    srld $r2 = $r6, 32
; CV2-NEXT:    srld $r3 = $r7, 32
; CV2-NEXT:    ;; # (end cycle 3)
; CV2-NEXT:    srld $r32 = $r8, 32
; CV2-NEXT:    srld $r33 = $r9, 32
; CV2-NEXT:    srld $r34 = $r10, 32
; CV2-NEXT:    srld $r35 = $r11, 32
; CV2-NEXT:    ;; # (end cycle 4)
; CV2-NEXT:    insf $r0 = $r5, 63, 32
; CV2-NEXT:    insf $r1 = $r6, 63, 32
; CV2-NEXT:    insf $r34 = $r11, 63, 32
; CV2-NEXT:    insf $r35 = $r4, 63, 32
; CV2-NEXT:    ;; # (end cycle 5)
; CV2-NEXT:    insf $r2 = $r7, 63, 32
; CV2-NEXT:    insf $r3 = $r16, 63, 32
; CV2-NEXT:    insf $r32 = $r9, 63, 32
; CV2-NEXT:    insf $r33 = $r10, 63, 32
; CV2-NEXT:    ;; # (end cycle 6)
; CV2-NEXT:    so 32[$r15] = $r0r1r2r3
; CV2-NEXT:    ;; # (end cycle 7)
; CV2-NEXT:    so 0[$r15] = $r32r33r34r35
; CV2-NEXT:    copyd $r0 = $r15
; CV2-NEXT:    ret
; CV2-NEXT:    ;; # (end cycle 8)
  %4 = load <16 x float>, <16 x float>* %1
  %5 = sitofp i16 %2 to float
  %6 = insertelement <16 x float> undef, float %5, i64 0
  %7 = shufflevector <16 x float> %6, <16 x float> %4, <16 x i32> <i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 0>
  store <16 x float> %7, <16 x float>* %0
  ret void
}

define void @shiftfwx_last(<16 x float>* noalias nocapture sret(<16 x float>) align 32 %0, <16 x float>* nocapture readonly %1, i16 %2) {
; CHECK-LABEL: shiftfwx_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sxhd $r0 = $r1
; CHECK-NEXT:    ld $r3 = 56[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    floatw.rn $r1 = $r0, 0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    srld $r0 = $r3, 32
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    insf $r1 = $r1, 63, 32
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ;; # (end cycle 6)
; CHECK-NEXT:    copyq $r4r5 = $r2, $r3
; CHECK-NEXT:    ;; # (end cycle 7)
; CHECK-NEXT:    so 0[$r15] = $r0r1r2r3
; CHECK-NEXT:    copyq $r6r7 = $r2, $r3
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    so 32[$r15] = $r4r5r6r7
; CHECK-NEXT:    copyd $r0 = $r15
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 9)
  %4 = load <16 x float>, <16 x float>* %1
  %5 = sitofp i16 %2 to float
  %6 = insertelement <16 x float> undef, float %5, i64 0
  %7 = shufflevector <16 x float> %6, <16 x float> %4, <16 x i32> <i32 31, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  store <16 x float> %7, <16 x float>* %0
  ret void
}

define <2 x double> @shiftfdp_one(<2 x double> %0, double %1) {
; CHECK-LABEL: shiftfdp_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    copyd $r1 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %3 = insertelement <2 x double> undef, double %1, i64 0
  %4 = shufflevector <2 x double> %3, <2 x double> %0, <2 x i32> <i32 3, i32 0>
  ret <2 x double> %4
}

define <4 x double> @shiftfdq_one(<4 x double> %0, double %1) {
; CHECK-LABEL: shiftfdq_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    copyd $r1 = $r2
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    copyd $r3 = $r4
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %3 = insertelement <4 x double> undef, double %1, i64 0
  %4 = shufflevector <4 x double> %3, <4 x double> %0, <4 x i32> <i32 5, i32 6, i32 7, i32 0>
  ret <4 x double> %4
}

define <4 x double> @shiftfdq_last(<4 x double> %0, double %1) {
; CHECK-LABEL: shiftfdq_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r3
; CHECK-NEXT:    copyd $r1 = $r4
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %3 = insertelement <4 x double> undef, double %1, i64 0
  %4 = shufflevector <4 x double> %3, <4 x double> %0, <4 x i32> <i32 7, i32 0, i32 0, i32 0>
  ret <4 x double> %4
}

define void @shiftfdo_one(<8 x double>* noalias nocapture sret(<8 x double>) align 32 %0, <8 x double>* nocapture readonly %1, double %2) {
; CHECK-LABEL: shiftfdo_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lo $r4r5r6r7 = 32[$r0]
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lo $r8r9r10r11 = 0[$r0]
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r0 = $r5
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    copyd $r1 = $r6
; CHECK-NEXT:    copyd $r8 = $r9
; CHECK-NEXT:    copyd $r9 = $r10
; CHECK-NEXT:    copyd $r10 = $r11
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r2 = $r7
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    so 32[$r15] = $r0r1r2r3
; CHECK-NEXT:    copyd $r11 = $r4
; CHECK-NEXT:    ;; # (end cycle 6)
; CHECK-NEXT:    so 0[$r15] = $r8r9r10r11
; CHECK-NEXT:    copyd $r0 = $r15
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 7)
  %4 = load <8 x double>, <8 x double>* %1
  %5 = insertelement <8 x double> undef, double %2, i64 0
  %6 = shufflevector <8 x double> %5, <8 x double> %4, <8 x i32> <i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 0>
  store <8 x double> %6, <8 x double>* %0
  ret void
}

define void @shiftfdo_last(<8 x double>* noalias nocapture sret(<8 x double>) align 32 %0, <8 x double>* nocapture readonly %1, double %2) {
; CHECK-LABEL: shiftfdo_last:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld $r0 = 56[$r0]
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    copyd $r4 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r5 = $r1
; CHECK-NEXT:    copyd $r6 = $r1
; CHECK-NEXT:    copyd $r7 = $r1
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    so 32[$r15] = $r4r5r6r7
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    so 0[$r15] = $r0r1r2r3
; CHECK-NEXT:    copyd $r0 = $r15
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 3)
  %4 = load <8 x double>, <8 x double>* %1
  %5 = insertelement <8 x double> undef, double %2, i64 0
  %6 = shufflevector <8 x double> %5, <8 x double> %4, <8 x i32> <i32 15, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0>
  store <8 x double> %6, <8 x double>* %0
  ret void
}
