; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -O0 -o - %s | FileCheck %s --check-prefixes=ALL
; RUN: llc -mcpu=kv3-2 -O0 -o - %s | FileCheck %s --check-prefixes=ALL
; RUN: clang -O0 -c -o /dev/null %s
; RUN: clang -O0 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define void @xundef1024(<1024 x i1>* %0) {
; ALL-LABEL: xundef1024:
; ALL:       # %bb.0:
; ALL-NEXT:    addd $r12 = $r12, -32
; ALL-NEXT:    ;;
; ALL-NEXT:    sd 24[$r12] = $r0
; ALL-NEXT:    ;;
; ALL-NEXT:    addd $r12 = $r12, 32
; ALL-NEXT:    ;;
; ALL-NEXT:    ret
; ALL-NEXT:    ;;
  %2 = alloca <1024 x i1>*
  store <1024 x i1>* %0, <1024 x i1>** %2
  %3 = load <1024 x i1>*, <1024 x i1>** %2
  store <1024 x i1> undef, <1024 x i1>* %3
  ret void
}

define void @xundef2048(<2048 x i1>* %0) {
; ALL-LABEL: xundef2048:
; ALL:       # %bb.0:
; ALL-NEXT:    addd $r12 = $r12, -32
; ALL-NEXT:    ;;
; ALL-NEXT:    sd 24[$r12] = $r0
; ALL-NEXT:    ;;
; ALL-NEXT:    addd $r12 = $r12, 32
; ALL-NEXT:    ;;
; ALL-NEXT:    ret
; ALL-NEXT:    ;;
  %2 = alloca <2048 x i1>*
  store <2048 x i1>* %0, <2048 x i1>** %2
  %3 = load <2048 x i1>*, <2048 x i1>** %2
  store <2048 x i1> undef, <2048 x i1>* %3
  ret void
}

define void @xundef256(<256 x i1>* %0) {
; ALL-LABEL: xundef256:
; ALL:       # %bb.0:
; ALL-NEXT:    addd $r12 = $r12, -32
; ALL-NEXT:    ;;
; ALL-NEXT:    sd 24[$r12] = $r0
; ALL-NEXT:    ;;
; ALL-NEXT:    addd $r12 = $r12, 32
; ALL-NEXT:    ;;
; ALL-NEXT:    ret
; ALL-NEXT:    ;;
  %2 = alloca <256 x i1>*
  store <256 x i1>* %0, <256 x i1>** %2
  %3 = load <256 x i1>*, <256 x i1>** %2
  store <256 x i1> undef, <256 x i1>* %3
  ret void
}

define void @xundef4096(<4096 x i1>* %0) {
; ALL-LABEL: xundef4096:
; ALL:       # %bb.0:
; ALL-NEXT:    addd $r12 = $r12, -32
; ALL-NEXT:    ;;
; ALL-NEXT:    sd 24[$r12] = $r0
; ALL-NEXT:    ;;
; ALL-NEXT:    addd $r12 = $r12, 32
; ALL-NEXT:    ;;
; ALL-NEXT:    ret
; ALL-NEXT:    ;;
  %2 = alloca <4096 x i1>*
  store <4096 x i1>* %0, <4096 x i1>** %2
  %3 = load <4096 x i1>*, <4096 x i1>** %2
  store <4096 x i1> undef, <4096 x i1>* %3
  ret void
}

define void @xundef512(<512 x i1>* %0) {
; ALL-LABEL: xundef512:
; ALL:       # %bb.0:
; ALL-NEXT:    addd $r12 = $r12, -32
; ALL-NEXT:    ;;
; ALL-NEXT:    sd 24[$r12] = $r0
; ALL-NEXT:    ;;
; ALL-NEXT:    addd $r12 = $r12, 32
; ALL-NEXT:    ;;
; ALL-NEXT:    ret
; ALL-NEXT:    ;;
  %2 = alloca <512 x i1>*
  store <512 x i1>* %0, <512 x i1>** %2
  %3 = load <512 x i1>*, <512 x i1>** %2
  store <512 x i1> undef, <512 x i1>* %3
  ret void
}

