; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

%struct.S = type { i32, i32, i32, i32 }

define i8 @preload_i8(i8 addrspace(257)* nocapture readonly %i){
; CHECK-LABEL: preload_i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lbz.us $r0 = 0[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load i8, i8 addrspace(257)* %i, align 1
  ret i8 %0
}

define i16 @preload_i16(i16 addrspace(257)* nocapture readonly %i){
; CHECK-LABEL: preload_i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lhz.us $r0 = 0[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load i16, i16 addrspace(257)* %i, align 2
  ret i16 %0
}

define i32 @preload_i32(i32 addrspace(257)* nocapture readonly %i){
; CHECK-LABEL: preload_i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lwz.us $r0 = 0[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load i32, i32 addrspace(257)* %i, align 4
  ret i32 %0
}

define i64 @preload_i64(i64 addrspace(257)* nocapture readonly %i){
; CHECK-LABEL: preload_i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld.us $r0 = 0[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load i64, i64 addrspace(257)* %i, align 8
  ret i64 %0
}

define float @fpreload_f32(float addrspace(257)* nocapture readonly %f){
; CHECK-LABEL: fpreload_f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lwz.us $r0 = 0[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load float, float addrspace(257)* %f, align 4
  ret float %0
}

define double @fpreload_f64(double addrspace(257)* nocapture readonly %d){
; CHECK-LABEL: fpreload_f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld.us $r0 = 0[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load double, double addrspace(257)* %d, align 8
  ret double %0
}

define <2 x float> @fpreload_v2f32(<2 x float> addrspace(257)* nocapture readonly %v){
; CHECK-LABEL: fpreload_v2f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld.us $r0 = 0[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load <2 x float>, <2 x float> addrspace(257)* %v, align 8
  ret <2 x float> %0
}

define <4 x float> @fpreload_v4f32(<4 x float> addrspace(257)* nocapture readonly %v){
; CHECK-LABEL: fpreload_v4f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lq.us $r0r1 = 0[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load <4 x float>, <4 x float> addrspace(257)* %v, align 16
  ret <4 x float> %0
}

define i32 @foo_preload_a(%struct.S addrspace(257)* nocapture readonly %s){
; CHECK-LABEL: foo_preload_a:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lwz.us $r0 = 0[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %a = getelementptr inbounds %struct.S, %struct.S addrspace(257)* %s, i64 0, i32 0
  %0 = load i32, i32 addrspace(257)* %a, align 4
  ret i32 %0
}

define i32 @foo_preload_b(%struct.S addrspace(257)* nocapture readonly %s){
; CHECK-LABEL: foo_preload_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lwz.us $r0 = 4[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %b = getelementptr inbounds %struct.S, %struct.S addrspace(257)* %s, i64 0, i32 1
  %0 = load i32, i32 addrspace(257)* %b, align 4
  ret i32 %0
}

define i32 @foo_preload_c(%struct.S addrspace(257)* nocapture readonly %s){
; CHECK-LABEL: foo_preload_c:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lwz.us $r0 = 8[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %c = getelementptr inbounds %struct.S, %struct.S addrspace(257)* %s, i64 0, i32 2
  %0 = load i32, i32 addrspace(257)* %c, align 4
  ret i32 %0
}

define i32 @foo_preload_d(%struct.S addrspace(257)* nocapture readonly %s){
; CHECK-LABEL: foo_preload_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lwz.us $r0 = 12[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %d = getelementptr inbounds %struct.S, %struct.S addrspace(257)* %s, i64 0, i32 3
  %0 = load i32, i32 addrspace(257)* %d, align 4
  ret i32 %0
}

define i32 @foo_preload_3(<4 x i32> addrspace(257)* nocapture readonly %v){
; CHECK-LABEL: foo_preload_3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lwz.us $r0 = 12[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load <4 x i32>, <4 x i32> addrspace(257)* %v, align 16
  %vecext = extractelement <4 x i32> %0, i32 3
  ret i32 %vecext
}

define i32 @foo_preload_x(<4 x i32> addrspace(257)* nocapture readonly %v, i32 %x){
; CHECK-LABEL: foo_preload_x:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andw $r1 = $r1, 3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lwz.us.xs $r0 = $r1[$r0]
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load <4 x i32>, <4 x i32> addrspace(257)* %v, align 16
  %vecext = extractelement <4 x i32> %0, i32 %x
  ret i32 %vecext
}
