; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --frame-pointer=all < %s | FileCheck -check-prefix=FP-ALL %s

target triple = "kvx-kalray-cos"

; int g1(int, int);
;
; int test(int x){
;   g1(x, x);
;
;   return 0;
; }

define dso_local i32 @test(i32 %x) {
; FP-ALL-LABEL: test:
; FP-ALL:       # %bb.0: # %entry
; FP-ALL-NEXT:    addd $r12 = $r12, -32
; FP-ALL-NEXT:    get $r16 = $ra
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sd 24[$r12] = $r16
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sd 16[$r12] = $r14
; FP-ALL-NEXT:    copyd $r1 = $r0
; FP-ALL-NEXT:    addd $r14 = $r12, 16
; FP-ALL-NEXT:    call g1
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    make $r0 = 0
; FP-ALL-NEXT:    addd $r12 = $r14, -16
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ld $r14 = 16[$r12]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ld $r16 = 24[$r12]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    set $ra = $r16
; FP-ALL-NEXT:    addd $r12 = $r12, 32
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ret
; FP-ALL-NEXT:    ;;
entry:
  %call = tail call i32 @g1(i32 %x, i32 %x)
  ret i32 0
}

declare dso_local i32 @g1(i32, i32)
