; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --frame-pointer=all < %s | FileCheck -check-prefix=FP-ALL %s

target triple = "kvx-kalray-cos"

; int g1(int, int*);
;
; int test(int sz, int x) {
;   int *toto = __fg
;   __builtin_alloca(sz);
;   g1(x, toto);
;
;   return toto[0];
; }

define dso_local i32 @test(i32 %sz, i32 %x) {
; FP-ALL-LABEL: test:
; FP-ALL:       # %bb.0: # %entry
; FP-ALL-NEXT:    sxwd $r0 = $r0
; FP-ALL-NEXT:    addd $r12 = $r12, -32
; FP-ALL-NEXT:    get $r16 = $ra
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sd 24[$r12] = $r16
; FP-ALL-NEXT:    addd $r0 = $r0, 31
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sd 16[$r12] = $r14
; FP-ALL-NEXT:    andd $r0 = $r0, -32
; FP-ALL-NEXT:    addd $r14 = $r12, 16
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sd 8[$r12] = $r18
; FP-ALL-NEXT:    sbfd $r18 = $r0, $r12
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    copyd $r12 = $r18
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    copyd $r0 = $r1
; FP-ALL-NEXT:    copyd $r1 = $r18
; FP-ALL-NEXT:    call g1
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r0 = 0[$r18]
; FP-ALL-NEXT:    addd $r12 = $r14, -16
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ld $r18 = 8[$r12]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ld $r14 = 16[$r12]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ld $r16 = 24[$r12]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    set $ra = $r16
; FP-ALL-NEXT:    addd $r12 = $r12, 32
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ret
; FP-ALL-NEXT:    ;;
entry:
  %conv = sext i32 %sz to i64
  %0 = alloca i8, i64 %conv, align 8
  %1 = bitcast i8* %0 to i32*
  %call = call i32 @g1(i32 %x, i32* nonnull %1)
  %2 = load i32, i32* %1, align 8
  ret i32 %2
}

declare dso_local i32 @g1(i32, i32*)
