; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --frame-pointer=none < %s | FileCheck -check-prefix=FP-NONE %s
; RUN: llc --frame-pointer=all < %s | FileCheck -check-prefix=FP-ALL %s

target triple = "kvx-kalray-cos"

; Original C code:
;
; int fn2(int *p) {
;   return fn1(p[0], p[1], p[2], p[3], p[4],
;              p[10], p[11], p[12], p[13], p[14],
;              p[20], p[21], p[22], p[23], p[24]);
; }

define i32 @fn(i32* nocapture readonly %p) {
; FP-NONE-LABEL: fn:
; FP-NONE:       # %bb.0: # %entry
; FP-NONE-NEXT:    addd $r12 = $r12, -32
; FP-NONE-NEXT:    get $r16 = $ra
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    sd 24[$r12] = $r16
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r15 = 0[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r1 = 4[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r2 = 8[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r3 = 12[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r4 = 16[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r5 = 40[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r6 = 44[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r7 = 48[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r8 = 52[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r9 = 56[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r10 = 80[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r11 = 84[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r16 = 88[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r17 = 92[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    lwz $r0 = 96[$r0]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    sw 16[$r12] = $r0
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    sw 8[$r12] = $r17
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    sw 0[$r12] = $r16
; FP-NONE-NEXT:    copyd $r0 = $r15
; FP-NONE-NEXT:    call g
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    ld $r16 = 24[$r12]
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    set $ra = $r16
; FP-NONE-NEXT:    addd $r12 = $r12, 32
; FP-NONE-NEXT:    ;;
; FP-NONE-NEXT:    ret
; FP-NONE-NEXT:    ;;
;
; FP-ALL-LABEL: fn:
; FP-ALL:       # %bb.0: # %entry
; FP-ALL-NEXT:    addd $r12 = $r12, -32
; FP-ALL-NEXT:    get $r16 = $ra
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sd 24[$r12] = $r16
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sd 16[$r12] = $r14
; FP-ALL-NEXT:    addd $r14 = $r12, 16
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r15 = 0[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r1 = 4[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r2 = 8[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r3 = 12[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r4 = 16[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r5 = 40[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r6 = 44[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r7 = 48[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r8 = 52[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r9 = 56[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r10 = 80[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r11 = 84[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r16 = 88[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r17 = 92[$r0]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    lwz $r0 = 96[$r0]
; FP-ALL-NEXT:    addd $r12 = $r12, -32
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sw 16[$r12] = $r0
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sw 8[$r12] = $r17
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    sw 0[$r12] = $r16
; FP-ALL-NEXT:    copyd $r0 = $r15
; FP-ALL-NEXT:    call g
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    addd $r12 = $r12, 32
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    addd $r12 = $r14, -16
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ld $r14 = 16[$r12]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ld $r16 = 24[$r12]
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    set $ra = $r16
; FP-ALL-NEXT:    addd $r12 = $r12, 32
; FP-ALL-NEXT:    ;;
; FP-ALL-NEXT:    ret
; FP-ALL-NEXT:    ;;
entry:
  %0 = load i32, i32* %p, align 4
  %arrayidx1 = getelementptr inbounds i32, i32* %p, i64 1
  %1 = load i32, i32* %arrayidx1, align 4
  %arrayidx2 = getelementptr inbounds i32, i32* %p, i64 2
  %2 = load i32, i32* %arrayidx2, align 4
  %arrayidx3 = getelementptr inbounds i32, i32* %p, i64 3
  %3 = load i32, i32* %arrayidx3, align 4
  %arrayidx4 = getelementptr inbounds i32, i32* %p, i64 4
  %4 = load i32, i32* %arrayidx4, align 4
  %arrayidx5 = getelementptr inbounds i32, i32* %p, i64 10
  %5 = load i32, i32* %arrayidx5, align 4
  %arrayidx6 = getelementptr inbounds i32, i32* %p, i64 11
  %6 = load i32, i32* %arrayidx6, align 4
  %arrayidx7 = getelementptr inbounds i32, i32* %p, i64 12
  %7 = load i32, i32* %arrayidx7, align 4
  %arrayidx8 = getelementptr inbounds i32, i32* %p, i64 13
  %8 = load i32, i32* %arrayidx8, align 4
  %arrayidx9 = getelementptr inbounds i32, i32* %p, i64 14
  %9 = load i32, i32* %arrayidx9, align 4
  %arrayidx10 = getelementptr inbounds i32, i32* %p, i64 20
  %10 = load i32, i32* %arrayidx10, align 4
  %arrayidx11 = getelementptr inbounds i32, i32* %p, i64 21
  %11 = load i32, i32* %arrayidx11, align 4
  %arrayidx12 = getelementptr inbounds i32, i32* %p, i64 22
  %12 = load i32, i32* %arrayidx12, align 4
  %arrayidx13 = getelementptr inbounds i32, i32* %p, i64 23
  %13 = load i32, i32* %arrayidx13, align 4
  %arrayidx14 = getelementptr inbounds i32, i32* %p, i64 24
  %14 = load i32, i32* %arrayidx14, align 4
  %call = tail call i32 bitcast (i32 (...)* @g to i32 (i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32, i32)*)(i32 %0, i32 %1, i32 %2, i32 %3, i32 %4, i32 %5, i32 %6, i32 %7, i32 %8, i32 %9, i32 %10, i32 %11, i32 %12, i32 %13, i32 %14) #2
  ret i32 %call
}

declare i32 @g(...)
