// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -emit-llvm %s -O3 -o - | FileCheck %s

#include <kvx_builtins.h>

// CHECK-LABEL: @fmulho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16> [[SHUFFLE]] to <4 x half>
// CHECK-NEXT:    [[SHUFFLE1:%.*]] = shufflevector <8 x i16> [[B:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i16> [[SHUFFLE1]] to <4 x half>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x half> @llvm.kvx.fmul.v4f16(<4 x half> [[TMP0]], <4 x half> [[TMP1]], i32 1, i32 0)
// CHECK-NEXT:    [[SHUFFLE2:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[SHUFFLE2]] to <4 x half>
// CHECK-NEXT:    [[SHUFFLE3:%.*]] = shufflevector <8 x i16> [[B]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[SHUFFLE3]] to <4 x half>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x half> @llvm.kvx.fmul.v4f16(<4 x half> [[TMP3]], <4 x half> [[TMP4]], i32 1, i32 0)
// CHECK-NEXT:    [[SHUFFLE4:%.*]] = shufflevector <4 x half> [[TMP2]], <4 x half> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <8 x half> [[SHUFFLE4]] to <8 x i16>
// CHECK-NEXT:    ret <8 x i16> [[TMP6]]
//
__kvx_v8hi fmulho(__kvx_v8hi a, __kvx_v8hi b){
  return __builtin_kvx_fmulho(a, b, ".ru");
}

// CHECK-LABEL: @fmulhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHUFFLE2:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast <4 x i16> [[SHUFFLE2]] to <4 x half>
// CHECK-NEXT:    [[SHUFFLE5:%.*]] = shufflevector <16 x i16> [[B:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = bitcast <4 x i16> [[SHUFFLE5]] to <4 x half>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x half> @llvm.kvx.fmul.v4f16(<4 x half> [[TMP0]], <4 x half> [[TMP1]], i32 1, i32 0)
// CHECK-NEXT:    [[SHUFFLE8:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = bitcast <4 x i16> [[SHUFFLE8]] to <4 x half>
// CHECK-NEXT:    [[SHUFFLE11:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = bitcast <4 x i16> [[SHUFFLE11]] to <4 x half>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x half> @llvm.kvx.fmul.v4f16(<4 x half> [[TMP3]], <4 x half> [[TMP4]], i32 1, i32 0)
// CHECK-NEXT:    [[SHUFFLE12:%.*]] = shufflevector <4 x half> [[TMP2]], <4 x half> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE13:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE15:%.*]] = shufflevector <8 x i16> [[SHUFFLE13]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP6:%.*]] = bitcast <4 x i16> [[SHUFFLE15]] to <4 x half>
// CHECK-NEXT:    [[SHUFFLE16:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE18:%.*]] = shufflevector <8 x i16> [[SHUFFLE16]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP7:%.*]] = bitcast <4 x i16> [[SHUFFLE18]] to <4 x half>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x half> @llvm.kvx.fmul.v4f16(<4 x half> [[TMP6]], <4 x half> [[TMP7]], i32 1, i32 0)
// CHECK-NEXT:    [[SHUFFLE21:%.*]] = shufflevector <8 x i16> [[SHUFFLE13]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = bitcast <4 x i16> [[SHUFFLE21]] to <4 x half>
// CHECK-NEXT:    [[SHUFFLE24:%.*]] = shufflevector <8 x i16> [[SHUFFLE16]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = bitcast <4 x i16> [[SHUFFLE24]] to <4 x half>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x half> @llvm.kvx.fmul.v4f16(<4 x half> [[TMP9]], <4 x half> [[TMP10]], i32 1, i32 0)
// CHECK-NEXT:    [[SHUFFLE25:%.*]] = shufflevector <4 x half> [[TMP8]], <4 x half> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[SHUFFLE26_UNCASTED:%.*]] = shufflevector <8 x half> [[SHUFFLE12]], <8 x half> [[SHUFFLE25]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[SHUFFLE26:%.*]] = bitcast <16 x half> [[SHUFFLE26_UNCASTED]] to <16 x i16>
// CHECK-NEXT:    ret <16 x i16> [[SHUFFLE26]]
//
__kvx_v16hi fmulhx(__kvx_v16hi a, __kvx_v16hi b){
  return __builtin_kvx_fmulhx(a, b, ".ru");
}
