; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -loop-vectorize < %s | FileCheck %s

target triple = "kvx-kalray-cos"

define void @matrix_mul_const(i32 %0, i32* nocapture %1, i16* nocapture readonly %2, i16 %3) local_unnamed_addr #0 {
; CHECK-LABEL: @matrix_mul_const(
; CHECK-NEXT:    [[TMP5:%.*]] = icmp sgt i32 [[TMP0:%.*]], 0
; CHECK-NEXT:    br i1 [[TMP5]], label [[TMP6:%.*]], label [[TMP50:%.*]]
; CHECK:       6:
; CHECK-NEXT:    [[TMP7:%.*]] = sext i16 [[TMP3:%.*]] to i32
; CHECK-NEXT:    [[TMP8:%.*]] = sext i32 [[TMP0]] to i64
; CHECK-NEXT:    [[TMP9:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-NEXT:    br label [[ITER_CHECK:%.*]]
; CHECK:       iter.check:
; CHECK-NEXT:    [[TMP10:%.*]] = phi i64 [ 0, [[TMP6]] ], [ [[TMP48:%.*]], [[TMP47:%.*]] ]
; CHECK-NEXT:    [[TMP11:%.*]] = mul i64 [[TMP8]], [[TMP10]]
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i32, i32* [[TMP1:%.*]], i64 [[TMP11]]
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = bitcast i32* [[SCEVGEP]] to i8*
; CHECK-NEXT:    [[TMP12:%.*]] = add i64 [[TMP9]], [[TMP11]]
; CHECK-NEXT:    [[SCEVGEP2:%.*]] = getelementptr i32, i32* [[TMP1]], i64 [[TMP12]]
; CHECK-NEXT:    [[SCEVGEP23:%.*]] = bitcast i32* [[SCEVGEP2]] to i8*
; CHECK-NEXT:    [[SCEVGEP4:%.*]] = getelementptr i16, i16* [[TMP2:%.*]], i64 [[TMP11]]
; CHECK-NEXT:    [[SCEVGEP45:%.*]] = bitcast i16* [[SCEVGEP4]] to i8*
; CHECK-NEXT:    [[SCEVGEP6:%.*]] = getelementptr i16, i16* [[TMP2]], i64 [[TMP12]]
; CHECK-NEXT:    [[SCEVGEP67:%.*]] = bitcast i16* [[SCEVGEP6]] to i8*
; CHECK-NEXT:    [[TMP13:%.*]] = mul nsw i64 [[TMP10]], [[TMP8]]
; CHECK-NEXT:    [[TMP14:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP9]], 8
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[VEC_EPILOG_SCALAR_PH:%.*]], label [[VECTOR_MEMCHECK:%.*]]
; CHECK:       vector.memcheck:
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult i8* [[SCEVGEP1]], [[SCEVGEP67]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult i8* [[SCEVGEP45]], [[SCEVGEP23]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label [[VEC_EPILOG_SCALAR_PH]], label [[VECTOR_MAIN_LOOP_ITER_CHECK:%.*]]
; CHECK:       vector.main.loop.iter.check:
; CHECK-NEXT:    [[MIN_ITERS_CHECK8:%.*]] = icmp ult i64 [[TMP9]], 16
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK8]], label [[VEC_EPILOG_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP9]], 16
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP9]], [[N_MOD_VF]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <16 x i32> poison, i32 [[TMP7]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <16 x i32> [[BROADCAST_SPLATINSERT]], <16 x i32> poison, <16 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP15:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP16:%.*]] = add nsw i64 [[TMP15]], [[TMP13]]
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i16, i16* [[TMP2]], i64 [[TMP16]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i16, i16* [[TMP17]], i32 0
; CHECK-NEXT:    [[TMP19:%.*]] = bitcast i16* [[TMP18]] to <16 x i16>*
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i16>, <16 x i16>* [[TMP19]], align 2, !alias.scope !0
; CHECK-NEXT:    [[TMP20:%.*]] = sext <16 x i16> [[WIDE_LOAD]] to <16 x i32>
; CHECK-NEXT:    [[TMP21:%.*]] = mul nsw <16 x i32> [[TMP20]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i32, i32* [[TMP1]], i64 [[TMP16]]
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i32, i32* [[TMP22]], i32 0
; CHECK-NEXT:    [[TMP24:%.*]] = bitcast i32* [[TMP23]] to <16 x i32>*
; CHECK-NEXT:    store <16 x i32> [[TMP21]], <16 x i32>* [[TMP24]], align 4, !alias.scope !3, !noalias !0
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 16
; CHECK-NEXT:    [[TMP25:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP25]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP9]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label [[TMP47]], label [[VEC_EPILOG_ITER_CHECK:%.*]]
; CHECK:       vec.epilog.iter.check:
; CHECK-NEXT:    [[N_VEC_REMAINING:%.*]] = sub i64 [[TMP9]], [[N_VEC]]
; CHECK-NEXT:    [[MIN_EPILOG_ITERS_CHECK:%.*]] = icmp ult i64 [[N_VEC_REMAINING]], 8
; CHECK-NEXT:    br i1 [[MIN_EPILOG_ITERS_CHECK]], label [[VEC_EPILOG_SCALAR_PH]], label [[VEC_EPILOG_PH]]
; CHECK:       vec.epilog.ph:
; CHECK-NEXT:    [[VEC_EPILOG_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[VEC_EPILOG_ITER_CHECK]] ], [ 0, [[VECTOR_MAIN_LOOP_ITER_CHECK]] ]
; CHECK-NEXT:    [[N_MOD_VF9:%.*]] = urem i64 [[TMP9]], 8
; CHECK-NEXT:    [[N_VEC10:%.*]] = sub i64 [[TMP9]], [[N_MOD_VF9]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT14:%.*]] = insertelement <8 x i32> poison, i32 [[TMP7]], i32 0
; CHECK-NEXT:    [[BROADCAST_SPLAT15:%.*]] = shufflevector <8 x i32> [[BROADCAST_SPLATINSERT14]], <8 x i32> poison, <8 x i32> zeroinitializer
; CHECK-NEXT:    br label [[VEC_EPILOG_VECTOR_BODY:%.*]]
; CHECK:       vec.epilog.vector.body:
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = phi i64 [ [[VEC_EPILOG_RESUME_VAL]], [[VEC_EPILOG_PH]] ], [ [[INDEX_NEXT16:%.*]], [[VEC_EPILOG_VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP26:%.*]] = add i64 [[OFFSET_IDX]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = add nsw i64 [[TMP26]], [[TMP13]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i16, i16* [[TMP2]], i64 [[TMP27]]
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i16, i16* [[TMP28]], i32 0
; CHECK-NEXT:    [[TMP30:%.*]] = bitcast i16* [[TMP29]] to <8 x i16>*
; CHECK-NEXT:    [[WIDE_LOAD13:%.*]] = load <8 x i16>, <8 x i16>* [[TMP30]], align 2, !alias.scope !7
; CHECK-NEXT:    [[TMP31:%.*]] = sext <8 x i16> [[WIDE_LOAD13]] to <8 x i32>
; CHECK-NEXT:    [[TMP32:%.*]] = mul nsw <8 x i32> [[TMP31]], [[BROADCAST_SPLAT15]]
; CHECK-NEXT:    [[TMP33:%.*]] = getelementptr inbounds i32, i32* [[TMP1]], i64 [[TMP27]]
; CHECK-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i32, i32* [[TMP33]], i32 0
; CHECK-NEXT:    [[TMP35:%.*]] = bitcast i32* [[TMP34]] to <8 x i32>*
; CHECK-NEXT:    store <8 x i32> [[TMP32]], <8 x i32>* [[TMP35]], align 4, !alias.scope !10, !noalias !7
; CHECK-NEXT:    [[INDEX_NEXT16]] = add nuw i64 [[OFFSET_IDX]], 8
; CHECK-NEXT:    [[TMP36:%.*]] = icmp eq i64 [[INDEX_NEXT16]], [[N_VEC10]]
; CHECK-NEXT:    br i1 [[TMP36]], label [[VEC_EPILOG_MIDDLE_BLOCK:%.*]], label [[VEC_EPILOG_VECTOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       vec.epilog.middle.block:
; CHECK-NEXT:    [[CMP_N11:%.*]] = icmp eq i64 [[TMP9]], [[N_VEC10]]
; CHECK-NEXT:    br i1 [[CMP_N11]], label [[TMP47]], label [[VEC_EPILOG_SCALAR_PH]]
; CHECK:       vec.epilog.scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC10]], [[VEC_EPILOG_MIDDLE_BLOCK]] ], [ [[N_VEC]], [[VEC_EPILOG_ITER_CHECK]] ], [ 0, [[VECTOR_MEMCHECK]] ], [ 0, [[ITER_CHECK]] ]
; CHECK-NEXT:    br label [[TMP37:%.*]]
; CHECK:       37:
; CHECK-NEXT:    [[TMP38:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[VEC_EPILOG_SCALAR_PH]] ], [ [[TMP45:%.*]], [[TMP37]] ]
; CHECK-NEXT:    [[TMP39:%.*]] = add nsw i64 [[TMP38]], [[TMP13]]
; CHECK-NEXT:    [[TMP40:%.*]] = getelementptr inbounds i16, i16* [[TMP2]], i64 [[TMP39]]
; CHECK-NEXT:    [[TMP41:%.*]] = load i16, i16* [[TMP40]], align 2
; CHECK-NEXT:    [[TMP42:%.*]] = sext i16 [[TMP41]] to i32
; CHECK-NEXT:    [[TMP43:%.*]] = mul nsw i32 [[TMP42]], [[TMP7]]
; CHECK-NEXT:    [[TMP44:%.*]] = getelementptr inbounds i32, i32* [[TMP1]], i64 [[TMP39]]
; CHECK-NEXT:    store i32 [[TMP43]], i32* [[TMP44]], align 4
; CHECK-NEXT:    [[TMP45]] = add nuw nsw i64 [[TMP38]], 1
; CHECK-NEXT:    [[TMP46:%.*]] = icmp eq i64 [[TMP45]], [[TMP14]]
; CHECK-NEXT:    br i1 [[TMP46]], label [[TMP47]], label [[TMP37]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       47:
; CHECK-NEXT:    [[TMP48]] = add nuw nsw i64 [[TMP10]], 1
; CHECK-NEXT:    [[TMP49:%.*]] = icmp eq i64 [[TMP48]], [[TMP9]]
; CHECK-NEXT:    br i1 [[TMP49]], label [[DOTLOOPEXIT:%.*]], label [[ITER_CHECK]]
; CHECK:       .loopexit:
; CHECK-NEXT:    br label [[TMP50]]
; CHECK:       50:
; CHECK-NEXT:    ret void
;

  %5 = icmp sgt i32 %0, 0
  br i1 %5, label %6, label %27

6:                                                ; preds = %4
  %7 = sext i16 %3 to i32
  %8 = sext i32 %0 to i64
  %9 = zext i32 %0 to i64
  br label %10

10:                                               ; preds = %6, %24
  %11 = phi i64 [ 0, %6 ], [ %25, %24 ]
  %12 = mul nsw i64 %11, %8
  %13 = zext i32 %0 to i64
  br label %14

14:                                               ; preds = %10, %14
  %15 = phi i64 [ 0, %10 ], [ %22, %14 ]
  %16 = add nsw i64 %15, %12
  %17 = getelementptr inbounds i16, i16* %2, i64 %16
  %18 = load i16, i16* %17, align 2
  %19 = sext i16 %18 to i32
  %20 = mul nsw i32 %19, %7
  %21 = getelementptr inbounds i32, i32* %1, i64 %16
  store i32 %20, i32* %21, align 4
  %22 = add nuw nsw i64 %15, 1
  %23 = icmp eq i64 %22, %13
  br i1 %23, label %24, label %14

24:                                               ; preds = %14
  %25 = add nuw nsw i64 %11, 1
  %26 = icmp eq i64 %25, %9
  br i1 %26, label %27, label %10

27:                                               ; preds = %24, %4
  ret void
}

attributes #0 = { nofree norecurse nounwind uwtable "disable-tail-calls"="false" "frame-pointer"="none" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
