; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - -relocation-model=pic %s | FileCheck %s
; RUN: clang -c -o /dev/null %s -mllvm -relocation-model=pic

target triple = "kvx-kalray-cos"

@.str = private unnamed_addr constant [9 x i8] c"foo: %p\0A\00", align 1
@foo = extern_weak global i8, align 1

define i32 @main() local_unnamed_addr {
; CHECK-LABEL: main:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pcrel $r0 = @gotaddr()
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    addd $r0 = $r0, @gotoff( .L.str )
; CHECK-NEXT:    pcrel $r1 = @gotaddr()
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r1 = @got( foo )[$r1]
; CHECK-NEXT:    call printf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %1 = tail call i32 (i8*, ...) @printf(i8* nonnull dereferenceable(1) getelementptr inbounds ([9 x i8], [9 x i8]* @.str, i64 0, i64 0), i8* @foo)
  ret i32 0
}

declare noundef i32 @printf(i8* nocapture noundef readonly, ...) local_unnamed_addr
