; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py
; RUN: opt -mcpu=kv3-1 -mtriple=kvx-kalray-cos -passes='print<cost-model>' -cost-kind=throughput -disable-output %s 2>&1 | FileCheck %s --check-prefix=CV1
; RUN: opt -mcpu=kv3-2 -mtriple=kvx-kalray-cos -passes='print<cost-model>' -cost-kind=throughput -disable-output %s 2>&1 | FileCheck %s --check-prefix=CV2

target triple = "kvx-kalray-cos"

define <2 x double> @test_ret_const() #0 {
; CV1-LABEL: 'test_ret_const'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> <double 1.000000e+00, double 2.000000e+00>
;
; CV2-LABEL: 'test_ret_const'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> <double 1.000000e+00, double 2.000000e+00>
;
  ret <2 x double> <double 1.0, double 2.0>
}

define double @test_extract_0(<2 x double> %a) #0 {
; CV1-LABEL: 'test_extract_0'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %e = extractelement <2 x double> %a, i32 0
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret double %e
;
; CV2-LABEL: 'test_extract_0'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %e = extractelement <2 x double> %a, i32 0
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret double %e
;
  %e = extractelement <2 x double> %a, i32 0
  ret double %e
}

define double @test_extract_1(<2 x double> %a) #0 {
; CV1-LABEL: 'test_extract_1'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %e = extractelement <2 x double> %a, i32 1
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret double %e
;
; CV2-LABEL: 'test_extract_1'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %e = extractelement <2 x double> %a, i32 1
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret double %e
;
  %e = extractelement <2 x double> %a, i32 1
  ret double %e
}

define double @test_extract_i(<2 x double> %a, i64 %idx) #0 {
; CV1-LABEL: 'test_extract_i'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %e = extractelement <2 x double> %a, i64 %idx
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret double %e
;
; CV2-LABEL: 'test_extract_i'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %e = extractelement <2 x double> %a, i64 %idx
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret double %e
;
  %e = extractelement <2 x double> %a, i64 %idx
  ret double %e
}

define <2 x double> @test_fadd(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fadd'
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fadd'
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = fadd <2 x double> %a, %b
  ret <2 x double> %r
}

define <2 x double> @test_fadd_imm_0(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fadd_imm_0'
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> <double 1.000000e+00, double 2.000000e+00>, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fadd_imm_0'
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> <double 1.000000e+00, double 2.000000e+00>, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = fadd <2 x double> <double 1.0, double 2.0>, %a
  ret <2 x double> %r
}

define <2 x double> @test_fadd_imm_1(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fadd_imm_1'
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %a, <double 1.000000e+00, double 2.000000e+00>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fadd_imm_1'
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %a, <double 1.000000e+00, double 2.000000e+00>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = fadd <2 x double> %a, <double 1.0, double 2.0>
  ret <2 x double> %r
}

define <2 x double> @test_fsub(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fsub'
; CV1-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %r = fsub <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fsub'
; CV2-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %r = fsub <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = fsub <2 x double> %a, %b
  ret <2 x double> %r
}

define <2 x double> @test_fsub_imm(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fsub_imm'
; CV1-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %r = fsub <2 x double> %a, <double 1.000000e+00, double 2.000000e+00>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fsub_imm'
; CV2-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %r = fsub <2 x double> %a, <double 1.000000e+00, double 2.000000e+00>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = fsub <2 x double> %a, <double 1.0, double 2.0>
  ret <2 x double> %r
}

define <2 x double> @test_fsub_fromimm(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fsub_fromimm'
; CV1-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %r = fsub <2 x double> <double 1.000000e+00, double 2.000000e+00>, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fsub_fromimm'
; CV2-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %r = fsub <2 x double> <double 1.000000e+00, double 2.000000e+00>, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = fsub <2 x double> <double 1.0, double 2.0>, %a
  ret <2 x double> %r
}

define <2 x double> @test_fneg(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fneg'
; CV1-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %r = fsub <2 x double> zeroinitializer, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fneg'
; CV2-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %r = fsub <2 x double> zeroinitializer, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = fsub <2 x double> <double 0.0, double 0.0>, %a
  ret <2 x double> %r
}

define <2 x double> @test_fmul(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fmul'
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fmul <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fmul'
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fmul <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = fmul <2 x double> %a, %b
  ret <2 x double> %r
}

define <2 x double> @test_fdiv(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fdiv'
; CV1-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %r = fdiv <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fdiv'
; CV2-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %r = fdiv <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = fdiv <2 x double> %a, %b
  ret <2 x double> %r
}

define <2 x double> @test_frem(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_frem'
; CV1-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %r = frem <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_frem'
; CV2-NEXT:  Cost Model: Found an estimated cost of 11 for instruction: %r = frem <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = frem <2 x double> %a, %b
  ret <2 x double> %r
}

define void @test_ldst_v2f64(<2 x double>* %a, <2 x double>* %b) {
; CV1-LABEL: 'test_ldst_v2f64'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %t1 = load <2 x double>, <2 x double>* %a, align 16
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x double> %t1, <2 x double>* %b, align 16
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
; CV2-LABEL: 'test_ldst_v2f64'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %t1 = load <2 x double>, <2 x double>* %a, align 16
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x double> %t1, <2 x double>* %b, align 16
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
  %t1 = load <2 x double>, <2 x double>* %a
  store <2 x double> %t1, <2 x double>* %b, align 16
  ret void
}

declare <2 x double> @test_callee(<2 x double> %a, <2 x double> %b) #0

define <2 x double> @test_call(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_call'
; CV1-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %r = call <2 x double> @test_callee(<2 x double> %a, <2 x double> %b)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_call'
; CV2-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %r = call <2 x double> @test_callee(<2 x double> %a, <2 x double> %b)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @test_callee(<2 x double> %a, <2 x double> %b)
  ret <2 x double> %r
}

define <2 x double> @test_call_flipped(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_call_flipped'
; CV1-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %r = call <2 x double> @test_callee(<2 x double> %b, <2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_call_flipped'
; CV2-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %r = call <2 x double> @test_callee(<2 x double> %b, <2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @test_callee(<2 x double> %b, <2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_tailcall_flipped(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_tailcall_flipped'
; CV1-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %r = tail call <2 x double> @test_callee(<2 x double> %b, <2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_tailcall_flipped'
; CV2-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %r = tail call <2 x double> @test_callee(<2 x double> %b, <2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = tail call <2 x double> @test_callee(<2 x double> %b, <2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_select(<2 x double> %a, <2 x double> %b, i1 zeroext %c) #0 {
; CV1-LABEL: 'test_select'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = select i1 %c, <2 x double> %a, <2 x double> %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_select'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = select i1 %c, <2 x double> %a, <2 x double> %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = select i1 %c, <2 x double> %a, <2 x double> %b
  ret <2 x double> %r
}

define <2 x double> @test_select_cc(<2 x double> %a, <2 x double> %b, <2 x double> %c, <2 x double> %d) #0 {
; CV1-LABEL: 'test_select_cc'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %cc = fcmp une <2 x double> %c, %d
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = select <2 x i1> %cc, <2 x double> %a, <2 x double> %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_select_cc'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %cc = fcmp une <2 x double> %c, %d
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = select <2 x i1> %cc, <2 x double> %a, <2 x double> %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %cc = fcmp une <2 x double> %c, %d
  %r = select <2 x i1> %cc, <2 x double> %a, <2 x double> %b
  ret <2 x double> %r
}

define <2 x float> @test_select_cc_f32_f32(<2 x float> %a, <2 x float> %b, <2 x double> %c, <2 x double> %d) #0 {
; CV1-LABEL: 'test_select_cc_f32_f32'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %cc = fcmp une <2 x double> %c, %d
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = select <2 x i1> %cc, <2 x float> %a, <2 x float> %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x float> %r
;
; CV2-LABEL: 'test_select_cc_f32_f32'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %cc = fcmp une <2 x double> %c, %d
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = select <2 x i1> %cc, <2 x float> %a, <2 x float> %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x float> %r
;
  %cc = fcmp une <2 x double> %c, %d
  %r = select <2 x i1> %cc, <2 x float> %a, <2 x float> %b
  ret <2 x float> %r
}

define <2 x i1> @test_fcmp_une(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_une'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp une <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_une'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp une <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp une <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_ueq(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_ueq'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ueq <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_ueq'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ueq <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp ueq <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_ugt(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_ugt'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ugt <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_ugt'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ugt <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp ugt <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_uge(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_uge'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp uge <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_uge'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp uge <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp uge <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_ult(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_ult'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ult <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_ult'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ult <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp ult <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_ule(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_ule'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ule <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_ule'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ule <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp ule <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_uno(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_uno'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp uno <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_uno'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp uno <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp uno <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_one(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_one'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp one <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_one'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp one <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp one <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_oeq(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_oeq'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp oeq <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_oeq'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp oeq <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp oeq <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_ogt(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_ogt'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ogt <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_ogt'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ogt <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp ogt <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_oge(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_oge'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp oge <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_oge'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp oge <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp oge <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_olt(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_olt'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp olt <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_olt'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp olt <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp olt <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_ole(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_ole'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ole <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_ole'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ole <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp ole <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i1> @test_fcmp_ord(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_fcmp_ord'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ord <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
; CV2-LABEL: 'test_fcmp_ord'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %r = fcmp ord <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %r
;
  %r = fcmp ord <2 x double> %a, %b
  ret <2 x i1> %r
}

define <2 x i32> @test_fptosi_i32(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fptosi_i32'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptosi <2 x double> %a to <2 x i32>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i32> %r
;
; CV2-LABEL: 'test_fptosi_i32'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptosi <2 x double> %a to <2 x i32>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i32> %r
;
  %r = fptosi <2 x double> %a to <2 x i32>
  ret <2 x i32> %r
}

define <2 x i64> @test_fptosi_i64(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fptosi_i64'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptosi <2 x double> %a to <2 x i64>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i64> %r
;
; CV2-LABEL: 'test_fptosi_i64'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptosi <2 x double> %a to <2 x i64>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i64> %r
;
  %r = fptosi <2 x double> %a to <2 x i64>
  ret <2 x i64> %r
}

define <2 x i32> @test_fptoui_2xi32(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fptoui_2xi32'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptoui <2 x double> %a to <2 x i32>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i32> %r
;
; CV2-LABEL: 'test_fptoui_2xi32'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptoui <2 x double> %a to <2 x i32>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i32> %r
;
  %r = fptoui <2 x double> %a to <2 x i32>
  ret <2 x i32> %r
}

define <2 x i64> @test_fptoui_2xi64(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fptoui_2xi64'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptoui <2 x double> %a to <2 x i64>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i64> %r
;
; CV2-LABEL: 'test_fptoui_2xi64'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptoui <2 x double> %a to <2 x i64>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i64> %r
;
  %r = fptoui <2 x double> %a to <2 x i64>
  ret <2 x i64> %r
}

define <2 x i16> @test_fptosi_i16(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fptosi_i16'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptosi <2 x double> %a to <2 x i16>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i16> %r
;
; CV2-LABEL: 'test_fptosi_i16'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptosi <2 x double> %a to <2 x i16>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i16> %r
;
  %r = fptosi <2 x double> %a to <2 x i16>
  ret <2 x i16> %r
}

define <2 x i16> @test_fptoui_i16(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fptoui_i16'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptoui <2 x double> %a to <2 x i16>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i16> %r
;
; CV2-LABEL: 'test_fptoui_i16'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptoui <2 x double> %a to <2 x i16>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i16> %r
;
  %r = fptoui <2 x double> %a to <2 x i16>
  ret <2 x i16> %r
}

define <2 x i8> @test_fptosi_i8(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fptosi_i8'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptosi <2 x double> %a to <2 x i8>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i8> %r
;
; CV2-LABEL: 'test_fptosi_i8'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptosi <2 x double> %a to <2 x i8>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i8> %r
;
  %r = fptosi <2 x double> %a to <2 x i8>
  ret <2 x i8> %r
}

define <2 x i8> @test_fptoui_i8(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fptoui_i8'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptoui <2 x double> %a to <2 x i8>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i8> %r
;
; CV2-LABEL: 'test_fptoui_i8'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = fptoui <2 x double> %a to <2 x i8>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i8> %r
;
  %r = fptoui <2 x double> %a to <2 x i8>
  ret <2 x i8> %r
}
define <2 x double> @test_uitofp_2xi32(<2 x i32> %a) #0 {
; CV1-LABEL: 'test_uitofp_2xi32'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = uitofp <2 x i32> %a to <2 x double>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_uitofp_2xi32'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = uitofp <2 x i32> %a to <2 x double>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = uitofp <2 x i32> %a to <2 x double>
  ret <2 x double> %r
}

define <2 x double> @test_uitofp_2xi64(<2 x i64> %a) #0 {
; CV1-LABEL: 'test_uitofp_2xi64'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = uitofp <2 x i64> %a to <2 x double>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_uitofp_2xi64'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = uitofp <2 x i64> %a to <2 x double>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = uitofp <2 x i64> %a to <2 x double>
  ret <2 x double> %r
}

define <2 x double> @test_sitofp_2xi32(<2 x i32> %a) #0 {
; CV1-LABEL: 'test_sitofp_2xi32'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = sitofp <2 x i32> %a to <2 x double>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_sitofp_2xi32'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = sitofp <2 x i32> %a to <2 x double>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = sitofp <2 x i32> %a to <2 x double>
  ret <2 x double> %r
}

define <2 x double> @test_sitofp_2xi64(<2 x i64> %a) #0 {
; CV1-LABEL: 'test_sitofp_2xi64'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = sitofp <2 x i64> %a to <2 x double>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_sitofp_2xi64'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = sitofp <2 x i64> %a to <2 x double>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = sitofp <2 x i64> %a to <2 x double>
  ret <2 x double> %r
}

define <2 x double> @test_uitofp_2xi32_fadd(<2 x i32> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_uitofp_2xi32_fadd'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %c = uitofp <2 x i32> %a to <2 x double>
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %b, %c
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_uitofp_2xi32_fadd'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %c = uitofp <2 x i32> %a to <2 x double>
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %b, %c
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %c = uitofp <2 x i32> %a to <2 x double>
  %r = fadd <2 x double> %b, %c
  ret <2 x double> %r
}

define <2 x double> @test_sitofp_2xi32_fadd(<2 x i32> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_sitofp_2xi32_fadd'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %c = sitofp <2 x i32> %a to <2 x double>
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %b, %c
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_sitofp_2xi32_fadd'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %c = sitofp <2 x i32> %a to <2 x double>
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %b, %c
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %c = sitofp <2 x i32> %a to <2 x double>
  %r = fadd <2 x double> %b, %c
  ret <2 x double> %r
}

define <2 x i64> @test_bitcast_2xdouble_to_2xi64(<2 x double> %a) #0 {
; CV1-LABEL: 'test_bitcast_2xdouble_to_2xi64'
; CV1-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: %r = bitcast <2 x double> %a to <2 x i64>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i64> %r
;
; CV2-LABEL: 'test_bitcast_2xdouble_to_2xi64'
; CV2-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: %r = bitcast <2 x double> %a to <2 x i64>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i64> %r
;
  %r = bitcast <2 x double> %a to <2 x i64>
  ret <2 x i64> %r
}

define <2 x double> @test_bitcast_2xi64_to_2xdouble(<2 x i64> %a) #0 {
; CV1-LABEL: 'test_bitcast_2xi64_to_2xdouble'
; CV1-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: %r = bitcast <2 x i64> %a to <2 x double>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_bitcast_2xi64_to_2xdouble'
; CV2-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: %r = bitcast <2 x i64> %a to <2 x double>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = bitcast <2 x i64> %a to <2 x double>
  ret <2 x double> %r
}

declare <2 x double> @llvm.sqrt.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.powi.v2f64(<2 x double> %a, i32 %b) #0
declare <2 x double> @llvm.sin.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.cos.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.pow.v2f64(<2 x double> %a, <2 x double> %b) #0
declare <2 x double> @llvm.exp.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.exp2.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.log.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.log10.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.log2.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.fma.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c) #0
declare <2 x double> @llvm.fabs.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.minnum.v2f64(<2 x double> %a, <2 x double> %b) #0
declare <2 x double> @llvm.maxnum.v2f64(<2 x double> %a, <2 x double> %b) #0
declare <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %b) #0
declare <2 x double> @llvm.floor.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.ceil.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.trunc.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.rint.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.nearbyint.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.round.v2f64(<2 x double> %a) #0
declare <2 x double> @llvm.fmuladd.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c) #0

define <2 x double> @test_sqrt(<2 x double> %a) #0 {
; CV1-LABEL: 'test_sqrt'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.sqrt.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_sqrt'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.sqrt.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.sqrt.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_powi(<2 x double> %a, i32 %b) #0 {
; CV1-LABEL: 'test_powi'
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = call <2 x double> @llvm.powi.v2f64.i32(<2 x double> %a, i32 %b)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_powi'
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = call <2 x double> @llvm.powi.v2f64.i32(<2 x double> %a, i32 %b)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.powi.v2f64(<2 x double> %a, i32 %b)
  ret <2 x double> %r
}

define <2 x double> @test_sin(<2 x double> %a) #0 {
; CV1-LABEL: 'test_sin'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.sin.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_sin'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.sin.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.sin.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_cos(<2 x double> %a) #0 {
; CV1-LABEL: 'test_cos'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.cos.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_cos'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.cos.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.cos.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_pow(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_pow'
; CV1-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call <2 x double> @llvm.pow.v2f64(<2 x double> %a, <2 x double> %b)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_pow'
; CV2-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call <2 x double> @llvm.pow.v2f64(<2 x double> %a, <2 x double> %b)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.pow.v2f64(<2 x double> %a, <2 x double> %b)
  ret <2 x double> %r
}

define <2 x double> @test_exp(<2 x double> %a) #0 {
; CV1-LABEL: 'test_exp'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.exp.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_exp'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.exp.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.exp.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_exp2(<2 x double> %a) #0 {
; CV1-LABEL: 'test_exp2'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.exp2.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_exp2'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.exp2.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.exp2.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_log(<2 x double> %a) #0 {
; CV1-LABEL: 'test_log'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.log.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_log'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.log.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.log.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_log10(<2 x double> %a) #0 {
; CV1-LABEL: 'test_log10'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.log10.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_log10'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.log10.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.log10.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_log2(<2 x double> %a) #0 {
; CV1-LABEL: 'test_log2'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.log2.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_log2'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.log2.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.log2.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_fma(<2 x double> %a, <2 x double> %b, <2 x double> %c) #0 {
; CV1-LABEL: 'test_fma'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = call <2 x double> @llvm.fma.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fma'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = call <2 x double> @llvm.fma.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.fma.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c)
  ret <2 x double> %r
}

define <2 x double> @test_fabs(<2 x double> %a) #0 {
; CV1-LABEL: 'test_fabs'
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = call <2 x double> @llvm.fabs.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fabs'
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = call <2 x double> @llvm.fabs.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.fabs.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_minnum(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_minnum'
; CV1-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call <2 x double> @llvm.minnum.v2f64(<2 x double> %a, <2 x double> %b)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_minnum'
; CV2-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call <2 x double> @llvm.minnum.v2f64(<2 x double> %a, <2 x double> %b)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.minnum.v2f64(<2 x double> %a, <2 x double> %b)
  ret <2 x double> %r
}

define <2 x double> @test_minnum_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_minnum_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call fast <2 x double> @llvm.minnum.v2f64(<2 x double> %a, <2 x double> %b)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_minnum_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call fast <2 x double> @llvm.minnum.v2f64(<2 x double> %a, <2 x double> %b)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call fast <2 x double> @llvm.minnum.v2f64(<2 x double> %a, <2 x double> %b)
  ret <2 x double> %r
}

define <2 x double> @test_maxnum(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_maxnum'
; CV1-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call <2 x double> @llvm.maxnum.v2f64(<2 x double> %a, <2 x double> %b)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_maxnum'
; CV2-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call <2 x double> @llvm.maxnum.v2f64(<2 x double> %a, <2 x double> %b)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.maxnum.v2f64(<2 x double> %a, <2 x double> %b)
  ret <2 x double> %r
}

define <2 x double> @test_maxnum_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_maxnum_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call fast <2 x double> @llvm.maxnum.v2f64(<2 x double> %a, <2 x double> %b)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_maxnum_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 7 for instruction: %r = call fast <2 x double> @llvm.maxnum.v2f64(<2 x double> %a, <2 x double> %b)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call fast <2 x double> @llvm.maxnum.v2f64(<2 x double> %a, <2 x double> %b)
  ret <2 x double> %r
}

define <2 x double> @test_copysign(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'test_copysign'
; CV1-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %r = call <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %b)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_copysign'
; CV2-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %r = call <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %b)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %b)
  ret <2 x double> %r
}

define <2 x double> @test_copysign_v2f16(<2 x double> %a, <2 x half> %b) #0 {
; CV1-LABEL: 'test_copysign_v2f16'
; CV1-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %tb = fpext <2 x half> %b to <2 x double>
; CV1-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %r = call <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %tb)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_copysign_v2f16'
; CV2-NEXT:  Cost Model: Found an estimated cost of 2 for instruction: %tb = fpext <2 x half> %b to <2 x double>
; CV2-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %r = call <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %tb)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %tb = fpext <2 x half> %b to <2 x double>
  %r = call <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %tb)
  ret <2 x double> %r
}

define <2 x double> @test_copysign_v2f32(<2 x double> %a, <2 x float> %b) #0 {
; CV1-LABEL: 'test_copysign_v2f32'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %tb = fpext <2 x float> %b to <2 x double>
; CV1-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %r = call <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %tb)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_copysign_v2f32'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %tb = fpext <2 x float> %b to <2 x double>
; CV2-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %r = call <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %tb)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %tb = fpext <2 x float> %b to <2 x double>
  %r = call <2 x double> @llvm.copysign.v2f64(<2 x double> %a, <2 x double> %tb)
  ret <2 x double> %r
}

define <2 x double> @test_floor(<2 x double> %a) #0 {
; CV1-LABEL: 'test_floor'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.floor.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_floor'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.floor.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.floor.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_ceil(<2 x double> %a) #0 {
; CV1-LABEL: 'test_ceil'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.ceil.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_ceil'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.ceil.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.ceil.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_trunc(<2 x double> %a) #0 {
; CV1-LABEL: 'test_trunc'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.trunc.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_trunc'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.trunc.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.trunc.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_rint(<2 x double> %a) #0 {
; CV1-LABEL: 'test_rint'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.rint.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_rint'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.rint.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.rint.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_nearbyint(<2 x double> %a) #0 {
; CV1-LABEL: 'test_nearbyint'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.nearbyint.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_nearbyint'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.nearbyint.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.nearbyint.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_round(<2 x double> %a) #0 {
; CV1-LABEL: 'test_round'
; CV1-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.round.v2f64(<2 x double> %a)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_round'
; CV2-NEXT:  Cost Model: Found an estimated cost of 6 for instruction: %r = call <2 x double> @llvm.round.v2f64(<2 x double> %a)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.round.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <2 x double> @test_fmuladd(<2 x double> %a, <2 x double> %b, <2 x double> %c) #0 {
; CV1-LABEL: 'test_fmuladd'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = call <2 x double> @llvm.fmuladd.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c)
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'test_fmuladd'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %r = call <2 x double> @llvm.fmuladd.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c)
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %r = call <2 x double> @llvm.fmuladd.v2f64(<2 x double> %a, <2 x double> %b, <2 x double> %c)
  ret <2 x double> %r
}

define <2 x double> @test_shufflevector(<2 x double> %a) #0 {
; CV1-LABEL: 'test_shufflevector'
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %s = shufflevector <2 x double> %a, <2 x double> undef, <2 x i32> <i32 1, i32 0>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %s
;
; CV2-LABEL: 'test_shufflevector'
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %s = shufflevector <2 x double> %a, <2 x double> undef, <2 x i32> <i32 1, i32 0>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %s
;
  %s = shufflevector <2 x double> %a, <2 x double> undef, <2 x i32> <i32 1, i32 0>
  ret <2 x double> %s
}

define <2 x double> @test_insertelement0(<2 x double> %a, double %x) #0 {
; CV1-LABEL: 'test_insertelement0'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %i = insertelement <2 x double> %a, double %x, i64 0
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %i
;
; CV2-LABEL: 'test_insertelement0'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %i = insertelement <2 x double> %a, double %x, i64 0
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %i
;
  %i = insertelement <2 x double> %a, double %x, i64 0
  ret <2 x double> %i
}

define <2 x double> @test_insertelement1(<2 x double> %a, double %x) #0 {
; CV1-LABEL: 'test_insertelement1'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %i = insertelement <2 x double> %a, double %x, i64 1
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %i
;
; CV2-LABEL: 'test_insertelement1'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %i = insertelement <2 x double> %a, double %x, i64 1
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %i
;
  %i = insertelement <2 x double> %a, double %x, i64 1
  ret <2 x double> %i
}

define <2 x double> @test_insertelement(<2 x double> %a, double %x, i64 %p) #0 {
; CV1-LABEL: 'test_insertelement'
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %i = insertelement <2 x double> %a, double %x, i64 %p
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %i
;
; CV2-LABEL: 'test_insertelement'
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %i = insertelement <2 x double> %a, double %x, i64 %p
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %i
;
  %i = insertelement <2 x double> %a, double %x, i64 %p
  ret <2 x double> %i
}

define <2 x i1> @fcmp_setoeq(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setoeq'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp oeq <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setoeq'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp oeq <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp oeq <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setoeq_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setoeq_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp oeq <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setoeq_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp oeq <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp oeq <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setogt(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setogt'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ogt <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setogt'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ogt <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ogt <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setogt_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setogt_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ogt <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setogt_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ogt <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ogt <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setoge(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setoge'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp oge <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setoge'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp oge <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp oge <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setoge_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setoge_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp oge <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setoge_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp oge <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp oge <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setolt(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setolt'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp olt <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setolt'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp olt <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp olt <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setolt_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setolt_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp olt <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setolt_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp olt <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp olt <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setole(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setole'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ole <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setole'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ole <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ole <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setole_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setole_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ole <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setole_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ole <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ole <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setone(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setone'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp one <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setone'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp one <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp one <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setone_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setone_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp one <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setone_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp one <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp one <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setord(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setord'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ord <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setord'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ord <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ord <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setord_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setord_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ord <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setord_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ord <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ord <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setuno(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setuno'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp uno <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setuno'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp uno <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp uno <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setuno_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setuno_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp uno <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setuno_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp uno <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp uno <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setueq(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setueq'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ueq <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setueq'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ueq <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ueq <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setueq_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setueq_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ueq <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setueq_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ueq <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ueq <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setugt(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setugt'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ugt <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setugt'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ugt <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ugt <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setugt_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setugt_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ugt <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setugt_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ugt <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ugt <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setuge(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setuge'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp uge <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setuge'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp uge <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp uge <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setuge_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setuge_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp uge <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setuge_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp uge <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp uge <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setult(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setult'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ult <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setult'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ult <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ult <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setult_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setult_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ult <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setult_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ult <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ult <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setule(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setule'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ule <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setule'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ule <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ule <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setule_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setule_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ule <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setule_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp ule <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp ule <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setune(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setune'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp une <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setune'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp une <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp une <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setune_single(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setune_single'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp une <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setune_single'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp une <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp une <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setoeq_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setoeq_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast oeq <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setoeq_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast oeq <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast oeq <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setoeq_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setoeq_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast oeq <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setoeq_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast oeq <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast oeq <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setogt_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setogt_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ogt <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setogt_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ogt <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ogt <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setogt_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setogt_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ogt <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setogt_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ogt <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ogt <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setoge_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setoge_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast oge <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setoge_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast oge <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast oge <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setoge_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setoge_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast oge <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setoge_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast oge <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast oge <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setolt_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setolt_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast olt <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setolt_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast olt <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast olt <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setolt_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setolt_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast olt <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setolt_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast olt <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast olt <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setole_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setole_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ole <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setole_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ole <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ole <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setole_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setole_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ole <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setole_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ole <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ole <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setone_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setone_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast one <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setone_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast one <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast one <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setone_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setone_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast one <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setone_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast one <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast one <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setord_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setord_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ord <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setord_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ord <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ord <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setord_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setord_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ord <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setord_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ord <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ord <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setuno_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setuno_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast uno <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setuno_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast uno <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast uno <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setuno_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setuno_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast uno <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setuno_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast uno <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast uno <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setueq_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setueq_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ueq <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setueq_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ueq <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ueq <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setueq_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setueq_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ueq <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setueq_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ueq <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ueq <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setugt_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setugt_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ugt <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setugt_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ugt <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ugt <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setugt_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setugt_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ugt <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setugt_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ugt <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ugt <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setuge_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setuge_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast uge <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setuge_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast uge <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast uge <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setuge_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setuge_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast uge <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setuge_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast uge <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast uge <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setult_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setult_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ult <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setult_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ult <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ult <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setult_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setult_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ult <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setult_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ult <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ult <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setule_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setule_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ule <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setule_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ule <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ule <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setule_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setule_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ule <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setule_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast ule <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast ule <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setune_fast(<2 x double> %a, <2 x double> %b) #0 {
; CV1-LABEL: 'fcmp_setune_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast une <2 x double> %a, %b
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setune_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast une <2 x double> %a, %b
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast une <2 x double> %a, %b
  ret <2 x i1> %0
}

define <2 x i1> @fcmp_setune_single_fast(<2 x double> %a) #0 {
; CV1-LABEL: 'fcmp_setune_single_fast'
; CV1-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast une <2 x double> %a, %a
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
; CV2-LABEL: 'fcmp_setune_single_fast'
; CV2-NEXT:  Cost Model: Found an estimated cost of 70000 for instruction: %0 = fcmp fast une <2 x double> %a, %a
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x i1> %0
;
entry:
  %0 = fcmp fast une <2 x double> %a, %a
  ret <2 x i1> %0
}

define <2 x double> @add_splat_const_op1(<2 x double> %vx) #0 {
; CV1-LABEL: 'add_splat_const_op1'
; CV1-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %splatx = shufflevector <2 x double> %vx, <2 x double> undef, <2 x i32> zeroinitializer
; CV1-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %splatx, <double 4.200000e+01, double 4.200000e+01>
; CV1-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
; CV2-LABEL: 'add_splat_const_op1'
; CV2-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %splatx = shufflevector <2 x double> %vx, <2 x double> undef, <2 x i32> zeroinitializer
; CV2-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: %r = fadd <2 x double> %splatx, <double 4.200000e+01, double 4.200000e+01>
; CV2-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret <2 x double> %r
;
  %splatx = shufflevector <2 x double> %vx, <2 x double> undef, <2 x i32> zeroinitializer
  %r = fadd <2 x double> %splatx, <double 42.0, double 42.0>
  ret <2 x double> %r
}

attributes #0 = { nounwind }
