; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -o - %s -O2 | FileCheck %s --check-prefixes=ALL
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=ALL

target triple = "kvx-kalray-cos"

; TODO: Bad scheduling, sbmm could start from cycle 2,
; fust after the first fixedwp.
define <8 x i8> @convert_8f16_fptosi_8i8(<8 x half> %0) {
; ALL-LABEL: convert_8f16_fptosi_8i8:
; ALL:       # %bb.0:
; ALL-NEXT:    fwidenlhwp $r1 = $r1
; ALL-NEXT:    fwidenmhwp $r2 = $r1
; ALL-NEXT:    ;; # (end cycle 0)
; ALL-NEXT:    fwidenlhwp $r0 = $r0
; ALL-NEXT:    fwidenmhwp $r2 = $r0
; ALL-NEXT:    fixedwp.rz $r3 = $r2, 0
; ALL-NEXT:    ;; # (end cycle 1)
; ALL-NEXT:    fixedwp.rz $r4 = $r1, 0
; ALL-NEXT:    ;; # (end cycle 2)
; ALL-NEXT:    fixedwp.rz $r1 = $r2, 0
; ALL-NEXT:    ;; # (end cycle 3)
; ALL-NEXT:    fixedwp.rz $r0 = $r0, 0
; ALL-NEXT:    ;; # (end cycle 4)
; ALL-NEXT:    sbmm8 $r2 = $r3, 0x20100201
; ALL-NEXT:    ;; # (end cycle 5)
; ALL-NEXT:    sbmm8 $r3 = $r4, 0x20100201
; ALL-NEXT:    ;; # (end cycle 6)
; ALL-NEXT:    sbmm8 $r1 = $r1, 0x20100201
; ALL-NEXT:    insf $r3 = $r2, 63, 32
; ALL-NEXT:    ;; # (end cycle 7)
; ALL-NEXT:    sbmm8 $r0 = $r0, 0x20100201
; ALL-NEXT:    ;; # (end cycle 8)
; ALL-NEXT:    insf $r0 = $r1, 63, 32
; ALL-NEXT:    sbmm8 $r1 = $r3, 0x40100401
; ALL-NEXT:    ;; # (end cycle 9)
; ALL-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; ALL-NEXT:    ;; # (end cycle 10)
; ALL-NEXT:    insf $r0 = $r1, 63, 32
; ALL-NEXT:    ret
; ALL-NEXT:    ;; # (end cycle 11)
  %2 = fptosi <8 x half> %0 to <8 x i8>
  ret <8 x i8> %2
}
