; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: clang -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define half @f1() {
; CHECK-LABEL: f1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0xbc00
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  ret half 0xHBC00
}

define float @f2() {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0x3f800000
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  ret float 1.000000e+00
}

define double @f3() {
; CHECK-LABEL: f3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0x3ff0000000000000
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  ret double 1.000000e+00
}
