; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define i32 @pos_sel_constants(i32 %a) {
; CHECK-LABEL: pos_sel_constants:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sraw $r0 = $r0, 31
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    andnw $r0 = $r0, 5
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %tmp.1 = icmp sgt i32 %a, -1
  %retval = select i1 %tmp.1, i32 5, i32 0
  ret i32 %retval
}

define i64 @pos_sel_constants_64(i64 %a) {
; CHECK-LABEL: pos_sel_constants_64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r0, 63
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    andnd $r0 = $r0, 5
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %tmp.1 = icmp sgt i64 %a, -1
  %retval = select i1 %tmp.1, i64 5, i64 0
  ret i64 %retval
}
