; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O3 | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s -O3 | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O3 -c -o /dev/null %s
; RUN: clang -O3 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define  <2 x i32> @minwp_rr(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: minwp_rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    minwp $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = icmp sgt <2 x i32> %a, %b
  %1 = select <2 x i1> %0, <2 x i32> %b, <2 x i32> %a
  ret <2 x i32> %1
}

define  <2 x i32> @minuwp_rr(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: minuwp_rr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    minuwp $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = icmp ugt <2 x i32> %a, %b
  %1 = select <2 x i1> %0, <2 x i32> %b, <2 x i32> %a
  ret <2 x i32> %1
}

define  <2 x i32> @minwp_splat(<2 x i32> %a) {
; CHECK-LABEL: minwp_splat:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    minwp.@ $r0 = $r0, 20
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = icmp slt <2 x i32> %a, <i32 20, i32 20>
  %1 = select <2 x i1> %0, <2 x i32> %a, <2 x i32> <i32 20, i32 20>
  ret <2 x i32> %1
}

define  <2 x i32> @minwp_nosplat(<2 x i32> %a) {
; CHECK-LABEL: minwp_nosplat:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    minwp $r0 = $r0, 20
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = icmp slt <2 x i32> %a, <i32 20, i32 0>
  %1 = select <2 x i1> %0, <2 x i32> %a, <2 x i32> <i32 20, i32 0>
  ret <2 x i32> %1
}

define  <2 x i32> @minuwp_splat(<2 x i32> %a) {
; CHECK-LABEL: minuwp_splat:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    minuwp.@ $r0 = $r0, 20
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = icmp ult <2 x i32> %a, <i32 20, i32 20>
  %1 = select <2 x i1> %0, <2 x i32> %a, <2 x i32> <i32 20, i32 20>
  ret <2 x i32> %1
}

define  <2 x i32> @minuwp_nosplat(<2 x i32> %a) {
; CHECK-LABEL: minuwp_nosplat:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    minuwp $r0 = $r0, 20
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = icmp ult <2 x i32> %a, <i32 20, i32 0>
  %1 = select <2 x i1> %0, <2 x i32> %a, <2 x i32> <i32 20, i32 0>
  ret <2 x i32> %1
}

define  <2 x i32> @minuwp_rr_2(<2 x i32> %a) {
; CHECK-LABEL: minuwp_rr_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r1 = 0x200000000
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    minuwp $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
entry:
  %0 = icmp ult <2 x i32> %a, <i32 0, i32 2>
  %1 = select <2 x i1> %0, <2 x i32> %a, <2 x i32> <i32 0, i32 2>
  ret <2 x i32> %1
}

define  <2 x i32> @minwp_rr_2(<2 x i32> %a) {
; CHECK-LABEL: minwp_rr_2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r1 = 0x1400000000
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    minwp $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
entry:
  %0 = icmp slt <2 x i32> %a, <i32 0, i32 20>
  %1 = select <2 x i1> %0, <2 x i32> %a, <2 x i32> <i32 0, i32 20>
  ret <2 x i32> %1
}

