; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define i64 @f_msbfwdrr(i64 %a, i32 %b, i32 %c){
; CHECK-LABEL: f_msbfwdrr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    msbfwd $r0 = $r2, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %b64 = sext i32 %b to i64
  %c64 = sext i32 %c to i64
  %mul = mul nsw i64 %c64, %b64
  %sub = sub nsw i64 %a, %mul
  ret i64 %sub
}

define i64 @f_msbfwdri_1(i64 %a, i32 %b){
; CHECK-LABEL: f_msbfwdri_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    msbfwd $r0 = $r1, 11
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %b64 = sext i32 %b to i64
  %mul = mul nsw i64 %b64, 11
  %sub = sub nsw i64 %a, %mul
  ret i64 %sub
}
