; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: clang -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"


define i64 @SBFWD(i64 %0, i32 %1) {
; CHECK-LABEL: SBFWD:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbfwd $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %3 = sext i32 %1 to i64
  %4 = sub nsw i64 %0, %3
  ret i64 %4
}

define i64 @SBFUWD(i64 %0, i32 %1) {
; CHECK-LABEL: SBFUWD:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbfuwd $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %3 = zext i32 %1 to i64
  %4 = sub nsw i64 %0, %3
  ret i64 %4
}
