; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

@a = common global i16 0, align 2

define void @test4(i16 %b, i16 %c){
; CHECK-LABEL: test4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sllw $r0 = $r0, $r1
; CHECK-NEXT:    make $r1 = a
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sh 0[$r1] = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %conv = zext i16 %b to i32
  %conv1 = zext i16 %c to i32
  %shl = shl i32 %conv, %conv1
  %conv2 = trunc i32 %shl to i16
  store i16 %conv2, i16* @a, align 2
  ret void
}

define void @test4b(i16 %b, i16 %c){
; CHECK-LABEL: test4b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    zxhd $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srlw $r0 = $r0, $r1
; CHECK-NEXT:    make $r1 = a
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sh 0[$r1] = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %conv = zext i16 %b to i32
  %conv1 = zext i16 %c to i32
  %shr = lshr i32 %conv, %conv1
  %conv2 = trunc i32 %shr to i16
  store i16 %conv2, i16* @a, align 2
  ret void
}

