; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define i32 @smax32(i32 %l) {
; CHECK-LABEL: smax32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sraw $r0 = $r0, 31
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %shift = ashr i32 %l, 31 ; 31 -> 0b11111
  ret i32 %shift
}

define i64 @smax64(i64 %l) {
; CHECK-LABEL: smax64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r0, 63
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %shift = ashr i64 %l, 63 ; 63 -> 0b111111
  ret i64 %shift
}

define i32 @smin32(i32 %l) {
; CHECK-LABEL: smin32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sraw $r0 = $r0, 1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %shift = ashr i32 %l, 1
  ret i32 %shift
}

define i64 @smin64(i64 %l) {
; CHECK-LABEL: smin64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r0, 1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %shift = ashr i64 %l, 1
  ret i64 %shift
}
