; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -o - %s | FileCheck %s --check-prefixes=CHECK,KV3_1
; RUN: llc -mcpu=kv3-2 -O2 -o - %s | FileCheck %s --check-prefixes=CHECK,KV3_2
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <4 x float> @test_ret_const() #0 {
; CHECK-LABEL: test_ret_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r0 = 0x400000003f800000
; CHECK-NEXT:    make $r1 = 0x400000003f800000
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  ret <4 x float> <float 1.0, float 2.0, float 1.0, float 2.0>
}

define float @test_extract_0(<4 x float> %a) #0 {
; CHECK-LABEL: test_extract_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %e = extractelement <4 x float> %a, i32 0
  ret float %e
}

define float @test_extract_1(<4 x float> %a) #0 {
; CHECK-LABEL: test_extract_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r0, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %e = extractelement <4 x float> %a, i32 1
  ret float %e
}

define float @test_extract_i(<4 x float> %a, i64 %idx) #0 {
; CHECK-LABEL: test_extract_i:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andw $r2 = $r2, 1
; CHECK-NEXT:    srlw $r3 = $r2, 1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    cmoved.odd $r3 ? $r0 = $r1
; CHECK-NEXT:    sllw $r1 = $r2, 5
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    srld $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %e = extractelement <4 x float> %a, i64 %idx
  ret float %e
}

define <4 x float> @test_fadd(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fadd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    faddwq $r0r1 = $r0r1, $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %r = fadd <4 x float> %a, %b
  ret <4 x float> %r
}

define <4 x float> @test_fadd_imm_0(<4 x float> %a) #0 {
; CHECK-LABEL: test_fadd_imm_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r3 = 0x400000003f800000
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    faddwq $r0r1 = $r0r1, $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fadd <4 x float> <float 1.0, float 2.0, float 1.0, float 2.0>, %a
  ret <4 x float> %r
}

define <4 x float> @test_fadd_imm_1(<4 x float> %a) #0 {
; CHECK-LABEL: test_fadd_imm_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r3 = 0x400000003f800000
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    faddwq $r0r1 = $r0r1, $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fadd <4 x float> %a, <float 1.0, float 2.0, float 1.0, float 2.0>
  ret <4 x float> %r
}

define <4 x float> @test_fsub(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fsub:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fsbfwq $r0r1 = $r2r3, $r0r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %r = fsub <4 x float> %a, %b
  ret <4 x float> %r
}

define <4 x float> @test_fsub_imm(<4 x float> %a) #0 {
; CHECK-LABEL: test_fsub_imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r3 = 0xc0000000bf800000
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    faddwq $r0r1 = $r0r1, $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fsub <4 x float> %a, <float 1.0, float 2.0, float 1.0, float 2.0>
  ret <4 x float> %r
}

define <4 x float> @test_fsub_fromimm(<4 x float> %a) #0 {
; CHECK-LABEL: test_fsub_fromimm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r3 = 0x400000003f800000
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    fsbfwq $r0r1 = $r0r1, $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fsub <4 x float> <float 1.0, float 2.0, float 1.0, float 2.0>, %a
  ret <4 x float> %r
}

define <4 x float> @test_fneg(<4 x float> %a) #0 {
; CHECK-LABEL: test_fneg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fnegwp $r0 = $r0
; CHECK-NEXT:    fnegwp $r1 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %r = fsub <4 x float> <float 0.0, float 0.0, float 0.0, float 0.0>, %a
  ret <4 x float> %r
}

define <4 x float> @test_fmul(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fmul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmulwq $r0r1 = $r0r1, $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %r = fmul <4 x float> %a, %b
  ret <4 x float> %r
}

define <4 x float> @test_fdiv(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fdiv:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sd 48[$r12] = $r22
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 32[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    sq 16[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r3
; CHECK-NEXT:    copyd $r19 = $r2
; CHECK-NEXT:    copyd $r20 = $r1
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    srad $r0 = $r20, 32
; CHECK-NEXT:    srad $r1 = $r18, 32
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call __divsf3
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    copyd $r0 = $r20
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    copyd $r22 = $r0
; CHECK-NEXT:    call __divsf3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r21, 32
; CHECK-NEXT:    srad $r1 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call __divsf3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r21
; CHECK-NEXT:    copyd $r1 = $r19
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call __divsf3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    insf $r18 = $r22, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 16[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 32[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r22 = 48[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 9)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fdiv <4 x float> %a, %b
  ret <4 x float> %r
}

define <4 x float> @test_frem(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_frem:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sd 48[$r12] = $r22
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 32[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    sq 16[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r3
; CHECK-NEXT:    copyd $r19 = $r2
; CHECK-NEXT:    copyd $r20 = $r1
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    srad $r0 = $r20, 32
; CHECK-NEXT:    srad $r1 = $r18, 32
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call fmodf
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    copyd $r0 = $r20
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    copyd $r22 = $r0
; CHECK-NEXT:    call fmodf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r21, 32
; CHECK-NEXT:    srad $r1 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call fmodf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r21
; CHECK-NEXT:    copyd $r1 = $r19
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call fmodf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    insf $r18 = $r22, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 16[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 32[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r22 = 48[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 9)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = frem <4 x float> %a, %b
  ret <4 x float> %r
}

define void @test_ldst_v4f32(ptr %a, ptr %b) {
; CHECK-LABEL: test_ldst_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lq $r2r3 = 0[$r0]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sq 0[$r1] = $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %t1 = load <4 x float>, ptr %a
  store <4 x float> %t1, ptr %b, align 16
  ret void
}

declare <4 x float> @test_callee(<4 x float> %a, <4 x float> %b) #0

define <4 x float> @test_call(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_call:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    call test_callee
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @test_callee(<4 x float> %a, <4 x float> %b)
  ret <4 x float> %r
}

define <4 x float> @test_call_flipped(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_call_flipped:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    copyd $r2 = $r0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    call test_callee
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @test_callee(<4 x float> %b, <4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_tailcall_flipped(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_tailcall_flipped:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    copyd $r2 = $r0
; CHECK-NEXT:    copyd $r3 = $r1
; CHECK-NEXT:    goto test_callee
; CHECK-NEXT:    ;; # (end cycle 0)
  %r = tail call <4 x float> @test_callee(<4 x float> %b, <4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_select(<4 x float> %a, <4 x float> %b, i1 zeroext %c) #0 {
; CHECK-LABEL: test_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmoved.even $r4 ? $r0 = $r2
; CHECK-NEXT:    cmoved.even $r4 ? $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %r = select i1 %c, <4 x float> %a, <4 x float> %b
  ret <4 x float> %r
}

define <4 x float> @test_select_cc(<4 x float> %a, <4 x float> %b, <4 x float> %c, <4 x float> %d) #0 {
; CHECK-LABEL: test_select_cc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.une $r4 = $r4, $r6
; CHECK-NEXT:    fcompnwp.une $r5 = $r5, $r7
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    cmovewp.even $r4 ? $r0 = $r2
; CHECK-NEXT:    cmovewp.even $r5 ? $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %cc = fcmp une <4 x float> %c, %d
  %r = select <4 x i1> %cc, <4 x float> %a, <4 x float> %b
  ret <4 x float> %r
}

define <4 x double> @test_select_cc_f32_f32(<4 x double> %a, <4 x double> %b, <4 x float> %c, <4 x float> %d) #0 {
; KV3_1-LABEL: test_select_cc_f32_f32:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    fcompnwp.une $r8 = $r8, $r10
; KV3_1-NEXT:    fcompnwp.une $r9 = $r9, $r11
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    sxwd $r8 = $r8
; KV3_1-NEXT:    sxwd $r9 = $r9
; KV3_1-NEXT:    srld $r10 = $r9, 32
; KV3_1-NEXT:    srld $r11 = $r8, 32
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    sxwd $r10 = $r10
; KV3_1-NEXT:    sxwd $r11 = $r11
; KV3_1-NEXT:    ;; # (end cycle 2)
; KV3_1-NEXT:    cmoved.dnez $r8 ? $r4 = $r0
; KV3_1-NEXT:    cmoved.dnez $r11 ? $r5 = $r1
; KV3_1-NEXT:    ;; # (end cycle 3)
; KV3_1-NEXT:    copyd $r0 = $r4
; KV3_1-NEXT:    copyd $r1 = $r5
; KV3_1-NEXT:    cmoved.dnez $r9 ? $r6 = $r2
; KV3_1-NEXT:    cmoved.dnez $r10 ? $r7 = $r3
; KV3_1-NEXT:    ;; # (end cycle 4)
; KV3_1-NEXT:    copyd $r2 = $r6
; KV3_1-NEXT:    copyd $r3 = $r7
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 5)
;
; KV3_2-LABEL: test_select_cc_f32_f32:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    fcompnwp.une $r8 = $r8, $r10
; KV3_2-NEXT:    fcompnwp.une $r9 = $r9, $r11
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    sxwd $r8 = $r8
; KV3_2-NEXT:    sxwd $r9 = $r9
; KV3_2-NEXT:    srld $r10 = $r9, 32
; KV3_2-NEXT:    srld $r11 = $r8, 32
; KV3_2-NEXT:    ;; # (end cycle 1)
; KV3_2-NEXT:    cmoved.dnez $r8 ? $r4 = $r0
; KV3_2-NEXT:    cmoved.dnez $r9 ? $r6 = $r2
; KV3_2-NEXT:    sxwd $r10 = $r10
; KV3_2-NEXT:    sxwd $r11 = $r11
; KV3_2-NEXT:    ;; # (end cycle 2)
; KV3_2-NEXT:    copyd $r0 = $r4
; KV3_2-NEXT:    cmoved.dnez $r11 ? $r5 = $r1
; KV3_2-NEXT:    cmoved.dnez $r10 ? $r7 = $r3
; KV3_2-NEXT:    ;; # (end cycle 3)
; KV3_2-NEXT:    copyd $r1 = $r5
; KV3_2-NEXT:    copyd $r2 = $r6
; KV3_2-NEXT:    copyd $r3 = $r7
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 4)
  %cc = fcmp une <4 x float> %c, %d
  %r = select <4 x i1> %cc, <4 x double> %a, <4 x double> %b
  ret <4 x double> %r
}

define <4 x i1> @test_fcmp_une(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_une:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.une $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.une $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp une <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ueq(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_ueq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.ueq $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.ueq $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp ueq <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ugt(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_ugt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.ult $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.ult $r1 = $r3, $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp ugt <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_uge(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_uge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.uge $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.uge $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp uge <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ult(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.ult $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.ult $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp ult <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ule(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_ule:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.uge $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.uge $r1 = $r3, $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp ule <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_uno(<4 x float> %a, <4 x float> %b) #0 {
; KV3_1-LABEL: test_fcmp_uno:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    fcompnwp.uge $r1 = $r1, $r3
; KV3_1-NEXT:    fcompnwp.ult $r4 = $r1, $r3
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    fcompnwp.uge $r0 = $r0, $r2
; KV3_1-NEXT:    andd $r1 = $r1, $r4
; KV3_1-NEXT:    fcompnwp.ult $r3 = $r0, $r2
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    andd $r0 = $r0, $r3
; KV3_1-NEXT:    sbmm8 $r1 = $r1, 0x1001
; KV3_1-NEXT:    ;; # (end cycle 2)
; KV3_1-NEXT:    sbmm8 $r0 = $r0, 0x1001
; KV3_1-NEXT:    ;; # (end cycle 3)
; KV3_1-NEXT:    insf $r0 = $r1, 31, 16
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 4)
;
; KV3_2-LABEL: test_fcmp_uno:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    fcompnwp.uge $r0 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.uge $r1 = $r1, $r3
; KV3_2-NEXT:    fcompnwp.ult $r3 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.ult $r4 = $r1, $r3
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    andd $r0 = $r0, $r3
; KV3_2-NEXT:    andd $r1 = $r1, $r4
; KV3_2-NEXT:    ;; # (end cycle 1)
; KV3_2-NEXT:    sbmm8 $r0 = $r0, 0x1001
; KV3_2-NEXT:    sbmm8 $r1 = $r1, 0x1001
; KV3_2-NEXT:    ;; # (end cycle 2)
; KV3_2-NEXT:    insf $r0 = $r1, 31, 16
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 3)
  %r = fcmp uno <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_one(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.one $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.one $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp one <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_oeq(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_oeq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.oeq $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.oeq $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp oeq <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ogt(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_ogt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.olt $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.olt $r1 = $r3, $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp ogt <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_oge(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_oge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp oge <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_olt(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_olt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.olt $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.olt $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp olt <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ole(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_fcmp_ole:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.oge $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.oge $r1 = $r3, $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %r = fcmp ole <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ord(<4 x float> %a, <4 x float> %b) #0 {
; KV3_1-LABEL: test_fcmp_ord:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; KV3_1-NEXT:    fcompnwp.olt $r4 = $r1, $r3
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; KV3_1-NEXT:    iord $r1 = $r1, $r4
; KV3_1-NEXT:    fcompnwp.olt $r3 = $r0, $r2
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    iord $r0 = $r0, $r3
; KV3_1-NEXT:    sbmm8 $r1 = $r1, 0x1001
; KV3_1-NEXT:    ;; # (end cycle 2)
; KV3_1-NEXT:    sbmm8 $r0 = $r0, 0x1001
; KV3_1-NEXT:    ;; # (end cycle 3)
; KV3_1-NEXT:    insf $r0 = $r1, 31, 16
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 4)
;
; KV3_2-LABEL: test_fcmp_ord:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; KV3_2-NEXT:    fcompnwp.olt $r3 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.olt $r4 = $r1, $r3
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    iord $r0 = $r0, $r3
; KV3_2-NEXT:    iord $r1 = $r1, $r4
; KV3_2-NEXT:    ;; # (end cycle 1)
; KV3_2-NEXT:    sbmm8 $r0 = $r0, 0x1001
; KV3_2-NEXT:    sbmm8 $r1 = $r1, 0x1001
; KV3_2-NEXT:    ;; # (end cycle 2)
; KV3_2-NEXT:    insf $r0 = $r1, 31, 16
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 3)
  %r = fcmp ord <4 x float> %a, %b
  ret <4 x i1> %r
}

define <4 x i32> @test_fptosi_i32(<4 x float> %a) #0 {
; CHECK-LABEL: test_fptosi_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fixedwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fixedwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %r = fptosi <4 x float> %a to <4 x i32>
  ret <4 x i32> %r
}

define <4 x i64> @test_fptosi_i64(<4 x float> %a) #0 {
; CHECK-LABEL: test_fptosi_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlwd $r1 = $r1
; CHECK-NEXT:    fwidenmwd $r2 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fwidenlwd $r0 = $r0
; CHECK-NEXT:    fixedd.rz $r3 = $r2, 0
; CHECK-NEXT:    fwidenmwd $r4 = $r0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    fixedd.rz $r2 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    fixedd.rz $r1 = $r4, 0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    fixedd.rz $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 4)
  %r = fptosi <4 x float> %a to <4 x i64>
  ret <4 x i64> %r
}

define <4 x i32> @test_fptoui_2xi32(<4 x float> %a) #0 {
; CHECK-LABEL: test_fptoui_2xi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fixeduwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fixeduwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %r = fptoui <4 x float> %a to <4 x i32>
  ret <4 x i32> %r
}

define <4 x i64> @test_fptoui_2xi64(<4 x float> %a) #0 {
; CHECK-LABEL: test_fptoui_2xi64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlwd $r1 = $r1
; CHECK-NEXT:    fwidenmwd $r2 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fwidenlwd $r0 = $r0
; CHECK-NEXT:    fixedud.rz $r3 = $r2, 0
; CHECK-NEXT:    fwidenmwd $r4 = $r0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    fixedud.rz $r2 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    fixedud.rz $r1 = $r4, 0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    fixedud.rz $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 4)
  %r = fptoui <4 x float> %a to <4 x i64>
  ret <4 x i64> %r
}

define <4 x i16> @test_fptosi_i16(<4 x float> %a) #0 {
; CHECK-LABEL: test_fptosi_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fixedwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fixedwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x20100201
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x20100201
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 6)
  %r = fptosi <4 x float> %a to <4 x i16>
  ret <4 x i16> %r
}

define <4 x i16> @test_fptoui_i16(<4 x float> %a) #0 {
; CHECK-LABEL: test_fptoui_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fixeduwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fixeduwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x20100201
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x20100201
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 6)
  %r = fptoui <4 x float> %a to <4 x i16>
  ret <4 x i16> %r
}

define <4 x i8> @test_fptosi_i8(<4 x float> %a) #0 {
; CHECK-LABEL: test_fptosi_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fixedwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fixedwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 6)
  %r = fptosi <4 x float> %a to <4 x i8>
  ret <4 x i8> %r
}

define <4 x i8> @test_fptoui_i8(<4 x float> %a) #0 {
; CHECK-LABEL: test_fptoui_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fixeduwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fixeduwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 6)
  %r = fptoui <4 x float> %a to <4 x i8>
  ret <4 x i8> %r
}
define <4 x float> @test_uitofp_2xi32(<4 x i32> %a) #0 {
; CHECK-LABEL: test_uitofp_2xi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    floatuwp.rn $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    floatuwp.rn $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %r = uitofp <4 x i32> %a to <4 x float>
  ret <4 x float> %r
}

define <4 x float> @test_uitofp_2xi64(<4 x i64> %a) #0 {
; CHECK-LABEL: test_uitofp_2xi64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r2
; CHECK-NEXT:    copyd $r19 = $r1
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    copyd $r0 = $r3
; CHECK-NEXT:    call __floatundisf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call __floatundisf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call __floatundisf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r20
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    call __floatundisf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r19, 63, 32
; CHECK-NEXT:    insf $r18 = $r21, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = uitofp <4 x i64> %a to <4 x float>
  ret <4 x float> %r
}

define <4 x float> @test_sitofp_2xi32(<4 x i32> %a) #0 {
; CHECK-LABEL: test_sitofp_2xi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    floatwp.rn $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    floatwp.rn $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %r = sitofp <4 x i32> %a to <4 x float>
  ret <4 x float> %r
}

define <4 x float> @test_sitofp_2xi64(<4 x i64> %a) #0 {
; CHECK-LABEL: test_sitofp_2xi64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r2
; CHECK-NEXT:    copyd $r19 = $r1
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    copyd $r0 = $r3
; CHECK-NEXT:    call __floatdisf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call __floatdisf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call __floatdisf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r20
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    call __floatdisf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r19, 63, 32
; CHECK-NEXT:    insf $r18 = $r21, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sitofp <4 x i64> %a to <4 x float>
  ret <4 x float> %r
}

define <4 x float> @test_uitofp_2xi32_fadd(<4 x i32> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_uitofp_2xi32_fadd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    floatuwp.rn $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    floatuwp.rn $r0 = $r0, 0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    faddwq $r0r1 = $r2r3, $r0r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 5)
  %c = uitofp <4 x i32> %a to <4 x float>
  %r = fadd <4 x float> %b, %c
  ret <4 x float> %r
}

define <4 x float> @test_sitofp_2xi32_fadd(<4 x i32> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_sitofp_2xi32_fadd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    floatwp.rn $r1 = $r1, 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    floatwp.rn $r0 = $r0, 0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    faddwq $r0r1 = $r2r3, $r0r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 5)
  %c = sitofp <4 x i32> %a to <4 x float>
  %r = fadd <4 x float> %b, %c
  ret <4 x float> %r
}

define <4 x float> @test_fptrunc_2xdouble(<4 x double> %a) #0 {
; CHECK-LABEL: test_fptrunc_2xdouble:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fnarrowdwp $r3 = $r2r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fnarrowdwp $r0 = $r0r1
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %r = fptrunc <4 x double> %a to <4 x float>
  ret <4 x float> %r
}

define <4 x double> @test_fpext_2xdouble(<4 x float> %a) #0 {
; CHECK-LABEL: test_fpext_2xdouble:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlwd $r2 = $r1
; CHECK-NEXT:    fwidenmwd $r3 = $r1
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fwidenlwd $r0 = $r0
; CHECK-NEXT:    fwidenmwd $r1 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %r = fpext <4 x float> %a to <4 x double>
  ret <4 x double> %r
}

define <4 x i32> @test_bitcast_2xfloat_to_2xi32(<4 x float> %a) #0 {
; CHECK-LABEL: test_bitcast_2xfloat_to_2xi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = bitcast <4 x float> %a to <4 x i32>
  ret <4 x i32> %r
}

define <4 x float> @test_bitcast_2xi32_to_2xfloat(<4 x i32> %a) #0 {
; CHECK-LABEL: test_bitcast_2xi32_to_2xfloat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = bitcast <4 x i32> %a to <4 x float>
  ret <4 x float> %r
}

declare <4 x float> @llvm.sqrt.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.powi.v4f32(<4 x float> %a, i32 %b) #0
declare <4 x float> @llvm.sin.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.cos.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.pow.v4f32(<4 x float> %a, <4 x float> %b) #0
declare <4 x float> @llvm.exp.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.exp2.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.log.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.log10.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.log2.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.fma.v4f32(<4 x float> %a, <4 x float> %b, <4 x float> %c) #0
declare <4 x float> @llvm.fabs.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.minnum.v4f32(<4 x float> %a, <4 x float> %b) #0
declare <4 x float> @llvm.maxnum.v4f32(<4 x float> %a, <4 x float> %b) #0
declare <4 x float> @llvm.copysign.v4f32(<4 x float> %a, <4 x float> %b) #0
declare <4 x float> @llvm.floor.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.ceil.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.trunc.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.rint.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.nearbyint.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.round.v4f32(<4 x float> %a) #0
declare <4 x float> @llvm.fmuladd.v4f32(<4 x float> %a, <4 x float> %b, <4 x float> %c) #0

define <4 x float> @test_sqrt(<4 x float> %a) #0 {
; CHECK-LABEL: test_sqrt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @llvm.sqrt.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_powi(<4 x float> %a, i32 %b) #0 {
; CHECK-LABEL: test_powi:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sd 48[$r12] = $r22
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 32[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    sq 16[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r2
; CHECK-NEXT:    copyd $r19 = $r1
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    call __powisf2
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call __powisf2
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r20, 32
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    call __powisf2
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r20
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    copyd $r22 = $r0
; CHECK-NEXT:    call __powisf2
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r22, 63, 32
; CHECK-NEXT:    insf $r19 = $r21, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 16[$r12]
; CHECK-NEXT:    copyd $r1 = $r19
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 32[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r22 = 48[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 9)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x float> @llvm.powi.v4f32(<4 x float> %a, i32 %b)
 ret <4 x float> %r
}

define <4 x float> @test_sin(<4 x float> %a) #0 {
; CHECK-LABEL: test_sin:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call sinf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call sinf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call sinf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call sinf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @llvm.sin.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_cos(<4 x float> %a) #0 {
; CHECK-LABEL: test_cos:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call cosf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call cosf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call cosf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call cosf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @llvm.cos.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_pow(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_pow:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sd 48[$r12] = $r22
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 32[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    sq 16[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r3
; CHECK-NEXT:    copyd $r19 = $r2
; CHECK-NEXT:    copyd $r20 = $r1
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    srad $r0 = $r20, 32
; CHECK-NEXT:    srad $r1 = $r18, 32
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call powf
; CHECK-NEXT:    ;; # (end cycle 5)
; CHECK-NEXT:    copyd $r0 = $r20
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    copyd $r22 = $r0
; CHECK-NEXT:    call powf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r21, 32
; CHECK-NEXT:    srad $r1 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call powf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r21
; CHECK-NEXT:    copyd $r1 = $r19
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call powf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    insf $r18 = $r22, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 16[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 32[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r22 = 48[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 9)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x float> @llvm.pow.v4f32(<4 x float> %a, <4 x float> %b)
 ret <4 x float> %r
}

define <4 x float> @test_exp(<4 x float> %a) #0 {
; CHECK-LABEL: test_exp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call expf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call expf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call expf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call expf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x float> @llvm.exp.v4f32(<4 x float> %a)
 ret <4 x float> %r
}

define <4 x float> @test_exp2(<4 x float> %a) #0 {
; CHECK-LABEL: test_exp2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call exp2f
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call exp2f
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call exp2f
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call exp2f
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x float> @llvm.exp2.v4f32(<4 x float> %a)
 ret <4 x float> %r
}

define <4 x float> @test_log(<4 x float> %a) #0 {
; CHECK-LABEL: test_log:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call logf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call logf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call logf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call logf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x float> @llvm.log.v4f32(<4 x float> %a)
 ret <4 x float> %r
}

define <4 x float> @test_log10(<4 x float> %a) #0 {
; CHECK-LABEL: test_log10:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call log10f
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call log10f
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call log10f
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call log10f
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x float> @llvm.log10.v4f32(<4 x float> %a)
 ret <4 x float> %r
}

define <4 x float> @test_log2(<4 x float> %a) #0 {
; CHECK-LABEL: test_log2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call log2f
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call log2f
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call log2f
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call log2f
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x float> @llvm.log2.v4f32(<4 x float> %a)
 ret <4 x float> %r
}

define <4 x float> @test_fma(<4 x float> %a, <4 x float> %b, <4 x float> %c) #0 {
; KV3_1-LABEL: test_fma:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    ffmawp $r5 = $r1, $r3
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    ffmawp $r4 = $r0, $r2
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    copyd $r0 = $r4
; KV3_1-NEXT:    copyd $r1 = $r5
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 5)
;
; KV3_2-LABEL: test_fma:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    ffmawq $r4r5 = $r0r1, $r2r3
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    copyd $r0 = $r4
; KV3_2-NEXT:    copyd $r1 = $r5
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 4)
  %r = call <4 x float> @llvm.fma.v4f32(<4 x float> %a, <4 x float> %b, <4 x float> %c)
  ret <4 x float> %r
}

define <4 x float> @test_fabs(<4 x float> %a) #0 {
; CHECK-LABEL: test_fabs:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fabswp $r0 = $r0
; CHECK-NEXT:    fabswp $r1 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %r = call <4 x float> @llvm.fabs.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_minnum(<4 x float> %a, <4 x float> %b) #0 {
; KV3_1-LABEL: test_minnum:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    sllwps $r4 = $r0, 1
; KV3_1-NEXT:    sllwps $r5 = $r1, 1
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    compnwp.gtu $r4 = $r4, 0xff000000.@
; KV3_1-NEXT:    compnwp.gtu $r5 = $r5, 0xff000000.@
; KV3_1-NEXT:    fcompnwp.olt $r6 = $r2, $r0
; KV3_1-NEXT:    fcompnwp.olt $r7 = $r3, $r1
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    iord $r4 = $r6, $r4
; KV3_1-NEXT:    iord $r5 = $r7, $r5
; KV3_1-NEXT:    ;; # (end cycle 2)
; KV3_1-NEXT:    cmovewp.odd $r4 ? $r0 = $r2
; KV3_1-NEXT:    cmovewp.odd $r5 ? $r1 = $r3
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 3)
;
; KV3_2-LABEL: test_minnum:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    fminwp $r0 = $r0, $r2
; KV3_2-NEXT:    fminwp $r1 = $r1, $r3
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 0)
  %r = call <4 x float> @llvm.minnum.v4f32(<4 x float> %a, <4 x float> %b)
  ret <4 x float> %r
}

define <4 x float> @test_minnum_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_minnum_fast:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fminwp $r0 = $r0, $r2
; CHECK-NEXT:    fminwp $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %r = call fast <4 x float> @llvm.minnum.v4f32(<4 x float> %a, <4 x float> %b)
  ret <4 x float> %r
}

define <4 x float> @test_maxnum(<4 x float> %a, <4 x float> %b) #0 {
; KV3_1-LABEL: test_maxnum:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    sllwps $r4 = $r0, 1
; KV3_1-NEXT:    sllwps $r5 = $r1, 1
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    compnwp.gtu $r4 = $r4, 0xff000000.@
; KV3_1-NEXT:    compnwp.gtu $r5 = $r5, 0xff000000.@
; KV3_1-NEXT:    fcompnwp.olt $r6 = $r0, $r2
; KV3_1-NEXT:    fcompnwp.olt $r7 = $r1, $r3
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    iord $r4 = $r6, $r4
; KV3_1-NEXT:    iord $r5 = $r7, $r5
; KV3_1-NEXT:    ;; # (end cycle 2)
; KV3_1-NEXT:    cmovewp.odd $r4 ? $r0 = $r2
; KV3_1-NEXT:    cmovewp.odd $r5 ? $r1 = $r3
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 3)
;
; KV3_2-LABEL: test_maxnum:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    fmaxwp $r0 = $r0, $r2
; KV3_2-NEXT:    fmaxwp $r1 = $r1, $r3
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 0)
  %r = call <4 x float> @llvm.maxnum.v4f32(<4 x float> %a, <4 x float> %b)
  ret <4 x float> %r
}

define <4 x float> @test_maxnum_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_maxnum_fast:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmaxwp $r0 = $r0, $r2
; CHECK-NEXT:    fmaxwp $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %r = call fast <4 x float> @llvm.maxnum.v4f32(<4 x float> %a, <4 x float> %b)
  ret <4 x float> %r
}

define <4 x float> @test_copysign(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_copysign:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fabswp $r0 = $r0
; CHECK-NEXT:    fabswp $r1 = $r1
; CHECK-NEXT:    andd $r2 = $r2, 0x80000000.@
; CHECK-NEXT:    andd $r3 = $r3, 0x80000000.@
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    iord $r0 = $r0, $r2
; CHECK-NEXT:    iord $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %r = call <4 x float> @llvm.copysign.v4f32(<4 x float> %a, <4 x float> %b)
  ret <4 x float> %r
}

define <4 x float> @test_copysign_v4f16(<4 x float> %a, <4 x half> %b) #0 {
; KV3_1-LABEL: test_copysign_v4f16:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    fwidenmhwp $r3 = $r2
; KV3_1-NEXT:    fwidenlhwp $r4 = $r2
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    fabswp $r0 = $r0
; KV3_1-NEXT:    fabswp $r1 = $r1
; KV3_1-NEXT:    andd $r2 = $r3, 0x80000000.@
; KV3_1-NEXT:    andd $r3 = $r4, 0x80000000.@
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    iord $r0 = $r0, $r3
; KV3_1-NEXT:    iord $r1 = $r1, $r2
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 2)
;
; KV3_2-LABEL: test_copysign_v4f16:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    fabswp $r0 = $r0
; KV3_2-NEXT:    fabswp $r1 = $r1
; KV3_2-NEXT:    fwidenmhwp $r3 = $r2
; KV3_2-NEXT:    fwidenlhwp $r4 = $r2
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    andd $r2 = $r3, 0x80000000.@
; KV3_2-NEXT:    andd $r3 = $r4, 0x80000000.@
; KV3_2-NEXT:    ;; # (end cycle 1)
; KV3_2-NEXT:    iord $r0 = $r0, $r3
; KV3_2-NEXT:    iord $r1 = $r1, $r2
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 2)
  %tb = fpext <4 x half> %b to <4 x float>
  %r = call <4 x float> @llvm.copysign.v4f32(<4 x float> %a, <4 x float> %tb)
  ret <4 x float> %r
}

define <4 x float> @test_copysign_v4f64(<4 x float> %a, <4 x double> %b) #0 {
; KV3_1-LABEL: test_copysign_v4f64:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    copyd $r4 = $r2
; KV3_1-NEXT:    copyd $r5 = $r3
; KV3_1-NEXT:    copyd $r6 = $r4
; KV3_1-NEXT:    copyd $r7 = $r5
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    fabswp $r1 = $r1
; KV3_1-NEXT:    fnarrowdwp $r3 = $r6r7
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    fabswp $r0 = $r0
; KV3_1-NEXT:    fnarrowdwp $r2 = $r4r5
; KV3_1-NEXT:    andd $r3 = $r3, 0x80000000.@
; KV3_1-NEXT:    ;; # (end cycle 2)
; KV3_1-NEXT:    iord $r1 = $r1, $r3
; KV3_1-NEXT:    andd $r2 = $r2, 0x80000000.@
; KV3_1-NEXT:    ;; # (end cycle 3)
; KV3_1-NEXT:    iord $r0 = $r0, $r2
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 4)
;
; KV3_2-LABEL: test_copysign_v4f64:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    copyd $r4 = $r2
; KV3_2-NEXT:    copyd $r5 = $r3
; KV3_2-NEXT:    copyd $r6 = $r4
; KV3_2-NEXT:    copyd $r7 = $r5
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    fabswp $r0 = $r0
; KV3_2-NEXT:    fabswp $r1 = $r1
; KV3_2-NEXT:    fnarrowdwp $r3 = $r6r7
; KV3_2-NEXT:    ;; # (end cycle 1)
; KV3_2-NEXT:    fnarrowdwp $r2 = $r4r5
; KV3_2-NEXT:    andd $r3 = $r3, 0x80000000.@
; KV3_2-NEXT:    ;; # (end cycle 2)
; KV3_2-NEXT:    iord $r1 = $r1, $r3
; KV3_2-NEXT:    andd $r2 = $r2, 0x80000000.@
; KV3_2-NEXT:    ;; # (end cycle 3)
; KV3_2-NEXT:    iord $r0 = $r0, $r2
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 4)
  %tb = fptrunc <4 x double> %b to <4 x float>
  %r = call <4 x float> @llvm.copysign.v4f32(<4 x float> %a, <4 x float> %tb)
  ret <4 x float> %r
}

define <4 x double> @test_copysign_extended(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_copysign_extended:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fabswp $r0 = $r0
; CHECK-NEXT:    fabswp $r1 = $r1
; CHECK-NEXT:    andd $r2 = $r2, 0x80000000.@
; CHECK-NEXT:    andd $r3 = $r3, 0x80000000.@
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    iord $r0 = $r0, $r2
; CHECK-NEXT:    iord $r1 = $r1, $r3
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    fwidenlwd $r2 = $r1
; CHECK-NEXT:    fwidenmwd $r3 = $r1
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    fwidenlwd $r0 = $r0
; CHECK-NEXT:    fwidenmwd $r1 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 3)
  %r = call <4 x float> @llvm.copysign.v4f32(<4 x float> %a, <4 x float> %b)
  %xr = fpext <4 x float> %r to <4 x double>
  ret <4 x double> %xr
}

define <4 x float> @test_copysign_fp16(<4 x float> %a, <4 x half> %b) #0 {
; KV3_1-LABEL: test_copysign_fp16:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    fwidenmhwp $r3 = $r2
; KV3_1-NEXT:    fwidenlhwp $r4 = $r2
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    fabswp $r0 = $r0
; KV3_1-NEXT:    fabswp $r1 = $r1
; KV3_1-NEXT:    andd $r2 = $r3, 0x80000000.@
; KV3_1-NEXT:    andd $r3 = $r4, 0x80000000.@
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    iord $r0 = $r0, $r3
; KV3_1-NEXT:    iord $r1 = $r1, $r2
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 2)
;
; KV3_2-LABEL: test_copysign_fp16:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    fabswp $r0 = $r0
; KV3_2-NEXT:    fabswp $r1 = $r1
; KV3_2-NEXT:    fwidenmhwp $r3 = $r2
; KV3_2-NEXT:    fwidenlhwp $r4 = $r2
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    andd $r2 = $r3, 0x80000000.@
; KV3_2-NEXT:    andd $r3 = $r4, 0x80000000.@
; KV3_2-NEXT:    ;; # (end cycle 1)
; KV3_2-NEXT:    iord $r0 = $r0, $r3
; KV3_2-NEXT:    iord $r1 = $r1, $r2
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 2)
  %eb = fpext <4 x half> %b to <4 x float>
  %r = call <4 x float> @llvm.copysign.v4f32(<4 x float> %a, <4 x float> %eb)
  ret <4 x float> %r
}

define <4 x float> @test_floor(<4 x float> %a) #0 {
; CHECK-LABEL: test_floor:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call floorf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call floorf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call floorf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call floorf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @llvm.floor.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_ceil(<4 x float> %a) #0 {
; CHECK-LABEL: test_ceil:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call ceilf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call ceilf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call ceilf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call ceilf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @llvm.ceil.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_trunc(<4 x float> %a) #0 {
; CHECK-LABEL: test_trunc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @llvm.trunc.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_rint(<4 x float> %a) #0 {
; CHECK-LABEL: test_rint:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call rintf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call rintf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call rintf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call rintf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @llvm.rint.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_nearbyint(<4 x float> %a) #0 {
; CHECK-LABEL: test_nearbyint:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call nearbyintf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call nearbyintf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call nearbyintf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call nearbyintf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @llvm.nearbyint.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_round(<4 x float> %a) #0 {
; CHECK-LABEL: test_round:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call roundf
; CHECK-NEXT:    ;; # (end cycle 4)
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call roundf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    srad $r0 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    call roundf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r19
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    call roundf
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    insf $r18 = $r20, 63, 32
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;; # (end cycle 3)
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;; # (end cycle 8)
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x float> @llvm.round.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <4 x float> @test_fmuladd(<4 x float> %a, <4 x float> %b, <4 x float> %c) #0 {
; KV3_1-LABEL: test_fmuladd:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    ffmawp $r5 = $r1, $r3
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    ffmawp $r4 = $r0, $r2
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    copyd $r0 = $r4
; KV3_1-NEXT:    copyd $r1 = $r5
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 5)
;
; KV3_2-LABEL: test_fmuladd:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    ffmawq $r4r5 = $r0r1, $r2r3
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    copyd $r0 = $r4
; KV3_2-NEXT:    copyd $r1 = $r5
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 4)
  %r = call <4 x float> @llvm.fmuladd.v4f32(<4 x float> %a, <4 x float> %b, <4 x float> %c)
  ret <4 x float> %r
}

; TODO: Copyd is not required
define <4 x float> @test_shufflevector(<4 x float> %a) #0 {
; CHECK-LABEL: test_shufflevector:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r1 = $r0, 0x804020180402010
; CHECK-NEXT:    sbmm8 $r2 = $r1, 0x804020180402010
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
  %s = shufflevector <4 x float> %a, <4 x float> undef, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
  ret <4 x float> %s
}

define <4 x float> @test_insertelement0(<4 x float> %a, float %x) #0 {
; CHECK-LABEL: test_insertelement0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r2, 31, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %i = insertelement <4 x float> %a, float %x, i64 0
  ret <4 x float> %i
}

define <4 x float> @test_insertelement1(<4 x float> %a, float %x) #0 {
; CHECK-LABEL: test_insertelement1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r2, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
  %i = insertelement <4 x float> %a, float %x, i64 1
  ret <4 x float> %i
}

define <4 x float> @test_insertelement(<4 x float> %a, float %x, i64 %p) #0 {
; CHECK-LABEL: test_insertelement:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r2 = $r2, 63, 31
; CHECK-NEXT:    insf $r3 = $r3, 63, 31
; CHECK-NEXT:    make $r4 = 0x300000002
; CHECK-NEXT:    make $r5 = 0x100000000
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    compnwp.eq $r3 = $r5, $r3
; CHECK-NEXT:    compnwp.eq $r4 = $r4, $r3
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    cmovewp.eqz $r3 ? $r0 = $r2
; CHECK-NEXT:    cmovewp.eqz $r4 ? $r1 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
  %i = insertelement <4 x float> %a, float %x, i64 %p
  ret <4 x float> %i
}

define <4 x i32> @fcmp_setoeq(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setoeq:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oeq $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.oeq $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp oeq <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setoeq_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setoeq_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oeq $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.oeq $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp oeq <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setogt(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setogt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.olt $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.olt $r1 = $r3, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ogt <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setogt_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setogt_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ogt <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setoge(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setoge:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp oge <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setoge_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setoge_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oeq $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.oeq $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp oge <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setolt(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setolt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.olt $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.olt $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp olt <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setolt_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setolt_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp olt <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setole(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setole:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oge $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.oge $r1 = $r3, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ole <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setole_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setole_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oeq $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.oeq $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ole <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setone(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setone:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.one $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.one $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp one <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setone_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setone_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp one <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setord(<4 x float> %a, <4 x float> %b) #0 {
; KV3_1-LABEL: fcmp_setord:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; KV3_1-NEXT:    fcompnwp.olt $r4 = $r1, $r3
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; KV3_1-NEXT:    iord $r1 = $r1, $r4
; KV3_1-NEXT:    fcompnwp.olt $r3 = $r0, $r2
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    iord $r0 = $r0, $r3
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 2)
;
; KV3_2-LABEL: fcmp_setord:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; KV3_2-NEXT:    fcompnwp.olt $r3 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.olt $r4 = $r1, $r3
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    iord $r0 = $r0, $r3
; KV3_2-NEXT:    iord $r1 = $r1, $r4
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 1)
entry:
  %0 = fcmp ord <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setord_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setord_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oeq $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.oeq $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ord <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setuno(<4 x float> %a, <4 x float> %b) #0 {
; KV3_1-LABEL: fcmp_setuno:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnwp.uge $r1 = $r1, $r3
; KV3_1-NEXT:    fcompnwp.ult $r4 = $r1, $r3
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    fcompnwp.uge $r0 = $r0, $r2
; KV3_1-NEXT:    andd $r1 = $r1, $r4
; KV3_1-NEXT:    fcompnwp.ult $r3 = $r0, $r2
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    andd $r0 = $r0, $r3
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 2)
;
; KV3_2-LABEL: fcmp_setuno:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnwp.uge $r0 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.uge $r1 = $r1, $r3
; KV3_2-NEXT:    fcompnwp.ult $r3 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.ult $r4 = $r1, $r3
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    andd $r0 = $r0, $r3
; KV3_2-NEXT:    andd $r1 = $r1, $r4
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 1)
entry:
  %0 = fcmp uno <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setuno_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setuno_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.une $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.une $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp uno <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setueq(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setueq:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.ueq $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.ueq $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ueq <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setueq_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setueq_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ueq <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setugt(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setugt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.ult $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.ult $r1 = $r3, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ugt <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setugt_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setugt_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.une $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.une $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ugt <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setuge(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setuge:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.uge $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.uge $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp uge <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setuge_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setuge_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp uge <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setult(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setult:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.ult $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.ult $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ult <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setult_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setult_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.une $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.une $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ult <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setule(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setule:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.uge $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.uge $r1 = $r3, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ule <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setule_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setule_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp ule <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setune(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setune:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.une $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.une $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp une <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setune_single(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setune_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.une $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.une $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp une <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setoeq_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setoeq_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oeq $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.oeq $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast oeq <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setoeq_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setoeq_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast oeq <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setogt_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setogt_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.olt $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.olt $r1 = $r3, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ogt <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setogt_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setogt_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ogt <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setoge_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setoge_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast oge <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setoge_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setoge_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast oge <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setolt_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setolt_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.olt $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.olt $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast olt <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setolt_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setolt_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast olt <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setole_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setole_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oge $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.oge $r1 = $r3, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ole <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setole_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setole_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ole <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setone_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setone_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.one $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.one $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast one <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setone_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setone_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast one <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setord_fast(<4 x float> %a, <4 x float> %b) #0 {
; KV3_1-LABEL: fcmp_setord_fast:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; KV3_1-NEXT:    fcompnwp.olt $r4 = $r1, $r3
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; KV3_1-NEXT:    iord $r1 = $r1, $r4
; KV3_1-NEXT:    fcompnwp.olt $r3 = $r0, $r2
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    iord $r0 = $r0, $r3
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 2)
;
; KV3_2-LABEL: fcmp_setord_fast:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; KV3_2-NEXT:    fcompnwp.olt $r3 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.olt $r4 = $r1, $r3
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    iord $r0 = $r0, $r3
; KV3_2-NEXT:    iord $r1 = $r1, $r4
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 1)
entry:
  %0 = fcmp fast ord <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setord_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setord_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oeq $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.oeq $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ord <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setuno_fast(<4 x float> %a, <4 x float> %b) #0 {
; KV3_1-LABEL: fcmp_setuno_fast:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnwp.uge $r1 = $r1, $r3
; KV3_1-NEXT:    fcompnwp.ult $r4 = $r1, $r3
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    fcompnwp.uge $r0 = $r0, $r2
; KV3_1-NEXT:    andd $r1 = $r1, $r4
; KV3_1-NEXT:    fcompnwp.ult $r3 = $r0, $r2
; KV3_1-NEXT:    ;; # (end cycle 1)
; KV3_1-NEXT:    andd $r0 = $r0, $r3
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 2)
;
; KV3_2-LABEL: fcmp_setuno_fast:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnwp.uge $r0 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.uge $r1 = $r1, $r3
; KV3_2-NEXT:    fcompnwp.ult $r3 = $r0, $r2
; KV3_2-NEXT:    fcompnwp.ult $r4 = $r1, $r3
; KV3_2-NEXT:    ;; # (end cycle 0)
; KV3_2-NEXT:    andd $r0 = $r0, $r3
; KV3_2-NEXT:    andd $r1 = $r1, $r4
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 1)
entry:
  %0 = fcmp fast uno <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setuno_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setuno_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.une $r0 = $r0, $r0
; CHECK-NEXT:    fcompnwp.une $r1 = $r1, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast uno <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setueq_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setueq_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oeq $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.oeq $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ueq <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setueq_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setueq_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ueq <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setugt_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setugt_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.olt $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.olt $r1 = $r3, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ugt <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setugt_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setugt_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ugt <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setuge_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setuge_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oge $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.oge $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast uge <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setuge_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setuge_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast uge <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setult_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setult_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.olt $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.olt $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ult <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setult_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setult_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ult <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setule_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setule_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.oge $r0 = $r2, $r0
; CHECK-NEXT:    fcompnwp.oge $r1 = $r3, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ule <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setule_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setule_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast ule <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setune_fast(<4 x float> %a, <4 x float> %b) #0 {
; CHECK-LABEL: fcmp_setune_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnwp.one $r0 = $r0, $r2
; CHECK-NEXT:    fcompnwp.one $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast une <4 x float> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

define <4 x i32> @fcmp_setune_single_fast(<4 x float> %a) #0 {
; CHECK-LABEL: fcmp_setune_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %0 = fcmp fast une <4 x float> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i32>
  ret <4 x i32> %1
}

attributes #0 = { nounwind }

define <4 x float> @fms(<4 x float>, <4 x float>, <4 x float>) {
; KV3_1-LABEL: fms:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    ffmswp $r1 = $r5, $r3
; KV3_1-NEXT:    ;; # (end cycle 0)
; KV3_1-NEXT:    ffmswp $r0 = $r4, $r2
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;; # (end cycle 1)
;
; KV3_2-LABEL: fms:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    ffmswq $r0r1 = $r4r5, $r2r3
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;; # (end cycle 0)
  %4 = fmul fast <4 x float> %2, %1
  %5 = fsub fast <4 x float> %0, %4
  ret <4 x float> %5
}

define void @subvec0fp(ptr %0) {
; CHECK-LABEL: subvec0fp:
; CHECK:       # %bb.0:
  br label %2

2:
  %3 = shufflevector <4 x float> zeroinitializer, <4 x float> undef, <2 x i32> <i32 0, i32 1>
  %4 = fadd <2 x float> zeroinitializer, %3
  %5 = shufflevector <2 x float> %4, <2 x float> poison, <4 x i32> <i32 0, i32 1, i32 undef, i32 undef>
  %6 = shufflevector <4 x float> %5, <4 x float> zeroinitializer, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
  store <4 x float> %6, ptr undef, align 16
  br label %2
}

define void @subvec2fp(ptr %0) {
; CHECK-LABEL: subvec2fp:
; CHECK:       # %bb.0:
  br label %2

2:
  %3 = shufflevector <4 x float> zeroinitializer, <4 x float> undef, <2 x i32> <i32 0, i32 1>
  %4 = fadd <2 x float> zeroinitializer, %3
  %5 = shufflevector <2 x float> %4, <2 x float> poison, <4 x i32> <i32 0, i32 1, i32 undef, i32 undef>
  %6 = shufflevector <4 x float> %5, <4 x float> zeroinitializer, <4 x i32> <i32 6, i32 7, i32 2, i32 3>
  store <4 x float> %6, ptr undef, align 16
  br label %2
}

; TODO: compd.eq is not required, should invert the fcomp CC and use cmoved.deqz
define <4 x float> @test_select_cmp(<4 x float> %a, <4 x float> %b, <4 x float> %c, <4 x float> %d) #0 {
; CHECK-LABEL: test_select_cmp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.une $r4 = $r4, $r6
; CHECK-NEXT:    fcompnwp.une $r5 = $r5, $r7
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    andd $r4 = $r4, $r5
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    compd.eq $r4 = $r4, -1
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    cmoved.even $r4 ? $r0 = $r2
; CHECK-NEXT:    cmoved.even $r4 ? $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 3)
  %cc = fcmp une <4 x float> %c, %d
  %bc = bitcast <4 x i1> %cc to i4
  %cmp = icmp eq i4 %bc, -1
  %r = select i1 %cmp, <4 x float> %a, <4 x float> %b
  ret <4 x float> %r
}
