; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <2 x float> @expand2(<2 x half> %a) {
; CHECK-LABEL: expand2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fwidenlhwp $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %conv = fpext <2 x half> %a to <2 x float>
  ret <2 x float> %conv
}

define <4 x float> @expand4(<4 x half> %a) {
; CHECK-LABEL: expand4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    fwidenlhwp $r2 = $r0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
entry:
  %conv = fpext <4 x half> %a to <4 x float>
  ret <4 x float> %conv
}

define <8 x float> @expand8(<8 x half> %a) {
; CHECK-LABEL: expand8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fwidenlhwp $r2 = $r1
; CHECK-NEXT:    fwidenlhwp $r4 = $r0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    copyd $r0 = $r4
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    fwidenmhwp $r3 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
entry:
  %conv = fpext <8 x half> %a to <8 x float>
  ret <8 x float> %conv
}

define <2 x half> @narrow2(<2 x float> %a) {
; CHECK-LABEL: narrow2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fnarrowwhq $r0 = $r0r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
entry:
  %conv = fptrunc <2 x float> %a to <2 x half>
  ret <2 x half> %conv
}

define <4 x half> @narrow4(<4 x float> %a) {
; CHECK-LABEL: narrow4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fnarrowwhq $r0 = $r0r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %conv = fptrunc <4 x float> %a to <4 x half>
  ret <4 x half> %conv
}

define <8 x half> @narrow8(<8 x float> %a) {
; CHECK-LABEL: narrow8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fnarrowwhq $r0 = $r0r1
; CHECK-NEXT:    fnarrowwhq $r1 = $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 0)
entry:
  %conv = fptrunc <8 x float> %a to <8 x half>
  ret <8 x half> %conv
}

define <2 x half> @narrow2d(<2 x double> %a) {
; CHECK-LABEL: narrow2d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fnarrowdwp $r0 = $r0r1
; CHECK-NEXT:    make $r1 = 0
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fnarrowwhq $r0 = $r0r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 1)
entry:
  %conv = fptrunc <2 x double> %a to <2 x half>
  ret <2 x half> %conv
}

define <4 x half> @narrow4d(<4 x double> %a) {
; CHECK-LABEL: narrow4d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fnarrowdwp $r3 = $r2r3
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    fnarrowdwp $r2 = $r0r1
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    fnarrowwhq $r0 = $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 2)
entry:
  %conv = fptrunc <4 x double> %a to <4 x half>
  ret <4 x half> %conv
}
