; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -o - %s | FileCheck %s
target triple = "kvx-kalray-cos"

define void @foo(i1 %v) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cb.even $r0 ? .LBB0_2
; CHECK-NEXT:    ;;
; CHECK-NEXT:  # %bb.1: # %b
; CHECK-NEXT:    fence
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:  .LBB0_2: # %e
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  br i1 %v, label %b, label %e

b:
  tail call void @llvm.kvx.fence()
  br label %e

e:
  ret void
}

declare void @llvm.kvx.fence()

