// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -O3 -triple kvx-kalray-cos -S -emit-llvm -target-cpu kv3-2 -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @use_2k_buff(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load <2048 x i1>, ptr [[X:%.*]], align 32, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <256 x i1> asm sideeffect "xaligno $0 = $1, $2", "=x,x,r,0"(<2048 x i1> [[TMP0]], i32 [[C:%.*]], <256 x i1> undef) #[[ATTR2:[0-9]+]], !srcloc !6
// CHECK-NEXT:    ret void
//
void use_2k_buff(__kvx_x2048 *x, int c) {
  __kvx_x256 out;
  __asm__ volatile("xaligno %0 = %1, %2"
                   : "+x"(out)
                   : "x"(x[0]), "r"(c)
                   : );
}

// CHECK-LABEL: @use_4k_buff(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load <4096 x i1>, ptr [[X:%.*]], align 32, !tbaa [[TBAA7:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <256 x i1> asm sideeffect "xaligno $0 = $1, $2", "=x,x,r,0"(<4096 x i1> [[TMP0]], i32 [[C:%.*]], <256 x i1> undef) #[[ATTR2]], !srcloc !9
// CHECK-NEXT:    ret void
//
void use_4k_buff(__kvx_x4096 *x, int c) {
  __kvx_x256 out;
  __asm__ volatile("xaligno %0 = %1, %2"
                   : "+x"(out)
                   : "x"(x[0]), "r"(c)
                   : );
}

// CHECK-LABEL: @use_2k_buff_clobber(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load <4096 x i1>, ptr [[X:%.*]], align 32, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <256 x i1> asm sideeffect "xaligno $0 = $1, $2", "=x,x,r,0,~{$a0..a7}"(<4096 x i1> [[TMP0]], i32 [[C:%.*]], <256 x i1> undef) #[[ATTR2]], !srcloc !10
// CHECK-NEXT:    ret void
//
void use_2k_buff_clobber(__kvx_x4096 *x, int c) {
  __kvx_x256 out;
  __asm__ volatile("xaligno %0 = %1, %2"
                   : "+x"(out)
                   : "x"(x[0]), "r"(c)
                   : "$a0..a7");
}

// CHECK-LABEL: @use_4k_buff_clobber(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load <4096 x i1>, ptr [[X:%.*]], align 32, !tbaa [[TBAA7]]
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <256 x i1> asm sideeffect "xaligno $0 = $1, $2", "=x,x,r,0,~{$a0..a15}"(<4096 x i1> [[TMP0]], i32 [[C:%.*]], <256 x i1> undef) #[[ATTR2]], !srcloc !11
// CHECK-NEXT:    ret void
//
void use_4k_buff_clobber(__kvx_x4096 *x, int c) {
  __kvx_x256 out;
  __asm__ volatile("xaligno %0 = %1, %2"
                   : "+x"(out)
                   : "x"(x[0]), "r"(c)
                   : "$a0..a15");
}
