// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

#define FALSE 0
#define TRUE 1

// CHECK-LABEL: @ld(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to i64*
// CHECK-NEXT:    [[TMP1:%.*]] = load volatile i64, i64* [[TMP0]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile i64, i64* [[TMP0]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load volatile i64, i64* [[TMP0]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = load volatile i64, i64* [[TMP0]], align 8
// CHECK-NEXT:    [[SEXT:%.*]] = shl i64 [[TMP4]], 32
// CHECK-NEXT:    [[CONV4:%.*]] = ashr exact i64 [[SEXT]], 32
// CHECK-NEXT:    ret i64 [[CONV4]]
//
long ld(volatile void *p) {
  int ret;
  ret = __builtin_kvx_ld(p, "", TRUE);
  ret = __builtin_kvx_ld(p, "", TRUE);
  ret = __builtin_kvx_ld(p, "", FALSE);
  ret = __builtin_kvx_ld(p, "", FALSE);
  return ret;
}
