// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -emit-llvm %s -O2 -o - | FileCheck %s

typedef __int128 i128;
typedef unsigned __int128 u128;
// CHECK-LABEL: @add(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i128 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret i128 [[ADD]]
//
i128 add(i128 a, i128 b){
    return a + b;
}

// CHECK-LABEL: @sub(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret i128 [[SUB]]
//
i128 sub(i128 a, i128 b){
    return a - b;
}

// CHECK-LABEL: @mul(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul nsw i128 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret i128 [[MUL]]
//
i128 mul(i128 a, i128 b){
    return a * b;
}

// CHECK-LABEL: @instxor(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[XOR:%.*]] = xor i128 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret i128 [[XOR]]
//
i128 instxor(i128 a, i128 b){
    return a ^ b;
}

// CHECK-LABEL: @nxor(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = xor i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[XOR:%.*]] = xor i128 [[TMP0]], -1
// CHECK-NEXT:    ret i128 [[XOR]]
//
i128 nxor(i128 a, i128 b){
    return ~a ^ b;
}

// CHECK-LABEL: @nand(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND:%.*]] = and i128 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    [[NEG:%.*]] = xor i128 [[AND]], -1
// CHECK-NEXT:    ret i128 [[NEG]]
//
i128 nand(i128 a, i128 b){
    return ~(a & b);
}

// CHECK-LABEL: @nor(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[OR:%.*]] = or i128 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    [[NEG:%.*]] = xor i128 [[OR]], -1
// CHECK-NEXT:    ret i128 [[NEG]]
//
i128 nor(i128 a, i128 b){
    return ~(a | b);
}

// CHECK-LABEL: @nor_2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND_DEMORGAN:%.*]] = or i128 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    [[AND:%.*]] = xor i128 [[AND_DEMORGAN]], -1
// CHECK-NEXT:    ret i128 [[AND]]
//
i128 nor_2(i128 a, i128 b){
    return ~a & ~b;
}

// CHECK-LABEL: @andn_1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[NEG:%.*]] = xor i128 [[A:%.*]], -1
// CHECK-NEXT:    [[AND:%.*]] = and i128 [[NEG]], [[B:%.*]]
// CHECK-NEXT:    ret i128 [[AND]]
//
i128 andn_1(i128 a, i128 b){
    return ~a & b;
}

// CHECK-LABEL: @andn_2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[NEG:%.*]] = xor i128 [[B:%.*]], -1
// CHECK-NEXT:    [[AND:%.*]] = and i128 [[NEG]], [[A:%.*]]
// CHECK-NEXT:    ret i128 [[AND]]
//
i128 andn_2(i128 a, i128 b){
    return a & ~b;
}

// CHECK-LABEL: @and(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[AND:%.*]] = and i128 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret i128 [[AND]]
//
i128 and(i128 a, i128 b){
    return a & b;
}

// CHECK-LABEL: @or(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[OR:%.*]] = or i128 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret i128 [[OR]]
//
i128 or(i128 a, i128 b){
    return a | b;
}

// CHECK-LABEL: @land(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i128 [[A:%.*]], 0
// CHECK-NEXT:    [[TOBOOL1:%.*]] = icmp ne i128 [[B:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = and i1 [[TOBOOL]], [[TOBOOL1]]
// CHECK-NEXT:    [[LAND_EXT:%.*]] = zext i1 [[TMP0]] to i32
// CHECK-NEXT:    ret i32 [[LAND_EXT]]
//
int land(i128 a, i128 b){
    return a && b;
}

// CHECK-LABEL: @lor(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = or i128 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ne i128 [[TMP0]], 0
// CHECK-NEXT:    [[LOR_EXT:%.*]] = zext i1 [[TMP1]] to i32
// CHECK-NEXT:    ret i32 [[LOR_EXT]]
//
int lor(i128 a, i128 b){
    return a || b;
}

// CHECK-LABEL: @sext_1_1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = and i8 [[A:%.*]], 1
// CHECK-NEXT:    [[AND:%.*]] = zext i8 [[TMP0]] to i32
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 0, [[AND]]
// CHECK-NEXT:    [[CONV1:%.*]] = sext i32 [[SUB]] to i128
// CHECK-NEXT:    ret i128 [[CONV1]]
//
i128 sext_1_1(char a){
    return -(a & 1);
}

// CHECK-LABEL: @sext_1_2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i8 [[A:%.*]], 0
// CHECK-NEXT:    [[TOBOOL2:%.*]] = icmp ne i8 [[B:%.*]], 0
// CHECK-NEXT:    [[TMP0:%.*]] = and i1 [[TOBOOL]], [[TOBOOL2]]
// CHECK-NEXT:    [[CONV3:%.*]] = sext i1 [[TMP0]] to i128
// CHECK-NEXT:    ret i128 [[CONV3]]
//
i128 sext_1_2(char a, char b){
    return -(a && b);
}

// CHECK-LABEL: @sext_8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = sext i8 [[B:%.*]] to i128
// CHECK-NEXT:    ret i128 [[CONV]]
//
i128 sext_8(char b){
    return b;
}

// CHECK-LABEL: @sext_16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[B:%.*]] to i128
// CHECK-NEXT:    ret i128 [[CONV]]
//
i128 sext_16(short b){
    return b;
}

// CHECK-LABEL: @sext_32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[B:%.*]] to i128
// CHECK-NEXT:    ret i128 [[CONV]]
//
i128 sext_32(int b){
    return b;
}

// CHECK-LABEL: @sext_64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = sext i64 [[B:%.*]] to i128
// CHECK-NEXT:    ret i128 [[CONV]]
//
i128 sext_64(long b){
    return b;
}

// CHECK-LABEL: @zext_8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[B:%.*]] to i128
// CHECK-NEXT:    ret i128 [[CONV]]
//
i128 zext_8(unsigned char b){
    return b;
}

// CHECK-LABEL: @zext_16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = zext i16 [[B:%.*]] to i128
// CHECK-NEXT:    ret i128 [[CONV]]
//
i128 zext_16(unsigned short b){
    return b;
}

// CHECK-LABEL: @zext_32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = zext i32 [[B:%.*]] to i128
// CHECK-NEXT:    ret i128 [[CONV]]
//
i128 zext_32(unsigned int b){
    return b;
}

// CHECK-LABEL: @zext_64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = zext i64 [[B:%.*]] to i128
// CHECK-NEXT:    ret i128 [[CONV]]
//
i128 zext_64(unsigned long b){
    return b;
}


// CHECK-LABEL: @MADDDT(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = sext i64 [[A:%.*]] to i128
// CHECK-NEXT:    [[CONV1:%.*]] = sext i64 [[B:%.*]] to i128
// CHECK-NEXT:    [[MUL:%.*]] = mul nsw i128 [[CONV1]], [[CONV]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i128 [[MUL]], [[C:%.*]]
// CHECK-NEXT:    ret i128 [[ADD]]
//
i128 MADDDT(i128 c, long a, long b){
    return c + (i128)a * (i128)b;
}

// CHECK-LABEL: @MADDSUDT_1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = zext i64 [[A:%.*]] to i128
// CHECK-NEXT:    [[CONV1:%.*]] = sext i64 [[B:%.*]] to i128
// CHECK-NEXT:    [[MUL:%.*]] = mul nsw i128 [[CONV1]], [[CONV]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i128 [[MUL]], [[C:%.*]]
// CHECK-NEXT:    ret i128 [[ADD]]
//
i128 MADDSUDT_1(i128 c, unsigned long a, long b){
    return c + (i128)a * (i128)b;
}

// CHECK-LABEL: @MADDSUDT_2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = sext i64 [[A:%.*]] to i128
// CHECK-NEXT:    [[CONV1:%.*]] = zext i64 [[B:%.*]] to i128
// CHECK-NEXT:    [[MUL:%.*]] = mul nsw i128 [[CONV1]], [[CONV]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i128 [[MUL]], [[C:%.*]]
// CHECK-NEXT:    ret i128 [[ADD]]
//
i128 MADDSUDT_2(i128 c, long a, unsigned long b){
    return c + (i128)a * (i128)b;
}

// CHECK-LABEL: @MADDUDT(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = zext i64 [[A:%.*]] to i128
// CHECK-NEXT:    [[CONV1:%.*]] = zext i64 [[B:%.*]] to i128
// CHECK-NEXT:    [[MUL:%.*]] = mul nuw nsw i128 [[CONV1]], [[CONV]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i128 [[MUL]], [[C:%.*]]
// CHECK-NEXT:    ret i128 [[ADD]]
//
i128 MADDUDT(i128 c, unsigned long a, unsigned long b){
    return c + (i128)a * (i128)b;
}

// CHECK-LABEL: @MADDUZDT(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = lshr i128 [[C:%.*]], 64
// CHECK-NEXT:    [[CONV:%.*]] = zext i64 [[A:%.*]] to i128
// CHECK-NEXT:    [[CONV1:%.*]] = zext i64 [[B:%.*]] to i128
// CHECK-NEXT:    [[MUL:%.*]] = mul nuw nsw i128 [[CONV1]], [[CONV]]
// CHECK-NEXT:    [[ADD:%.*]] = add nuw i128 [[MUL]], [[SHR]]
// CHECK-NEXT:    ret i128 [[ADD]]
//
i128 MADDUZDT(u128 c, unsigned long a, unsigned long b){
    return (c >> 64) + (i128)a * (i128)b;
}

// CHECK-LABEL: @MSBFDT(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = sext i64 [[A:%.*]] to i128
// CHECK-NEXT:    [[CONV1:%.*]] = sext i64 [[B:%.*]] to i128
// CHECK-NEXT:    [[MUL:%.*]] = mul nsw i128 [[CONV1]], [[CONV]]
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i128 [[C:%.*]], [[MUL]]
// CHECK-NEXT:    ret i128 [[SUB]]
//
i128 MSBFDT(i128 c, long a, long b){
    return c - (i128)a * (i128)b;
}

// CHECK-LABEL: @MSBFSUDT_1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = zext i64 [[A:%.*]] to i128
// CHECK-NEXT:    [[CONV1:%.*]] = sext i64 [[B:%.*]] to i128
// CHECK-NEXT:    [[MUL:%.*]] = mul nsw i128 [[CONV1]], [[CONV]]
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i128 [[C:%.*]], [[MUL]]
// CHECK-NEXT:    ret i128 [[SUB]]
//
i128 MSBFSUDT_1(i128 c, unsigned long a, long b){
    return c - (i128)a * (i128)b;
}

// CHECK-LABEL: @MSBFSUDT_2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = sext i64 [[A:%.*]] to i128
// CHECK-NEXT:    [[CONV1:%.*]] = zext i64 [[B:%.*]] to i128
// CHECK-NEXT:    [[MUL:%.*]] = mul nsw i128 [[CONV1]], [[CONV]]
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i128 [[C:%.*]], [[MUL]]
// CHECK-NEXT:    ret i128 [[SUB]]
//
i128 MSBFSUDT_2(i128 c, long a, unsigned long b){
    return c - (i128)a * (i128)b;
}

// CHECK-LABEL: @MSBFUDT(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = zext i64 [[A:%.*]] to i128
// CHECK-NEXT:    [[CONV1:%.*]] = zext i64 [[B:%.*]] to i128
// CHECK-NEXT:    [[MUL:%.*]] = mul nuw nsw i128 [[CONV1]], [[CONV]]
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i128 [[C:%.*]], [[MUL]]
// CHECK-NEXT:    ret i128 [[SUB]]
//
i128 MSBFUDT(i128 c, unsigned long a, unsigned long b){
    return c - (i128)a * (i128)b;
}

// CHECK-LABEL: @ld(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i128, ptr [[A:%.*]], align 16, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    ret i128 [[TMP0]]
//
i128 ld(i128 *a){
  return a[0];
}

// CHECK-LABEL: @st(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    store i128 [[V:%.*]], ptr [[A:%.*]], align 16, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
void st(i128 v, i128 *a){
  a[0] = v;
}

// CHECK-LABEL: @not(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[NEG:%.*]] = xor i128 [[A:%.*]], -1
// CHECK-NEXT:    ret i128 [[NEG]]
//
i128 not(i128 a){
  return ~a;
}

// CHECK-LABEL: @neg(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i128 0, [[A:%.*]]
// CHECK-NEXT:    ret i128 [[SUB]]
//
i128 neg(i128 a){
  return -a;
}

// CHECK-LABEL: @lnot(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i128 [[A:%.*]], 0
// CHECK-NEXT:    [[LNOT_EXT:%.*]] = zext i1 [[TOBOOL_NOT]] to i32
// CHECK-NEXT:    ret i32 [[LNOT_EXT]]
//
int lnot(i128 a){
  return !a;
}

// CHECK-LABEL: @lnot_eqz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i128 [[A:%.*]], 0
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int lnot_eqz(i128 a){
  return a == 0;
}

// CHECK-LABEL: @nez(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ne i128 [[A:%.*]], 0
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int nez(i128 a){
  return a != 0;
}

// CHECK-LABEL: @gez(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i128 [[A:%.*]], -1
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int gez(i128 a){
  return a >= 0;
}

// CHECK-LABEL: @u_gez(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i32 1
//
int u_gez(u128 a){
  return a >= 0;
}

// CHECK-LABEL: @gtz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i128 [[A:%.*]], 0
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int gtz(i128 a){
  return a > 0;
}

// CHECK-LABEL: @u_gtz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ne i128 [[A:%.*]], 0
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int u_gtz(u128 a){
  return a > 0;
}

// CHECK-LABEL: @ltz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A_LOBIT:%.*]] = lshr i128 [[A:%.*]], 127
// CHECK-NEXT:    [[TMP0:%.*]] = trunc i128 [[A_LOBIT]] to i32
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int ltz(i128 a){
  return a < 0;
}

// CHECK-LABEL: @u_ltz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i32 0
//
int u_ltz(u128 a){
  return a < 0;
}

// CHECK-LABEL: @lez(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i128 [[A:%.*]], 1
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int lez(i128 a){
  return a <= 0;
}

// CHECK-LABEL: @u_lez(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i128 [[A:%.*]], 0
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int u_lez(u128 a){
  return a <= 0;
}

// CHECK-LABEL: @eq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int eq(i128 a, i128 b){
  return a == b;
}

// CHECK-LABEL: @ne(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ne i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int ne(i128 a, i128 b){
  return a != b;
}

// CHECK-LABEL: @gt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int gt(i128 a, i128 b){
  return a > b;
}

// CHECK-LABEL: @u_gt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ugt i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int u_gt(u128 a, i128 b){
  return a > b;
}

// CHECK-LABEL: @ge(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp sge i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int ge(i128 a, i128 b){
  return a >= b;
}

// CHECK-LABEL: @uge(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp uge i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int uge(u128 a, i128 b){
  return a >= b;
}

// CHECK-LABEL: @lt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int lt(i128 a, i128 b){
  return a < b;
}

// CHECK-LABEL: @ult(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ult i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int ult(u128 a, i128 b){
  return a < b;
}

// CHECK-LABEL: @le(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp sle i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int le(i128 a, i128 b){
  return a <= b;
}

// CHECK-LABEL: @ule(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CMP:%.*]] = icmp ule i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int ule(u128 a, i128 b){
  return a <= b;
}

// CHECK-LABEL: @shl_64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHL:%.*]] = shl i128 [[A:%.*]], 64
// CHECK-NEXT:    ret i128 [[SHL]]
//
i128 shl_64(i128 a){
  return a << 64;
}

// CHECK-LABEL: @lshr_64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = lshr i128 [[A:%.*]], 64
// CHECK-NEXT:    ret i128 [[SHR]]
//
u128 lshr_64(u128 a){
  return a >> 64;
}

// CHECK-LABEL: @ashr_64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = ashr i128 [[A:%.*]], 64
// CHECK-NEXT:    ret i128 [[SHR]]
//
i128 ashr_64(i128 a){
  return a >> 64;
}

// CHECK-LABEL: @shl(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SH_PROM:%.*]] = zext i32 [[B:%.*]] to i128
// CHECK-NEXT:    [[SHL:%.*]] = shl i128 [[A:%.*]], [[SH_PROM]]
// CHECK-NEXT:    ret i128 [[SHL]]
//
i128 shl(i128 a, int b){
    return a << b;
}

// CHECK-LABEL: @lshr(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SH_PROM:%.*]] = zext i32 [[B:%.*]] to i128
// CHECK-NEXT:    [[SHR:%.*]] = lshr i128 [[A:%.*]], [[SH_PROM]]
// CHECK-NEXT:    ret i128 [[SHR]]
//
i128 lshr(u128 a, unsigned b){
    return a >> b;
}

// CHECK-LABEL: @ashr(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SH_PROM:%.*]] = zext i32 [[B:%.*]] to i128
// CHECK-NEXT:    [[SHR:%.*]] = ashr i128 [[A:%.*]], [[SH_PROM]]
// CHECK-NEXT:    ret i128 [[SHR]]
//
i128 ashr(i128 a, unsigned b){
    return a >> b;
}

// CHECK-LABEL: @sdiv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret i128 [[DIV]]
//
i128 sdiv(i128 a, i128 b){
  return a/b;
}

// CHECK-LABEL: @udiv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = udiv i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret i128 [[DIV]]
//
u128 udiv(u128 a, u128 b){
  return a/b;
}

// CHECK-LABEL: @sudiv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = udiv i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret i128 [[DIV]]
//
i128 sudiv(i128 a, u128 b){
  return a/b;
}

// CHECK-LABEL: @usdiv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = udiv i128 [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret i128 [[DIV]]
//
i128 usdiv(u128 a, i128 b){
  return a/b;
}
