// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -emit-llvm %s -Os -o - | FileCheck %s --check-prefixes=OPS
// RUN: %clang_cc1 -triple kvx-kalray-cos -emit-llvm %s -Oz -o - | FileCheck %s --check-prefixes=OPZ
// RUN: %clang_cc1 -triple kvx-kalray-cos -emit-llvm %s -O3 -o - | FileCheck %s --check-prefixes=OP3


// OPS-LABEL: @matrix_mul_const(
// OPS-NEXT:  entry:
// OPS-NEXT:    [[CMP24_NOT:%.*]] = icmp eq i32 [[N:%.*]], 0
// OPS-NEXT:    br i1 [[CMP24_NOT]], label [[FOR_END12:%.*]], label [[FOR_COND1_PREHEADER_LR_PH:%.*]]
// OPS:       for.cond1.preheader.lr.ph:
// OPS-NEXT:    [[CONV4:%.*]] = sext i16 [[VAL:%.*]] to i32
// OPS-NEXT:    [[TMP0:%.*]] = zext i32 [[N]] to i64
// OPS-NEXT:    [[FLATTEN_TRIPCOUNT:%.*]] = mul nuw i64 [[TMP0]], [[TMP0]]
// OPS-NEXT:    br label [[FOR_COND1_PREHEADER:%.*]]
// OPS:       for.cond1.preheader:
// OPS-NEXT:    [[INDVAR26:%.*]] = phi i64 [ 0, [[FOR_COND1_PREHEADER_LR_PH]] ], [ [[INDVAR_NEXT27:%.*]], [[FOR_COND1_PREHEADER]] ]
// OPS-NEXT:    [[IDXPROM:%.*]] = and i64 [[INDVAR26]], 4294967295
// OPS-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i16, ptr [[A:%.*]], i64 [[IDXPROM]]
// OPS-NEXT:    [[TMP1:%.*]] = load i16, ptr [[ARRAYIDX]], align 2, !tbaa [[TBAA2:![0-9]+]]
// OPS-NEXT:    [[CONV:%.*]] = sext i16 [[TMP1]] to i32
// OPS-NEXT:    [[MUL5:%.*]] = mul nsw i32 [[CONV]], [[CONV4]]
// OPS-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM]]
// OPS-NEXT:    store i32 [[MUL5]], ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA6:![0-9]+]]
// OPS-NEXT:    [[INDVAR_NEXT27]] = add nuw i64 [[INDVAR26]], 1
// OPS-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVAR_NEXT27]], [[FLATTEN_TRIPCOUNT]]
// OPS-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_END12]], label [[FOR_COND1_PREHEADER]], !llvm.loop [[LOOP8:![0-9]+]]
// OPS:       for.end12:
// OPS-NEXT:    ret void
//
// OPZ-LABEL: @matrix_mul_const(
// OPZ-NEXT:  entry:
// OPZ-NEXT:    [[CONV4:%.*]] = sext i16 [[VAL:%.*]] to i32
// OPZ-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[N:%.*]] to i64
// OPZ-NEXT:    br label [[FOR_COND:%.*]]
// OPZ:       for.cond:
// OPZ-NEXT:    [[I_0:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC11:%.*]], [[FOR_INC10:%.*]] ]
// OPZ-NEXT:    [[EXITCOND23_NOT:%.*]] = icmp eq i32 [[I_0]], [[N]]
// OPZ-NEXT:    br i1 [[EXITCOND23_NOT]], label [[FOR_END12:%.*]], label [[FOR_COND1_PREHEADER:%.*]]
// OPZ:       for.cond1.preheader:
// OPZ-NEXT:    [[MUL:%.*]] = mul i32 [[I_0]], [[N]]
// OPZ-NEXT:    br label [[FOR_COND1:%.*]]
// OPZ:       for.cond1:
// OPZ-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_COND1_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY3:%.*]] ]
// OPZ-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV]], [[WIDE_TRIP_COUNT]]
// OPZ-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_INC10]], label [[FOR_BODY3]]
// OPZ:       for.body3:
// OPZ-NEXT:    [[TMP0:%.*]] = trunc i64 [[INDVARS_IV]] to i32
// OPZ-NEXT:    [[ADD:%.*]] = add i32 [[MUL]], [[TMP0]]
// OPZ-NEXT:    [[IDXPROM:%.*]] = zext i32 [[ADD]] to i64
// OPZ-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i16, ptr [[A:%.*]], i64 [[IDXPROM]]
// OPZ-NEXT:    [[TMP1:%.*]] = load i16, ptr [[ARRAYIDX]], align 2, !tbaa [[TBAA2:![0-9]+]]
// OPZ-NEXT:    [[CONV:%.*]] = sext i16 [[TMP1]] to i32
// OPZ-NEXT:    [[MUL5:%.*]] = mul nsw i32 [[CONV]], [[CONV4]]
// OPZ-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM]]
// OPZ-NEXT:    store i32 [[MUL5]], ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA6:![0-9]+]]
// OPZ-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
// OPZ-NEXT:    br label [[FOR_COND1]], !llvm.loop [[LOOP8:![0-9]+]]
// OPZ:       for.inc10:
// OPZ-NEXT:    [[INC11]] = add i32 [[I_0]], 1
// OPZ-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP10:![0-9]+]]
// OPZ:       for.end12:
// OPZ-NEXT:    ret void
//
// OP3-LABEL: @matrix_mul_const(
// OP3-NEXT:  entry:
// OP3-NEXT:    [[CMP24_NOT:%.*]] = icmp eq i32 [[N:%.*]], 0
// OP3-NEXT:    br i1 [[CMP24_NOT]], label [[FOR_END12:%.*]], label [[FOR_COND1_PREHEADER_LR_PH:%.*]]
// OP3:       for.cond1.preheader.lr.ph:
// OP3-NEXT:    [[CONV4:%.*]] = sext i16 [[VAL:%.*]] to i32
// OP3-NEXT:    [[TMP0:%.*]] = zext i32 [[N]] to i64
// OP3-NEXT:    [[FLATTEN_TRIPCOUNT:%.*]] = mul nuw i64 [[TMP0]], [[TMP0]]
// OP3-NEXT:    [[TMP1:%.*]] = add i64 [[FLATTEN_TRIPCOUNT]], -1
// OP3-NEXT:    [[XTRAITER:%.*]] = and i64 [[FLATTEN_TRIPCOUNT]], 5
// OP3-NEXT:    [[TMP2:%.*]] = icmp ult i64 [[TMP1]], 7
// OP3-NEXT:    br i1 [[TMP2]], label [[FOR_END12_LOOPEXIT_UNR_LCSSA:%.*]], label [[FOR_COND1_PREHEADER_LR_PH_NEW:%.*]]
// OP3:       for.cond1.preheader.lr.ph.new:
// OP3-NEXT:    [[UNROLL_ITER:%.*]] = and i64 [[FLATTEN_TRIPCOUNT]], -8
// OP3-NEXT:    br label [[FOR_COND1_PREHEADER:%.*]]
// OP3:       for.cond1.preheader:
// OP3-NEXT:    [[INDVAR26:%.*]] = phi i64 [ 0, [[FOR_COND1_PREHEADER_LR_PH_NEW]] ], [ [[INDVAR_NEXT27_7:%.*]], [[FOR_COND1_PREHEADER]] ]
// OP3-NEXT:    [[NITER:%.*]] = phi i64 [ 0, [[FOR_COND1_PREHEADER_LR_PH_NEW]] ], [ [[NITER_NEXT_7:%.*]], [[FOR_COND1_PREHEADER]] ]
// OP3-NEXT:    [[IDXPROM:%.*]] = and i64 [[INDVAR26]], 4294967288
// OP3-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i16, ptr [[A:%.*]], i64 [[IDXPROM]]
// OP3-NEXT:    [[TMP3:%.*]] = load i16, ptr [[ARRAYIDX]], align 2, !tbaa [[TBAA2:![0-9]+]]
// OP3-NEXT:    [[CONV:%.*]] = sext i16 [[TMP3]] to i32
// OP3-NEXT:    [[MUL5:%.*]] = mul nsw i32 [[CONV]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9:%.*]] = getelementptr inbounds i32, ptr [[C:%.*]], i64 [[IDXPROM]]
// OP3-NEXT:    store i32 [[MUL5]], ptr [[ARRAYIDX9]], align 4, !tbaa [[TBAA6:![0-9]+]]
// OP3-NEXT:    [[INDVAR_NEXT27:%.*]] = and i64 [[INDVAR26]], 4294967288
// OP3-NEXT:    [[IDXPROM_1:%.*]] = or i64 [[INDVAR_NEXT27]], 1
// OP3-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_1]]
// OP3-NEXT:    [[TMP4:%.*]] = load i16, ptr [[ARRAYIDX_1]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_1:%.*]] = sext i16 [[TMP4]] to i32
// OP3-NEXT:    [[MUL5_1:%.*]] = mul nsw i32 [[CONV_1]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_1:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_1]]
// OP3-NEXT:    store i32 [[MUL5_1]], ptr [[ARRAYIDX9_1]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_1:%.*]] = and i64 [[INDVAR26]], 4294967288
// OP3-NEXT:    [[IDXPROM_2:%.*]] = or i64 [[INDVAR_NEXT27_1]], 2
// OP3-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_2]]
// OP3-NEXT:    [[TMP5:%.*]] = load i16, ptr [[ARRAYIDX_2]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_2:%.*]] = sext i16 [[TMP5]] to i32
// OP3-NEXT:    [[MUL5_2:%.*]] = mul nsw i32 [[CONV_2]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_2:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_2]]
// OP3-NEXT:    store i32 [[MUL5_2]], ptr [[ARRAYIDX9_2]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_2:%.*]] = and i64 [[INDVAR26]], 4294967288
// OP3-NEXT:    [[IDXPROM_3:%.*]] = or i64 [[INDVAR_NEXT27_2]], 3
// OP3-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_3]]
// OP3-NEXT:    [[TMP6:%.*]] = load i16, ptr [[ARRAYIDX_3]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_3:%.*]] = sext i16 [[TMP6]] to i32
// OP3-NEXT:    [[MUL5_3:%.*]] = mul nsw i32 [[CONV_3]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_3:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_3]]
// OP3-NEXT:    store i32 [[MUL5_3]], ptr [[ARRAYIDX9_3]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_3:%.*]] = and i64 [[INDVAR26]], 4294967288
// OP3-NEXT:    [[IDXPROM_4:%.*]] = or i64 [[INDVAR_NEXT27_3]], 4
// OP3-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_4]]
// OP3-NEXT:    [[TMP7:%.*]] = load i16, ptr [[ARRAYIDX_4]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_4:%.*]] = sext i16 [[TMP7]] to i32
// OP3-NEXT:    [[MUL5_4:%.*]] = mul nsw i32 [[CONV_4]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_4:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_4]]
// OP3-NEXT:    store i32 [[MUL5_4]], ptr [[ARRAYIDX9_4]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_4:%.*]] = and i64 [[INDVAR26]], 4294967288
// OP3-NEXT:    [[IDXPROM_5:%.*]] = or i64 [[INDVAR_NEXT27_4]], 5
// OP3-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_5]]
// OP3-NEXT:    [[TMP8:%.*]] = load i16, ptr [[ARRAYIDX_5]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_5:%.*]] = sext i16 [[TMP8]] to i32
// OP3-NEXT:    [[MUL5_5:%.*]] = mul nsw i32 [[CONV_5]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_5:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_5]]
// OP3-NEXT:    store i32 [[MUL5_5]], ptr [[ARRAYIDX9_5]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_5:%.*]] = and i64 [[INDVAR26]], 4294967288
// OP3-NEXT:    [[IDXPROM_6:%.*]] = or i64 [[INDVAR_NEXT27_5]], 6
// OP3-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_6]]
// OP3-NEXT:    [[TMP9:%.*]] = load i16, ptr [[ARRAYIDX_6]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_6:%.*]] = sext i16 [[TMP9]] to i32
// OP3-NEXT:    [[MUL5_6:%.*]] = mul nsw i32 [[CONV_6]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_6:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_6]]
// OP3-NEXT:    store i32 [[MUL5_6]], ptr [[ARRAYIDX9_6]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_6:%.*]] = and i64 [[INDVAR26]], 4294967288
// OP3-NEXT:    [[IDXPROM_7:%.*]] = or i64 [[INDVAR_NEXT27_6]], 7
// OP3-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_7]]
// OP3-NEXT:    [[TMP10:%.*]] = load i16, ptr [[ARRAYIDX_7]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_7:%.*]] = sext i16 [[TMP10]] to i32
// OP3-NEXT:    [[MUL5_7:%.*]] = mul nsw i32 [[CONV_7]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_7:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_7]]
// OP3-NEXT:    store i32 [[MUL5_7]], ptr [[ARRAYIDX9_7]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_7]] = add nuw i64 [[INDVAR26]], 8
// OP3-NEXT:    [[NITER_NEXT_7]] = add i64 [[NITER]], 8
// OP3-NEXT:    [[NITER_NCMP_7:%.*]] = icmp eq i64 [[NITER_NEXT_7]], [[UNROLL_ITER]]
// OP3-NEXT:    br i1 [[NITER_NCMP_7]], label [[FOR_END12_LOOPEXIT_UNR_LCSSA]], label [[FOR_COND1_PREHEADER]], !llvm.loop [[LOOP8:![0-9]+]]
// OP3:       for.end12.loopexit.unr-lcssa:
// OP3-NEXT:    [[INDVAR26_UNR:%.*]] = phi i64 [ 0, [[FOR_COND1_PREHEADER_LR_PH]] ], [ [[INDVAR_NEXT27_7]], [[FOR_COND1_PREHEADER]] ]
// OP3-NEXT:    [[LCMP_MOD_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 0
// OP3-NEXT:    br i1 [[LCMP_MOD_NOT]], label [[FOR_END12]], label [[FOR_COND1_PREHEADER_EPIL:%.*]]
// OP3:       for.cond1.preheader.epil:
// OP3-NEXT:    [[IDXPROM_EPIL:%.*]] = and i64 [[INDVAR26_UNR]], 4294967295
// OP3-NEXT:    [[ARRAYIDX_EPIL:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_EPIL]]
// OP3-NEXT:    [[TMP11:%.*]] = load i16, ptr [[ARRAYIDX_EPIL]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_EPIL:%.*]] = sext i16 [[TMP11]] to i32
// OP3-NEXT:    [[MUL5_EPIL:%.*]] = mul nsw i32 [[CONV_EPIL]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_EPIL:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_EPIL]]
// OP3-NEXT:    store i32 [[MUL5_EPIL]], ptr [[ARRAYIDX9_EPIL]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[EPIL_ITER_CMP_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 1
// OP3-NEXT:    br i1 [[EPIL_ITER_CMP_NOT]], label [[FOR_END12]], label [[FOR_COND1_PREHEADER_EPIL_1:%.*]]
// OP3:       for.cond1.preheader.epil.1:
// OP3-NEXT:    [[INDVAR_NEXT27_EPIL:%.*]] = add nuw i64 [[INDVAR26_UNR]], 1
// OP3-NEXT:    [[IDXPROM_EPIL_1:%.*]] = and i64 [[INDVAR_NEXT27_EPIL]], 4294967295
// OP3-NEXT:    [[ARRAYIDX_EPIL_1:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_EPIL_1]]
// OP3-NEXT:    [[TMP12:%.*]] = load i16, ptr [[ARRAYIDX_EPIL_1]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_EPIL_1:%.*]] = sext i16 [[TMP12]] to i32
// OP3-NEXT:    [[MUL5_EPIL_1:%.*]] = mul nsw i32 [[CONV_EPIL_1]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_EPIL_1:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_EPIL_1]]
// OP3-NEXT:    store i32 [[MUL5_EPIL_1]], ptr [[ARRAYIDX9_EPIL_1]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_EPIL_1:%.*]] = add nuw i64 [[INDVAR26_UNR]], 2
// OP3-NEXT:    [[IDXPROM_EPIL_2:%.*]] = and i64 [[INDVAR_NEXT27_EPIL_1]], 4294967295
// OP3-NEXT:    [[ARRAYIDX_EPIL_2:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_EPIL_2]]
// OP3-NEXT:    [[TMP13:%.*]] = load i16, ptr [[ARRAYIDX_EPIL_2]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_EPIL_2:%.*]] = sext i16 [[TMP13]] to i32
// OP3-NEXT:    [[MUL5_EPIL_2:%.*]] = mul nsw i32 [[CONV_EPIL_2]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_EPIL_2:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_EPIL_2]]
// OP3-NEXT:    store i32 [[MUL5_EPIL_2]], ptr [[ARRAYIDX9_EPIL_2]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_EPIL_2:%.*]] = add nuw i64 [[INDVAR26_UNR]], 3
// OP3-NEXT:    [[IDXPROM_EPIL_3:%.*]] = and i64 [[INDVAR_NEXT27_EPIL_2]], 4294967295
// OP3-NEXT:    [[ARRAYIDX_EPIL_3:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_EPIL_3]]
// OP3-NEXT:    [[TMP14:%.*]] = load i16, ptr [[ARRAYIDX_EPIL_3]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_EPIL_3:%.*]] = sext i16 [[TMP14]] to i32
// OP3-NEXT:    [[MUL5_EPIL_3:%.*]] = mul nsw i32 [[CONV_EPIL_3]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_EPIL_3:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_EPIL_3]]
// OP3-NEXT:    store i32 [[MUL5_EPIL_3]], ptr [[ARRAYIDX9_EPIL_3]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[EPIL_ITER_CMP_3_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 4
// OP3-NEXT:    br i1 [[EPIL_ITER_CMP_3_NOT]], label [[FOR_END12]], label [[FOR_COND1_PREHEADER_EPIL_4:%.*]]
// OP3:       for.cond1.preheader.epil.4:
// OP3-NEXT:    [[INDVAR_NEXT27_EPIL_3:%.*]] = add nuw i64 [[INDVAR26_UNR]], 4
// OP3-NEXT:    [[IDXPROM_EPIL_4:%.*]] = and i64 [[INDVAR_NEXT27_EPIL_3]], 4294967295
// OP3-NEXT:    [[ARRAYIDX_EPIL_4:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_EPIL_4]]
// OP3-NEXT:    [[TMP15:%.*]] = load i16, ptr [[ARRAYIDX_EPIL_4]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_EPIL_4:%.*]] = sext i16 [[TMP15]] to i32
// OP3-NEXT:    [[MUL5_EPIL_4:%.*]] = mul nsw i32 [[CONV_EPIL_4]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_EPIL_4:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_EPIL_4]]
// OP3-NEXT:    store i32 [[MUL5_EPIL_4]], ptr [[ARRAYIDX9_EPIL_4]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[EPIL_ITER_CMP_4_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 5
// OP3-NEXT:    br i1 [[EPIL_ITER_CMP_4_NOT]], label [[FOR_END12]], label [[FOR_COND1_PREHEADER_EPIL_5:%.*]]
// OP3:       for.cond1.preheader.epil.5:
// OP3-NEXT:    [[INDVAR_NEXT27_EPIL_4:%.*]] = add nuw i64 [[INDVAR26_UNR]], 5
// OP3-NEXT:    [[IDXPROM_EPIL_5:%.*]] = and i64 [[INDVAR_NEXT27_EPIL_4]], 4294967295
// OP3-NEXT:    [[ARRAYIDX_EPIL_5:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_EPIL_5]]
// OP3-NEXT:    [[TMP16:%.*]] = load i16, ptr [[ARRAYIDX_EPIL_5]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_EPIL_5:%.*]] = sext i16 [[TMP16]] to i32
// OP3-NEXT:    [[MUL5_EPIL_5:%.*]] = mul nsw i32 [[CONV_EPIL_5]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_EPIL_5:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_EPIL_5]]
// OP3-NEXT:    store i32 [[MUL5_EPIL_5]], ptr [[ARRAYIDX9_EPIL_5]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    [[INDVAR_NEXT27_EPIL_5:%.*]] = add nuw i64 [[INDVAR26_UNR]], 6
// OP3-NEXT:    [[IDXPROM_EPIL_6:%.*]] = and i64 [[INDVAR_NEXT27_EPIL_5]], 4294967295
// OP3-NEXT:    [[ARRAYIDX_EPIL_6:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[IDXPROM_EPIL_6]]
// OP3-NEXT:    [[TMP17:%.*]] = load i16, ptr [[ARRAYIDX_EPIL_6]], align 2, !tbaa [[TBAA2]]
// OP3-NEXT:    [[CONV_EPIL_6:%.*]] = sext i16 [[TMP17]] to i32
// OP3-NEXT:    [[MUL5_EPIL_6:%.*]] = mul nsw i32 [[CONV_EPIL_6]], [[CONV4]]
// OP3-NEXT:    [[ARRAYIDX9_EPIL_6:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[IDXPROM_EPIL_6]]
// OP3-NEXT:    store i32 [[MUL5_EPIL_6]], ptr [[ARRAYIDX9_EPIL_6]], align 4, !tbaa [[TBAA6]]
// OP3-NEXT:    br label [[FOR_END12]]
// OP3:       for.end12:
// OP3-NEXT:    ret void
//
void matrix_mul_const(unsigned int N, signed int *C, signed short *A, signed short val)
{
    unsigned int i, j;
    for (i = 0; i < N; i++)
    {
        for (j = 0; j < N; j++)
        {
            C[i * N + j] = (signed int)A[i * N + j] * (signed int)val;
        }
    }
}
