// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: @setcs_asm(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void asm sideeffect "set $$cs = $0", "r,~{$cs}"(i64 [[L:%.*]]) #[[ATTR1:[0-9]+]], !srcloc !2
// CHECK-NEXT:    [[ADD:%.*]] = fadd float [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret float [[ADD]]
//
float setcs_asm(long l, float a, float b) {
  __asm__ volatile("set $cs = %0"
                   :
                   : "r"(l)
                   : "$cs");
  return a + b;
}

// CHECK-LABEL: @setcs_builtin(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.write_register.i64(metadata [[META3:![0-9]+]], i64 [[L:%.*]])
// CHECK-NEXT:    [[ADD:%.*]] = fadd float [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret float [[ADD]]
//
float setcs_builtin(long l, float a, float b) {
  __builtin_kvx_set(/*$cs*/ 4, l);
  return a + b;
}

// CHECK-LABEL: @setcs_asm2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = fmul float [[B:%.*]], [[C:%.*]]
// CHECK-NEXT:    tail call void asm sideeffect "set $$cs = $0", "r,~{$cs}"(i64 [[L:%.*]]) #[[ATTR1]], !srcloc !4
// CHECK-NEXT:    [[ADD:%.*]] = fadd float [[MUL]], [[A:%.*]]
// CHECK-NEXT:    ret float [[ADD]]
//
float setcs_asm2(long l, float a, float b, float c) {
  float d = c * b;
  __asm__ volatile("set $cs = %0"
                   :
                   : "r"(l)
                   : "$cs");
  return a + d;
}

// CHECK-LABEL: @setcs_builtin2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = fmul float [[B:%.*]], [[C:%.*]]
// CHECK-NEXT:    tail call void @llvm.write_register.i64(metadata [[META3]], i64 [[L:%.*]])
// CHECK-NEXT:    [[ADD:%.*]] = fadd float [[MUL]], [[A:%.*]]
// CHECK-NEXT:    ret float [[ADD]]
//
float setcs_builtin2(long l, float a, float b, float c) {
  float d = c * b;
  __builtin_kvx_set(/*$cs*/ 4, l);
  return a + d;
}
