; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: clang -c -o /dev/null %s
; RUN: clang -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

; This test is a minimal reproducer for T14394, it covers SELECT_CC operation for v4f32 type.

; Original C code is:
;
; typedef float v4f32 __attribute__((vector_size(4 * sizeof(float))));
;
; v4f32 select_cc(int a, v4f32 v1, v4f32 v2) {
;   return a > 0 ? v1 : v2;
; }

define <4 x float> @select_cc(i32 %0, <4 x float> %1, <4 x float> %2) {
; CHECK-LABEL: select_cc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r2
; CHECK-NEXT:    copyd $r4 = $r3
; CHECK-NEXT:    copyd $r5 = $r4
; CHECK-NEXT:    ;; # (end cycle 0)
; CHECK-NEXT:    compw.gt $r0 = $r0, 0
; CHECK-NEXT:    ;; # (end cycle 1)
; CHECK-NEXT:    cmoved.even $r0 ? $r2 = $r4
; CHECK-NEXT:    cmoved.even $r0 ? $r3 = $r5
; CHECK-NEXT:    ;; # (end cycle 2)
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;; # (end cycle 3)
  %4 = icmp sgt i32 %0, 0
  %5 = select i1 %4, <4 x float> %1, <4 x float> %2
  ret <4 x float> %5
}
