; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=kvx -exception-model sjlj | FileCheck --check-prefixes=CHECK %s
; RUN: llc < %s -mtriple=kvx -relocation-model=pic -exception-model sjlj | FileCheck --check-prefixes=PIC %s

%struct.__jmp_buf_tag = type { [25 x i64], i64, [16 x i64] }

@buf = common global [1 x %struct.__jmp_buf_tag] zeroinitializer, align 8

define i32 @f_setjmp() {
; CHECK-LABEL: f_setjmp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r0 = buf
; CHECK-NEXT:    make $r1 = .LBB0_3
; CHECK-NEXT:    addd $r12 = $r12, -128
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 120[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 112[$r12] = $r14
; CHECK-NEXT:    ;;
; CHECK-NEXT:    so 80[$r12] = $r28r29r30r31
; CHECK-NEXT:    ;;
; CHECK-NEXT:    so 48[$r12] = $r24r25r26r27
; CHECK-NEXT:    ;;
; CHECK-NEXT:    so 16[$r12] = $r20r21r22r23
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 8[$r0] = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    goto .LBB0_2
; CHECK-NEXT:    ;;
; CHECK-NEXT:  .LBB0_3: # Block address taken
; CHECK-NEXT:    make $r0 = 1
; CHECK-NEXT:    ;;
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r20r21r22r23 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r24r25r26r27 = 48[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r28r29r30r31 = 80[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r14 = 112[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 120[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 128
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
;
; PIC-LABEL: f_setjmp:
; PIC:       # %bb.0:
; PIC-NEXT:    pcrel $r1 = @pcrel( .LBB0_3 )
; PIC-NEXT:    addd $r12 = $r12, -128
; PIC-NEXT:    get $r16 = $ra
; PIC-NEXT:    ;;
; PIC-NEXT:    sd 120[$r12] = $r16
; PIC-NEXT:    ;;
; PIC-NEXT:    sd 112[$r12] = $r14
; PIC-NEXT:    ;;
; PIC-NEXT:    so 80[$r12] = $r28r29r30r31
; PIC-NEXT:    ;;
; PIC-NEXT:    so 48[$r12] = $r24r25r26r27
; PIC-NEXT:    ;;
; PIC-NEXT:    so 16[$r12] = $r20r21r22r23
; PIC-NEXT:    ;;
; PIC-NEXT:    sq 0[$r12] = $r18r19
; PIC-NEXT:    pcrel $r0 = @gotaddr()
; PIC-NEXT:    ;;
; PIC-NEXT:    ld $r0 = @got( buf )[$r0]
; PIC-NEXT:    ;;
; PIC-NEXT:    sd 8[$r0] = $r1
; PIC-NEXT:    ;;
; PIC-NEXT:  # %bb.1:
; PIC-NEXT:    make $r0 = 0
; PIC-NEXT:    goto .LBB0_2
; PIC-NEXT:    ;;
; PIC-NEXT:  .LBB0_3: # Block address taken
; PIC-NEXT:    make $r0 = 1
; PIC-NEXT:    ;;
; PIC-NEXT:  .LBB0_2:
; PIC-NEXT:    lq $r18r19 = 0[$r12]
; PIC-NEXT:    ;;
; PIC-NEXT:    lo $r20r21r22r23 = 16[$r12]
; PIC-NEXT:    ;;
; PIC-NEXT:    lo $r24r25r26r27 = 48[$r12]
; PIC-NEXT:    ;;
; PIC-NEXT:    lo $r28r29r30r31 = 80[$r12]
; PIC-NEXT:    ;;
; PIC-NEXT:    ld $r14 = 112[$r12]
; PIC-NEXT:    ;;
; PIC-NEXT:    ld $r16 = 120[$r12]
; PIC-NEXT:    ;;
; PIC-NEXT:    set $ra = $r16
; PIC-NEXT:    addd $r12 = $r12, 128
; PIC-NEXT:    ;;
; PIC-NEXT:    ret
; PIC-NEXT:    ;;



   %1 = call i32 @llvm.eh.sjlj.setjmp(i8* bitcast ([1 x %struct.__jmp_buf_tag]* @buf to i8*))
   ret i32 %1
}

declare i32 @llvm.eh.sjlj.setjmp(i8*) nounwind
