; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -O2 | FileCheck %s
target triple = "kvx-kalray-cos"

define <8 x i8> @xor(<8 x i8> %a, <8 x i8> %b){
; CHECK-LABEL: xor:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xord $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %xor = xor <8 x i8> %b, %a
  ret <8 x i8> %xor
}

define <8 x i8> @xor_imm(<8 x i8> %a){
; CHECK-LABEL: xor_imm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r1 = 0x303030303030303
; CHECK-NEXT:    ;;
; CHECK-NEXT:    xord $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %xor = xor <8 x i8> %a, <i8 3, i8 3, i8 3, i8 3, i8 3, i8 3, i8 3, i8 3>
  ret <8 x i8> %xor
}

define <8 x i8> @or(<8 x i8> %a, <8 x i8> %b){
; CHECK-LABEL: or:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ord $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %or = or <8 x i8> %b, %a
  ret <8 x i8> %or
}

define <8 x i8> @or_imm(<8 x i8> %a){
; CHECK-LABEL: or_imm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r1 = 0xf0f0f0f0f0f0f0f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ord $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %or = or <8 x i8> %a, <i8 15, i8 15, i8 15, i8 15, i8 15, i8 15, i8 15, i8 15>
  ret <8 x i8> %or
}

define <8 x i8> @and(<8 x i8> %a, <8 x i8> %b){
; CHECK-LABEL: and:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andd $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %and = and <8 x i8> %b, %a
  ret <8 x i8> %and
}

define <8 x i8> @and_imm(<8 x i8> %a){
; CHECK-LABEL: and_imm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r1 = 0x7f7f7f7f7f7f7f7f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %and = and <8 x i8> %a, <i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127, i8 127>
  ret <8 x i8> %and
}

