// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: clang -cc1 -triple kvx-kalray-cos -emit-llvm %s -O2 -o - | FileCheck %s

// CHECK-LABEL: @lbz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = addrspacecast i8* [[P:%.*]] to i8 addrspace(256)*
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, i8 addrspace(256)* [[TMP0]], align 1
// CHECK-NEXT:    ret i8 [[TMP1]]
//
unsigned char lbz(void *p) {
  return __builtin_kvx_lbz(p, ".u", 0);
}

// CHECK-LABEL: @lbs_volatile(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = addrspacecast i8* [[P:%.*]] to i8 addrspace(257)*
// CHECK-NEXT:    [[TMP1:%.*]] = load volatile i8, i8 addrspace(257)* [[TMP0]], align 1
// CHECK-NEXT:    [[CONV:%.*]] = sext i8 [[TMP1]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int lbs_volatile(void *p) {
  return __builtin_kvx_lbs(p, ".us", 1);
}

// CHECK-LABEL: @lhz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to i16*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast i16* [[TMP0]] to i16 addrspace(256)*
// CHECK-NEXT:    [[TMP2:%.*]] = load i16, i16 addrspace(256)* [[TMP1]], align 2
// CHECK-NEXT:    ret i16 [[TMP2]]
//
unsigned short lhz(void *p) {
  return __builtin_kvx_lhz(p, ".u", 0);
}

// CHECK-LABEL: @lhs_volatile(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to i16*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast i16* [[TMP0]] to i16 addrspace(257)*
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile i16, i16 addrspace(257)* [[TMP1]], align 2
// CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP2]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int lhs_volatile(void *p) {
  return __builtin_kvx_lhs(p, ".us", 1);
}

// CHECK-LABEL: @lwz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to i32*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast i32* [[TMP0]] to i32 addrspace(256)*
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, i32 addrspace(256)* [[TMP1]], align 4
// CHECK-NEXT:    ret i32 [[TMP2]]
//
unsigned int lwz(void *p) {
  return __builtin_kvx_lwz(p, ".u", 0);
}

// CHECK-LABEL: @lws_volatile(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to i32*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast i32* [[TMP0]] to i32 addrspace(257)*
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile i32, i32 addrspace(257)* [[TMP1]], align 4
// CHECK-NEXT:    ret i32 [[TMP2]]
//
int lws_volatile(void *p) {
  return __builtin_kvx_lws(p, ".us", 1);
}

// CHECK-LABEL: @lwf(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to float*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast float* [[TMP0]] to float addrspace(258)*
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile float, float addrspace(258)* [[TMP1]], align 4
// CHECK-NEXT:    ret float [[TMP2]]
//
float lwf(void *p) {
  return __builtin_kvx_lwf(p, ".s", 1);
}

// CHECK-LABEL: @ld(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to i64*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast i64* [[TMP0]] to i64 addrspace(258)*
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile i64, i64 addrspace(258)* [[TMP1]], align 8
// CHECK-NEXT:    ret i64 [[TMP2]]
//
long ld(void *p) {
  return __builtin_kvx_ld(p, ".s", 1);
}

// CHECK-LABEL: @ldf(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to double*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast double* [[TMP0]] to double addrspace(258)*
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile double, double addrspace(258)* [[TMP1]], align 8
// CHECK-NEXT:    ret double [[TMP2]]
//
double ldf(void *p) {
  return __builtin_kvx_ldf(p, ".s", 1);
}

typedef char int8x8_t __attribute__((__vector_size__(8 * sizeof(char))));

// CHECK-LABEL: @ldbo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to <8 x i8>*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast <8 x i8>* [[TMP0]] to <8 x i8> addrspace(258)*
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile <8 x i8>, <8 x i8> addrspace(258)* [[TMP1]], align 8
// CHECK-NEXT:    ret <8 x i8> [[TMP2]]
//
int8x8_t ldbo(void *p) {
  return __builtin_kvx_ldbo(p, ".s", 1);
}

typedef short int16x4_t __attribute__((__vector_size__(4 * sizeof(short))));

// CHECK-LABEL: @ldhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to <4 x i16>*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast <4 x i16>* [[TMP0]] to <4 x i16> addrspace(258)*
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile <4 x i16>, <4 x i16> addrspace(258)* [[TMP1]], align 8
// CHECK-NEXT:    ret <4 x i16> [[TMP2]]
//
int16x4_t ldhq(void *p) {
  return __builtin_kvx_ldhq(p, ".s", 1);
}

typedef int int32x2_t __attribute__((__vector_size__(2 * sizeof(int))));

// CHECK-LABEL: @ldwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to <2 x i32>*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast <2 x i32>* [[TMP0]] to <2 x i32> addrspace(258)*
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile <2 x i32>, <2 x i32> addrspace(258)* [[TMP1]], align 8
// CHECK-NEXT:    ret <2 x i32> [[TMP2]]
//
int32x2_t ldwp(void *p) {
  return __builtin_kvx_ldwp(p, ".s", 1);
}

typedef float float32x2_t __attribute__((__vector_size__(2 * sizeof(float))));

// CHECK-LABEL: @ldfwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to <2 x float>*
// CHECK-NEXT:    [[TMP1:%.*]] = addrspacecast <2 x float>* [[TMP0]] to <2 x float> addrspace(258)*
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile <2 x float>, <2 x float> addrspace(258)* [[TMP1]], align 8
// CHECK-NEXT:    ret <2 x float> [[TMP2]]
//
float32x2_t ldfwp(void *p) {
  return __builtin_kvx_ldfwp(p, ".s", 1);
}

// CHECK-LABEL: @sdbo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to <8 x i8>*
// CHECK-NEXT:    store volatile <8 x i8> [[V:%.*]], <8 x i8>* [[TMP0]], align 8
// CHECK-NEXT:    ret void
//
void sdbo(void *p, int8x8_t v) {
  __builtin_kvx_sdbo(p, v, 1);
}

// CHECK-LABEL: @sdhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to <4 x i16>*
// CHECK-NEXT:    store volatile <4 x i16> [[V:%.*]], <4 x i16>* [[TMP0]], align 8
// CHECK-NEXT:    ret void
//
void sdhq(void *p, int16x4_t v) {
  __builtin_kvx_sdhq(p, v, 1);
}

// CHECK-LABEL: @sdwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to <2 x i32>*
// CHECK-NEXT:    store volatile <2 x i32> [[V:%.*]], <2 x i32>* [[TMP0]], align 8
// CHECK-NEXT:    ret void
//
void sdwp(void *p, int32x2_t v) {
  __builtin_kvx_sdwp(p, v, 1);
}

// CHECK-LABEL: @sdfwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = bitcast i8* [[P:%.*]] to <2 x float>*
// CHECK-NEXT:    store volatile <2 x float> [[V:%.*]], <2 x float>* [[TMP0]], align 8
// CHECK-NEXT:    ret void
//
void sdfwp(void *p, float32x2_t v) {
  __builtin_kvx_sdfwp(p, v, 1);
}
