; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -o - %s | FileCheck %s
; RUN: llc -mcpu=kv3-2 -O2 -o - %s | FileCheck %s --check-prefix=V2
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define float @ffdmdaw(<2 x float> %a, <2 x float> %b, float %c) {
; CHECK-LABEL: ffdmdaw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fdot2w $r0 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    faddw $r0 = $r0, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
;
; V2-LABEL: ffdmdaw:
; V2:       # %bb.0: # %entry
; V2-NEXT:    ffdmdaw $r2 = $r0, $r1
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r0 = $r2
; V2-NEXT:    ret
; V2-NEXT:    ;;
entry:
  %0 = tail call float @llvm.kvx.ffdmdaw(<2 x float> %a, <2 x float> %b, float %c, i32 7, i32 0)
  ret float %0
}

declare float @llvm.kvx.ffdmdaw(<2 x float>, <2 x float>, float, i32, i32) #1

define <2 x float> @ffdmdawp(<4 x float> %a, <4 x float> %b, <2 x float> %c) {
; CHECK-LABEL: ffdmdawp:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ffmawp $r4 = $r0, $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ffmawp $r4 = $r1, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r4
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
;
; V2-LABEL: ffdmdawp:
; V2:       # %bb.0: # %entry
; V2-NEXT:    ffdmdawp $r4 = $r0r1, $r2r3
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r0 = $r4
; V2-NEXT:    ret
; V2-NEXT:    ;;
entry:
  %0 = tail call <2 x float> @llvm.kvx.ffdmdawp(<4 x float> %a, <4 x float> %b, <2 x float> %c, i32 7, i32 0)
  ret <2 x float> %0
}

declare <2 x float> @llvm.kvx.ffdmdawp(<4 x float>, <4 x float>, <2 x float>, i32, i32) #1

define <4 x float> @ffdmdawq(<8 x float> %a, <8 x float> %b, <4 x float> %c) {
; CHECK-LABEL: ffdmdawq:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r5 = $r2
; CHECK-NEXT:    copyd $r6 = $r5
; CHECK-NEXT:    copyd $r11 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ffmawp $r8 = $r0, $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ffmawp $r9 = $r2, $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ffmawp $r8 = $r5, $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ffmawp $r9 = $r3, $r7
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r1 = $r9
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
;
; V2-LABEL: ffdmdawq:
; V2:       # %bb.0: # %entry
; V2-NEXT:    copyd $r5 = $r2
; V2-NEXT:    copyd $r6 = $r5
; V2-NEXT:    copyd $r10 = $r4
; V2-NEXT:    copyd $r11 = $r6
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r2 = $r1
; V2-NEXT:    copyd $r4 = $r0
; V2-NEXT:    ;;
; V2-NEXT:    ffdmdawp $r8 = $r4r5, $r10r11
; V2-NEXT:    ;;
; V2-NEXT:    ffdmdawp $r9 = $r2r3, $r6r7
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r0 = $r8
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r1 = $r9
; V2-NEXT:    ret
; V2-NEXT:    ;;
entry:
  %0 = shufflevector <4 x float> %c, <4 x float> undef, <2 x i32> <i32 0, i32 1>
  %1 = shufflevector <8 x float> %a, <8 x float> undef, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %2 = shufflevector <8 x float> %b, <8 x float> undef, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %3 = shufflevector <4 x float> %c, <4 x float> undef, <2 x i32> <i32 2, i32 3>
  %4 = shufflevector <8 x float> %a, <8 x float> undef, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  %5 = shufflevector <8 x float> %b, <8 x float> undef, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  %6 = tail call <2 x float> @llvm.kvx.ffdmdawp(<4 x float> %1, <4 x float> %2, <2 x float> %0, i32 7, i32 0)
  %7 = tail call <2 x float> @llvm.kvx.ffdmdawp(<4 x float> %4, <4 x float> %5, <2 x float> %3, i32 7, i32 0)
  %8 = shufflevector <2 x float> %6, <2 x float> %7, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x float> %8
}

define <4 x float> @ffdmdawq_rn_s(<8 x float> %a, <8 x float> %b, <4 x float> %c) {
; CHECK-LABEL: ffdmdawq_rn_s:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r5 = $r2
; CHECK-NEXT:    copyd $r6 = $r5
; CHECK-NEXT:    copyd $r11 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ffmawp.rn.s $r8 = $r0, $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ffmawp.rn.s $r9 = $r2, $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ffmawp.rn.s $r8 = $r5, $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ffmawp.rn.s $r9 = $r3, $r7
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r1 = $r9
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
;
; V2-LABEL: ffdmdawq_rn_s:
; V2:       # %bb.0: # %entry
; V2-NEXT:    copyd $r5 = $r2
; V2-NEXT:    copyd $r6 = $r5
; V2-NEXT:    copyd $r10 = $r4
; V2-NEXT:    copyd $r11 = $r6
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r2 = $r1
; V2-NEXT:    copyd $r4 = $r0
; V2-NEXT:    ;;
; V2-NEXT:    ffdmdawp.rn.s $r8 = $r4r5, $r10r11
; V2-NEXT:    ;;
; V2-NEXT:    ffdmdawp.rn.s $r9 = $r2r3, $r6r7
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r0 = $r8
; V2-NEXT:    ;;
; V2-NEXT:    copyd $r1 = $r9
; V2-NEXT:    ret
; V2-NEXT:    ;;
entry:
  %0 = shufflevector <4 x float> %c, <4 x float> undef, <2 x i32> <i32 0, i32 1>
  %1 = shufflevector <8 x float> %a, <8 x float> undef, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %2 = shufflevector <8 x float> %b, <8 x float> undef, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %3 = shufflevector <4 x float> %c, <4 x float> undef, <2 x i32> <i32 2, i32 3>
  %4 = shufflevector <8 x float> %a, <8 x float> undef, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  %5 = shufflevector <8 x float> %b, <8 x float> undef, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
  %6 = tail call <2 x float> @llvm.kvx.ffdmdawp(<4 x float> %1, <4 x float> %2, <2 x float> %0, i32 0, i32 1)
  %7 = tail call <2 x float> @llvm.kvx.ffdmdawp(<4 x float> %4, <4 x float> %5, <2 x float> %3, i32 0, i32 1)
  %8 = shufflevector <2 x float> %6, <2 x float> %7, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x float> %8
}
