; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK,CV2
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <8 x i8> @selectbo(<8 x i8> %0, <8 x i8> %1, <8 x i8> %2) {
; CHECK-LABEL: selectbo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmovebo.even $r2 ? $r1 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = tail call <8 x i8> @llvm.kvx.select.vec.v8i8(<8 x i8> %0, <8 x i8> %1, <8 x i8> %2, i32 7)
  ret <8 x i8> %4
}

declare <8 x i8> @llvm.kvx.select.vec.v8i8(<8 x i8>, <8 x i8>, <8 x i8>, i32)

define double @selectfd(double %0, double %1, i64 %2) {
; CHECK-LABEL: selectfd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmoved.wgtz $r2 ? $r0 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = tail call double @llvm.kvx.select.f64(double %1, double %0, i64 %2, i32 13)
  ret double %4
}

declare double @llvm.kvx.select.f64(double, double, i64, i32)

define <32 x i8> @selectbv(<32 x i8> %0, <32 x i8> %1, <32 x i8> %2) {
; CHECK-LABEL: selectbv:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmovebo.eqz $r8 ? $r4 = $r0
; CHECK-NEXT:    cmovebo.eqz $r9 ? $r5 = $r1
; CHECK-NEXT:    cmovebo.eqz $r10 ? $r6 = $r2
; CHECK-NEXT:    cmovebo.eqz $r11 ? $r7 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r4
; CHECK-NEXT:    copyd $r1 = $r5
; CHECK-NEXT:    copyd $r2 = $r6
; CHECK-NEXT:    copyd $r3 = $r7
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = shufflevector <32 x i8> %0, <32 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %5 = shufflevector <32 x i8> %1, <32 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %6 = shufflevector <32 x i8> %2, <32 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %7 = tail call <8 x i8> @llvm.kvx.select.vec.v8i8(<8 x i8> %4, <8 x i8> %5, <8 x i8> %6, i32 1)
  %8 = shufflevector <32 x i8> %0, <32 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %9 = shufflevector <32 x i8> %1, <32 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %10 = shufflevector <32 x i8> %2, <32 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %11 = tail call <8 x i8> @llvm.kvx.select.vec.v8i8(<8 x i8> %8, <8 x i8> %9, <8 x i8> %10, i32 1)
  %12 = shufflevector <32 x i8> %0, <32 x i8> undef, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  %13 = shufflevector <32 x i8> %1, <32 x i8> undef, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  %14 = shufflevector <32 x i8> %2, <32 x i8> undef, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
  %15 = tail call <8 x i8> @llvm.kvx.select.vec.v8i8(<8 x i8> %12, <8 x i8> %13, <8 x i8> %14, i32 1)
  %16 = shufflevector <32 x i8> %0, <32 x i8> undef, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %17 = shufflevector <32 x i8> %1, <32 x i8> undef, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %18 = shufflevector <32 x i8> %2, <32 x i8> undef, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %19 = tail call <8 x i8> @llvm.kvx.select.vec.v8i8(<8 x i8> %16, <8 x i8> %17, <8 x i8> %18, i32 1)
  %20 = shufflevector <8 x i8> %7, <8 x i8> %11, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %21 = shufflevector <8 x i8> %15, <8 x i8> %19, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %22 = shufflevector <16 x i8> %20, <16 x i8> %21, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  ret <32 x i8> %22
}

define <16 x i8> @selectbx(<16 x i8> %0, <16 x i8> %1, <16 x i8> %2) {
; CHECK-LABEL: selectbx:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmovebo.gez $r4 ? $r2 = $r0
; CHECK-NEXT:    cmovebo.gez $r5 ? $r3 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = shufflevector <16 x i8> %0, <16 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %5 = shufflevector <16 x i8> %1, <16 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %6 = shufflevector <16 x i8> %2, <16 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %7 = tail call <8 x i8> @llvm.kvx.select.vec.v8i8(<8 x i8> %4, <8 x i8> %5, <8 x i8> %6, i32 3)
  %8 = shufflevector <16 x i8> %0, <16 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %9 = shufflevector <16 x i8> %1, <16 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %10 = shufflevector <16 x i8> %2, <16 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %11 = tail call <8 x i8> @llvm.kvx.select.vec.v8i8(<8 x i8> %8, <8 x i8> %9, <8 x i8> %10, i32 3)
  %12 = shufflevector <8 x i8> %7, <8 x i8> %11, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  ret <16 x i8> %12
}

