; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -relocation-model=pic < %s -mtriple=kvx-kalray-cos | FileCheck %s

; reduced testcase from T13087

declare i64 @get_x()
declare i64 @get_y()
declare i64 @get_z()

define i64 @foo(double*, double*, double*, { i32, [3 x i64], [3 x i64], [3 x i64], i8*, i32*, i32 }*, i64, i64, i64) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r20 = 56[$r3]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r21 = 32[$r3]
; CHECK-NEXT:    call get_x
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    call get_y
; CHECK-NEXT:    ;;
; CHECK-NEXT:    call get_z
; CHECK-NEXT:    ;;
; CHECK-NEXT:    maddd $r21 = $r20, $r18
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    addd $r0 = $r21, $r19
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %8 = getelementptr { i32, [3 x i64], [3 x i64], [3 x i64], i8*, i32*, i32 }, { i32, [3 x i64], [3 x i64], [3 x i64], i8*, i32*, i32 }* %3, i64 0, i32 3, i64 0
  %9 = load i64, i64* %8, align 8
  %10 = getelementptr { i32, [3 x i64], [3 x i64], [3 x i64], i8*, i32*, i32 }, { i32, [3 x i64], [3 x i64], [3 x i64], i8*, i32*, i32 }* %3, i64 0, i32 2, i64 0
  %11 = load i64, i64* %10, align 8
  %12 = tail call i64 @get_x()
  %13 = tail call i64 @get_y()
  %14 = tail call i64 @get_z()
  %15 = mul i64 %9, %4
  %16 = add i64 %15, %11
  %17 = add i64 %16, %12
  ret i64 %17
}
