; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -o - %s | FileCheck %s
target triple = "kvx-kalray-cos"

define i32 @CLRF_bottom_int(i32 %0) {
; CHECK-LABEL: CLRF_bottom_int:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andw $r0 = $r0, 0xfffff000
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = and i32 %0, -4096
  ret i32 %2
}

define i32 @CLRF_top_int(i32 %0) {
; CHECK-LABEL: CLRF_top_int:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andw $r0 = $r0, 0xfffff
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = and i32 %0, 1048575
  ret i32 %2
}

define i32 @CLRF_center_int(i32 %0) {
; CHECK-LABEL: CLRF_center_int:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andw $r0 = $r0, 0xf000000f
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = and i32 %0, -268435441
  ret i32 %2
}

define i32 @CLRF_sides_int(i32 %0) {
; CHECK-LABEL: CLRF_sides_int:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andw $r0 = $r0, 0x200000
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = and i32 %0, 2097152
  ret i32 %2
}

define i64 @CLRF_bottom_long(i64 %0) {
; CHECK-LABEL: CLRF_bottom_long:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andd $r0 = $r0, 0xfffffff000000000
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = and i64 %0, -68719476736
  ret i64 %2
}

define i64 @CLRF_top_long(i64 %0) {
; CHECK-LABEL: CLRF_top_long:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andd $r0 = $r0, 0xffffffffff
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = and i64 %0, 1099511627775
  ret i64 %2
}

define i64 @CLRF_center_long(i64 %0) {
; CHECK-LABEL: CLRF_center_long:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andd $r0 = $r0, 0xffff00000000ffff
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = and i64 %0, -281474976645121
  ret i64 %2
}

define i64 @CLRF_sides_long(i64 %0) {
; CHECK-LABEL: CLRF_sides_long:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andd $r0 = $r0, 0xfffffffe
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %2 = and i64 %0, 4294967294
  ret i64 %2
}
