; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -O2 -o - %s | FileCheck %s --check-prefixes=CV1
; RUN: clang -O2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define void @test_lvc(<1024 x i1>* nocapture readonly %0, i8* %1, <1024 x i1>* nocapture %2, <1024 x i1>* nocapture readnone %3) {
; CV1-LABEL: test_lvc:
; CV1:       # %bb.0:
; CV1-NEXT:    xlo.u $a3 = 96[$r0]
; CV1-NEXT:    ;; # (end cycle 0)
; CV1-NEXT:    xlo.u $a2 = 64[$r0]
; CV1-NEXT:    ;; # (end cycle 1)
; CV1-NEXT:    xlo.u $a1 = 32[$r0]
; CV1-NEXT:    ;; # (end cycle 2)
; CV1-NEXT:    xlo.u $a0 = 0[$r0]
; CV1-NEXT:    ;; # (end cycle 3)
; CV1-NEXT:    xlo.u.q1 $a0a1a2a3 = 0[$r1]
; CV1-NEXT:    ;; # (end cycle 6)
; CV1-NEXT:    xso 32[$r2] = $a1
; CV1-NEXT:    ;; # (end cycle 9)
; CV1-NEXT:    xso 0[$r2] = $a0
; CV1-NEXT:    ;; # (end cycle 10)
; CV1-NEXT:    xso 96[$r2] = $a3
; CV1-NEXT:    ;; # (end cycle 11)
; CV1-NEXT:    xso 64[$r2] = $a2
; CV1-NEXT:    ret
; CV1-NEXT:    ;; # (end cycle 12)
  %5 = load <1024 x i1>, <1024 x i1>* %0, align 32
  %6 = tail call <1024 x i1> @llvm.kvx.lvc(<1024 x i1> %5, i8* %1, i32 2, i32 1)
  %7 = load <1024 x i1>, <1024 x i1>* %0, align 32
  %8 = tail call <1024 x i1> @llvm.kvx.lvc(<1024 x i1> %7, i8* %1, i32 2, i32 1)
  store <1024 x i1> %6, <1024 x i1>* %2, align 32
  store <1024 x i1> %8, <1024 x i1>* %2, align 32
  ret void
}

declare <1024 x i1> @llvm.kvx.lvc(<1024 x i1>, i8*, i32, i32)

