; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O3 --post-RA-scheduler=false -o - %s | FileCheck %s --check-prefixes=NORMAL
; RUN: llc -O3 --post-RA-scheduler=false --pre-RA-sched=vliw-td -o - %s | FileCheck %s --check-prefixes=VLIW
target triple = "kvx-kalray-cos"

define void @foo(i8* nocapture %0, float* nocapture %1) {
; NORMAL-LABEL: foo:
; NORMAL:       # %bb.0:
; NORMAL-NEXT:    lv $a3 = 96[$r0]
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    lv $a2 = 64[$r0]
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    lv $a1 = 32[$r0]
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    lv $a0 = 0[$r0]
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    lwz $r2 = 0[$r1]
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    faddw $r2 = $r2, 0x42280000
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    sw 0[$r1] = $r2
; NORMAL-NEXT:    make $r1 = 0x10000000000000
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    #APP
; NORMAL-NEXT:    wfxm $pcr, $r1
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    #NO_APP
; NORMAL-NEXT:    make $r1 = 0x100000
; NORMAL-NEXT:    mt44d $a0a1a2a3 = $a0a1a2a3
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    #APP
; NORMAL-NEXT:    wfxm $pcr, $r1
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    #NO_APP
; NORMAL-NEXT:    sv 96[$r0] = $a3
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    sv 64[$r0] = $a2
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    sv 32[$r0] = $a1
; NORMAL-NEXT:    ;;
; NORMAL-NEXT:    sv 0[$r0] = $a0
; NORMAL-NEXT:    ret
; NORMAL-NEXT:    ;;
;
; VLIW-LABEL: foo:
; VLIW:       # %bb.0:
; VLIW-NEXT:    lwz $r2 = 0[$r1]
; VLIW-NEXT:    make $r3 = 0x10000000000000
; VLIW-NEXT:    ;;
; VLIW-NEXT:    lv $a3 = 96[$r0]
; VLIW-NEXT:    ;;
; VLIW-NEXT:    lv $a2 = 64[$r0]
; VLIW-NEXT:    faddw $r2 = $r2, 0x42280000
; VLIW-NEXT:    ;;
; VLIW-NEXT:    lv $a1 = 32[$r0]
; VLIW-NEXT:    ;;
; VLIW-NEXT:    lv $a0 = 0[$r0]
; VLIW-NEXT:    ;;
; VLIW-NEXT:    sw 0[$r1] = $r2
; VLIW-NEXT:    make $r1 = 0x100000
; VLIW-NEXT:    ;;
; VLIW-NEXT:    #APP
; VLIW-NEXT:    wfxm $pcr, $r3
; VLIW-NEXT:    ;;
; VLIW-NEXT:    #NO_APP
; VLIW-NEXT:    mt44d $a0a1a2a3 = $a0a1a2a3
; VLIW-NEXT:    ;;
; VLIW-NEXT:    #APP
; VLIW-NEXT:    wfxm $pcr, $r1
; VLIW-NEXT:    ;;
; VLIW-NEXT:    #NO_APP
; VLIW-NEXT:    sv 96[$r0] = $a3
; VLIW-NEXT:    ;;
; VLIW-NEXT:    sv 0[$r0] = $a0
; VLIW-NEXT:    ;;
; VLIW-NEXT:    sv 64[$r0] = $a2
; VLIW-NEXT:    ;;
; VLIW-NEXT:    sv 32[$r0] = $a1
; VLIW-NEXT:    ret
; VLIW-NEXT:    ;;
%3 = bitcast i8* %0 to <1024 x i1>*
%4 = load <1024 x i1>, <1024 x i1>* %3, align 32
%5 = load float, float* %1, align 4
%6 = fadd float %5, 4.200000e+01
store float %6, float* %1, align 4
tail call void asm sideeffect "wfxm $$pcr, $0", "r,~{$pcr}"(i64 4503599627370496)
%7 = tail call <1024 x i1> @llvm.kvx.xmt44d(<1024 x i1> %4)
tail call void asm sideeffect "wfxm $$pcr, $0", "r,~{$pcr}"(i64 1048576)
store <1024 x i1> %7, <1024 x i1>* %3, align 32
ret void
}

declare <1024 x i1> @llvm.kvx.xmt44d(<1024 x i1>)
