; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=kvx-kalray-cos | FileCheck %s

define float @truncf32(float %x) {
; CHECK-LABEL: truncf32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %tmp = call float @llvm.trunc.f32(float %x)
  ret float %tmp
}

define double @truncf64(double %x) {
; CHECK-LABEL: truncf64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    call trunc
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %tmp = call double @llvm.trunc.f64(double %x)
  ret double %tmp
}

define <2 x float> @truncv2f32(<2 x float> %x) {
; CHECK-LABEL: truncv2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 8[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srad $r0 = $r18, 32
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 8[$r12]
; CHECK-NEXT:    insf $r0 = $r19, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %tmp = call <2 x float> @llvm.trunc.v2f32(<2 x float> %x)
  ret <2 x float> %tmp
}

define <2 x double> @truncv2f64(<2 x double> %x) {
; CHECK-LABEL: truncv2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 8[$r12] = $r18
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    call trunc
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r18
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call trunc
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r20
; CHECK-NEXT:    copyd $r1 = $r0
; CHECK-NEXT:    ld $r18 = 8[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %tmp = call <2 x double> @llvm.trunc.v2f64(<2 x double> %x)
  ret <2 x double> %tmp
}

declare float @llvm.trunc.f32(float)
declare double @llvm.trunc.f64(double)
declare <2x float> @llvm.trunc.v2f32(<2 x float>)
declare <2x double> @llvm.trunc.v2f64(<2 x double>)
