; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s | FileCheck %s
target triple = "kvx-kalray-cos"

define void @f() {
; CHECK-LABEL: f:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r0 = 0x4d2
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sw 28[$r12] = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    #APP
; CHECK-NEXT:    addd $tp = $r0, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ;;
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %1 = alloca i32, align 4
  store i32 1234, i32* %1, align 4
  %2 = load i32, i32* %1, align 4
  call void asm sideeffect "addd $$tp = $0, 0\0A\09;;", "r,~{$r13}"(i32 %2)
  ret void
}

define i64 @foo(){
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    copyd $r0 = $r10
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = tail call i64 @llvm.read_register.i64(metadata !0)
  ret i64 %0
}

declare i64 @llvm.read_register.i64(metadata) #1

attributes #1 = { nounwind readonly }

!llvm.named.register.r10 = !{!0}

!0 = !{!"r10"}
