# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple kvx-kalray-cos -run-pass=branch-relaxation -o - %s | FileCheck %s
---
name:            out_bounds
alignment:       134217728
tracksRegLiveness: true
liveins:
  - { reg: '$r0' }
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
machineFunctionInfo: {}
body:             |
  ; CHECK-LABEL: name: out_bounds
  ; CHECK: bb.0 (align 134217728):
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.5(0x40000000)
  ; CHECK-NEXT:   liveins: $r0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   CB killed $r0, %bb.1, 6
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r4 = MAKEi64 %bb.2
  ; CHECK-NEXT:   IGOTO killed $r4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   INLINEASM &nop, 1 /* sideeffect attdialect */
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $r4 = MAKEi64 %bb.2
  ; CHECK-NEXT:   IGOTO killed $r4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2 (align 134217728):
  ; CHECK-NEXT:   BUNDLE implicit-def $r0, implicit $ra {
  ; CHECK-NEXT:     $r0 = MAKEi16 3
  ; CHECK-NEXT:     RET implicit $ra, implicit internal $r0
  ; CHECK-NEXT:   }
  bb.0 (align 134217728):
    successors: %bb.1, %bb.2
    liveins: $r0

    CB killed $r0, %bb.2, 7

  bb.1:
    INLINEASM &nop, 1
    GOTO %bb.2

  bb.2 (align 134217728):
    BUNDLE implicit-def $r0, implicit $ra {
      $r0 = MAKEi16 3
      RET implicit $ra, implicit internal $r0
    }

...
