; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s
; RUN: clang -O2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

; The tests below emphasize how the LLVM compiler moves around floating-point
; instructions regardless of the presence of calls. Indeed, by default, the
; compiler does not seek to preserve rounding mode.
; Cf flag `-fno-rounding-math` of the Clang Compiler User's Manual

define float @setcs_asm(i64 %l, float %a, float %b) {
; CHECK-LABEL: setcs_asm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    set $cs = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    faddw $r0 = $r1, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  tail call void asm sideeffect "set $$cs = $0", "r,~{$cs}"(i64 %l)
  %add = fadd float %a, %b
  ret float %add
}

define float @setcs_builtin(i64 %l, float %a, float %b) {
; CHECK-LABEL: setcs_builtin:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    set $cs = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    faddw $r0 = $r1, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  tail call void asm sideeffect "set $$cs = $0", "r,~{$cs}"(i64 %l)
  %add = fadd float %a, %b
  ret float %add
}

define float @setcs_asm2(i64 %l, float %a, float %b, float %c) {
; CHECK-LABEL: setcs_asm2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmulw $r2 = $r2, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    #APP
; CHECK-NEXT:    set $cs = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    faddw $r0 = $r2, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %mul = fmul float %b, %c
  tail call void asm sideeffect "set $$cs = $0", "r,~{$cs}"(i64 %l)
  %add = fadd float %mul, %a
  ret float %add
}

define float @setcs_builtin2(i64 %l, float %a, float %b, float %c) {
; CHECK-LABEL: setcs_builtin2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fmulw $r2 = $r2, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    #APP
; CHECK-NEXT:    set $cs = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    faddw $r0 = $r2, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %mul = fmul float %b, %c
  tail call void asm sideeffect "set $$cs = $0", "r,~{$cs}"(i64 %l)
  %add = fadd float %mul, %a
  ret float %add
}
