; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -O2 -o - %s | FileCheck %s --check-prefix=ALL
; RUN: llc -mcpu=kv3-2 -O2 -o - %s | FileCheck %s --check-prefix=ALL
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define i32 @b(i32 %0) {
; ALL-LABEL: b:
; ALL:       # %bb.0:
; ALL-NEXT:    sraw $r1 = $r0, 31
; ALL-NEXT:    ;;
; ALL-NEXT:    srlw $r1 = $r1, 25
; ALL-NEXT:    ;;
; ALL-NEXT:    addw $r1 = $r0, $r1
; ALL-NEXT:    ;;
; ALL-NEXT:    andw $r1 = $r1, -128
; ALL-NEXT:    ;;
; ALL-NEXT:    sbfw $r0 = $r1, $r0
; ALL-NEXT:    ret
; ALL-NEXT:    ;;
 %2 = srem i32 %0, 128
 ret i32 %2
}
