; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --disable-kvx-loadstore-packing=false -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 --disable-kvx-loadstore-packing=false -o - %s | FileCheck %s --check-prefixes=CHECK
target triple = "kvx-kalray-cos"

; Function Attrs: norecurse nounwind
define void @f2(i64* nocapture readonly %a, i64* nocapture %b) {
; CHECK-LABEL: f2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lq $r2r3 = 0[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r1] = $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load i64, i64* %a, align 8
  %arrayidx1 = getelementptr inbounds i64, i64* %a, i64 1
  %1 = load i64, i64* %arrayidx1, align 8
  store i64 %0, i64* %b, align 8
  %arrayidx3 = getelementptr inbounds i64, i64* %b, i64 1
  store i64 %1, i64* %arrayidx3, align 8
  ret void

}

; Function Attrs: norecurse nounwind
define void @f4(i64* nocapture readonly %a, i64* nocapture %b) {
; CHECK-LABEL: f4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lo $r4r5r6r7 = 0[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    so 0[$r1] = $r4r5r6r7
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = load i64, i64* %a, align 8
  %arrayidx1 = getelementptr inbounds i64, i64* %a, i64 1
  %1 = load i64, i64* %arrayidx1, align 8
  %arrayidx2 = getelementptr inbounds i64, i64* %a, i64 2
  %2 = load i64, i64* %arrayidx2, align 8
  %arrayidx3 = getelementptr inbounds i64, i64* %a, i64 3
  %3 = load i64, i64* %arrayidx3, align 8
  store i64 %0, i64* %b, align 8
  %arrayidx5 = getelementptr inbounds i64, i64* %b, i64 1
  store i64 %1, i64* %arrayidx5, align 8
  %arrayidx6 = getelementptr inbounds i64, i64* %b, i64 2
  store i64 %2, i64* %arrayidx6, align 8
  %arrayidx7 = getelementptr inbounds i64, i64* %b, i64 3
  store i64 %3, i64* %arrayidx7, align 8
  ret void

}
