; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -o - %s -O2 | FileCheck %s
target triple = "kvx-kalray-cos"

@a = global i32 0, align 4

define i32 @add_pm0() {
; CHECK-LABEL: add_pm0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = a
; CHECK-NEXT:    get $r1 = $pm0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lwz $r2 = 0[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    addw $r1 = $r2, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sw 0[$r0] = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = tail call i64 @llvm.kvx.get(i32 13)
  %1 = load i32, i32* @a, align 4
  %2 = trunc i64 %0 to i32
  %conv1 = add i32 %1, %2
  store i32 %conv1, i32* @a, align 4
  ret i32 undef
}

declare i64 @llvm.kvx.get(i32)

