; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=kvx-kalray-cos | FileCheck %s

target triple = "kvx-kalray-cos"

declare void @bar()

define fastcc void @foo() {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    goto bar
; CHECK-NEXT:    ;;
  tail call void @bar()
  ret void
}
