; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O1 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -O1 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O1 -c -o /dev/null %s
; RUN: clang -march=kv3-2 -O1 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

@v = external global [5 x i32], align 4

; Function Attrs: nounwind
define i32 @foo(){
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = v
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lwz $r0 = 16[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mulw $r0 = $r0, $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    goto bar
; CHECK-NEXT:    ;;
entry:
  %0 = load i32, i32* getelementptr inbounds ([5 x i32], [5 x i32]* @v, i64 0, i64 4), align 4
  %mul = mul nsw i32 %0, %0
  %call = tail call i32 @bar(i32 %mul)
  ret i32 %call

}

declare i32 @bar(i32)
