; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mcpu=kv3-1 -O0 -o - %s | FileCheck %s --check-prefix=CV1
; RUN: llc -mcpu=kv3-2 -O0 -o - %s | FileCheck %s --check-prefix=CV2
; FIXME: cv2 has no zero tca registers
target triple = "kvx-kalray-cos"

define void @zeroinit256() {
; CV1-LABEL: zeroinit256:
; CV1:       # %bb.0:
; CV1-NEXT:    addd $r12 = $r12, -32
; CV1-NEXT:    ;;
; CV1-NEXT:    # implicit-def: $a0
; CV1-NEXT:  .LBB0_1: # =>This Inner Loop Header: Depth=1
; CV1-NEXT:    lv $a0 = 0[$r12]
; CV1-NEXT:    ;;
; CV1-NEXT:    copyv $a0 = $a48
; CV1-NEXT:    ;;
; CV1-NEXT:    sv 0[$r12] = $a0
; CV1-NEXT:    ;;
; CV1-NEXT:    goto .LBB0_1
; CV1-NEXT:    ;;
;
; CV2-LABEL: zeroinit256:
; CV2:       # %bb.0:
; CV2-NEXT:    addd $r12 = $r12, -32
; CV2-NEXT:    ;;
; CV2-NEXT:    # implicit-def: $a0
; CV2-NEXT:  .LBB0_1: # =>This Inner Loop Header: Depth=1
; CV2-NEXT:    xlo $a0 = 0[$r12]
; CV2-NEXT:    ;;
; CV2-NEXT:    copyv $a0 = $a48
; CV2-NEXT:    ;;
; CV2-NEXT:    xso 0[$r12] = $a0
; CV2-NEXT:    ;;
; CV2-NEXT:    goto .LBB0_1
; CV2-NEXT:    ;;
  br label %1

1:
  %2 = phi <256 x i1> [ %3, %1 ], [ undef, %0 ]
  %3 = select i1 undef, <256 x i1> %2, <256 x i1> zeroinitializer
  br label %1
}

define void @zeroinit512() {
; CV1-LABEL: zeroinit512:
; CV1:       # %bb.0:
; CV1-NEXT:    addd $r12 = $r12, -192
; CV1-NEXT:    ;;
; CV1-NEXT:    get $r16 = $ra
; CV1-NEXT:    ;;
; CV1-NEXT:    sd 184[$r12] = $r16
; CV1-NEXT:    ;;
; CV1-NEXT:    sd 176[$r12] = $r14
; CV1-NEXT:    ;;
; CV1-NEXT:    addd $r14 = $r12, 176
; CV1-NEXT:    ;;
; CV1-NEXT:    sd 168[$r12] = $r31
; CV1-NEXT:    ;;
; CV1-NEXT:    andd $r31 = $r12, -64
; CV1-NEXT:    ;;
; CV1-NEXT:    # implicit-def: $w0
; CV1-NEXT:  .LBB1_1: # =>This Inner Loop Header: Depth=1
; CV1-NEXT:    lv $a0 = 64[$r31]
; CV1-NEXT:    ;;
; CV1-NEXT:    lv $a1 = 96[$r31]
; CV1-NEXT:    ;;
; CV1-NEXT:    copyv $a0 = $a50
; CV1-NEXT:    ;;
; CV1-NEXT:    copyv $a1 = $a51
; CV1-NEXT:    ;;
; CV1-NEXT:    sv 64[$r31] = $a0
; CV1-NEXT:    ;;
; CV1-NEXT:    sv 96[$r31] = $a1
; CV1-NEXT:    ;;
; CV1-NEXT:    goto .LBB1_1
; CV1-NEXT:    ;;
;
; CV2-LABEL: zeroinit512:
; CV2:       # %bb.0:
; CV2-NEXT:    addd $r12 = $r12, -192
; CV2-NEXT:    ;;
; CV2-NEXT:    get $r16 = $ra
; CV2-NEXT:    ;;
; CV2-NEXT:    sd 184[$r12] = $r16
; CV2-NEXT:    ;;
; CV2-NEXT:    sd 176[$r12] = $r14
; CV2-NEXT:    ;;
; CV2-NEXT:    addd $r14 = $r12, 176
; CV2-NEXT:    ;;
; CV2-NEXT:    sd 168[$r12] = $r31
; CV2-NEXT:    ;;
; CV2-NEXT:    andd $r31 = $r12, -64
; CV2-NEXT:    ;;
; CV2-NEXT:    # implicit-def: $w0
; CV2-NEXT:  .LBB1_1: # =>This Inner Loop Header: Depth=1
; CV2-NEXT:    xlo $a0 = 64[$r31]
; CV2-NEXT:    ;;
; CV2-NEXT:    xlo $a1 = 96[$r31]
; CV2-NEXT:    ;;
; CV2-NEXT:    copyv $a0 = $a50
; CV2-NEXT:    ;;
; CV2-NEXT:    copyv $a1 = $a51
; CV2-NEXT:    ;;
; CV2-NEXT:    xso 64[$r31] = $a0
; CV2-NEXT:    ;;
; CV2-NEXT:    xso 96[$r31] = $a1
; CV2-NEXT:    ;;
; CV2-NEXT:    goto .LBB1_1
; CV2-NEXT:    ;;
  br label %1

1:
  %2 = phi <512 x i1> [ %3, %1 ], [ undef, %0 ]
  %3 = select i1 undef, <512 x i1> %2, <512 x i1> zeroinitializer
  br label %1
}

define void @zeroinit1024() {
; CV1-LABEL: zeroinit1024:
; CV1:       # %bb.0:
; CV1-NEXT:    addd $r12 = $r12, -384
; CV1-NEXT:    ;;
; CV1-NEXT:    get $r16 = $ra
; CV1-NEXT:    ;;
; CV1-NEXT:    sd 376[$r12] = $r16
; CV1-NEXT:    ;;
; CV1-NEXT:    sd 368[$r12] = $r14
; CV1-NEXT:    ;;
; CV1-NEXT:    addd $r14 = $r12, 368
; CV1-NEXT:    ;;
; CV1-NEXT:    sd 360[$r12] = $r31
; CV1-NEXT:    ;;
; CV1-NEXT:    andd $r31 = $r12, -128
; CV1-NEXT:    ;;
; CV1-NEXT:    # implicit-def: $x0
; CV1-NEXT:  .LBB2_1: # =>This Inner Loop Header: Depth=1
; CV1-NEXT:    lv $a0 = 128[$r31]
; CV1-NEXT:    ;;
; CV1-NEXT:    lv $a1 = 160[$r31]
; CV1-NEXT:    ;;
; CV1-NEXT:    lv $a2 = 192[$r31]
; CV1-NEXT:    ;;
; CV1-NEXT:    lv $a3 = 224[$r31]
; CV1-NEXT:    ;;
; CV1-NEXT:    copyv $a0 = $a48
; CV1-NEXT:    ;;
; CV1-NEXT:    copyv $a1 = $a49
; CV1-NEXT:    ;;
; CV1-NEXT:    copyv $a2 = $a50
; CV1-NEXT:    ;;
; CV1-NEXT:    copyv $a3 = $a51
; CV1-NEXT:    ;;
; CV1-NEXT:    sv 128[$r31] = $a0
; CV1-NEXT:    ;;
; CV1-NEXT:    sv 160[$r31] = $a1
; CV1-NEXT:    ;;
; CV1-NEXT:    sv 192[$r31] = $a2
; CV1-NEXT:    ;;
; CV1-NEXT:    sv 224[$r31] = $a3
; CV1-NEXT:    ;;
; CV1-NEXT:    goto .LBB2_1
; CV1-NEXT:    ;;
;
; CV2-LABEL: zeroinit1024:
; CV2:       # %bb.0:
; CV2-NEXT:    addd $r12 = $r12, -384
; CV2-NEXT:    ;;
; CV2-NEXT:    get $r16 = $ra
; CV2-NEXT:    ;;
; CV2-NEXT:    sd 376[$r12] = $r16
; CV2-NEXT:    ;;
; CV2-NEXT:    sd 368[$r12] = $r14
; CV2-NEXT:    ;;
; CV2-NEXT:    addd $r14 = $r12, 368
; CV2-NEXT:    ;;
; CV2-NEXT:    sd 360[$r12] = $r31
; CV2-NEXT:    ;;
; CV2-NEXT:    andd $r31 = $r12, -128
; CV2-NEXT:    ;;
; CV2-NEXT:    # implicit-def: $x0
; CV2-NEXT:  .LBB2_1: # =>This Inner Loop Header: Depth=1
; CV2-NEXT:    xlo $a0 = 128[$r31]
; CV2-NEXT:    ;;
; CV2-NEXT:    xlo $a1 = 160[$r31]
; CV2-NEXT:    ;;
; CV2-NEXT:    xlo $a2 = 192[$r31]
; CV2-NEXT:    ;;
; CV2-NEXT:    xlo $a3 = 224[$r31]
; CV2-NEXT:    ;;
; CV2-NEXT:    copyv $a0 = $a48
; CV2-NEXT:    ;;
; CV2-NEXT:    copyv $a1 = $a49
; CV2-NEXT:    ;;
; CV2-NEXT:    copyv $a2 = $a50
; CV2-NEXT:    ;;
; CV2-NEXT:    copyv $a3 = $a51
; CV2-NEXT:    ;;
; CV2-NEXT:    xso 128[$r31] = $a0
; CV2-NEXT:    ;;
; CV2-NEXT:    xso 160[$r31] = $a1
; CV2-NEXT:    ;;
; CV2-NEXT:    xso 192[$r31] = $a2
; CV2-NEXT:    ;;
; CV2-NEXT:    xso 224[$r31] = $a3
; CV2-NEXT:    ;;
; CV2-NEXT:    goto .LBB2_1
; CV2-NEXT:    ;;
  br label %1

1:
  %2 = phi <1024 x i1> [ %3, %1 ], [ undef, %0 ]
  %3 = select i1 undef, <1024 x i1> %2, <1024 x i1> zeroinitializer
  br label %1
}
