; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -o - %s | FileCheck %s --check-prefixes=CHECK,KV3_1
; RUN: llc -mcpu=kv3-2 -O2 -o - %s | FileCheck %s --check-prefixes=CHECK,KV3_2
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <4 x half> @test_ret_const() #0 {
; CHECK-LABEL: test_ret_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r0 = 0x4400420040003c00
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  ret <4 x half> <half 1.0, half 2.0, half 3.0, half 4.0>
}

define half @test_extract_0(<4 x half> %a) #0 {
; CHECK-LABEL: test_extract_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %e = extractelement <4 x half> %a, i32 0
  ret half %e
}

define half @test_extract_1(<4 x half> %a) #0 {
; CHECK-LABEL: test_extract_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srlw $r0 = $r0, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %e = extractelement <4 x half> %a, i32 1
  ret half %e
}

define half @test_extract_2(<4 x half> %a) #0 {
; CHECK-LABEL: test_extract_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r0 = $r0, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %e = extractelement <4 x half> %a, i32 2
  ret half %e
}

define half @test_extract_3(<4 x half> %a) #0 {
; CHECK-LABEL: test_extract_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r0 = $r0, 48
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %e = extractelement <4 x half> %a, i32 3
  ret half %e
}

define half @test_extract_i(<4 x half> %a, i64 %idx) #0 {
; CHECK-LABEL: test_extract_i:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sllw $r1 = $r1, 4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %e = extractelement <4 x half> %a, i64 %idx
  ret half %e
}

define <4 x half> @test_fadd(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fadd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    faddhq $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fadd <4 x half> %a, %b
  ret <4 x half> %r
}

define <4 x half> @test_fadd_imm_0(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fadd_imm_0:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    faddhq $r0 = $r0, 0x4400420040003c00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fadd_imm_0:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0x4400420040003c00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    faddhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fadd <4 x half> <half 1.0, half 2.0, half 3.0, half 4.0>, %a
  ret <4 x half> %r
}

define <4 x half> @test_fadd_imm_1(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fadd_imm_1:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    faddhq $r0 = $r0, 0x4400420040003c00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fadd_imm_1:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0x4400420040003c00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    faddhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fadd <4 x half> %a, <half 1.0, half 2.0, half 3.0, half 4.0>
  ret <4 x half> %r
}

define <4 x half> @test_fadd_imm_2(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fadd_imm_2:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    faddhq $r0 = $r0, 0x40003c0040003c00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fadd_imm_2:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0x40003c0040003c00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    faddhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fadd <4 x half> %a, <half 1.0, half 2.0, half 1.0, half 2.0>
  ret <4 x half> %r
}

define <4 x half> @test_fadd_imm_3(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fadd_imm_3:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    faddhq $r0 = $r0, 0x40003c00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fadd_imm_3:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0x40003c00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    faddhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fadd <4 x half> %a, <half 1.0, half 2.0, half 0.0, half 0.0>
  ret <4 x half> %r
}

define <4 x half> @test_fsub(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fsub:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fsbfhq $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fsub <4 x half> %a, %b
  ret <4 x half> %r
}

define <4 x half> @test_fsub_imm_1(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fsub_imm_1:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    faddhq $r0 = $r0, 0xc400c200c000bc00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fsub_imm_1:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0xc400c200c000bc00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    faddhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fsub <4 x half> %a, <half 1.0, half 2.0, half 3.0, half 4.0>
  ret <4 x half> %r
}

define <4 x half> @test_fsub_imm_2(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fsub_imm_2:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    faddhq $r0 = $r0, 0x80008000c000bc00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fsub_imm_2:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0x80008000c000bc00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    faddhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fsub <4 x half> %a, <half 1.0, half 2.0, half 0.0, half 0.0>
  ret <4 x half> %r
}

define <4 x half> @test_fsub_imm_3(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fsub_imm_3:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    faddhq $r0 = $r0, 0xc000bc00c000bc00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fsub_imm_3:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0xc000bc00c000bc00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    faddhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fsub <4 x half> %a, <half 1.0, half 2.0, half 1.0, half 2.0>
  ret <4 x half> %r
}

define <4 x half> @test_fsub_fromimm1(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fsub_fromimm1:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    fsbfhq $r0 = $r0, 0x4400420040003c00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fsub_fromimm1:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0x4400420040003c00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fsbfhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fsub <4 x half> <half 1.0, half 2.0, half 3.0, half 4.0>, %a
  ret <4 x half> %r
}

define <4 x half> @test_fsub_fromimm2(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fsub_fromimm2:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    fsbfhq $r0 = $r0, 0x40003c00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fsub_fromimm2:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0x40003c00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fsbfhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fsub <4 x half> <half 1.0, half 2.0, half 0.0, half 0.0>, %a
  ret <4 x half> %r
}

define <4 x half> @test_fsub_fromimm3(<4 x half> %a) #0 {
; KV3_1-LABEL: test_fsub_fromimm3:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    fsbfhq $r0 = $r0, 0x40003c0040003c00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fsub_fromimm3:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0x40003c0040003c00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fsbfhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fsub <4 x half> <half 1.0, half 2.0, half 1.0, half 2.0>, %a
  ret <4 x half> %r
}

define <4 x half> @test_fneg(<4 x half> %a) #0 {
; CHECK-LABEL: test_fneg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fneghq $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fsub <4 x half> <half 0.0, half 0.0, half 0.0, half 0.0>, %a
  ret <4 x half> %r
}

define <4 x half> @test_fmul(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fmul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmulhq $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fmul <4 x half> %a, %b
  ret <4 x half> %r
}

define <4 x half> @test_fmul_imm(<4 x half> %a) {
; KV3_1-LABEL: test_fmul_imm:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    fmulhq $r0 = $r0, 0x40003c0040003c00
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_fmul_imm:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    make $r1 = 0x40003c0040003c00
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fmulhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = fmul <4 x half> %a, <half 1.0, half 2.0, half 1.0, half 2.0>
  ret <4 x half> %r
}

define <4 x half> @test_fdiv(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fdiv:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r19, 48
; CHECK-NEXT:    srld $r1 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    call __divsf3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r19, 32
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    call __divsf3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r19
; CHECK-NEXT:    fnarrowwh $r21 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r1 = $r18
; CHECK-NEXT:    insf $r21 = $r20, 31, 16
; CHECK-NEXT:    call __divsf3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r19
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    call __divsf3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fdiv <4 x half> %a, %b
  ret <4 x half> %r
}

define <4 x half> @test_frem(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_frem:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r19, 48
; CHECK-NEXT:    srld $r1 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    call fmodf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r19, 32
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    call fmodf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r19
; CHECK-NEXT:    fnarrowwh $r21 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r1 = $r18
; CHECK-NEXT:    insf $r21 = $r20, 31, 16
; CHECK-NEXT:    call fmodf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r19
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    call fmodf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = frem <4 x half> %a, %b
  ret <4 x half> %r
}

define void @test_ldst_v4f16(<4 x half>* %a, <4 x half>* %b) {
; CHECK-LABEL: test_ldst_v4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld $r0 = 0[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 0[$r1] = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %t1 = load <4 x half>, <4 x half>* %a
  store <4 x half> %t1, <4 x half>* %b, align 16
  ret void
}

declare <4 x half> @test_callee(<4 x half> %a, <4 x half> %b) #0

define <4 x half> @test_call(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_call:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    call test_callee
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @test_callee(<4 x half> %a, <4 x half> %b)
  ret <4 x half> %r
}

define <4 x half> @test_call_flipped(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_call_flipped:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    copyd $r2 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r1 = $r2
; CHECK-NEXT:    call test_callee
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @test_callee(<4 x half> %b, <4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_tailcall_flipped(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_tailcall_flipped:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    copyd $r2 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r1 = $r2
; CHECK-NEXT:    goto test_callee
; CHECK-NEXT:    ;;
  %r = tail call <4 x half> @test_callee(<4 x half> %b, <4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_select(<4 x half> %a, <4 x half> %b, i1 zeroext %c) #0 {
; CHECK-LABEL: test_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmoved.even $r2 ? $r0 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = select i1 %c, <4 x half> %a, <4 x half> %b
  ret <4 x half> %r
}

define <4 x half> @test_select_cc(<4 x half> %a, <4 x half> %b, <4 x half> %c, <4 x half> %d) #0 {
; CHECK-LABEL: test_select_cc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.une $r2 = $r2, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovehq.even $r2 ? $r0 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %cc = fcmp une <4 x half> %c, %d
  %r = select <4 x i1> %cc, <4 x half> %a, <4 x half> %b
  ret <4 x half> %r
}

define <4 x float> @test_select_cc_f32_f16(<4 x float> %a, <4 x float> %b, <4 x half> %c, <4 x half> %d) #0 {
; CHECK-LABEL: test_select_cc_f32_f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.une $r4 = $r4, $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxmhwp $r5 = $r4
; CHECK-NEXT:    sxlhwp $r6 = $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovewp.even $r6 ? $r0 = $r2
; CHECK-NEXT:    cmovewp.even $r5 ? $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %cc = fcmp une <4 x half> %c, %d
  %r = select <4 x i1> %cc, <4 x float> %a, <4 x float> %b
  ret <4 x float> %r
}

define <4 x half> @test_select_cc_f16_f32(<4 x half> %a, <4 x half> %b, <4 x float> %c, <4 x float> %d) #0 {
; CHECK-LABEL: test_select_cc_f16_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnwp.une $r2 = $r2, $r4
; CHECK-NEXT:    fcompnwp.une $r3 = $r3, $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r2 = $r2, 0x20100201
; CHECK-NEXT:    sbmm8 $r3 = $r3, 0x20100201
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r2 = $r3, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovehq.even $r2 ? $r0 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %cc = fcmp une <4 x float> %c, %d
  %r = select <4 x i1> %cc, <4 x half> %a, <4 x half> %b
  ret <4 x half> %r
}

define <4 x i1> @test_fcmp_une(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_une:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.une $r0 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp une <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ueq(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_ueq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.ueq $r0 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp ueq <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ugt(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_ugt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.ult $r0 = $r1, $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp ugt <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_uge(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_uge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.uge $r0 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp uge <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ult(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.ult $r0 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp ult <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ule(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_ule:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.uge $r0 = $r1, $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp ule <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_uno(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_uno:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.uge $r0 = $r0, $r1
; CHECK-NEXT:    fcompnhq.ult $r2 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r0 = $r0, $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp uno <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_one(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.one $r0 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp one <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_oeq(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_oeq:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.oeq $r0 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp oeq <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ogt(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_ogt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.olt $r0 = $r1, $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp ogt <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_oge(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_oge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.oge $r0 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp oge <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_olt(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_olt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.olt $r0 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp olt <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ole(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_ole:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.oge $r0 = $r1, $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp ole <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_fcmp_ord(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_fcmp_ord:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fcompnhq.oge $r0 = $r0, $r1
; CHECK-NEXT:    fcompnhq.olt $r2 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ord $r0 = $r0, $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x40100401
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fcmp ord <4 x half> %a, %b
  ret <4 x i1> %r
}

define <4 x i16> @test_fptosi_i16(<4 x half> %a) #0 {
; CHECK-LABEL: test_fptosi_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlhwp $r0 = $r0
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x20100201
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x20100201
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fptosi <4 x half> %a to <4 x i16>
  ret <4 x i16> %r
}

define <4 x i32> @test_fptosi_i32(<4 x half> %a) #0 {
; CHECK-LABEL: test_fptosi_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlhwp $r0 = $r0
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fptosi <4 x half> %a to <4 x i32>
  ret <4 x i32> %r
}

define <4 x i64> @test_fptosi_i64(<4 x half> %a) #0 {
; CHECK-LABEL: test_fptosi_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlhwp $r0 = $r0
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlwd $r1 = $r1
; CHECK-NEXT:    fwidenmwd $r2 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlwd $r0 = $r0
; CHECK-NEXT:    fixedd.rz $r3 = $r2, 0
; CHECK-NEXT:    fwidenmwd $r4 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedd.rz $r2 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedd.rz $r1 = $r4, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedd.rz $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fptosi <4 x half> %a to <4 x i64>
  ret <4 x i64> %r
}

define <4 x i16> @test_fptoui_4xi16(<4 x half> %a) #0 {
; CHECK-LABEL: test_fptoui_4xi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlhwp $r0 = $r0
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixeduwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixeduwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x20100201
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x20100201
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fptoui <4 x half> %a to <4 x i16>
  ret <4 x i16> %r
}

define <4 x i32> @test_fptoui_4xi32(<4 x half> %a) #0 {
; CHECK-LABEL: test_fptoui_4xi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlhwp $r0 = $r0
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixeduwp.rz $r1 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixeduwp.rz $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fptoui <4 x half> %a to <4 x i32>
  ret <4 x i32> %r
}

define <4 x i64> @test_fptoui_4xi64(<4 x half> %a) #0 {
; CHECK-LABEL: test_fptoui_4xi64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlhwp $r0 = $r0
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlwd $r1 = $r1
; CHECK-NEXT:    fwidenmwd $r2 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlwd $r0 = $r0
; CHECK-NEXT:    fixedud.rz $r3 = $r2, 0
; CHECK-NEXT:    fwidenmwd $r4 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedud.rz $r2 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedud.rz $r1 = $r4, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fixedud.rz $r0 = $r0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fptoui <4 x half> %a to <4 x i64>
  ret <4 x i64> %r
}

define <4 x half> @test_uitofp_4xi16(<4 x i16> %a) #0 {
; KV3_1-LABEL: test_uitofp_4xi16:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    sbmm8 $r1 = $r0, 0x804000002010
; KV3_1-NEXT:    sbmm8 $r2 = $r0, 0x80400000201
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    floatuwp.rn $r0 = $r2, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    floatuwp.rn $r1 = $r1, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowwhq.rn $r0 = $r0r1
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_uitofp_4xi16:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    zxmhwp $r1 = $r0
; KV3_2-NEXT:    zxlhwp $r2 = $r0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    floatuwp.rn $r0 = $r2, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    floatuwp.rn $r1 = $r1, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowwhq.rn $r0 = $r0r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = uitofp <4 x i16> %a to <4 x half>
  ret <4 x half> %r
}

define <4 x half> @test_uitofp_4xi32(<4 x i32> %a) #0 {
; CHECK-LABEL: test_uitofp_4xi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    floatuwp.rn $r0 = $r0, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    floatuwp.rn $r1 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwhq.rn $r0 = $r0r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = uitofp <4 x i32> %a to <4 x half>
  ret <4 x half> %r
}

; Could use vector fnarrow variants
define <4 x half> @test_uitofp_4xi64(<4 x i64> %a) #0 {
; KV3_1-LABEL: test_uitofp_4xi64:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    floatud.rn $r3 = $r3, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    floatud.rn $r2 = $r2, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    floatud.rn $r1 = $r1, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    floatud.rn $r0 = $r0, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowdw.rn $r3 = $r3
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowdw.rn $r2 = $r2
; KV3_1-NEXT:    fnarrowwh.rn $r3 = $r3
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowdw.rn $r1 = $r1
; KV3_1-NEXT:    fnarrowwh.rn $r2 = $r2
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowdw.rn $r0 = $r0
; KV3_1-NEXT:    fnarrowwh.rn $r1 = $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowwh.rn $r0 = $r0
; KV3_1-NEXT:    insf $r2 = $r3, 31, 16
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    insf $r0 = $r1, 31, 16
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    insf $r0 = $r2, 63, 32
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_uitofp_4xi64:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    floatud.rn $r3 = $r3, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    floatud.rn $r2 = $r2, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    floatud.rn $r1 = $r1, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    floatud.rn $r0 = $r0, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowdw.rn $r3 = $r3
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowdw.rn $r2 = $r2
; KV3_2-NEXT:    fnarrowwh.rn $r3 = $r3
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowdw.rn $r1 = $r1
; KV3_2-NEXT:    fnarrowwh.rn $r2 = $r2
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowdw.rn $r0 = $r0
; KV3_2-NEXT:    fnarrowwh.rn $r1 = $r1
; KV3_2-NEXT:    insf $r2 = $r3, 31, 16
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowwh.rn $r0 = $r0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    insf $r0 = $r1, 31, 16
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    insf $r0 = $r2, 63, 32
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = uitofp <4 x i64> %a to <4 x half>
  ret <4 x half> %r
}

define <4 x half> @test_sitofp_4xi32(<4 x i32> %a) #0 {
; CHECK-LABEL: test_sitofp_4xi32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    floatwp.rn $r0 = $r0, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    floatwp.rn $r1 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwhq.rn $r0 = $r0r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sitofp <4 x i32> %a to <4 x half>
  ret <4 x half> %r
}

define <4 x half> @test_sitofp_4xi64(<4 x i64> %a) #0 {
; KV3_1-LABEL: test_sitofp_4xi64:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    floatd.rn $r3 = $r3, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    floatd.rn $r2 = $r2, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    floatd.rn $r1 = $r1, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    floatd.rn $r0 = $r0, 0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowdw.rn $r3 = $r3
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowdw.rn $r2 = $r2
; KV3_1-NEXT:    fnarrowwh.rn $r3 = $r3
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowdw.rn $r1 = $r1
; KV3_1-NEXT:    fnarrowwh.rn $r2 = $r2
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowdw.rn $r0 = $r0
; KV3_1-NEXT:    fnarrowwh.rn $r1 = $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    fnarrowwh.rn $r0 = $r0
; KV3_1-NEXT:    insf $r2 = $r3, 31, 16
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    insf $r0 = $r1, 31, 16
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    insf $r0 = $r2, 63, 32
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_sitofp_4xi64:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    floatd.rn $r3 = $r3, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    floatd.rn $r2 = $r2, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    floatd.rn $r1 = $r1, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    floatd.rn $r0 = $r0, 0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowdw.rn $r3 = $r3
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowdw.rn $r2 = $r2
; KV3_2-NEXT:    fnarrowwh.rn $r3 = $r3
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowdw.rn $r1 = $r1
; KV3_2-NEXT:    fnarrowwh.rn $r2 = $r2
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowdw.rn $r0 = $r0
; KV3_2-NEXT:    fnarrowwh.rn $r1 = $r1
; KV3_2-NEXT:    insf $r2 = $r3, 31, 16
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    fnarrowwh.rn $r0 = $r0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    insf $r0 = $r1, 31, 16
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    insf $r0 = $r2, 63, 32
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = sitofp <4 x i64> %a to <4 x half>
  ret <4 x half> %r
}

define <4 x half> @test_uitofp_4xi32_fadd(<4 x i32> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_uitofp_4xi32_fadd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    floatuwp.rn $r0 = $r0, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    floatuwp.rn $r1 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwhq.rn $r0 = $r0r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    faddhq $r0 = $r2, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %c = uitofp <4 x i32> %a to <4 x half>
  %r = fadd <4 x half> %b, %c
  ret <4 x half> %r
}

define <4 x half> @test_sitofp_4xi32_fadd(<4 x i32> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_sitofp_4xi32_fadd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    floatwp.rn $r0 = $r0, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    floatwp.rn $r1 = $r1, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwhq.rn $r0 = $r0r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    faddhq $r0 = $r2, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %c = sitofp <4 x i32> %a to <4 x half>
  %r = fadd <4 x half> %b, %c
  ret <4 x half> %r
}

define <4 x half> @test_fptrunc_4xfloat(<4 x float> %a) #0 {
; CHECK-LABEL: test_fptrunc_4xfloat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fnarrowwhq $r0 = $r0r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fptrunc <4 x float> %a to <4 x half>
  ret <4 x half> %r
}

define <4 x half> @test_fptrunc_4xdouble(<4 x double> %a) #0 {
; CHECK-LABEL: test_fptrunc_4xdouble:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fnarrowdwp $r3 = $r2r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowdwp $r2 = $r0r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwhq $r0 = $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fptrunc <4 x double> %a to <4 x half>
  ret <4 x half> %r
}

define <4 x float> @test_fpext_4xfloat(<4 x half> %a) #0 {
; CHECK-LABEL: test_fpext_4xfloat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    fwidenlhwp $r2 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fpext <4 x half> %a to <4 x float>
  ret <4 x float> %r
}

define <4 x double> @test_fpext_4xdouble(<4 x half> %a) #0 {
; CHECK-LABEL: test_fpext_4xdouble:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fwidenlhwp $r0 = $r0
; CHECK-NEXT:    fwidenmhwp $r1 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlwd $r2 = $r1
; CHECK-NEXT:    fwidenmwd $r3 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlwd $r0 = $r0
; CHECK-NEXT:    fwidenmwd $r1 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = fpext <4 x half> %a to <4 x double>
  ret <4 x double> %r
}

define <4 x i16> @test_bitcast_4xhalf_to_4xi16(<4 x half> %a) #0 {
; CHECK-LABEL: test_bitcast_4xhalf_to_4xi16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = bitcast <4 x half> %a to <4 x i16>
  ret <4 x i16> %r
}

define <4 x half> @test_bitcast_4xi16_to_4xhalf(<4 x i16> %a) #0 {
; CHECK-LABEL: test_bitcast_4xi16_to_4xhalf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = bitcast <4 x i16> %a to <4 x half>
  ret <4 x half> %r
}

declare <4 x half> @llvm.sqrt.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.powi.v4f16(<4 x half> %a, i32 %b) #0
declare <4 x half> @llvm.sin.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.cos.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.pow.v4f16(<4 x half> %a, <4 x half> %b) #0
declare <4 x half> @llvm.exp.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.exp2.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.log.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.log10.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.log2.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.fma.v4f16(<4 x half> %a, <4 x half> %b, <4 x half> %c) #0
declare <4 x half> @llvm.fabs.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.minnum.v4f16(<4 x half> %a, <4 x half> %b) #0
declare <4 x half> @llvm.maxnum.v4f16(<4 x half> %a, <4 x half> %b) #0
declare <4 x half> @llvm.copysign.v4f16(<4 x half> %a, <4 x half> %b) #0
declare <4 x half> @llvm.floor.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.ceil.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.trunc.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.rint.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.nearbyint.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.round.v4f16(<4 x half> %a) #0
declare <4 x half> @llvm.fmuladd.v4f16(<4 x half> %a, <4 x half> %b, <4 x half> %c) #0

define <4 x half> @test_sqrt(<4 x half> %a) #0 {
; CHECK-LABEL: test_sqrt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call sqrtf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.sqrt.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_powi(<4 x half> %a, i32 %b) #0 {
; CHECK-LABEL: test_powi:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r19, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call __powisf2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r19, 32
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call __powisf2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r19
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r21 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r21 = $r20, 31, 16
; CHECK-NEXT:    call __powisf2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r19
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    call __powisf2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x half> @llvm.powi.v4f16(<4 x half> %a, i32 %b)
 ret <4 x half> %r
}

define <4 x half> @test_sin(<4 x half> %a) #0 {
; CHECK-LABEL: test_sin:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call sinf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call sinf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call sinf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call sinf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.sin.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_cos(<4 x half> %a) #0 {
; CHECK-LABEL: test_cos:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call cosf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call cosf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call cosf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call cosf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.cos.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_pow(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_pow:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 40[$r12] = $r20r21
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 24[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r1
; CHECK-NEXT:    copyd $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r19, 48
; CHECK-NEXT:    srld $r1 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    call powf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r19, 32
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    call powf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r19
; CHECK-NEXT:    fnarrowwh $r21 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r1 = $r18
; CHECK-NEXT:    insf $r21 = $r20, 31, 16
; CHECK-NEXT:    call powf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r19
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    call powf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 24[$r12]
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r20r21 = 40[$r12]
; CHECK-NEXT:    insf $r0 = $r21, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x half> @llvm.pow.v4f16(<4 x half> %a, <4 x half> %b)
 ret <4 x half> %r
}

define <4 x half> @test_exp(<4 x half> %a) #0 {
; CHECK-LABEL: test_exp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call expf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call expf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call expf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call expf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x half> @llvm.exp.v4f16(<4 x half> %a)
 ret <4 x half> %r
}

define <4 x half> @test_exp2(<4 x half> %a) #0 {
; CHECK-LABEL: test_exp2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call exp2f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call exp2f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call exp2f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call exp2f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x half> @llvm.exp2.v4f16(<4 x half> %a)
 ret <4 x half> %r
}

define <4 x half> @test_log(<4 x half> %a) #0 {
; CHECK-LABEL: test_log:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call logf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call logf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call logf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call logf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x half> @llvm.log.v4f16(<4 x half> %a)
 ret <4 x half> %r
}

define <4 x half> @test_log10(<4 x half> %a) #0 {
; CHECK-LABEL: test_log10:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call log10f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call log10f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call log10f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call log10f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x half> @llvm.log10.v4f16(<4 x half> %a)
 ret <4 x half> %r
}

define <4 x half> @test_log2(<4 x half> %a) #0 {
; CHECK-LABEL: test_log2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call log2f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call log2f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call log2f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call log2f
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
 %r = call <4 x half> @llvm.log2.v4f16(<4 x half> %a)
 ret <4 x half> %r
}

define <4 x half> @test_fma(<4 x half> %a, <4 x half> %b, <4 x half> %c) #0 {
; CHECK-LABEL: test_fma:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ffmahq $r2 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.fma.v4f16(<4 x half> %a, <4 x half> %b, <4 x half> %c)
  ret <4 x half> %r
}

define <4 x half> @test_fabs(<4 x half> %a) #0 {
; CHECK-LABEL: test_fabs:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fabshq $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.fabs.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_minnum(<4 x half> %a, <4 x half> %b) #0 {
; KV3_1-LABEL: test_minnum:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    addd $r12 = $r12, -64
; KV3_1-NEXT:    get $r16 = $ra
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sd 56[$r12] = $r16
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sd 48[$r12] = $r22
; KV3_1-NEXT:    fwidenlhwp $r22 = $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sq 32[$r12] = $r20r21
; KV3_1-NEXT:    fwidenmhwp $r21 = $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sq 16[$r12] = $r18r19
; KV3_1-NEXT:    srld $r1 = $r22, 32
; KV3_1-NEXT:    fwidenlhwp $r18 = $r0
; KV3_1-NEXT:    fwidenmhwp $r19 = $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srld $r0 = $r18, 32
; KV3_1-NEXT:    call fminf
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    copyd $r0 = $r18
; KV3_1-NEXT:    copyd $r1 = $r22
; KV3_1-NEXT:    copyd $r20 = $r0
; KV3_1-NEXT:    call fminf
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srld $r0 = $r21, 32
; KV3_1-NEXT:    srld $r1 = $r19, 32
; KV3_1-NEXT:    copyd $r18 = $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    insf $r18 = $r20, 63, 32
; KV3_1-NEXT:    call fminf
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    copyd $r0 = $r21
; KV3_1-NEXT:    copyd $r1 = $r19
; KV3_1-NEXT:    copyd $r20 = $r0
; KV3_1-NEXT:    call fminf
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    copyd $r19 = $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    insf $r19 = $r20, 63, 32
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    lq $r18r19 = 16[$r12]
; KV3_1-NEXT:    fnarrowwhq $r0 = $r18r19
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    lq $r20r21 = 32[$r12]
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    ld $r22 = 48[$r12]
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    ld $r16 = 56[$r12]
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    set $ra = $r16
; KV3_1-NEXT:    addd $r12 = $r12, 64
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_minnum:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    fminhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = call <4 x half> @llvm.minnum.v4f16(<4 x half> %a, <4 x half> %b)
  ret <4 x half> %r
}

define <4 x half> @test_minnum_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_minnum_fast:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fminhq $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call fast <4 x half> @llvm.minnum.v4f16(<4 x half> %a, <4 x half> %b)
  ret <4 x half> %r
}

define <4 x half> @test_maxnum(<4 x half> %a, <4 x half> %b) #0 {
; KV3_1-LABEL: test_maxnum:
; KV3_1:       # %bb.0:
; KV3_1-NEXT:    addd $r12 = $r12, -64
; KV3_1-NEXT:    get $r16 = $ra
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sd 56[$r12] = $r16
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sd 48[$r12] = $r22
; KV3_1-NEXT:    fwidenlhwp $r22 = $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sq 32[$r12] = $r20r21
; KV3_1-NEXT:    fwidenmhwp $r21 = $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sq 16[$r12] = $r18r19
; KV3_1-NEXT:    srld $r1 = $r22, 32
; KV3_1-NEXT:    fwidenlhwp $r18 = $r0
; KV3_1-NEXT:    fwidenmhwp $r19 = $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srld $r0 = $r18, 32
; KV3_1-NEXT:    call fmaxf
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    copyd $r0 = $r18
; KV3_1-NEXT:    copyd $r1 = $r22
; KV3_1-NEXT:    copyd $r20 = $r0
; KV3_1-NEXT:    call fmaxf
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srld $r0 = $r21, 32
; KV3_1-NEXT:    srld $r1 = $r19, 32
; KV3_1-NEXT:    copyd $r18 = $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    insf $r18 = $r20, 63, 32
; KV3_1-NEXT:    call fmaxf
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    copyd $r0 = $r21
; KV3_1-NEXT:    copyd $r1 = $r19
; KV3_1-NEXT:    copyd $r20 = $r0
; KV3_1-NEXT:    call fmaxf
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    copyd $r19 = $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    insf $r19 = $r20, 63, 32
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    lq $r18r19 = 16[$r12]
; KV3_1-NEXT:    fnarrowwhq $r0 = $r18r19
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    lq $r20r21 = 32[$r12]
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    ld $r22 = 48[$r12]
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    ld $r16 = 56[$r12]
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    set $ra = $r16
; KV3_1-NEXT:    addd $r12 = $r12, 64
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: test_maxnum:
; KV3_2:       # %bb.0:
; KV3_2-NEXT:    fmaxhq $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
  %r = call <4 x half> @llvm.maxnum.v4f16(<4 x half> %a, <4 x half> %b)
  ret <4 x half> %r
}

define <4 x half> @test_maxnum_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_maxnum_fast:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fmaxhq $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call fast <4 x half> @llvm.maxnum.v4f16(<4 x half> %a, <4 x half> %b)
  ret <4 x half> %r
}

define <4 x half> @test_copysign(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_copysign:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fabshq $r0 = $r0
; CHECK-NEXT:    andd.@ $r1 = $r1, 0x80008000
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ord $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.copysign.v4f16(<4 x half> %a, <4 x half> %b)
  ret <4 x half> %r
}

define <4 x half> @test_copysign_v4f32(<4 x half> %a, <4 x float> %b) #0 {
; CHECK-LABEL: test_copysign_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fabshq $r0 = $r0
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    copyd $r3 = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwhq.rna.s $r1 = $r2r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd.@ $r1 = $r1, 0x80008000
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ord $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %tb = fptrunc <4 x float> %b to <4 x half>
  %r = call <4 x half> @llvm.copysign.v4f16(<4 x half> %a, <4 x half> %tb)
  ret <4 x half> %r
}

; TODO: The bundler could eliminate these useless copyd
define <4 x half> @test_copysign_v4f64(<4 x half> %a, <4 x double> %b) #0 {
; CHECK-LABEL: test_copysign_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r5 = $r2
; CHECK-NEXT:    copyd $r6 = $r3
; CHECK-NEXT:    copyd $r8 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r8, 63
; CHECK-NEXT:    srld $r2 = $r5, 63
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 15, 15
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r2, 31, 31
; CHECK-NEXT:    srld $r2 = $r6, 63
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r2, 47, 47
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 63, 63
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %tb = fptrunc <4 x double> %b to <4 x half>
  %r = call <4 x half> @llvm.copysign.v4f16(<4 x half> %a, <4 x half> %tb)
  ret <4 x half> %r
}

define <4 x float> @test_copysign_extended(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: test_copysign_extended:
; CHECK:       # %bb.0:
; CHECK-NEXT:    fabshq $r0 = $r0
; CHECK-NEXT:    andd.@ $r1 = $r1, 0x80008000
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ord $r1 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhwp $r0 = $r1
; CHECK-NEXT:    fwidenmhwp $r1 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.copysign.v4f16(<4 x half> %a, <4 x half> %b)
  %xr = fpext <4 x half> %r to <4 x float>
  ret <4 x float> %xr
}

define <4 x half> @test_floor(<4 x half> %a) #0 {
; CHECK-LABEL: test_floor:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call floorf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call floorf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call floorf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call floorf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.floor.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_ceil(<4 x half> %a) #0 {
; CHECK-LABEL: test_ceil:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call ceilf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call ceilf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call ceilf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call ceilf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.ceil.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_trunc(<4 x half> %a) #0 {
; CHECK-LABEL: test_trunc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call truncf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.trunc.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_rint(<4 x half> %a) #0 {
; CHECK-LABEL: test_rint:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call rintf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call rintf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call rintf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call rintf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.rint.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_nearbyint(<4 x half> %a) #0 {
; CHECK-LABEL: test_nearbyint:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call nearbyintf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call nearbyintf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call nearbyintf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call nearbyintf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.nearbyint.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_round(<4 x half> %a) #0 {
; CHECK-LABEL: test_round:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r18, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r0 = $r0
; CHECK-NEXT:    call roundf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r1 = $r18, 32
; CHECK-NEXT:    fnarrowwh $r19 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call roundf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenmhw $r0 = $r18
; CHECK-NEXT:    fnarrowwh $r20 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r20 = $r19, 31, 16
; CHECK-NEXT:    call roundf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fwidenlhw $r1 = $r18
; CHECK-NEXT:    fnarrowwh $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    call roundf
; CHECK-NEXT:    ;;
; CHECK-NEXT:    fnarrowwh $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 0[$r12]
; CHECK-NEXT:    insf $r0 = $r18, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    ld $r20 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.round.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x half> @test_fmuladd(<4 x half> %a, <4 x half> %b, <4 x half> %c) #0 {
; CHECK-LABEL: test_fmuladd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ffmahq $r2 = $r0, $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x half> @llvm.fmuladd.v4f16(<4 x half> %a, <4 x half> %b, <4 x half> %c)
  ret <4 x half> %r
}

define <4 x half> @test_shufflevector(<4 x half> %a) #0 {
; CHECK-LABEL: test_shufflevector:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r1 = $r0, 48
; CHECK-NEXT:    srlw $r2 = $r0, 16
; CHECK-NEXT:    srld $r3 = $r0, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r3, 31, 16
; CHECK-NEXT:    insf $r2 = $r0, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r2, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %s = shufflevector <4 x half> %a, <4 x half> undef, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
  ret <4 x half> %s
}

define <4 x half> @test_shufflevector2(<4 x half> %a) #0 {
; CHECK-LABEL: test_shufflevector2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srld $r1 = $r0, 32
; CHECK-NEXT:    srld $r2 = $r0, 48
; CHECK-NEXT:    srlw $r3 = $r0, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r3, 31, 16
; CHECK-NEXT:    insf $r2 = $r1, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r2, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %s = shufflevector <4 x half> %a, <4 x half> undef, <4 x i32> <i32 0, i32 1, i32 3, i32 2>
  ret <4 x half> %s
}

define <4 x half> @test_insertelement0(<4 x half> %a, half %x) #0 {
; CHECK-LABEL: test_insertelement0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 15, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x half> %a, half %x, i64 0
  ret <4 x half> %i
}

define <4 x half> @test_insertelement1(<4 x half> %a, half %x) #0 {
; CHECK-LABEL: test_insertelement1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x half> %a, half %x, i64 1
  ret <4 x half> %i
}

define <4 x half> @test_insertelement2(<4 x half> %a, half %x) #0 {
; CHECK-LABEL: test_insertelement2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 47, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x half> %a, half %x, i64 2
  ret <4 x half> %i
}

define <4 x half> @test_insertelement3(<4 x half> %a, half %x) #0 {
; CHECK-LABEL: test_insertelement3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 63, 48
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x half> %a, half %x, i64 3
  ret <4 x half> %i
}

define <4 x half> @test_insertelement(<4 x half> %a, half %x, i64 %p) #0 {
; CHECK-LABEL: test_insertelement:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r1 = $r1, 31, 16
; CHECK-NEXT:    insf $r2 = $r2, 31, 16
; CHECK-NEXT:    make $r3 = 0x3000200010000
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r1, 63, 32
; CHECK-NEXT:    insf $r2 = $r2, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    compnhq.eq $r2 = $r3, $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovehq.nez $r2 ? $r0 = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x half> %a, half %x, i64 %p
  ret <4 x half> %i
}

define <4 x i16> @fcmp_setoeq(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setoeq:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.oeq $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp oeq <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setoeq_single(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setoeq_single:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setoeq_single:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp oeq <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setogt(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setogt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.olt $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp ogt <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setogt_single(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setogt_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp ogt <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setoge(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setoge:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.oge $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp oge <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setoge_single(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setoge_single:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setoge_single:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp oge <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setolt(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setolt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.olt $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp olt <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setolt_single(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setolt_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp olt <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setole(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setole:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.oge $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp ole <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setole_single(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setole_single:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setole_single:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp ole <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setone(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setone:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.one $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp one <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setone_single(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setone_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp one <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setord(<4 x half> %a, <4 x half> %b) #0 {
; KV3_1-LABEL: fcmp_setord:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.oge $r0 = $r0, $r1
; KV3_1-NEXT:    fcompnhq.olt $r2 = $r0, $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    ord $r0 = $r0, $r2
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setord:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.oge $r0 = $r0, $r1
; KV3_2-NEXT:    fcompnhq.olt $r2 = $r0, $r1
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    ord $r0 = $r0, $r2
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp ord <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setord_single(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setord_single:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setord_single:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp ord <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setuno(<4 x half> %a, <4 x half> %b) #0 {
; KV3_1-LABEL: fcmp_setuno:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.uge $r0 = $r0, $r1
; KV3_1-NEXT:    fcompnhq.ult $r2 = $r0, $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    andd $r0 = $r0, $r2
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setuno:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.uge $r0 = $r0, $r1
; KV3_2-NEXT:    fcompnhq.ult $r2 = $r0, $r1
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    andd $r0 = $r0, $r2
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp uno <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setuno_single(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setuno_single:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_1-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    andd $r0 = $r0, $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setuno_single:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_2-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    andd $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp uno <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setueq(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setueq:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.ueq $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp ueq <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setueq_single(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setueq_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp ueq <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setugt(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setugt:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.ult $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp ugt <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setugt_single(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setugt_single:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_1-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    andd $r0 = $r0, $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setugt_single:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_2-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    andd $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp ugt <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setuge(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setuge:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.uge $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp uge <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setuge_single(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setuge_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp uge <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setult(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setult:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.ult $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp ult <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setult_single(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setult_single:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_1-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    andd $r0 = $r0, $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setult_single:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_2-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    andd $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp ult <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setule(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setule:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.uge $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp ule <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setule_single(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setule_single:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp ule <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setune(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setune:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.une $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp une <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setune_single(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setune_single:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_1-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    andd $r0 = $r0, $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setune_single:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_2-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    andd $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp une <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setoeq_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setoeq_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.oeq $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast oeq <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setoeq_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setoeq_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast oeq <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setogt_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setogt_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.olt $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ogt <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setogt_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setogt_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ogt <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setoge_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setoge_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.oge $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast oge <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setoge_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setoge_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast oge <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setolt_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setolt_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.olt $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast olt <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setolt_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setolt_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast olt <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setole_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setole_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.oge $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ole <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setole_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setole_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ole <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setone_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setone_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.one $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast one <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setone_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setone_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast one <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setord_fast(<4 x half> %a, <4 x half> %b) #0 {
; KV3_1-LABEL: fcmp_setord_fast:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.oge $r0 = $r0, $r1
; KV3_1-NEXT:    fcompnhq.olt $r2 = $r0, $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    ord $r0 = $r0, $r2
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setord_fast:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.oge $r0 = $r0, $r1
; KV3_2-NEXT:    fcompnhq.olt $r2 = $r0, $r1
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    ord $r0 = $r0, $r2
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp fast ord <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setord_single_fast(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setord_single_fast:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setord_single_fast:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.oeq $r0 = $r0, $r0
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp fast ord <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

; Shouldn't this be just a true? Isn't fast unordered free?
define <4 x i16> @fcmp_setuno_fast(<4 x half> %a, <4 x half> %b) #0 {
; KV3_1-LABEL: fcmp_setuno_fast:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.uge $r0 = $r0, $r1
; KV3_1-NEXT:    fcompnhq.ult $r2 = $r0, $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    andd $r0 = $r0, $r2
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setuno_fast:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.uge $r0 = $r0, $r1
; KV3_2-NEXT:    fcompnhq.ult $r2 = $r0, $r1
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    andd $r0 = $r0, $r2
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp fast uno <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setuno_single_fast(<4 x half> %a) #0 {
; KV3_1-LABEL: fcmp_setuno_single_fast:
; KV3_1:       # %bb.0: # %entry
; KV3_1-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_1-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    andd $r0 = $r0, $r1
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    sllhqs $r0 = $r0, 15
; KV3_1-NEXT:    ;;
; KV3_1-NEXT:    srahqs $r0 = $r0, 15
; KV3_1-NEXT:    ret
; KV3_1-NEXT:    ;;
;
; KV3_2-LABEL: fcmp_setuno_single_fast:
; KV3_2:       # %bb.0: # %entry
; KV3_2-NEXT:    fcompnhq.uge $r0 = $r0, $r0
; KV3_2-NEXT:    fcompnhq.ult $r1 = $r0, $r0
; KV3_2-NEXT:    ;;
; KV3_2-NEXT:    andd $r0 = $r0, $r1
; KV3_2-NEXT:    ret
; KV3_2-NEXT:    ;;
entry:
  %0 = fcmp fast uno <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setueq_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setueq_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.oeq $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ueq <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setueq_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setueq_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ueq <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setugt_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setugt_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.olt $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ugt <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setugt_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setugt_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ugt <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setuge_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setuge_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.oge $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast uge <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setuge_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setuge_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast uge <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setult_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setult_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.olt $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ult <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setult_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setult_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ult <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setule_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setule_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.oge $r0 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ule <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setule_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setule_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast ule <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setune_fast(<4 x half> %a, <4 x half> %b) #0 {
; CHECK-LABEL: fcmp_setune_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fcompnhq.one $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast une <4 x half> %a, %b
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define <4 x i16> @fcmp_setune_single_fast(<4 x half> %a) #0 {
; CHECK-LABEL: fcmp_setune_single_fast:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = fcmp fast une <4 x half> %a, %a
  %1 = sext <4 x i1> %0 to <4 x i16>
  ret <4 x i16> %1
}

define float @fwidenmhw(<4 x half> %v) #0 {
; CHECK-LABEL: fwidenmhw:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fwidenmhw $r0 = $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %vecext = extractelement <4 x half> %v, i32 1
  %conv = fpext half %vecext to float
  ret float %conv
}

define <4 x half> @concat (<2 x half> %a, <2 x half> %b) #0 {
; CHECK-LABEL: concat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v = shufflevector <2 x half> %a, <2 x half> %b, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x half> %v
}

attributes #0 = { nounwind }
