; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mcpu=kv3-2 -O2 -o - %s | FileCheck %s --check-prefixes=CHECK
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <4 x i32> @test_ret_const() #0 {
; CHECK-LABEL: test_ret_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r0 = 0x200000001
; CHECK-NEXT:    make $r1 = 0x200000001
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  ret <4 x i32> <i32 1, i32 2, i32 1, i32 2>
}

define i32 @test_extract_0(<4 x i32> %a) #0 {
; CHECK-LABEL: test_extract_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %e = extractelement <4 x i32> %a, i32 0
  ret i32 %e
}

define i32 @test_extract_1(<4 x i32> %a) #0 {
; CHECK-LABEL: test_extract_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r0 = $r0, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %e = extractelement <4 x i32> %a, i32 1
  ret i32 %e
}

define <4 x i32> @test_fma(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c) #0 {
; CHECK-LABEL: test_fma:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maddwp $r1 = $r3, $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    maddwp $r0 = $r2, $r4
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %m = mul <4 x i32> %b, %c
  %ad = add <4 x i32> %a, %m
  ret <4 x i32> %ad
}

define <4 x i32> @test_fma_imm(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_fma_imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r5 = 0x200000001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    maddwp $r1 = $r3, $r5
; CHECK-NEXT:    copyd $r4 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    maddwp $r0 = $r2, $r4
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %m = mul <4 x i32> <i32 1, i32 2, i32 1, i32 2>, %b
  %ad = add <4 x i32> %a, %m
  ret <4 x i32> %ad
}


define i32 @test_extract_i(<4 x i32> %a, i64 %idx) #0 {
; CHECK-LABEL: test_extract_i:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andw $r2 = $r2, 1
; CHECK-NEXT:    srlw $r3 = $r2, 1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.odd $r3 ? $r0 = $r1
; CHECK-NEXT:    sllw $r1 = $r2, 5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %e = extractelement <4 x i32> %a, i64 %idx
  ret i32 %e
}

define <4 x i32> @test_add(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_add:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addwp $r0 = $r0, $r2
; CHECK-NEXT:    addwp $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = add <4 x i32> %a, %b
  ret <4 x i32> %r
}

define <4 x i32> @test_add_imm_0(<4 x i32> %a) #0 {
; CHECK-LABEL: test_add_imm_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r3 = 0x200000001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    addwp $r1 = $r1, $r3
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    addwp $r0 = $r0, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = add <4 x i32> <i32 1, i32 2, i32 1, i32 2>, %a
  ret <4 x i32> %r
}

define <4 x i32> @test_add_imm_1(<4 x i32> %a) #0 {
; CHECK-LABEL: test_add_imm_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r3 = 0x200000001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    addwp $r1 = $r1, $r3
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    addwp $r0 = $r0, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = add <4 x i32> %a, <i32 1, i32 2, i32 1, i32 2>
  ret <4 x i32> %r
}

define <4 x i32> @test_sub(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_sub:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbfwp $r0 = $r2, $r0
; CHECK-NEXT:    sbfwp $r1 = $r3, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sub <4 x i32> %a, %b
  ret <4 x i32> %r
}

define <4 x i32> @test_sub_imm(<4 x i32> %a) #0 {
; CHECK-LABEL: test_sub_imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r3 = 0x200000001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbfwp $r1 = $r3, $r1
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbfwp $r0 = $r2, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sub <4 x i32> %a, <i32 1, i32 2, i32 1, i32 2>
  ret <4 x i32> %r
}

define <4 x i32> @test_sub_fromimm(<4 x i32> %a) #0 {
; CHECK-LABEL: test_sub_fromimm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r3 = 0x200000001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbfwp $r1 = $r1, $r3
; CHECK-NEXT:    copyd $r2 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbfwp $r0 = $r0, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sub <4 x i32> <i32 1, i32 2, i32 1, i32 2>, %a
  ret <4 x i32> %r
}

define <4 x i32> @test_neg(<4 x i32> %a) #0 {
; CHECK-LABEL: test_neg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    make $r2 = 0
; CHECK-NEXT:    make $r3 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbfwp $r0 = $r0, $r2
; CHECK-NEXT:    sbfwp $r1 = $r1, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sub <4 x i32> <i32 0, i32 0, i32 0, i32 0>, %a
  ret <4 x i32> %r
}

define <4 x i32> @test_mul(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_mul:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mulwq $r0r1 = $r0r1, $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = mul <4 x i32> %a, %b
  ret <4 x i32> %r
}

define <4 x i32> @test_mul_2(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c) #0 {
; CHECK-LABEL: test_mul_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mulwq $r0r1 = $r0r1, $r2r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    mulwq $r0r1 = $r0r1, $r4r5
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = mul <4 x i32> %a, %b
  %r1 = mul <4 x i32> %r, %c
  ret <4 x i32> %r1
}

define <4 x i32> @test_div(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_div:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 48[$r12] = $r22
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 32[$r12] = $r20r21
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 16[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r3
; CHECK-NEXT:    copyd $r19 = $r2
; CHECK-NEXT:    copyd $r20 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srad $r0 = $r20, 32
; CHECK-NEXT:    srad $r1 = $r18, 32
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r0 = $r0
; CHECK-NEXT:    sxwd $r1 = $r1
; CHECK-NEXT:    call __divdi3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r0 = $r20
; CHECK-NEXT:    sxwd $r1 = $r18
; CHECK-NEXT:    copyd $r22 = $r0
; CHECK-NEXT:    call __divdi3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srad $r0 = $r21, 32
; CHECK-NEXT:    srad $r1 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r0 = $r0
; CHECK-NEXT:    sxwd $r1 = $r1
; CHECK-NEXT:    call __divdi3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r0 = $r21
; CHECK-NEXT:    sxwd $r1 = $r19
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call __divdi3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    insf $r18 = $r22, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 16[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r20r21 = 32[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r22 = 48[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sdiv <4 x i32> %a, %b
  ret <4 x i32> %r
}

define <4 x i32> @test_rem(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_rem:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -64
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 56[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 48[$r12] = $r22
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 32[$r12] = $r20r21
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 16[$r12] = $r18r19
; CHECK-NEXT:    copyd $r18 = $r3
; CHECK-NEXT:    copyd $r19 = $r2
; CHECK-NEXT:    copyd $r20 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srad $r0 = $r20, 32
; CHECK-NEXT:    srad $r1 = $r18, 32
; CHECK-NEXT:    copyd $r21 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r0 = $r0
; CHECK-NEXT:    sxwd $r1 = $r1
; CHECK-NEXT:    call __moddi3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r0 = $r20
; CHECK-NEXT:    sxwd $r1 = $r18
; CHECK-NEXT:    copyd $r22 = $r0
; CHECK-NEXT:    call __moddi3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srad $r0 = $r21, 32
; CHECK-NEXT:    srad $r1 = $r19, 32
; CHECK-NEXT:    copyd $r18 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r0 = $r0
; CHECK-NEXT:    sxwd $r1 = $r1
; CHECK-NEXT:    call __moddi3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r0 = $r21
; CHECK-NEXT:    sxwd $r1 = $r19
; CHECK-NEXT:    copyd $r20 = $r0
; CHECK-NEXT:    call __moddi3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r20, 63, 32
; CHECK-NEXT:    insf $r18 = $r22, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 16[$r12]
; CHECK-NEXT:    copyd $r1 = $r18
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r20r21 = 32[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r22 = 48[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 56[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 64
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = srem <4 x i32> %a, %b
  ret <4 x i32> %r
}

define void @test_ldst_v4i32(<4 x i32>* %a, <4 x i32>* %b) {
; CHECK-LABEL: test_ldst_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lq $r2r3 = 0[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r1] = $r2r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %t1 = load <4 x i32>, <4 x i32>* %a
  store <4 x i32> %t1, <4 x i32>* %b, align 16
  ret void
}

declare <4 x i32> @test_callee(<4 x i32> %a, <4 x i32> %b) #0

define <4 x i32> @test_call(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_call:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    call test_callee
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x i32> @test_callee(<4 x i32> %a, <4 x i32> %b)
  ret <4 x i32> %r
}

define <4 x i32> @test_call_flipped(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_call_flipped:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    copyd $r4 = $r1
; CHECK-NEXT:    copyd $r5 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    copyd $r2 = $r5
; CHECK-NEXT:    copyd $r3 = $r4
; CHECK-NEXT:    call test_callee
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x i32> @test_callee(<4 x i32> %b, <4 x i32> %a)
  ret <4 x i32> %r
}

define <4 x i32> @test_tailcall_flipped(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_tailcall_flipped:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r2
; CHECK-NEXT:    copyd $r1 = $r3
; CHECK-NEXT:    copyd $r4 = $r1
; CHECK-NEXT:    copyd $r5 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r2 = $r5
; CHECK-NEXT:    copyd $r3 = $r4
; CHECK-NEXT:    goto test_callee
; CHECK-NEXT:    ;;
  %r = tail call <4 x i32> @test_callee(<4 x i32> %b, <4 x i32> %a)
  ret <4 x i32> %r
}

define <4 x i32> @test_select(<4 x i32> %a, <4 x i32> %b, i1 zeroext %c) #0 {
; CHECK-LABEL: test_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmoved.even $r4 ? $r0 = $r2
; CHECK-NEXT:    cmoved.even $r4 ? $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = select i1 %c, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %r
}

define <4 x i32> @test_select_cc(<4 x i32> %a, <4 x i32> %b, <4 x i32> %c, <4 x i32> %d) #0 {
; CHECK-LABEL: test_select_cc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    compnwp.lt $r4 = $r4, $r6
; CHECK-NEXT:    compnwp.lt $r5 = $r5, $r7
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovewp.even $r4 ? $r0 = $r2
; CHECK-NEXT:    cmovewp.even $r5 ? $r1 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %cc = icmp slt <4 x i32> %c, %d
  %r = select <4 x i1> %cc, <4 x i32> %a, <4 x i32> %b
  ret <4 x i32> %r
}

define <4 x i64> @test_select_cc_f32_f32(<4 x i64> %a, <4 x i64> %b, <4 x i32> %c, <4 x i32> %d) #0 {
; CHECK-LABEL: test_select_cc_f32_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    compnwp.ltu $r8 = $r8, $r10
; CHECK-NEXT:    compnwp.ltu $r9 = $r9, $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r8 = $r8
; CHECK-NEXT:    sxwd $r9 = $r9
; CHECK-NEXT:    srld $r10 = $r9, 32
; CHECK-NEXT:    srld $r11 = $r8, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r10 = $r10
; CHECK-NEXT:    sxwd $r11 = $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.dnez $r8 ? $r4 = $r0
; CHECK-NEXT:    cmoved.dnez $r11 ? $r5 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r0 = $r4
; CHECK-NEXT:    copyd $r1 = $r5
; CHECK-NEXT:    cmoved.dnez $r9 ? $r6 = $r2
; CHECK-NEXT:    cmoved.dnez $r10 ? $r7 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r2 = $r6
; CHECK-NEXT:    copyd $r3 = $r7
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %cc = icmp ult <4 x i32> %c, %d
  %r = select <4 x i1> %cc, <4 x i64> %a, <4 x i64> %b
  ret <4 x i64> %r
}

define <4 x i1> @test_icmp_ule(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_icmp_ule:
; CHECK:       # %bb.0:
; CHECK-NEXT:    compnwp.leu $r0 = $r0, $r2
; CHECK-NEXT:    compnwp.leu $r1 = $r1, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = icmp ule <4 x i32> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_icmp_slt(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_icmp_slt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    compnwp.lt $r0 = $r0, $r2
; CHECK-NEXT:    compnwp.lt $r1 = $r1, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = icmp slt <4 x i32> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_icmp_ugt(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_icmp_ugt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    compnwp.gtu $r0 = $r0, $r2
; CHECK-NEXT:    compnwp.gtu $r1 = $r1, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = icmp ugt <4 x i32> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_icmp_uge(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_icmp_uge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    compnwp.geu $r0 = $r0, $r2
; CHECK-NEXT:    compnwp.geu $r1 = $r1, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = icmp uge <4 x i32> %a, %b
  ret <4 x i1> %r
}

define <4 x i1> @test_icmp_ult(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_icmp_ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    compnwp.ltu $r0 = $r0, $r2
; CHECK-NEXT:    compnwp.ltu $r1 = $r1, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = icmp ult <4 x i32> %a, %b
  ret <4 x i1> %r
}

define <4 x i64> @test_sext_2xi64(<4 x i32> %a) #0 {
; CHECK-LABEL: test_sext_2xi64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sxwd $r0 = $r0
; CHECK-NEXT:    srad $r2 = $r0, 32
; CHECK-NEXT:    srad $r3 = $r1, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxwd $r2 = $r1
; CHECK-NEXT:    sxwd $r5 = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r1 = $r5
; CHECK-NEXT:    sxwd $r3 = $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sext <4 x i32> %a to <4 x i64>
  ret <4 x i64> %r
}

declare <4 x i32> @llvm.abs.v4i32(<4 x i32>, i1) #0

define <4 x i32> @test_abs(<4 x i32> %a) #0 {
; CHECK-LABEL: test_abs:
; CHECK:       # %bb.0:
; CHECK-NEXT:    absw $r0 = $r0
; CHECK-NEXT:    absw $r1 = $r1
; CHECK-NEXT:    srad $r2 = $r1, 32
; CHECK-NEXT:    srad $r3 = $r0, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    absw $r2 = $r2
; CHECK-NEXT:    absw $r3 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r3, 63, 32
; CHECK-NEXT:    insf $r1 = $r2, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = call <4 x i32> @llvm.abs.v4i32(<4 x i32> %a, i1 false)
  ret <4 x i32> %r
}

define <4 x i32> @test_insertelement0(<4 x i32> %a, i32 %x) #0 {
; CHECK-LABEL: test_insertelement0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r2, 31, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x i32> %a, i32 %x, i64 0
  ret <4 x i32> %i
}

define <4 x i32> @test_insertelement1(<4 x i32> %a, i32 %x) #0 {
; CHECK-LABEL: test_insertelement1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r2, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x i32> %a, i32 %x, i64 1
  ret <4 x i32> %i
}

define <4 x i32> @test_insertelement2(<4 x i32> %a, i32 %x) #0 {
; CHECK-LABEL: test_insertelement2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r1 = $r2, 31, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x i32> %a, i32 %x, i64 2
  ret <4 x i32> %i
}

define <4 x i32> @test_insertelement3(<4 x i32> %a, i32 %x) #0 {
; CHECK-LABEL: test_insertelement3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r1 = $r2, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x i32> %a, i32 %x, i64 3
  ret <4 x i32> %i
}

define <4 x i32> @test_insertelement(<4 x i32> %a, i32 %x, i64 %p) #0 {
; CHECK-LABEL: test_insertelement:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r2 = $r2, 63, 31
; CHECK-NEXT:    insf $r3 = $r3, 63, 31
; CHECK-NEXT:    make $r4 = 0x300000002
; CHECK-NEXT:    make $r5 = 0x100000000
; CHECK-NEXT:    ;;
; CHECK-NEXT:    compnwp.eq $r3 = $r5, $r3
; CHECK-NEXT:    compnwp.eq $r4 = $r4, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovewp.eqz $r3 ? $r0 = $r2
; CHECK-NEXT:    cmovewp.eqz $r4 ? $r1 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %i = insertelement <4 x i32> %a, i32 %x, i64 %p
  ret <4 x i32> %i
}

define <4 x i8> @trunc_to_v4i8(<4 x i32> %a) {
; CHECK-LABEL: trunc_to_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sbmm8 $r0 = $r0, 0x1001
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x1001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = trunc <4 x i32> %a to <4 x i8>
  ret <4 x i8> %r
}

define <4 x i8> @trunc_to_v4i8_buildvector(i32 %arg1, i32 %arg2, i32 %arg3, i32 %arg4) {
; CHECK-LABEL: trunc_to_v4i8_buildvector:
; CHECK:       # %bb.0:
; CHECK-NEXT:    insf $r0 = $r1, 15, 8
; CHECK-NEXT:    insf $r2 = $r3, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r2, 31, 16
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v0 = insertelement <4 x i32> undef, i32 %arg1, i32 0
  %v1 = insertelement <4 x i32> %v0, i32 %arg2, i32 1
  %v2 = insertelement <4 x i32> %v1, i32 %arg3, i32 2
  %v3 = insertelement <4 x i32> %v2, i32 %arg4, i32 3
  %conv = trunc <4 x i32> %v3 to <4 x i8>
  ret <4 x i8> %conv
}

define <4 x i32> @concat(<2 x i32> %a, <2 x i32> %b){
; CHECK-LABEL: concat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v = shufflevector <2 x i32> %a, <2 x i32> %b, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %v
}

define <4 x i32> @revconcat(<2 x i32> %b, <2 x i32> %a){
; CHECK-LABEL: revconcat:
; CHECK:       # %bb.0:
; CHECK-NEXT:    copyd $r0 = $r1
; CHECK-NEXT:    copyd $r2 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r1 = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v = shufflevector <2 x i32> %a, <2 x i32> %b, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x i32> %v
}

define void @bug() {
; CHECK-LABEL: bug:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:  .LBB40_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    insf $r3 = $r0, 31, 0
; CHECK-NEXT:    goto .LBB40_1
; CHECK-NEXT:    ;;
entry:
  br label %loop

loop:
  %0 = phi <4 x i32> [ %1, %loop ], [ undef, %entry ]
  %1 = insertelement <4 x i32> %0, i32 0, i64 2
  %2 = extractelement <4 x i32> %0, i32 3
  br label %loop
}

define <4 x i32> @MULHWQ(<4 x i16> %a, <4 x i16> %b) {
; CHECK-LABEL: MULHWQ:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mulhwq $r0r1 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = sext <4 x i16> %a to <4 x i32>
  %1 = sext <4 x i16> %b to <4 x i32>
  %mul = mul nsw <4 x i32> %1, %0
  ret <4 x i32> %mul
}

define <4 x i32> @MULSUHWQ(<4 x i16> %a, <4 x i16> %b) {
; CHECK-LABEL: MULSUHWQ:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mulsuhwq $r0r1 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = sext <4 x i16> %a to <4 x i32>
  %1 = zext <4 x i16> %b to <4 x i32>
  %mul = mul nsw <4 x i32> %1, %0
  ret <4 x i32> %mul
}

define <4 x i32> @MULUHWQ(<4 x i16> %a, <4 x i16> %b) {
; CHECK-LABEL: MULUHWQ:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    muluhwq $r0r1 = $r1, $r0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = zext <4 x i16> %a to <4 x i32>
  %1 = zext <4 x i16> %b to <4 x i32>
  %mul = mul nuw <4 x i32> %1, %0
  ret <4 x i32> %mul
}

define <4 x i32> @MADDHWQ(<4 x i32> %0, <4 x i16> %1, <4 x i16> %2) {
; CHECK-LABEL: MADDHWQ:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maddhwq $r0r1 = $r3, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = sext <4 x i16> %1 to <4 x i32>
  %5 = sext <4 x i16> %2 to <4 x i32>
  %6 = mul nsw <4 x i32> %5, %4
  %7 = add <4 x i32> %6, %0
  ret <4 x i32> %7
}

define <4 x i32> @MADDSUHWQ(<4 x i32> %0, <4 x i16> %1, <4 x i16> %2) {
; CHECK-LABEL: MADDSUHWQ:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maddsuhwq $r0r1 = $r2, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = sext <4 x i16> %1 to <4 x i32>
  %5 = zext <4 x i16> %2 to <4 x i32>
  %6 = mul nsw <4 x i32> %5, %4
  %7 = add <4 x i32> %6, %0
  ret <4 x i32> %7
}

define <4 x i32> @MADDUHWQ(<4 x i32> %0, <4 x i16> %1, <4 x i16> %2) {
; CHECK-LABEL: MADDUHWQ:
; CHECK:       # %bb.0:
; CHECK-NEXT:    madduhwq $r0r1 = $r3, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = zext <4 x i16> %1 to <4 x i32>
  %5 = zext <4 x i16> %2 to <4 x i32>
  %6 = mul nuw <4 x i32> %5, %4
  %7 = add <4 x i32> %6, %0
  ret <4 x i32> %7
}

define <3 x i32> @MADDSUHWQ_v3(<3 x i32> %0, <3 x i16> %1, <3 x i16> %2) {
; CHECK-LABEL: MADDSUHWQ_v3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maddsuhwq $r0r1 = $r2, $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r0, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = sext <3 x i16> %1 to <3 x i32>
  %5 = zext <3 x i16> %2 to <3 x i32>
  %6 = mul nsw <3 x i32> %5, %4
  %7 = add <3 x i32> %6, %0
  ret <3 x i32> %7
}


define <4 x i32> @MSBFHWQ(<4 x i32> %0, <4 x i16> %1, <4 x i16> %2) {
; CHECK-LABEL: MSBFHWQ:
; CHECK:       # %bb.0:
; CHECK-NEXT:    msbfhwq $r0r1 = $r3, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = sext <4 x i16> %1 to <4 x i32>
  %5 = sext <4 x i16> %2 to <4 x i32>
  %6 = mul nsw <4 x i32> %5, %4
  %7 = sub <4 x i32> %0, %6
  ret <4 x i32> %7
}

define <4 x i32> @MSBFSUHWQ(<4 x i32> %0, <4 x i16> %1, <4 x i16> %2) {
; CHECK-LABEL: MSBFSUHWQ:
; CHECK:       # %bb.0:
; CHECK-NEXT:    msbfsuhwq $r0r1 = $r2, $r3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = sext <4 x i16> %1 to <4 x i32>
  %5 = zext <4 x i16> %2 to <4 x i32>
  %6 = mul nsw <4 x i32> %5, %4
  %7 = sub <4 x i32> %0, %6
  ret <4 x i32> %7
}

define <4 x i32> @MSBFUHWQ(<4 x i32> %0, <4 x i16> %1, <4 x i16> %2) {
; CHECK-LABEL: MSBFUHWQ:
; CHECK:       # %bb.0:
; CHECK-NEXT:    msbfuhwq $r0r1 = $r3, $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %4 = zext <4 x i16> %1 to <4 x i32>
  %5 = zext <4 x i16> %2 to <4 x i32>
  %6 = mul nuw <4 x i32> %5, %4
  %7 = sub <4 x i32> %0, %6
  ret <4 x i32> %7
}

attributes #0 = { nounwind }

define <4 x i32> @test_div_4(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_div_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r2 = $r0, 32
; CHECK-NEXT:    srad $r3 = $r1, 32
; CHECK-NEXT:    sraw $r4 = $r0, 31
; CHECK-NEXT:    sraw $r5 = $r1, 31
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sraw $r2 = $r2, 31
; CHECK-NEXT:    sraw $r3 = $r3, 31
; CHECK-NEXT:    srlw $r4 = $r4, 30
; CHECK-NEXT:    srlw $r5 = $r5, 30
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srlw $r2 = $r2, 30
; CHECK-NEXT:    srlw $r3 = $r3, 30
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r4 = $r2, 63, 32
; CHECK-NEXT:    insf $r5 = $r3, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    addwp $r0 = $r0, $r4
; CHECK-NEXT:    addwp $r1 = $r1, $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sraw $r0 = $r0, 2
; CHECK-NEXT:    sraw $r1 = $r1, 2
; CHECK-NEXT:    srld $r2 = $r1, 32
; CHECK-NEXT:    srld $r3 = $r0, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sraw $r2 = $r2, 2
; CHECK-NEXT:    sraw $r3 = $r3, 2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r3, 63, 32
; CHECK-NEXT:    insf $r1 = $r2, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sdiv <4 x i32> %a, <i32 4, i32 4, i32 4, i32 4>
  ret <4 x i32> %r
}

define <4 x i32> @test_div_32(<4 x i32> %a, <4 x i32> %b) #0 {
; CHECK-LABEL: test_div_32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    srad $r2 = $r0, 32
; CHECK-NEXT:    srad $r3 = $r1, 32
; CHECK-NEXT:    sraw $r4 = $r0, 31
; CHECK-NEXT:    sraw $r5 = $r1, 31
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sraw $r2 = $r2, 31
; CHECK-NEXT:    sraw $r3 = $r3, 31
; CHECK-NEXT:    srlw $r4 = $r4, 27
; CHECK-NEXT:    srlw $r5 = $r5, 27
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srlw $r2 = $r2, 27
; CHECK-NEXT:    srlw $r3 = $r3, 27
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r4 = $r2, 63, 32
; CHECK-NEXT:    insf $r5 = $r3, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    addwp $r0 = $r0, $r4
; CHECK-NEXT:    addwp $r1 = $r1, $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sraw $r0 = $r0, 5
; CHECK-NEXT:    sraw $r1 = $r1, 5
; CHECK-NEXT:    srld $r2 = $r1, 32
; CHECK-NEXT:    srld $r3 = $r0, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sraw $r2 = $r2, 5
; CHECK-NEXT:    sraw $r3 = $r3, 5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r3, 63, 32
; CHECK-NEXT:    insf $r1 = $r2, 63, 32
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %r = sdiv <4 x i32> %a, <i32 32, i32 32, i32 32, i32 32>
  ret <4 x i32> %r
}
