; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - %s -O2 | FileCheck %s --check-prefixes=CHECK,CV1
; RUN: llc -mcpu=kv3-2 -o - %s -O2 | FileCheck %s --check-prefixes=CHECK,CV2
; RUN: clang -O2 -c -o /dev/null %s
; RUN: clang -O2 -march=kv3-2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define <4 x i16> @ashiftR_imm(<4 x i16> %a){
; CHECK-LABEL: ashiftR_imm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srahqs $r0 = $r0, 3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %shr = ashr <4 x i16> %a, <i16 3, i16 3, i16 3, i16 3>
  ret <4 x i16> %shr
}

define <4 x i16> @lshiftR_imm(<4 x i16> %a){
; CHECK-LABEL: lshiftR_imm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srlhqs $r0 = $r0, 3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %shr = lshr <4 x i16> %a, <i16 3, i16 3, i16 3, i16 3>
  ret <4 x i16> %shr
}

define <4 x i16> @shiftL_imm(<4 x i16> %a){
; CHECK-LABEL: shiftL_imm:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sllhqs $r0 = $r0, 3
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %shl = shl <4 x i16> %a, <i16 3, i16 3, i16 3, i16 3>
  ret <4 x i16> %shl
}

define <4 x i16> @ashiftR(<4 x i16> %a, i32 %c){
; CHECK-LABEL: ashiftR:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srahqs $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = trunc i32 %c to i16
  %1 = insertelement <4 x i16> undef, i16 %0, i32 0
  %sh_prom = shufflevector <4 x i16> %1, <4 x i16> undef, <4 x i32> zeroinitializer
  %shr = ashr <4 x i16> %a, %sh_prom
  ret <4 x i16> %shr
}

define <4 x i16> @lshiftR(<4 x i16> %a, i32 %c){
; CHECK-LABEL: lshiftR:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    srlhqs $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = trunc i32 %c to i16
  %1 = insertelement <4 x i16> undef, i16 %0, i32 0
  %sh_prom = shufflevector <4 x i16> %1, <4 x i16> undef, <4 x i32> zeroinitializer
  %shr = lshr <4 x i16> %a, %sh_prom
  ret <4 x i16> %shr
}

define <4 x i16> @shiftL(<4 x i16> %a, i32 %c){
; CHECK-LABEL: shiftL:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sllhqs $r0 = $r0, $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %0 = trunc i32 %c to i16
  %1 = insertelement <4 x i16> undef, i16 %0, i32 0
  %sh_prom = shufflevector <4 x i16> %1, <4 x i16> undef, <4 x i32> zeroinitializer
  %shl = shl <4 x i16> %a, %sh_prom
  ret <4 x i16> %shl
}

; TODO: Improve when some shifts are the same value.
; Although LLVM eliminates the shifts, it does not
; eliminate the insf. Either custom-lower or create
; patterns for all 12 variations.
define <4 x i16> @ashiftR_imm_vec(<4 x i16> %a){
; CV1-LABEL: ashiftR_imm_vec:
; CV1:       # %bb.0: # %entry
; CV1-NEXT:    srahqs $r1 = $r0, 3
; CV1-NEXT:    srahqs $r2 = $r0, 4
; CV1-NEXT:    ;;
; CV1-NEXT:    srahqs $r0 = $r0, 2
; CV1-NEXT:    copyd $r3 = $r1
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r3 = $r2, 15, 0
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r1 = $r3, 31, 0
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r0 = $r1, 47, 0
; CV1-NEXT:    ret
; CV1-NEXT:    ;;
;
; CV2-LABEL: ashiftR_imm_vec:
; CV2:       # %bb.0: # %entry
; CV2-NEXT:    srahqs $r0 = $r0, 2
; CV2-NEXT:    srahqs $r1 = $r0, 3
; CV2-NEXT:    srahqs $r2 = $r0, 4
; CV2-NEXT:    ;;
; CV2-NEXT:    copyd $r3 = $r1
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r3 = $r2, 15, 0
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r1 = $r3, 31, 0
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r0 = $r1, 47, 0
; CV2-NEXT:    ret
; CV2-NEXT:    ;;
entry:
  %shr = ashr <4 x i16> %a, <i16 4, i16 3, i16 3, i16 2>
  ret <4 x i16> %shr
}

define <4 x i16> @lshiftR_imm_vec(<4 x i16> %a){
; CV1-LABEL: lshiftR_imm_vec:
; CV1:       # %bb.0: # %entry
; CV1-NEXT:    srlhqs $r1 = $r0, 2
; CV1-NEXT:    srlhqs $r2 = $r0, 1
; CV1-NEXT:    ;;
; CV1-NEXT:    srlhqs $r1 = $r0, 3
; CV1-NEXT:    insf $r2 = $r1, 15, 0
; CV1-NEXT:    ;;
; CV1-NEXT:    srlhqs $r0 = $r0, 4
; CV1-NEXT:    insf $r1 = $r2, 31, 0
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r0 = $r1, 47, 0
; CV1-NEXT:    ret
; CV1-NEXT:    ;;
;
; CV2-LABEL: lshiftR_imm_vec:
; CV2:       # %bb.0: # %entry
; CV2-NEXT:    srlhqs $r1 = $r0, 2
; CV2-NEXT:    srlhqs $r2 = $r0, 1
; CV2-NEXT:    ;;
; CV2-NEXT:    srlhqs $r0 = $r0, 4
; CV2-NEXT:    srlhqs $r1 = $r0, 3
; CV2-NEXT:    insf $r2 = $r1, 15, 0
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r1 = $r2, 31, 0
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r0 = $r1, 47, 0
; CV2-NEXT:    ret
; CV2-NEXT:    ;;
entry:
  %shr = lshr <4 x i16> %a, <i16 2, i16 1, i16 3, i16 4>
  ret <4 x i16> %shr
}

define <4 x i16> @shiftL_imm_vec(<4 x i16> %a){
; CHECK-LABEL: shiftL_imm_vec:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    sllhqs $r0 = $r0, 5
; CHECK-NEXT:    sllhqs $r1 = $r0, 3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyd $r2 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r2 = $r2, 15, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r2, 31, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r0 = $r1, 47, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
entry:
  %shl = shl <4 x i16> %a, <i16 3, i16 3, i16 3, i16 5>
  ret <4 x i16> %shl
}

define <4 x i16> @ashiftR_rr_vec(<4 x i16> %a, <4 x i16> %b){
; CV1-LABEL: ashiftR_rr_vec:
; CV1:       # %bb.0: # %entry
; CV1-NEXT:    extfz $r2 = $r1, 19, 16
; CV1-NEXT:    srahqs $r3 = $r0, $r1
; CV1-NEXT:    ;;
; CV1-NEXT:    srahqs $r2 = $r0, $r2
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r2 = $r3, 15, 0
; CV1-NEXT:    extfz $r3 = $r1, 35, 32
; CV1-NEXT:    ;;
; CV1-NEXT:    extfz $r1 = $r1, 51, 48
; CV1-NEXT:    srahqs $r3 = $r0, $r3
; CV1-NEXT:    ;;
; CV1-NEXT:    srahqs $r0 = $r0, $r1
; CV1-NEXT:    insf $r3 = $r2, 31, 0
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r0 = $r3, 47, 0
; CV1-NEXT:    ret
; CV1-NEXT:    ;;
;
; CV2-LABEL: ashiftR_rr_vec:
; CV2:       # %bb.0: # %entry
; CV2-NEXT:    extfz $r1 = $r1, 51, 48
; CV2-NEXT:    extfz $r2 = $r1, 19, 16
; CV2-NEXT:    srahqs $r3 = $r0, $r1
; CV2-NEXT:    extfz $r4 = $r1, 35, 32
; CV2-NEXT:    ;;
; CV2-NEXT:    srahqs $r2 = $r0, $r2
; CV2-NEXT:    ;;
; CV2-NEXT:    srahqs $r0 = $r0, $r1
; CV2-NEXT:    insf $r2 = $r3, 15, 0
; CV2-NEXT:    srahqs $r3 = $r0, $r4
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r3 = $r2, 31, 0
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r0 = $r3, 47, 0
; CV2-NEXT:    ret
; CV2-NEXT:    ;;
entry:
  %shr = ashr <4 x i16> %a, %b
  ret <4 x i16> %shr
}

define <4 x i16> @lshiftR_rr_vec(<4 x i16> %a, <4 x i16> %b){
; CV1-LABEL: lshiftR_rr_vec:
; CV1:       # %bb.0: # %entry
; CV1-NEXT:    extfz $r2 = $r1, 19, 16
; CV1-NEXT:    srlhqs $r3 = $r0, $r1
; CV1-NEXT:    ;;
; CV1-NEXT:    srlhqs $r2 = $r0, $r2
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r2 = $r3, 15, 0
; CV1-NEXT:    extfz $r3 = $r1, 35, 32
; CV1-NEXT:    ;;
; CV1-NEXT:    extfz $r1 = $r1, 51, 48
; CV1-NEXT:    srlhqs $r3 = $r0, $r3
; CV1-NEXT:    ;;
; CV1-NEXT:    srlhqs $r0 = $r0, $r1
; CV1-NEXT:    insf $r3 = $r2, 31, 0
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r0 = $r3, 47, 0
; CV1-NEXT:    ret
; CV1-NEXT:    ;;
;
; CV2-LABEL: lshiftR_rr_vec:
; CV2:       # %bb.0: # %entry
; CV2-NEXT:    extfz $r1 = $r1, 51, 48
; CV2-NEXT:    extfz $r2 = $r1, 19, 16
; CV2-NEXT:    srlhqs $r3 = $r0, $r1
; CV2-NEXT:    extfz $r4 = $r1, 35, 32
; CV2-NEXT:    ;;
; CV2-NEXT:    srlhqs $r2 = $r0, $r2
; CV2-NEXT:    ;;
; CV2-NEXT:    srlhqs $r0 = $r0, $r1
; CV2-NEXT:    insf $r2 = $r3, 15, 0
; CV2-NEXT:    srlhqs $r3 = $r0, $r4
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r3 = $r2, 31, 0
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r0 = $r3, 47, 0
; CV2-NEXT:    ret
; CV2-NEXT:    ;;
entry:
  %shr = lshr <4 x i16> %a, %b
  ret <4 x i16> %shr
}

define <4 x i16> @shiftL_rr_vec(<4 x i16> %a, <4 x i16> %b){
; CV1-LABEL: shiftL_rr_vec:
; CV1:       # %bb.0: # %entry
; CV1-NEXT:    extfz $r2 = $r1, 19, 16
; CV1-NEXT:    sllhqs $r3 = $r0, $r1
; CV1-NEXT:    ;;
; CV1-NEXT:    sllhqs $r2 = $r0, $r2
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r2 = $r3, 15, 0
; CV1-NEXT:    extfz $r3 = $r1, 35, 32
; CV1-NEXT:    ;;
; CV1-NEXT:    extfz $r1 = $r1, 51, 48
; CV1-NEXT:    sllhqs $r3 = $r0, $r3
; CV1-NEXT:    ;;
; CV1-NEXT:    sllhqs $r0 = $r0, $r1
; CV1-NEXT:    insf $r3 = $r2, 31, 0
; CV1-NEXT:    ;;
; CV1-NEXT:    insf $r0 = $r3, 47, 0
; CV1-NEXT:    ret
; CV1-NEXT:    ;;
;
; CV2-LABEL: shiftL_rr_vec:
; CV2:       # %bb.0: # %entry
; CV2-NEXT:    extfz $r1 = $r1, 51, 48
; CV2-NEXT:    extfz $r2 = $r1, 19, 16
; CV2-NEXT:    sllhqs $r3 = $r0, $r1
; CV2-NEXT:    extfz $r4 = $r1, 35, 32
; CV2-NEXT:    ;;
; CV2-NEXT:    sllhqs $r2 = $r0, $r2
; CV2-NEXT:    ;;
; CV2-NEXT:    sllhqs $r0 = $r0, $r1
; CV2-NEXT:    insf $r2 = $r3, 15, 0
; CV2-NEXT:    sllhqs $r3 = $r0, $r4
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r3 = $r2, 31, 0
; CV2-NEXT:    ;;
; CV2-NEXT:    insf $r0 = $r3, 47, 0
; CV2-NEXT:    ret
; CV2-NEXT:    ;;
entry:
  %shl = shl <4 x i16> %a, %b
  ret <4 x i16> %shl
}
