; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s | FileCheck %s
target triple = "kvx-kalray-cos"

define void @test_v1_select(<1 x i8> * %m, <1 x i8> * %n){
; CHECK-LABEL: test_v1_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbz $r2 = 0[$r0]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lbs $r1 = 0[$r1]
; CHECK-NEXT:    compw.eq $r3 = $r2, 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    compw.gt $r4 = $r1, -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andw $r3 = $r3, $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r3 ? $r1 = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sb 0[$r0] = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <1 x i8>, <1 x i8>* %m, align 8
  %v2 = load <1 x i8>, <1 x i8>* %n, align 8
  %c1 = icmp eq <1 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <1 x i8> %v2, <i8 -1>
  %c3 = and <1 x i1> %c1, %c2
  %v3 = select <1 x i1> %c3, <1 x i8> %v1, <1 x i8> %v2
  store <1 x i8> %v3, <1 x i8> * %m, align 8
  ret void
}

define void @test_v2_select(<2 x i8> * %m, <2 x i8> * %n){
; CHECK-LABEL: test_v2_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lhz $r2 = 0[$r0]
; CHECK-NEXT:    make $r3 = 0
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lhz $r1 = 0[$r1]
; CHECK-NEXT:    sbmm8 $r2 = $r2, 0x20001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxlbhq $r4 = $r1
; CHECK-NEXT:    compnhq.eq $r3 = $r2, $r3
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x20001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    compnhq.gt $r4 = $r4, $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andw $r3 = $r3, $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andw $r3 = $r3, 0xff00ff
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovehq.even $r3 ? $r2 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r1 = $r2, 0x401
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sh 0[$r0] = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <2 x i8>, <2 x i8>* %m, align 8
  %v2 = load <2 x i8>, <2 x i8>* %n, align 8
  %c1 = icmp eq <2 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <2 x i8> %v2, <i8 -1, i8 -1>
  %c3 = and <2 x i1> %c1, %c2
  %v3 = select <2 x i1> %c3, <2 x i8> %v1, <2 x i8> %v2
  store <2 x i8> %v3, <2 x i8> * %m, align 8
  ret void
}

define void @test_v3_select(<3 x i8> * %m, <3 x i8> * %n){
; CHECK-LABEL: test_v3_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lwz $r2 = 0[$r0]
; CHECK-NEXT:    make $r3 = 0
; CHECK-NEXT:    make $r5 = 0xffffffffffff
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lwz $r1 = 0[$r1]
; CHECK-NEXT:    sbmm8 $r2 = $r2, 0x8000400020001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxlbhq $r4 = $r1
; CHECK-NEXT:    compnhq.eq $r3 = $r2, $r3
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x8000400020001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    compnhq.gt $r4 = $r4, $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r3 = $r3, $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r3 = $r3, 0xff00ff00ff00ff
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovehq.even $r3 ? $r2 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r1 = $r2, 0x40100401
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r2 = $r1, 23, 16
; CHECK-NEXT:    zxhd $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sb 2[$r0] = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sh 0[$r0] = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <3 x i8>, <3 x i8>* %m, align 8
  %v2 = load <3 x i8>, <3 x i8>* %n, align 8
  %c1 = icmp eq <3 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <3 x i8> %v2, <i8 -1, i8 -1, i8 -1>
  %c3 = and <3 x i1> %c1, %c2
  %v3 = select <3 x i1> %c3, <3 x i8> %v1, <3 x i8> %v2
  store <3 x i8> %v3, <3 x i8> * %m, align 8
  ret void
}

define void @test_v4_select(<4 x i8> * %m, <4 x i8> * %n){
; CHECK-LABEL: test_v4_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lwz $r2 = 0[$r0]
; CHECK-NEXT:    make $r3 = 0
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lwz $r1 = 0[$r1]
; CHECK-NEXT:    sbmm8 $r2 = $r2, 0x8000400020001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxlbhq $r4 = $r1
; CHECK-NEXT:    compnhq.eq $r3 = $r2, $r3
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x8000400020001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    compnhq.gt $r4 = $r4, $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r3 = $r3, $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r3 = $r3, 0xff00ff00ff00ff
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovehq.even $r3 ? $r2 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r1 = $r2, 0x40100401
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sw 0[$r0] = $r1
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <4 x i8>, <4 x i8>* %m, align 8
  %v2 = load <4 x i8>, <4 x i8>* %n, align 8
  %c1 = icmp eq <4 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <4 x i8> %v2, <i8 -1, i8 -1, i8 -1, i8 -1>
  %c3 = and <4 x i1> %c1, %c2
  %v3 = select <4 x i1> %c3, <4 x i8> %v1, <4 x i8> %v2
  store <4 x i8> %v3, <4 x i8> * %m, align 8
  ret void
}

define void @test_v8_select(<8 x i8> * %m, <8 x i8> * %n){
; CHECK-LABEL: test_v8_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ld $r1 = 0[$r1]
; CHECK-NEXT:    make $r4 = 0
; CHECK-NEXT:    make $r6 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r2 = 0[$r0]
; CHECK-NEXT:    sxmbhq $r5 = $r1
; CHECK-NEXT:    sxlbhq $r7 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r3 = $r2, 0x80004000200010
; CHECK-NEXT:    sbmm8 $r2 = $r2, 0x8000400020001
; CHECK-NEXT:    compnhq.gt $r5 = $r5, $r6
; CHECK-NEXT:    compnhq.gt $r6 = $r7, $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    compnhq.eq $r8 = $r3, $r4
; CHECK-NEXT:    compnhq.eq $r4 = $r2, $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r4 = $r4, $r6
; CHECK-NEXT:    andd $r5 = $r8, $r5
; CHECK-NEXT:    sbmm8 $r6 = $r1, 0x80004000200010
; CHECK-NEXT:    sbmm8 $r1 = $r1, 0x8000400020001
; CHECK-NEXT:    ;;
; CHECK-NEXT:    andd $r5 = $r5, 0xff00ff00ff00ff
; CHECK-NEXT:    andd $r4 = $r4, 0xff00ff00ff00ff
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmovehq.even $r4 ? $r2 = $r1
; CHECK-NEXT:    cmovehq.even $r5 ? $r3 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sbmm8 $r1 = $r3, 0x40100401
; CHECK-NEXT:    sbmm8 $r2 = $r2, 0x40100401
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r2 = $r1, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 0[$r0] = $r2
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <8 x i8>, <8 x i8>* %m, align 8
  %v2 = load <8 x i8>, <8 x i8>* %n, align 8
  %c1 = icmp eq <8 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <8 x i8> %v2, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %c3 = and <8 x i1> %c1, %c2
  %v3 = select <8 x i1> %c3, <8 x i8> %v1, <8 x i8> %v2
  store <8 x i8> %v3, <8 x i8> * %m, align 8
  ret void
}

define void @test_v16_select(<16 x i8> * %m, <16 x i8> * %n){
; CHECK-LABEL: test_v16_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lq $r34r35 = 0[$r0]
; CHECK-NEXT:    make $r43 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r3 = $r35, 56
; CHECK-NEXT:    extfz $r2 = $r35, 55, 48
; CHECK-NEXT:    extfz $r6 = $r35, 47, 40
; CHECK-NEXT:    srlw $r10 = $r35, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r4 = $r3
; CHECK-NEXT:    zxbd $r5 = $r2
; CHECK-NEXT:    extfz $r8 = $r35, 39, 32
; CHECK-NEXT:    zxbd $r7 = $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r32 = $r4
; CHECK-NEXT:    make $r4 = -1
; CHECK-NEXT:    zxbd $r9 = $r8
; CHECK-NEXT:    extfz $r15 = $r35, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r32 ? $r4 = 0
; CHECK-NEXT:    copyw $r32 = $r5
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    zxbd $r33 = $r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r32 ? $r5 = 0
; CHECK-NEXT:    copyw $r32 = $r7
; CHECK-NEXT:    make $r7 = -1
; CHECK-NEXT:    zxbd $r11 = $r10
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r32 ? $r7 = 0
; CHECK-NEXT:    copyw $r32 = $r9
; CHECK-NEXT:    make $r9 = -1
; CHECK-NEXT:    insf $r5 = $r4, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r4 = -1
; CHECK-NEXT:    cmoved.wnez $r32 ? $r9 = 0
; CHECK-NEXT:    extfz $r17 = $r35, 15, 8
; CHECK-NEXT:    zxbd $r16 = $r15
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r11 ? $r4 = 0
; CHECK-NEXT:    make $r11 = -1
; CHECK-NEXT:    zxbd $r35 = $r33
; CHECK-NEXT:    insf $r9 = $r7, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r16 ? $r11 = 0
; CHECK-NEXT:    copyw $r16 = $r35
; CHECK-NEXT:    make $r35 = -1
; CHECK-NEXT:    zxbd $r32 = $r17
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r7 = -1
; CHECK-NEXT:    cmoved.wnez $r16 ? $r35 = 0
; CHECK-NEXT:    insf $r11 = $r4, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r32 ? $r7 = 0
; CHECK-NEXT:    insf $r9 = $r5, 31, 16
; CHECK-NEXT:    srld $r5 = $r34, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r35 = $r7, 15, 8
; CHECK-NEXT:    extfz $r4 = $r34, 55, 48
; CHECK-NEXT:    zxbd $r36 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r35 = $r11, 31, 16
; CHECK-NEXT:    extfz $r7 = $r34, 47, 40
; CHECK-NEXT:    zxbd $r37 = $r4
; CHECK-NEXT:    copyw $r42 = $r36
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r36 = -1
; CHECK-NEXT:    insf $r35 = $r9, 63, 32
; CHECK-NEXT:    extfz $r9 = $r34, 39, 32
; CHECK-NEXT:    srlw $r11 = $r34, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r37 ? $r43 = 0
; CHECK-NEXT:    cmoved.wnez $r42 ? $r36 = 0
; CHECK-NEXT:    zxbd $r38 = $r7
; CHECK-NEXT:    make $r37 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r39 = $r9
; CHECK-NEXT:    extfz $r16 = $r34, 23, 16
; CHECK-NEXT:    cmoved.wnez $r38 ? $r37 = 0
; CHECK-NEXT:    zxbd $r40 = $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r38 = $r39
; CHECK-NEXT:    make $r39 = -1
; CHECK-NEXT:    insf $r43 = $r36, 15, 8
; CHECK-NEXT:    make $r36 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r38 ? $r39 = 0
; CHECK-NEXT:    extfz $r32 = $r34, 15, 8
; CHECK-NEXT:    zxbd $r34 = $r34
; CHECK-NEXT:    zxbd $r41 = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r40 ? $r36 = 0
; CHECK-NEXT:    make $r40 = -1
; CHECK-NEXT:    insf $r39 = $r37, 15, 8
; CHECK-NEXT:    zxbd $r38 = $r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r41 ? $r40 = 0
; CHECK-NEXT:    make $r37 = -1
; CHECK-NEXT:    zxbd $r42 = $r34
; CHECK-NEXT:    make $r41 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r38 ? $r37 = 0
; CHECK-NEXT:    cmoved.wnez $r42 ? $r41 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r40 = $r36, 15, 8
; CHECK-NEXT:    insf $r41 = $r37, 15, 8
; CHECK-NEXT:    lq $r36r37 = 0[$r1]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r39 = $r43, 31, 16
; CHECK-NEXT:    insf $r41 = $r40, 31, 16
; CHECK-NEXT:    srld $r1 = $r37, 56
; CHECK-NEXT:    srlw $r46 = $r37, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r41 = $r39, 63, 32
; CHECK-NEXT:    extfz $r38 = $r37, 55, 48
; CHECK-NEXT:    srlw $r54 = $r36, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r39 = $r1
; CHECK-NEXT:    extfz $r42 = $r37, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r53 = $r39
; CHECK-NEXT:    make $r39 = -1
; CHECK-NEXT:    sxbd $r40 = $r38
; CHECK-NEXT:    extfz $r43 = $r37, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r53 ? $r39 = 0
; CHECK-NEXT:    copyw $r53 = $r40
; CHECK-NEXT:    make $r40 = -1
; CHECK-NEXT:    sxbd $r44 = $r42
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r53 ? $r40 = 0
; CHECK-NEXT:    copyw $r53 = $r44
; CHECK-NEXT:    make $r44 = -1
; CHECK-NEXT:    sxbd $r45 = $r43
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r53 ? $r44 = 0
; CHECK-NEXT:    copyw $r53 = $r45
; CHECK-NEXT:    make $r45 = -1
; CHECK-NEXT:    extfz $r50 = $r37, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r53 ? $r45 = 0
; CHECK-NEXT:    extfz $r48 = $r37, 23, 16
; CHECK-NEXT:    zxbd $r37 = $r37
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r40 = $r39, 15, 8
; CHECK-NEXT:    insf $r45 = $r44, 15, 8
; CHECK-NEXT:    make $r39 = -1
; CHECK-NEXT:    make $r44 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r47 = $r46
; CHECK-NEXT:    sxbd $r51 = $r50
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r47 ? $r39 = 0
; CHECK-NEXT:    cmoved.wltz $r51 ? $r44 = 0
; CHECK-NEXT:    make $r47 = -1
; CHECK-NEXT:    make $r51 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r49 = $r48
; CHECK-NEXT:    sxbd $r52 = $r37
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r49 ? $r47 = 0
; CHECK-NEXT:    cmoved.wltz $r52 ? $r51 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r47 = $r39, 15, 8
; CHECK-NEXT:    insf $r51 = $r44, 15, 8
; CHECK-NEXT:    srld $r39 = $r36, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r45 = $r40, 31, 16
; CHECK-NEXT:    insf $r51 = $r47, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r44 = $r39
; CHECK-NEXT:    extfz $r40 = $r36, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r51 = $r45, 63, 32
; CHECK-NEXT:    extfz $r47 = $r36, 47, 40
; CHECK-NEXT:    copyw $r61 = $r44
; CHECK-NEXT:    make $r44 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r45 = $r40
; CHECK-NEXT:    extfz $r49 = $r36, 39, 32
; CHECK-NEXT:    andd $r35 = $r35, $r51
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r61 ? $r44 = 0
; CHECK-NEXT:    copyw $r61 = $r45
; CHECK-NEXT:    make $r45 = -1
; CHECK-NEXT:    sxbd $r52 = $r47
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r61 ? $r45 = 0
; CHECK-NEXT:    copyw $r61 = $r52
; CHECK-NEXT:    make $r52 = -1
; CHECK-NEXT:    sxbd $r53 = $r49
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r61 ? $r52 = 0
; CHECK-NEXT:    copyw $r61 = $r53
; CHECK-NEXT:    make $r53 = -1
; CHECK-NEXT:    extfz $r58 = $r36, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r61 ? $r53 = 0
; CHECK-NEXT:    extfz $r56 = $r36, 23, 16
; CHECK-NEXT:    zxbd $r36 = $r36
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r45 = $r44, 15, 8
; CHECK-NEXT:    insf $r53 = $r52, 15, 8
; CHECK-NEXT:    make $r44 = -1
; CHECK-NEXT:    make $r52 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r55 = $r54
; CHECK-NEXT:    sxbd $r59 = $r58
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r55 ? $r44 = 0
; CHECK-NEXT:    cmoved.wltz $r59 ? $r52 = 0
; CHECK-NEXT:    make $r55 = -1
; CHECK-NEXT:    make $r59 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r57 = $r56
; CHECK-NEXT:    sxbd $r60 = $r36
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r57 ? $r55 = 0
; CHECK-NEXT:    cmoved.wltz $r60 ? $r59 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r44, 15, 8
; CHECK-NEXT:    insf $r59 = $r52, 15, 8
; CHECK-NEXT:    srld $r52 = $r35, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r53 = $r45, 31, 16
; CHECK-NEXT:    insf $r59 = $r55, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r44 = $r35, 55, 48
; CHECK-NEXT:    insf $r59 = $r53, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r52 ? $r1 = $r3
; CHECK-NEXT:    cmoved.wnez $r44 ? $r38 = $r2
; CHECK-NEXT:    srlw $r2 = $r35, 24
; CHECK-NEXT:    zxbd $r3 = $r35
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r38 = $r1, 15, 8
; CHECK-NEXT:    andd $r1 = $r41, $r59
; CHECK-NEXT:    cmoved.wnez $r2 ? $r46 = $r10
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r45 = $r35, 47, 40
; CHECK-NEXT:    extfz $r51 = $r35, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r53 = $r35, 23, 16
; CHECK-NEXT:    extfz $r2 = $r1, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r53 ? $r48 = $r15
; CHECK-NEXT:    extfz $r55 = $r35, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r45 ? $r42 = $r6
; CHECK-NEXT:    cmoved.wnez $r51 ? $r43 = $r8
; CHECK-NEXT:    srld $r8 = $r1, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r3 ? $r37 = $r33
; CHECK-NEXT:    extfz $r3 = $r1, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r6 = $r1, 39, 32
; CHECK-NEXT:    extfz $r10 = $r1, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r15 = $r1, 15, 8
; CHECK-NEXT:    cmoved.wnez $r2 ? $r40 = $r4
; CHECK-NEXT:    srlw $r2 = $r1, 24
; CHECK-NEXT:    zxbd $r1 = $r1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r55 ? $r50 = $r17
; CHECK-NEXT:    cmoved.wnez $r8 ? $r39 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r3 ? $r47 = $r7
; CHECK-NEXT:    cmoved.wnez $r6 ? $r49 = $r9
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r2 ? $r54 = $r11
; CHECK-NEXT:    cmoved.wnez $r10 ? $r56 = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r15 ? $r58 = $r32
; CHECK-NEXT:    cmoved.wnez $r1 ? $r36 = $r34
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r43 = $r42, 15, 8
; CHECK-NEXT:    insf $r48 = $r46, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r37 = $r50, 15, 8
; CHECK-NEXT:    insf $r40 = $r39, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r49 = $r47, 15, 8
; CHECK-NEXT:    insf $r56 = $r54, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r58, 15, 8
; CHECK-NEXT:    insf $r43 = $r38, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r37 = $r48, 31, 16
; CHECK-NEXT:    insf $r49 = $r40, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r56, 31, 16
; CHECK-NEXT:    insf $r37 = $r43, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r36 = $r49, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sq 0[$r0] = $r36r37
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <16 x i8>, <16 x i8>* %m, align 16
  %v2 = load <16 x i8>, <16 x i8>* %n, align 16
  %c1 = icmp eq <16 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <16 x i8> %v2, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %c3 = and <16 x i1> %c1, %c2
  %v3 = select <16 x i1> %c3, <16 x i8> %v1, <16 x i8> %v2
  store <16 x i8> %v3, <16 x i8> * %m, align 16
  ret void
}

define void @test_v32_select(<32 x i8> * %m, <32 x i8> * %n){
; CHECK-LABEL: test_v32_select:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addd $r12 = $r12, -288
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_def_cfa_offset 288
; CHECK-NEXT:    so 256[$r12] = $r28r29r30r31
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 28, -8
; CHECK-NEXT:    .cfi_offset 29, -16
; CHECK-NEXT:    .cfi_offset 30, -24
; CHECK-NEXT:    .cfi_offset 31, -32
; CHECK-NEXT:    so 224[$r12] = $r24r25r26r27
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 24, -40
; CHECK-NEXT:    .cfi_offset 25, -48
; CHECK-NEXT:    .cfi_offset 26, -56
; CHECK-NEXT:    .cfi_offset 27, -64
; CHECK-NEXT:    so 192[$r12] = $r20r21r22r23
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 20, -72
; CHECK-NEXT:    .cfi_offset 21, -80
; CHECK-NEXT:    .cfi_offset 22, -88
; CHECK-NEXT:    .cfi_offset 23, -96
; CHECK-NEXT:    sq 176[$r12] = $r18r19
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 18, -104
; CHECK-NEXT:    .cfi_offset 19, -112
; CHECK-NEXT:    sd 168[$r12] = $r0
; CHECK-NEXT:    make $r56 = -1
; CHECK-NEXT:    make $r57 = -1
; CHECK-NEXT:    make $r58 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r4r5r6r7 = 0[$r0]
; CHECK-NEXT:    make $r51 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r3 = $r5, 55, 48
; CHECK-NEXT:    srld $r0 = $r5, 56
; CHECK-NEXT:    extfz $r8 = $r5, 47, 40
; CHECK-NEXT:    srlw $r39 = $r5, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 96[$r12] = $r3
; CHECK-NEXT:    extfz $r9 = $r5, 39, 32
; CHECK-NEXT:    zxbd $r2 = $r3
; CHECK-NEXT:    zxbd $r3 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 88[$r12] = $r0
; CHECK-NEXT:    zxbd $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 64[$r12] = $r8
; CHECK-NEXT:    zxbd $r8 = $r9
; CHECK-NEXT:    zxbd $r49 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 48[$r12] = $r9
; CHECK-NEXT:    copyw $r10 = $r0
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    extfz $r42 = $r5, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r47 = $r5, 15, 8
; CHECK-NEXT:    zxbd $r5 = $r39
; CHECK-NEXT:    zxbd $r11 = $r49
; CHECK-NEXT:    cmoved.wnez $r10 ? $r0 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r10 = $r2
; CHECK-NEXT:    make $r2 = -1
; CHECK-NEXT:    zxbd $r9 = $r42
; CHECK-NEXT:    cmoved.wnez $r11 ? $r56 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srlw $r40 = $r4, 24
; CHECK-NEXT:    cmoved.wnez $r10 ? $r2 = 0
; CHECK-NEXT:    copyw $r10 = $r3
; CHECK-NEXT:    make $r3 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r43 = $r4, 23, 16
; CHECK-NEXT:    insf $r2 = $r0, 15, 8
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r10 ? $r3 = 0
; CHECK-NEXT:    copyw $r10 = $r8
; CHECK-NEXT:    make $r8 = -1
; CHECK-NEXT:    cmoved.wnez $r5 ? $r0 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    extfz $r48 = $r4, 15, 8
; CHECK-NEXT:    cmoved.wnez $r10 ? $r8 = 0
; CHECK-NEXT:    zxbd $r10 = $r47
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r9 ? $r5 = 0
; CHECK-NEXT:    zxbd $r50 = $r4
; CHECK-NEXT:    insf $r8 = $r3, 15, 8
; CHECK-NEXT:    make $r3 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r5 = $r0, 15, 8
; CHECK-NEXT:    srld $r0 = $r4, 56
; CHECK-NEXT:    cmoved.wnez $r10 ? $r3 = 0
; CHECK-NEXT:    zxbd $r10 = $r50
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r8 = $r2, 31, 16
; CHECK-NEXT:    zxbd $r46 = $r6
; CHECK-NEXT:    insf $r56 = $r3, 15, 8
; CHECK-NEXT:    zxbd $r45 = $r7
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r3 = $r4, 55, 48
; CHECK-NEXT:    insf $r56 = $r5, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 80[$r12] = $r3
; CHECK-NEXT:    extfz $r5 = $r4, 47, 40
; CHECK-NEXT:    zxbd $r2 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 72[$r12] = $r0
; CHECK-NEXT:    insf $r56 = $r8, 63, 32
; CHECK-NEXT:    zxbd $r0 = $r0
; CHECK-NEXT:    extfz $r8 = $r4, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 56[$r12] = $r5
; CHECK-NEXT:    zxbd $r3 = $r5
; CHECK-NEXT:    zxbd $r4 = $r40
; CHECK-NEXT:    cmoved.wnez $r10 ? $r57 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 40[$r12] = $r8
; CHECK-NEXT:    copyw $r9 = $r0
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    zxbd $r5 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r8 = $r43
; CHECK-NEXT:    cmoved.wnez $r9 ? $r0 = 0
; CHECK-NEXT:    copyw $r9 = $r2
; CHECK-NEXT:    make $r2 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r38 = $r6, 23, 16
; CHECK-NEXT:    extfz $r44 = $r6, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r9 ? $r2 = 0
; CHECK-NEXT:    copyw $r9 = $r3
; CHECK-NEXT:    make $r3 = -1
; CHECK-NEXT:    extfz $r41 = $r7, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r9 ? $r3 = 0
; CHECK-NEXT:    copyw $r9 = $r5
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    insf $r2 = $r0, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r9 ? $r5 = 0
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    zxbd $r9 = $r48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r5 = $r3, 15, 8
; CHECK-NEXT:    make $r3 = -1
; CHECK-NEXT:    cmoved.wnez $r4 ? $r0 = 0
; CHECK-NEXT:    make $r4 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r8 ? $r4 = 0
; CHECK-NEXT:    cmoved.wnez $r9 ? $r3 = 0
; CHECK-NEXT:    zxbd $r9 = $r46
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r4 = $r0, 15, 8
; CHECK-NEXT:    insf $r57 = $r3, 15, 8
; CHECK-NEXT:    srld $r0 = $r6, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r57 = $r4, 31, 16
; CHECK-NEXT:    insf $r5 = $r2, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r3 = $r6, 55, 48
; CHECK-NEXT:    insf $r57 = $r5, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r4 = $r6, 47, 40
; CHECK-NEXT:    extfz $r5 = $r6, 39, 32
; CHECK-NEXT:    sd 128[$r12] = $r3
; CHECK-NEXT:    zxbd $r2 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 120[$r12] = $r0
; CHECK-NEXT:    zxbd $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 112[$r12] = $r4
; CHECK-NEXT:    zxbd $r3 = $r4
; CHECK-NEXT:    zxbd $r4 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 104[$r12] = $r5
; CHECK-NEXT:    srlw $r5 = $r6, 24
; CHECK-NEXT:    zxbd $r6 = $r38
; CHECK-NEXT:    cmoved.wnez $r9 ? $r58 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 16[$r12] = $r5
; CHECK-NEXT:    copyw $r8 = $r0
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    zxbd $r5 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r8 ? $r0 = 0
; CHECK-NEXT:    copyw $r8 = $r2
; CHECK-NEXT:    make $r2 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r8 ? $r2 = 0
; CHECK-NEXT:    copyw $r8 = $r3
; CHECK-NEXT:    make $r3 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r8 ? $r3 = 0
; CHECK-NEXT:    copyw $r8 = $r4
; CHECK-NEXT:    make $r4 = -1
; CHECK-NEXT:    insf $r2 = $r0, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r8 ? $r4 = 0
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    zxbd $r8 = $r44
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r4 = $r3, 15, 8
; CHECK-NEXT:    make $r3 = -1
; CHECK-NEXT:    cmoved.wnez $r5 ? $r0 = 0
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r6 ? $r5 = 0
; CHECK-NEXT:    cmoved.wnez $r8 ? $r3 = 0
; CHECK-NEXT:    make $r8 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r5 = $r0, 15, 8
; CHECK-NEXT:    insf $r58 = $r3, 15, 8
; CHECK-NEXT:    srld $r0 = $r7, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r58 = $r5, 31, 16
; CHECK-NEXT:    insf $r4 = $r2, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r3 = $r7, 55, 48
; CHECK-NEXT:    insf $r58 = $r4, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r4 = $r7, 47, 40
; CHECK-NEXT:    extfz $r5 = $r7, 39, 32
; CHECK-NEXT:    sd 160[$r12] = $r3
; CHECK-NEXT:    zxbd $r2 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 152[$r12] = $r0
; CHECK-NEXT:    zxbd $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 144[$r12] = $r4
; CHECK-NEXT:    zxbd $r3 = $r4
; CHECK-NEXT:    zxbd $r4 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 136[$r12] = $r5
; CHECK-NEXT:    srlw $r5 = $r7, 24
; CHECK-NEXT:    extfz $r6 = $r7, 23, 16
; CHECK-NEXT:    cmoved.wnez $r2 ? $r8 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r2 = -1
; CHECK-NEXT:    sd 32[$r12] = $r5
; CHECK-NEXT:    zxbd $r5 = $r5
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sd 24[$r12] = $r6
; CHECK-NEXT:    copyw $r7 = $r0
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    cmoved.wnez $r3 ? $r2 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r3 = $r4
; CHECK-NEXT:    cmoved.wnez $r7 ? $r0 = 0
; CHECK-NEXT:    make $r4 = -1
; CHECK-NEXT:    zxbd $r7 = $r45
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r6 = $r6
; CHECK-NEXT:    cmoved.wnez $r3 ? $r4 = 0
; CHECK-NEXT:    insf $r8 = $r0, 15, 8
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    zxbd $r3 = $r41
; CHECK-NEXT:    insf $r4 = $r2, 15, 8
; CHECK-NEXT:    make $r2 = -1
; CHECK-NEXT:    cmoved.wnez $r5 ? $r0 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    cmoved.wnez $r3 ? $r2 = 0
; CHECK-NEXT:    cmoved.wnez $r7 ? $r51 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r6 ? $r5 = 0
; CHECK-NEXT:    make $r6 = -1
; CHECK-NEXT:    insf $r51 = $r2, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r5 = $r0, 15, 8
; CHECK-NEXT:    lo $r0r1r2r3 = 0[$r1]
; CHECK-NEXT:    insf $r4 = $r8, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r51 = $r5, 31, 16
; CHECK-NEXT:    srld $r22 = $r1, 56
; CHECK-NEXT:    extfz $r63 = $r1, 55, 48
; CHECK-NEXT:    srlw $r33 = $r1, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r51 = $r4, 63, 32
; CHECK-NEXT:    sxbd $r4 = $r22
; CHECK-NEXT:    zxbd $r53 = $r1
; CHECK-NEXT:    srld $r20 = $r0, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r26 = $r1, 47, 40
; CHECK-NEXT:    copyw $r59 = $r4
; CHECK-NEXT:    make $r4 = -1
; CHECK-NEXT:    sxbd $r5 = $r63
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r23 = $r1, 39, 32
; CHECK-NEXT:    cmoved.wltz $r59 ? $r4 = 0
; CHECK-NEXT:    copyw $r59 = $r5
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r7 = $r26
; CHECK-NEXT:    cmoved.wltz $r59 ? $r5 = 0
; CHECK-NEXT:    srlw $r32 = $r0, 24
; CHECK-NEXT:    srld $r36 = $r3, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r59 = $r7
; CHECK-NEXT:    make $r7 = -1
; CHECK-NEXT:    sxbd $r9 = $r23
; CHECK-NEXT:    extfz $r17 = $r1, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srlw $r30 = $r2, 24
; CHECK-NEXT:    cmoved.wltz $r59 ? $r7 = 0
; CHECK-NEXT:    copyw $r59 = $r9
; CHECK-NEXT:    make $r9 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r61 = $r1, 23, 16
; CHECK-NEXT:    cmoved.wltz $r59 ? $r9 = 0
; CHECK-NEXT:    srlw $r34 = $r3, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r1 = $r17
; CHECK-NEXT:    sxbd $r55 = $r53
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r9 = $r7, 15, 8
; CHECK-NEXT:    copyw $r7 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    cmoved.wltz $r55 ? $r6 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r1 = 0
; CHECK-NEXT:    insf $r5 = $r4, 15, 8
; CHECK-NEXT:    make $r4 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r6 = $r1, 15, 8
; CHECK-NEXT:    sxbd $r1 = $r20
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r60 = $r0, 55, 48
; CHECK-NEXT:    sxbd $r52 = $r33
; CHECK-NEXT:    copyw $r18 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r9 = $r5, 31, 16
; CHECK-NEXT:    extfz $r27 = $r0, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r5 = $r60
; CHECK-NEXT:    cmoved.wltz $r52 ? $r4 = 0
; CHECK-NEXT:    make $r52 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r54 = $r61
; CHECK-NEXT:    cmoved.wltz $r18 ? $r1 = 0
; CHECK-NEXT:    copyw $r18 = $r5
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r24 = $r0, 39, 32
; CHECK-NEXT:    sxbd $r7 = $r27
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r54 ? $r52 = 0
; CHECK-NEXT:    cmoved.wltz $r18 ? $r5 = 0
; CHECK-NEXT:    copyw $r18 = $r7
; CHECK-NEXT:    make $r7 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r54 = $r24
; CHECK-NEXT:    insf $r52 = $r4, 15, 8
; CHECK-NEXT:    make $r4 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r18 ? $r7 = 0
; CHECK-NEXT:    copyw $r18 = $r54
; CHECK-NEXT:    make $r54 = -1
; CHECK-NEXT:    extfz $r11 = $r0, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r6 = $r52, 31, 16
; CHECK-NEXT:    zxbd $r52 = $r0
; CHECK-NEXT:    cmoved.wltz $r18 ? $r54 = 0
; CHECK-NEXT:    srld $r18 = $r2, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r21 = $r0, 23, 16
; CHECK-NEXT:    sxbd $r0 = $r11
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r62 = $r52
; CHECK-NEXT:    insf $r5 = $r1, 15, 8
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r7, 15, 8
; CHECK-NEXT:    copyw $r7 = $r0
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    sxbd $r55 = $r32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r62 ? $r4 = 0
; CHECK-NEXT:    cmoved.wltz $r55 ? $r1 = 0
; CHECK-NEXT:    make $r55 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r59 = $r21
; CHECK-NEXT:    cmoved.wltz $r7 ? $r0 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r59 ? $r55 = 0
; CHECK-NEXT:    insf $r4 = $r0, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r0 = $r18
; CHECK-NEXT:    extfz $r59 = $r2, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r1, 15, 8
; CHECK-NEXT:    copyw $r15 = $r0
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    extfz $r25 = $r2, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r1 = $r59
; CHECK-NEXT:    cmoved.wltz $r15 ? $r0 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r15 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    extfz $r19 = $r2, 39, 32
; CHECK-NEXT:    sxbd $r7 = $r25
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r15 ? $r1 = 0
; CHECK-NEXT:    insf $r4 = $r55, 31, 16
; CHECK-NEXT:    copyw $r15 = $r7
; CHECK-NEXT:    make $r7 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r55 = $r19
; CHECK-NEXT:    insf $r54 = $r5, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r31 = $r2, 23, 16
; CHECK-NEXT:    cmoved.wltz $r15 ? $r7 = 0
; CHECK-NEXT:    copyw $r15 = $r55
; CHECK-NEXT:    make $r55 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r16 = $r2, 15, 8
; CHECK-NEXT:    cmoved.wltz $r15 ? $r55 = 0
; CHECK-NEXT:    make $r15 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r6 = $r9, 63, 32
; CHECK-NEXT:    insf $r4 = $r54, 63, 32
; CHECK-NEXT:    zxbd $r54 = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r28 = $r31
; CHECK-NEXT:    extfz $r10 = $r3, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r2 = $r16
; CHECK-NEXT:    sxbd $r9 = $r36
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r1 = $r0, 15, 8
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    insf $r55 = $r7, 15, 8
; CHECK-NEXT:    copyw $r7 = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r2 = -1
; CHECK-NEXT:    sxbd $r62 = $r30
; CHECK-NEXT:    cmoved.wltz $r28 ? $r15 = 0
; CHECK-NEXT:    copyw $r37 = $r9
; CHECK-NEXT:    ;;
; CHECK-NEXT:    make $r9 = -1
; CHECK-NEXT:    sxbd $r29 = $r54
; CHECK-NEXT:    make $r28 = -1
; CHECK-NEXT:    sxbd $r8 = $r10
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r35 = $r3, 47, 40
; CHECK-NEXT:    cmoved.wltz $r62 ? $r0 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r2 = 0
; CHECK-NEXT:    cmoved.wltz $r29 ? $r28 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r62 = $r3, 39, 32
; CHECK-NEXT:    cmoved.wltz $r37 ? $r9 = 0
; CHECK-NEXT:    copyw $r37 = $r8
; CHECK-NEXT:    make $r8 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r7 = $r35
; CHECK-NEXT:    cmoved.wltz $r37 ? $r8 = 0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r37 = $r7
; CHECK-NEXT:    make $r7 = -1
; CHECK-NEXT:    insf $r15 = $r0, 15, 8
; CHECK-NEXT:    insf $r28 = $r2, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r5 = $r62
; CHECK-NEXT:    insf $r28 = $r15, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r1, 31, 16
; CHECK-NEXT:    cmoved.wltz $r37 ? $r7 = 0
; CHECK-NEXT:    copyw $r37 = $r5
; CHECK-NEXT:    make $r5 = -1
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r28 = $r55, 63, 32
; CHECK-NEXT:    cmoved.wltz $r37 ? $r5 = 0
; CHECK-NEXT:    zxbd $r55 = $r3
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r29 = $r3, 23, 16
; CHECK-NEXT:    extfz $r15 = $r3, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    sxbd $r3 = $r34
; CHECK-NEXT:    insf $r5 = $r7, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    copyw $r7 = $r3
; CHECK-NEXT:    make $r3 = -1
; CHECK-NEXT:    sxbd $r0 = $r29
; CHECK-NEXT:    sxbd $r1 = $r15
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r3 = 0
; CHECK-NEXT:    copyw $r7 = $r0
; CHECK-NEXT:    make $r0 = -1
; CHECK-NEXT:    sxbd $r2 = $r55
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r0 = 0
; CHECK-NEXT:    copyw $r7 = $r1
; CHECK-NEXT:    make $r1 = -1
; CHECK-NEXT:    insf $r8 = $r9, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r1 = 0
; CHECK-NEXT:    copyw $r7 = $r2
; CHECK-NEXT:    make $r2 = -1
; CHECK-NEXT:    insf $r0 = $r3, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wltz $r7 ? $r2 = 0
; CHECK-NEXT:    ld $r37 = 88[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r9 = 96[$r12]
; CHECK-NEXT:    insf $r5 = $r8, 31, 16
; CHECK-NEXT:    insf $r2 = $r1, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r2 = $r0, 31, 16
; CHECK-NEXT:    andd $r0 = $r56, $r6
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r6 = $r0, 56
; CHECK-NEXT:    extfz $r1 = $r0, 55, 48
; CHECK-NEXT:    extfz $r3 = $r0, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r6 ? $r22 = $r37
; CHECK-NEXT:    ld $r6 = 64[$r12]
; CHECK-NEXT:    cmoved.wnez $r1 ? $r63 = $r9
; CHECK-NEXT:    srlw $r1 = $r0, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r2 = $r5, 63, 32
; CHECK-NEXT:    extfz $r7 = $r0, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r8 = $r0, 15, 8
; CHECK-NEXT:    extfz $r5 = $r0, 39, 32
; CHECK-NEXT:    zxbd $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r3 ? $r26 = $r6
; CHECK-NEXT:    ld $r3 = 48[$r12]
; CHECK-NEXT:    cmoved.wnez $r0 ? $r53 = $r49
; CHECK-NEXT:    andd $r0 = $r57, $r4
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r9 = 72[$r12]
; CHECK-NEXT:    cmoved.wnez $r8 ? $r17 = $r47
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r8 = 80[$r12]
; CHECK-NEXT:    cmoved.wnez $r1 ? $r33 = $r39
; CHECK-NEXT:    cmoved.wnez $r5 ? $r23 = $r3
; CHECK-NEXT:    srld $r5 = $r0, 56
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r0, 55, 48
; CHECK-NEXT:    cmoved.wnez $r5 ? $r20 = $r9
; CHECK-NEXT:    ld $r5 = 56[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r7 ? $r61 = $r42
; CHECK-NEXT:    cmoved.wnez $r1 ? $r60 = $r8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r3 = $r0, 47, 40
; CHECK-NEXT:    srlw $r1 = $r0, 24
; CHECK-NEXT:    extfz $r6 = $r0, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r7 = $r0, 15, 8
; CHECK-NEXT:    extfz $r4 = $r0, 39, 32
; CHECK-NEXT:    zxbd $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r3 ? $r27 = $r5
; CHECK-NEXT:    ld $r3 = 40[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r9 = 120[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r8 = 128[$r12]
; CHECK-NEXT:    cmoved.wnez $r0 ? $r52 = $r50
; CHECK-NEXT:    andd $r0 = $r58, $r28
; CHECK-NEXT:    cmoved.wnez $r1 ? $r32 = $r40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    srld $r5 = $r0, 56
; CHECK-NEXT:    cmoved.wnez $r4 ? $r24 = $r3
; CHECK-NEXT:    extfz $r3 = $r0, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r5 ? $r18 = $r9
; CHECK-NEXT:    ld $r5 = 112[$r12]
; CHECK-NEXT:    extfz $r1 = $r0, 55, 48
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r4 = $r0, 39, 32
; CHECK-NEXT:    cmoved.wnez $r6 ? $r21 = $r43
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r3 ? $r25 = $r5
; CHECK-NEXT:    ld $r3 = 104[$r12]
; CHECK-NEXT:    cmoved.wnez $r1 ? $r59 = $r8
; CHECK-NEXT:    srlw $r1 = $r0, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r7 ? $r11 = $r48
; CHECK-NEXT:    extfz $r6 = $r0, 23, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r7 = $r0, 15, 8
; CHECK-NEXT:    zxbd $r0 = $r0
; CHECK-NEXT:    cmoved.wnez $r4 ? $r19 = $r3
; CHECK-NEXT:    ld $r4 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r8 = 152[$r12]
; CHECK-NEXT:    cmoved.wnez $r0 ? $r54 = $r46
; CHECK-NEXT:    andd $r0 = $r51, $r2
; CHECK-NEXT:    cmoved.wnez $r7 ? $r16 = $r44
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r7 = 160[$r12]
; CHECK-NEXT:    cmoved.wnez $r1 ? $r30 = $r4
; CHECK-NEXT:    srld $r4 = $r0, 56
; CHECK-NEXT:    extfz $r2 = $r0, 47, 40
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r4 ? $r36 = $r8
; CHECK-NEXT:    ld $r4 = 144[$r12]
; CHECK-NEXT:    extfz $r3 = $r0, 39, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r1 = $r0, 55, 48
; CHECK-NEXT:    cmoved.wnez $r6 ? $r31 = $r38
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r2 ? $r35 = $r4
; CHECK-NEXT:    ld $r2 = 136[$r12]
; CHECK-NEXT:    cmoved.wnez $r1 ? $r10 = $r7
; CHECK-NEXT:    srlw $r1 = $r0, 24
; CHECK-NEXT:    ;;
; CHECK-NEXT:    extfz $r6 = $r0, 15, 8
; CHECK-NEXT:    extfz $r5 = $r0, 23, 16
; CHECK-NEXT:    zxbd $r0 = $r0
; CHECK-NEXT:    ;;
; CHECK-NEXT:    cmoved.wnez $r3 ? $r62 = $r2
; CHECK-NEXT:    ld $r3 = 32[$r12]
; CHECK-NEXT:    cmoved.wnez $r6 ? $r15 = $r41
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r2 = 24[$r12]
; CHECK-NEXT:    cmoved.wnez $r0 ? $r55 = $r45
; CHECK-NEXT:    insf $r63 = $r22, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r0 = 168[$r12]
; CHECK-NEXT:    cmoved.wnez $r1 ? $r34 = $r3
; CHECK-NEXT:    cmoved.wnez $r5 ? $r29 = $r2
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r23 = $r26, 15, 8
; CHECK-NEXT:    insf $r61 = $r33, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r53 = $r17, 15, 8
; CHECK-NEXT:    insf $r60 = $r20, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r24 = $r27, 15, 8
; CHECK-NEXT:    insf $r21 = $r32, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r52 = $r11, 15, 8
; CHECK-NEXT:    insf $r59 = $r18, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r19 = $r25, 15, 8
; CHECK-NEXT:    insf $r31 = $r30, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r16, 15, 8
; CHECK-NEXT:    insf $r10 = $r36, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r62 = $r35, 15, 8
; CHECK-NEXT:    insf $r29 = $r34, 15, 8
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r15, 15, 8
; CHECK-NEXT:    insf $r23 = $r63, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r53 = $r61, 31, 16
; CHECK-NEXT:    insf $r24 = $r60, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r52 = $r21, 31, 16
; CHECK-NEXT:    insf $r19 = $r59, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r54 = $r31, 31, 16
; CHECK-NEXT:    insf $r62 = $r10, 31, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r29, 31, 16
; CHECK-NEXT:    insf $r53 = $r23, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r52 = $r24, 63, 32
; CHECK-NEXT:    insf $r54 = $r19, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    insf $r55 = $r62, 63, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    so 0[$r0] = $r52r53r54r55
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lq $r18r19 = 176[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r20r21r22r23 = 192[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r24r25r26r27 = 224[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    lo $r28r29r30r31 = 256[$r12]
; CHECK-NEXT:    addd $r12 = $r12, 288
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
  %v1 = load <32 x i8>, <32 x i8>* %m, align 32
  %v2 = load <32 x i8>, <32 x i8>* %n, align 32
  %c1 = icmp eq <32 x i8> %v1, zeroinitializer
  %c2 = icmp sgt <32 x i8> %v2, <i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1, i8 -1>
  %c3 = and <32 x i1> %c1, %c2
  %v3 = select <32 x i1> %c3, <32 x i8> %v1, <32 x i8> %v2
  store <32 x i8> %v3, <32 x i8> * %m, align 32
  ret void
}
