; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -o - %s | FileCheck %s
; RUN: clang -O2 -c -o /dev/null %s

target triple = "kvx-kalray-cos"

define void @f() local_unnamed_addr #0 !dbg !7 {
; CHECK-LABEL: f:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:    .file 1 "d" "cfi.c"
; CHECK-NEXT:    .loc 1 3 0 # cfi.c:3:0
; CHECK-NEXT:    .cfi_sections .debug_frame
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_register 67, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .loc 1 12 1 prologue_end # cfi.c:12:1
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 67, -8
; CHECK-NEXT:    sd 16[$r12] = $r14
; CHECK-NEXT:    addd $r14 = $r12, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_def_cfa 14, 16
; CHECK-NEXT:    .cfi_offset 14, -16
; CHECK-NEXT:    addd $r12 = $r14, -16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r14 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
; CHECK-NEXT:  .Ltmp0:
entry:
  ret void, !dbg !19
}

define void @g() local_unnamed_addr #0 !dbg !20 {
; CHECK-LABEL: g:
; CHECK:       .Lfunc_begin1:
; CHECK-NEXT:    .loc 1 14 0 # cfi.c:14:0
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_register 67, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .loc 1 22 1 prologue_end # cfi.c:22:1
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 67, -8
; CHECK-NEXT:    sd 16[$r12] = $r14
; CHECK-NEXT:    addd $r14 = $r12, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_def_cfa 14, 16
; CHECK-NEXT:    .cfi_offset 14, -16
; CHECK-NEXT:    addd $r12 = $r14, -16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r14 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
; CHECK-NEXT:  .Ltmp1:
entry:
  ret void, !dbg !27
}

define i8 @h() local_unnamed_addr #0 !dbg !28 {
; CHECK-LABEL: h:
; CHECK:       .Lfunc_begin2:
; CHECK-NEXT:    .loc 1 24 0 # cfi.c:24:0
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:  # %bb.0: # %entry
; CHECK-NEXT:    make $r0 = 236
; CHECK-NEXT:    addd $r12 = $r12, -32
; CHECK-NEXT:    get $r16 = $ra
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_register 67, 16
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .loc 1 0 0 is_stmt 0 # cfi.c:0:0
; CHECK-NEXT:    sd 24[$r12] = $r16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_offset 67, -8
; CHECK-NEXT:    sd 16[$r12] = $r14
; CHECK-NEXT:    addd $r14 = $r12, 16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_def_cfa 14, 16
; CHECK-NEXT:    .cfi_offset 14, -16
; CHECK-NEXT:  .Ltmp2:
; CHECK-NEXT:    #DEBUG_VALUE: h:a <- [DW_OP_LLVM_fragment 0 8] -1
; CHECK-NEXT:    #DEBUG_VALUE: h:a <- [DW_OP_LLVM_fragment 8 8] -2
; CHECK-NEXT:    #DEBUG_VALUE: h:a <- [DW_OP_LLVM_fragment 16 8] -3
; CHECK-NEXT:    #DEBUG_VALUE: h:a <- [DW_OP_LLVM_fragment 24 8] -4
; CHECK-NEXT:    #DEBUG_VALUE: h:b <- [DW_OP_LLVM_fragment 0 8] -1
; CHECK-NEXT:    #DEBUG_VALUE: h:b <- [DW_OP_LLVM_fragment 8 8] -2
; CHECK-NEXT:    #DEBUG_VALUE: h:b <- [DW_OP_LLVM_fragment 16 8] -3
; CHECK-NEXT:    #DEBUG_VALUE: h:b <- [DW_OP_LLVM_fragment 24 8] -4
; CHECK-NEXT:    .loc 1 33 3 prologue_end is_stmt 1 # cfi.c:33:3
; CHECK-NEXT:    addd $r12 = $r14, -16
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r14 = 16[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    ld $r16 = 24[$r12]
; CHECK-NEXT:    ;;
; CHECK-NEXT:    set $ra = $r16
; CHECK-NEXT:    addd $r12 = $r12, 32
; CHECK-NEXT:    ;;
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:    ret
; CHECK-NEXT:    ;;
; CHECK-NEXT:  .Ltmp3:
entry:
  call void @llvm.dbg.value(metadata i8 -1, metadata !32, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 8)), !dbg !37
  call void @llvm.dbg.value(metadata i8 -2, metadata !32, metadata !DIExpression(DW_OP_LLVM_fragment, 8, 8)), !dbg !37
  call void @llvm.dbg.value(metadata i8 -3, metadata !32, metadata !DIExpression(DW_OP_LLVM_fragment, 16, 8)), !dbg !37
  call void @llvm.dbg.value(metadata i8 -4, metadata !32, metadata !DIExpression(DW_OP_LLVM_fragment, 24, 8)), !dbg !37
  call void @llvm.dbg.value(metadata i8 -1, metadata !36, metadata !DIExpression(DW_OP_LLVM_fragment, 0, 8)), !dbg !37
  call void @llvm.dbg.value(metadata i8 -2, metadata !36, metadata !DIExpression(DW_OP_LLVM_fragment, 8, 8)), !dbg !37
  call void @llvm.dbg.value(metadata i8 -3, metadata !36, metadata !DIExpression(DW_OP_LLVM_fragment, 16, 8)), !dbg !37
  call void @llvm.dbg.value(metadata i8 -4, metadata !36, metadata !DIExpression(DW_OP_LLVM_fragment, 24, 8)), !dbg !37
  ret i8 -20, !dbg !38
}

declare void @llvm.dbg.value(metadata, metadata, metadata) #1

attributes #0 = { norecurse nounwind readnone "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "frame-pointer"="all" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "unsafe-fp-math"="false" "use-soft-float"="false" }
attributes #1 = { nounwind readnone speculatable willreturn }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3, !4, !5}
!llvm.ident = !{!6}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, producer: "Kalray clang version 10.0.1 (git:software/tools/llvm-project 413660a1a7a7a2ef431d0d906778c974f42d70d8)", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "cfi.c", directory: "d")
!2 = !{}
!3 = !{i32 7, !"Dwarf Version", i32 2}
!4 = !{i32 2, !"Debug Info Version", i32 3}
!5 = !{i32 1, !"wchar_size", i32 4}
!6 = !{!"Kalray clang version 10.0.1 (git:software/tools/llvm-project 413660a1a7a7a2ef431d0d906778c974f42d70d8)"}
!7 = distinct !DISubprogram(name: "f", scope: !8, file: !8, line: 3, type: !9, scopeLine: 3, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !11)
!8 = !DIFile(filename: "cfi.c", directory: "d")
!9 = !DISubroutineType(types: !10)
!10 = !{null}
!11 = !{!12, !14, !16, !17, !18}
!12 = !DILocalVariable(name: "a", scope: !7, file: !8, line: 4, type: !13)
!13 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!14 = !DILocalVariable(name: "b", scope: !7, file: !8, line: 5, type: !15)
!15 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!16 = !DILocalVariable(name: "c", scope: !7, file: !8, line: 6, type: !15)
!17 = !DILocalVariable(name: "d", scope: !7, file: !8, line: 7, type: !15)
!18 = !DILocalVariable(name: "e", scope: !7, file: !8, line: 8, type: !13)
!19 = !DILocation(line: 12, column: 1, scope: !7)
!20 = distinct !DISubprogram(name: "g", scope: !8, file: !8, line: 14, type: !9, scopeLine: 14, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !21)
!21 = !{!22, !23, !24, !25, !26}
!22 = !DILocalVariable(name: "a", scope: !20, file: !8, line: 15, type: !13)
!23 = !DILocalVariable(name: "b", scope: !20, file: !8, line: 16, type: !13)
!24 = !DILocalVariable(name: "c", scope: !20, file: !8, line: 17, type: !15)
!25 = !DILocalVariable(name: "d", scope: !20, file: !8, line: 18, type: !15)
!26 = !DILocalVariable(name: "e", scope: !20, file: !8, line: 19, type: !15)
!27 = !DILocation(line: 22, column: 1, scope: !20)
!28 = distinct !DISubprogram(name: "h", scope: !8, file: !8, line: 24, type: !29, scopeLine: 24, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !31)
!29 = !DISubroutineType(types: !30)
!30 = !{!13}
!31 = !{!32, !36}
!32 = !DILocalVariable(name: "a", scope: !28, file: !8, line: 25, type: !33)
!33 = !DICompositeType(tag: DW_TAG_array_type, baseType: !13, size: 32, elements: !34)
!34 = !{!35}
!35 = !DISubrange(count: 4)
!36 = !DILocalVariable(name: "b", scope: !28, file: !8, line: 26, type: !33)
!37 = !DILocation(line: 0, scope: !28)
!38 = !DILocation(line: 33, column: 3, scope: !28)
