// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-1 -S -O2 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -S -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @abdw_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.abd.i32(i32 [[A:%.*]], i32 [[B:%.*]], i32 0)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int abdw_rr_(int a, int b) { return __builtin_kvx_abdw(a, b, ""); }

// CHECK-LABEL: @abdw_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.abd.i32(i32 [[A:%.*]], i32 [[B:%.*]], i32 1)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int abdw_rr_s(int a, int b) { return __builtin_kvx_abdw(a, b, ".s"); }

// CHECK-LABEL: @abdw_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.abd.i32(i32 [[A:%.*]], i32 [[B:%.*]], i32 2)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int abdw_rr_u(int a, int b) { return __builtin_kvx_abdw(a, b, ".u"); }

// CHECK-LABEL: @abdw_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.abd.i32(i32 [[A:%.*]], i32 48879, i32 0)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int abdw_ri_(int a) { return __builtin_kvx_abdw(a, 0xbeef, ""); }

// CHECK-LABEL: @abdw_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.abd.i32(i32 [[A:%.*]], i32 48879, i32 1)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int abdw_ri_s(int a) { return __builtin_kvx_abdw(a, 0xbeef, ".s"); }

// CHECK-LABEL: @abdw_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.abd.i32(i32 [[A:%.*]], i32 48879, i32 2)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int abdw_ri_u(int a) { return __builtin_kvx_abdw(a, 0xbeef, ".u"); }

// CHECK-LABEL: @abdd_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[A:%.*]], i64 [[B:%.*]], i32 0)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long abdd_rr_(long a, long b) { return __builtin_kvx_abdd(a, b, ""); }

// CHECK-LABEL: @abdd_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[A:%.*]], i64 [[B:%.*]], i32 1)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long abdd_rr_s(long a, long b) { return __builtin_kvx_abdd(a, b, ".s"); }

// CHECK-LABEL: @abdd_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[A:%.*]], i64 [[B:%.*]], i32 2)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long abdd_rr_u(long a, long b) { return __builtin_kvx_abdd(a, b, ".u"); }

// CHECK-LABEL: @abdd_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[A:%.*]], i64 3735928559, i32 0)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long abdd_ri_(long a) { return __builtin_kvx_abdd(a, 0xdeadbeef, ""); }

// CHECK-LABEL: @abdd_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[A:%.*]], i64 3735928559, i32 1)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long abdd_ri_s(long a) { return __builtin_kvx_abdd(a, 0xdeadbeef, ".s"); }

// CHECK-LABEL: @abdd_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[A:%.*]], i64 3735928559, i32 2)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long abdd_ri_u(long a) { return __builtin_kvx_abdd(a, 0xdeadbeef, ".u"); }

// CHECK-LABEL: @abdd_ri_at_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[A:%.*]], i64 -2401053088876216593, i32 0)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long abdd_ri_at_(long a) { return __builtin_kvx_abdd(a, 0xdeadbeefdeadbeef, ""); }

// CHECK-LABEL: @abdd_ri_at_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[A:%.*]], i64 -2401053088876216593, i32 1)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long abdd_ri_at_s(long a) { return __builtin_kvx_abdd(a, 0xdeadbeefdeadbeef, ".s"); }

// CHECK-LABEL: @abdd_ri_at_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[A:%.*]], i64 -2401053088876216593, i32 2)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long abdd_ri_at_u(long a) { return __builtin_kvx_abdd(a, 0xdeadbeefdeadbeef, ".u"); }

// CHECK-LABEL: @abdbo_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[A:%.*]], <8 x i8> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 abdbo_rr_(v8i8 a, v8i8 b) { return __builtin_kvx_abdbo(a, b, ""); }

// CHECK-LABEL: @abdbo_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[A:%.*]], <8 x i8> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 abdbo_rr_s(v8i8 a, v8i8 b) { return __builtin_kvx_abdbo(a, b, ".s"); }

// CHECK-LABEL: @abdbo_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[A:%.*]], <8 x i8> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 abdbo_rr_u(v8i8 a, v8i8 b) { return __builtin_kvx_abdbo(a, b, ".u"); }

// CHECK-LABEL: @abdbo_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 0, i8 0, i8 0, i8 0>, i32 0)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 abdbo_ri_(v8i8 a) { v8i8 b = {1, 2, 3, 4, 0, 0, 0, 0}; return __builtin_kvx_abdbo(a, b, ""); }

// CHECK-LABEL: @abdbo_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 0, i8 0, i8 0, i8 0>, i32 1)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 abdbo_ri_s(v8i8 a) { v8i8 b = {1, 2, 3, 4, 0, 0, 0, 0}; return __builtin_kvx_abdbo(a, b, ".s"); }

// CHECK-LABEL: @abdbo_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 0, i8 0, i8 0, i8 0>, i32 2)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 abdbo_ri_u(v8i8 a) { v8i8 b = {1, 2, 3, 4, 0, 0, 0, 0}; return __builtin_kvx_abdbo(a, b, ".u"); }

// CHECK-LABEL: @abdbo_ri_at_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 0)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 abdbo_ri_at_(v8i8 a) { v8i8 b = {1, 2, 3, 4, 1, 2, 3, 4}; return __builtin_kvx_abdbo(a, b, ""); }

// CHECK-LABEL: @abdbo_ri_at_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 1)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 abdbo_ri_at_s(v8i8 a) { v8i8 b = {1, 2, 3, 4, 1, 2, 3, 4}; return __builtin_kvx_abdbo(a, b, ".s"); }

// CHECK-LABEL: @abdbo_ri_at_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 2)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 abdbo_ri_at_u(v8i8 a) { v8i8 b = {1, 2, 3, 4, 1, 2, 3, 4}; return __builtin_kvx_abdbo(a, b, ".u"); }

// CHECK-LABEL: @abdbp_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.abd.v2i8(<2 x i8> [[A:%.*]], <2 x i8> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 abdbp_rr_(v2i8 a, v2i8 b) { return __builtin_kvx_abdbp(a, b, ""); }

// CHECK-LABEL: @abdbp_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.abd.v2i8(<2 x i8> [[A:%.*]], <2 x i8> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 abdbp_rr_s(v2i8 a, v2i8 b) { return __builtin_kvx_abdbp(a, b, ".s"); }

// CHECK-LABEL: @abdbp_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.abd.v2i8(<2 x i8> [[A:%.*]], <2 x i8> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 abdbp_rr_u(v2i8 a, v2i8 b) { return __builtin_kvx_abdbp(a, b, ".u"); }

// CHECK-LABEL: @abdbp_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.abd.v2i8(<2 x i8> [[A:%.*]], <2 x i8> <i8 1, i8 2>, i32 0)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 abdbp_ri_(v2i8 a) { v2i8 b = {1, 2}; return __builtin_kvx_abdbp(a, b, ""); }

// CHECK-LABEL: @abdbp_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.abd.v2i8(<2 x i8> [[A:%.*]], <2 x i8> <i8 1, i8 2>, i32 1)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 abdbp_ri_s(v2i8 a) { v2i8 b = {1, 2}; return __builtin_kvx_abdbp(a, b, ".s"); }

// CHECK-LABEL: @abdbp_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.abd.v2i8(<2 x i8> [[A:%.*]], <2 x i8> <i8 1, i8 2>, i32 2)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 abdbp_ri_u(v2i8 a) { v2i8 b = {1, 2}; return __builtin_kvx_abdbp(a, b, ".u"); }

// CHECK-LABEL: @abdbq_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.abd.v4i8(<4 x i8> [[A:%.*]], <4 x i8> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 abdbq_rr_(v4i8 a, v4i8 b) { return __builtin_kvx_abdbq(a, b, ""); }

// CHECK-LABEL: @abdbq_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.abd.v4i8(<4 x i8> [[A:%.*]], <4 x i8> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 abdbq_rr_s(v4i8 a, v4i8 b) { return __builtin_kvx_abdbq(a, b, ".s"); }

// CHECK-LABEL: @abdbq_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.abd.v4i8(<4 x i8> [[A:%.*]], <4 x i8> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 abdbq_rr_u(v4i8 a, v4i8 b) { return __builtin_kvx_abdbq(a, b, ".u"); }

// CHECK-LABEL: @abdbq_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.abd.v4i8(<4 x i8> [[A:%.*]], <4 x i8> <i8 1, i8 2, i8 3, i8 4>, i32 0)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 abdbq_ri_(v4i8 a) { v4i8 b = {1, 2, 3, 4}; return __builtin_kvx_abdbq(a, b, ""); }

// CHECK-LABEL: @abdbq_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.abd.v4i8(<4 x i8> [[A:%.*]], <4 x i8> <i8 1, i8 2, i8 3, i8 4>, i32 1)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 abdbq_ri_s(v4i8 a) { v4i8 b = {1, 2, 3, 4}; return __builtin_kvx_abdbq(a, b, ".s"); }

// CHECK-LABEL: @abdbq_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.abd.v4i8(<4 x i8> [[A:%.*]], <4 x i8> <i8 1, i8 2, i8 3, i8 4>, i32 2)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 abdbq_ri_u(v4i8 a) { v4i8 b = {1, 2, 3, 4}; return __builtin_kvx_abdbq(a, b, ".u"); }

// CHECK-LABEL: @abdbv_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i8> [[B:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP6]], <8 x i8> [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP9]], <8 x i8> [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP11]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> [[TMP13]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP14]]
//
v32i8 abdbv_rr_(v32i8 a, v32i8 b) { return __builtin_kvx_abdbv(a, b, ""); }

// CHECK-LABEL: @abdbv_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i8> [[B:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP6]], <8 x i8> [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP9]], <8 x i8> [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP11]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> [[TMP13]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP14]]
//
v32i8 abdbv_rr_s(v32i8 a, v32i8 b) { return __builtin_kvx_abdbv(a, b, ".s"); }

// CHECK-LABEL: @abdbv_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i8> [[B:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP6]], <8 x i8> [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP9]], <8 x i8> [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP11]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> [[TMP13]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP14]]
//
v32i8 abdbv_rr_u(v32i8 a, v32i8 b) { return __builtin_kvx_abdbv(a, b, ".u"); }

// CHECK-LABEL: @abdbv_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP2]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP4]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP6]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32i8 abdbv_ri_(v32i8 a) { v32i8 b = {1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4}; return __builtin_kvx_abdbv(a, b, ""); }

// CHECK-LABEL: @abdbv_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP2]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP4]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP6]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32i8 abdbv_ri_s(v32i8 a) { v32i8 b = {1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4}; return __builtin_kvx_abdbv(a, b, ".s"); }

// CHECK-LABEL: @abdbv_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP2]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP4]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP6]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32i8 abdbv_ri_u(v32i8 a) { v32i8 b = {1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4}; return __builtin_kvx_abdbv(a, b, ".u"); }

// CHECK-LABEL: @abdbx_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[B:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[B]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP6]]
//
v16i8 abdbx_rr_(v16i8 a, v16i8 b) { return __builtin_kvx_abdbx(a, b, ""); }

// CHECK-LABEL: @abdbx_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[B:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[B]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP6]]
//
v16i8 abdbx_rr_s(v16i8 a, v16i8 b) { return __builtin_kvx_abdbx(a, b, ".s"); }

// CHECK-LABEL: @abdbx_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[B:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[B]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP6]]
//
v16i8 abdbx_rr_u(v16i8 a, v16i8 b) { return __builtin_kvx_abdbx(a, b, ".u"); }

// CHECK-LABEL: @abdbx_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP2]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16i8 abdbx_ri_(v16i8 a) { v16i8 b = {1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4}; return __builtin_kvx_abdbx(a, b, ""); }

// CHECK-LABEL: @abdbx_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP2]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16i8 abdbx_ri_s(v16i8 a) { v16i8 b = {1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4}; return __builtin_kvx_abdbx(a, b, ".s"); }

// CHECK-LABEL: @abdbx_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.abd.v8i8(<8 x i8> [[TMP2]], <8 x i8> <i8 1, i8 2, i8 3, i8 4, i8 1, i8 2, i8 3, i8 4>, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16i8 abdbx_ri_u(v16i8 a) { v16i8 b = {1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4}; return __builtin_kvx_abdbx(a, b, ".u"); }

// CHECK-LABEL: @abddp_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i64> [[B:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x i64> [[B]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP3]], i64 [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x i64> undef, i64 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x i64> [[TMP6]], i64 [[TMP5]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP7]]
//
v2i64 abddp_rr_(v2i64 a, v2i64 b) { return __builtin_kvx_abddp(a, b, ""); }

// CHECK-LABEL: @abddp_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i64> [[B:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x i64> [[B]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP3]], i64 [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x i64> undef, i64 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x i64> [[TMP6]], i64 [[TMP5]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP7]]
//
v2i64 abddp_rr_s(v2i64 a, v2i64 b) { return __builtin_kvx_abddp(a, b, ".s"); }

// CHECK-LABEL: @abddp_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x i64> [[B:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x i64> [[B]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP3]], i64 [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x i64> undef, i64 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x i64> [[TMP6]], i64 [[TMP5]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP7]]
//
v2i64 abddp_rr_u(v2i64 a, v2i64 b) { return __builtin_kvx_abddp(a, b, ".u"); }

// CHECK-LABEL: @abddp_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 1234, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP2]], i64 4321, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i64> [[TMP4]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP5]]
//
v2i64 abddp_ri_(v2i64 a) { v2i64 b = {1234, 4321}; return __builtin_kvx_abddp(a, b, ""); }

// CHECK-LABEL: @abddp_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 1234, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP2]], i64 4321, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i64> [[TMP4]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP5]]
//
v2i64 abddp_ri_s(v2i64 a) { v2i64 b = {1234, 4321}; return __builtin_kvx_abddp(a, b, ".s"); }

// CHECK-LABEL: @abddp_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 1234, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP2]], i64 4321, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i64> [[TMP4]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP5]]
//
v2i64 abddp_ri_u(v2i64 a) { v2i64 b = {1234, 4321}; return __builtin_kvx_abddp(a, b, ".u"); }

// CHECK-LABEL: @abddq_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x i64> [[B:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[B]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP3]], i64 [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[A]], i64 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x i64> [[B]], i64 2
// CHECK-NEXT:    [[TMP8:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP6]], i64 [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x i64> [[A]], i64 3
// CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x i64> [[B]], i64 3
// CHECK-NEXT:    [[TMP11:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP9]], i64 [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x i64> undef, i64 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP13:%.*]] = insertelement <4 x i64> [[TMP12]], i64 [[TMP5]], i64 1
// CHECK-NEXT:    [[TMP14:%.*]] = insertelement <4 x i64> [[TMP13]], i64 [[TMP8]], i64 2
// CHECK-NEXT:    [[TMP15:%.*]] = insertelement <4 x i64> [[TMP14]], i64 [[TMP11]], i64 3
// CHECK-NEXT:    ret <4 x i64> [[TMP15]]
//
v4i64 abddq_rr_(v4i64 a, v4i64 b) { return __builtin_kvx_abddq(a, b, ""); }

// CHECK-LABEL: @abddq_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x i64> [[B:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[B]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP3]], i64 [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[A]], i64 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x i64> [[B]], i64 2
// CHECK-NEXT:    [[TMP8:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP6]], i64 [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x i64> [[A]], i64 3
// CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x i64> [[B]], i64 3
// CHECK-NEXT:    [[TMP11:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP9]], i64 [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x i64> undef, i64 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP13:%.*]] = insertelement <4 x i64> [[TMP12]], i64 [[TMP5]], i64 1
// CHECK-NEXT:    [[TMP14:%.*]] = insertelement <4 x i64> [[TMP13]], i64 [[TMP8]], i64 2
// CHECK-NEXT:    [[TMP15:%.*]] = insertelement <4 x i64> [[TMP14]], i64 [[TMP11]], i64 3
// CHECK-NEXT:    ret <4 x i64> [[TMP15]]
//
v4i64 abddq_rr_s(v4i64 a, v4i64 b) { return __builtin_kvx_abddq(a, b, ".s"); }

// CHECK-LABEL: @abddq_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x i64> [[B:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[B]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP3]], i64 [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[A]], i64 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x i64> [[B]], i64 2
// CHECK-NEXT:    [[TMP8:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP6]], i64 [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x i64> [[A]], i64 3
// CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x i64> [[B]], i64 3
// CHECK-NEXT:    [[TMP11:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP9]], i64 [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x i64> undef, i64 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP13:%.*]] = insertelement <4 x i64> [[TMP12]], i64 [[TMP5]], i64 1
// CHECK-NEXT:    [[TMP14:%.*]] = insertelement <4 x i64> [[TMP13]], i64 [[TMP8]], i64 2
// CHECK-NEXT:    [[TMP15:%.*]] = insertelement <4 x i64> [[TMP14]], i64 [[TMP11]], i64 3
// CHECK-NEXT:    ret <4 x i64> [[TMP15]]
//
v4i64 abddq_rr_u(v4i64 a, v4i64 b) { return __builtin_kvx_abddq(a, b, ".u"); }

// CHECK-LABEL: @abddq_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 12, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP2]], i64 23, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[A]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP4]], i64 34, i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[A]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP6]], i64 45, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i64> [[TMP8]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i64> [[TMP9]], i64 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i64> [[TMP10]], i64 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i64> [[TMP11]]
//
v4i64 abddq_ri_(v4i64 a) { v4i64 b = {12, 23, 34, 45}; return __builtin_kvx_abddq(a, b, ""); }

// CHECK-LABEL: @abddq_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 12, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP2]], i64 23, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[A]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP4]], i64 34, i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[A]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP6]], i64 45, i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i64> [[TMP8]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i64> [[TMP9]], i64 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i64> [[TMP10]], i64 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i64> [[TMP11]]
//
v4i64 abddq_ri_s(v4i64 a) { v4i64 b = {12, 23, 34, 45}; return __builtin_kvx_abddq(a, b, ".s"); }

// CHECK-LABEL: @abddq_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[A:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP0]], i64 12, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i64> [[A]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP2]], i64 23, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[A]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP4]], i64 34, i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[A]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i64 @llvm.kvx.abd.i64(i64 [[TMP6]], i64 45, i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i64> [[TMP8]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i64> [[TMP9]], i64 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i64> [[TMP10]], i64 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i64> [[TMP11]]
//
v4i64 abddq_ri_u(v4i64 a) { v4i64 b = {12, 23, 34, 45}; return __builtin_kvx_abddq(a, b, ".u"); }

// CHECK-LABEL: @abdho_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[B:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[B]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP6]]
//
v8i16 abdho_rr_(v8i16 a, v8i16 b) { return __builtin_kvx_abdho(a, b, ""); }

// CHECK-LABEL: @abdho_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[B:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[B]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP6]]
//
v8i16 abdho_rr_s(v8i16 a, v8i16 b) { return __builtin_kvx_abdho(a, b, ".s"); }

// CHECK-LABEL: @abdho_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[B:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[B]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP6]]
//
v8i16 abdho_rr_u(v8i16 a, v8i16 b) { return __builtin_kvx_abdho(a, b, ".u"); }

// CHECK-LABEL: @abdho_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 2, i16 4, i16 2, i16 4>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP2]], <4 x i16> <i16 2, i16 2, i16 0, i16 0>, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
v8i16 abdho_ri_(v8i16 a) { v8i16 b = { 2, 4, 2, 4, 2, 2, 0, 0}; return __builtin_kvx_abdho(a, b, ""); }

// CHECK-LABEL: @abdho_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 2, i16 4, i16 2, i16 4>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP2]], <4 x i16> <i16 2, i16 2, i16 0, i16 0>, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
v8i16 abdho_ri_s(v8i16 a) { v8i16 b = { 2, 4, 2, 4, 2, 2, 0, 0}; return __builtin_kvx_abdho(a, b, ".s"); }

// CHECK-LABEL: @abdho_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 2, i16 4, i16 2, i16 4>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP2]], <4 x i16> <i16 2, i16 2, i16 0, i16 0>, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
v8i16 abdho_ri_u(v8i16 a) { v8i16 b = { 2, 4, 2, 4, 2, 2, 0, 0}; return __builtin_kvx_abdho(a, b, ".u"); }

// CHECK-LABEL: @abdhp_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.abd.v2i16(<2 x i16> [[A:%.*]], <2 x i16> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 abdhp_rr_(v2i16 a, v2i16 b) { return __builtin_kvx_abdhp(a, b, ""); }

// CHECK-LABEL: @abdhp_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.abd.v2i16(<2 x i16> [[A:%.*]], <2 x i16> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 abdhp_rr_s(v2i16 a, v2i16 b) { return __builtin_kvx_abdhp(a, b, ".s"); }

// CHECK-LABEL: @abdhp_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.abd.v2i16(<2 x i16> [[A:%.*]], <2 x i16> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 abdhp_rr_u(v2i16 a, v2i16 b) { return __builtin_kvx_abdhp(a, b, ".u"); }

// CHECK-LABEL: @abdhp_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.abd.v2i16(<2 x i16> [[A:%.*]], <2 x i16> <i16 32, i16 33>, i32 0)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 abdhp_ri_(v2i16 a) { v2i16 b = {32, 33}; return __builtin_kvx_abdhp(a, b, ""); }

// CHECK-LABEL: @abdhp_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.abd.v2i16(<2 x i16> [[A:%.*]], <2 x i16> <i16 32, i16 33>, i32 1)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 abdhp_ri_s(v2i16 a) { v2i16 b = {32, 33}; return __builtin_kvx_abdhp(a, b, ".s"); }

// CHECK-LABEL: @abdhp_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.abd.v2i16(<2 x i16> [[A:%.*]], <2 x i16> <i16 32, i16 33>, i32 2)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 abdhp_ri_u(v2i16 a) { v2i16 b = {32, 33}; return __builtin_kvx_abdhp(a, b, ".u"); }

// CHECK-LABEL: @abdhq_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[A:%.*]], <4 x i16> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 abdhq_rr_(v4i16 a, v4i16 b) { return __builtin_kvx_abdhq(a, b, ""); }

// CHECK-LABEL: @abdhq_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[A:%.*]], <4 x i16> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 abdhq_rr_s(v4i16 a, v4i16 b) { return __builtin_kvx_abdhq(a, b, ".s"); }

// CHECK-LABEL: @abdhq_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[A:%.*]], <4 x i16> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 abdhq_rr_u(v4i16 a, v4i16 b) { return __builtin_kvx_abdhq(a, b, ".u"); }

// CHECK-LABEL: @abdhq_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 1, i16 2, i16 0, i16 0>, i32 0)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 abdhq_ri_(v4i16 a) { v4i16 b = {1, 2, 0, 0}; return __builtin_kvx_abdhq(a, b, ""); }

// CHECK-LABEL: @abdhq_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 1, i16 2, i16 0, i16 0>, i32 1)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 abdhq_ri_s(v4i16 a) { v4i16 b = {1, 2, 0, 0}; return __builtin_kvx_abdhq(a, b, ".s"); }

// CHECK-LABEL: @abdhq_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 1, i16 2, i16 0, i16 0>, i32 2)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 abdhq_ri_u(v4i16 a) { v4i16 b = {1, 2, 0, 0}; return __builtin_kvx_abdhq(a, b, ".u"); }

// CHECK-LABEL: @abdhq_ri_at_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 1, i16 2, i16 1, i16 2>, i32 0)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 abdhq_ri_at_(v4i16 a) { v4i16 b = {1, 2, 1, 2}; return __builtin_kvx_abdhq(a, b, ""); }

// CHECK-LABEL: @abdhq_ri_at_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 1, i16 2, i16 1, i16 2>, i32 1)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 abdhq_ri_at_s(v4i16 a) { v4i16 b = {1, 2, 1, 2}; return __builtin_kvx_abdhq(a, b, ".s"); }

// CHECK-LABEL: @abdhq_ri_at_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 1, i16 2, i16 1, i16 2>, i32 2)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 abdhq_ri_at_u(v4i16 a) { v4i16 b = {1, 2, 1, 2}; return __builtin_kvx_abdhq(a, b, ".u"); }

// CHECK-LABEL: @abdhx_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i16> [[B:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP6]], <4 x i16> [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP9]], <4 x i16> [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i16> [[TMP12]], <8 x i16> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP14]]
//
v16i16 abdhx_rr_(v16i16 a, v16i16 b) { return __builtin_kvx_abdhx(a, b, ""); }

// CHECK-LABEL: @abdhx_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i16> [[B:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP6]], <4 x i16> [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP9]], <4 x i16> [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i16> [[TMP12]], <8 x i16> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP14]]
//
v16i16 abdhx_rr_s(v16i16 a, v16i16 b) { return __builtin_kvx_abdhx(a, b, ".s"); }

// CHECK-LABEL: @abdhx_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i16> [[B:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP6]], <4 x i16> [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP9]], <4 x i16> [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i16> [[TMP12]], <8 x i16> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP14]]
//
v16i16 abdhx_rr_u(v16i16 a, v16i16 b) { return __builtin_kvx_abdhx(a, b, ".u"); }

// CHECK-LABEL: @abdhx_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 1, i16 2, i16 3, i16 4>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP2]], <4 x i16> <i16 1, i16 2, i16 3, i16 4>, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP4]], <4 x i16> <i16 1, i16 2, i16 3, i16 4>, i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP6]], <4 x i16> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
v16i16 abdhx_ri_(v16i16 a) { v16i16 b = {1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 0, 0, 0, 0}; return __builtin_kvx_abdhx(a, b, ""); }

// CHECK-LABEL: @abdhx_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 1, i16 2, i16 3, i16 4>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP2]], <4 x i16> <i16 1, i16 2, i16 3, i16 4>, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP4]], <4 x i16> <i16 1, i16 2, i16 3, i16 4>, i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP6]], <4 x i16> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
v16i16 abdhx_ri_s(v16i16 a) { v16i16 b = {1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 0, 0, 0, 0}; return __builtin_kvx_abdhx(a, b, ".s"); }

// CHECK-LABEL: @abdhx_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 1, i16 2, i16 3, i16 4>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP2]], <4 x i16> <i16 1, i16 2, i16 3, i16 4>, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP4]], <4 x i16> <i16 1, i16 2, i16 3, i16 4>, i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.abd.v4i16(<4 x i16> [[TMP6]], <4 x i16> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
v16i16 abdhx_ri_u(v16i16 a) { v16i16 b = {1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 0, 0, 0, 0}; return __builtin_kvx_abdhx(a, b, ".u"); }

// CHECK-LABEL: @abdwo_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i32> [[B:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP6]], <2 x i32> [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP9]], <2 x i32> [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i32> [[TMP12]], <4 x i32> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP14]]
//
v8i32 abdwo_rr_(v8i32 a, v8i32 b) { return __builtin_kvx_abdwo(a, b, ""); }

// CHECK-LABEL: @abdwo_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i32> [[B:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP6]], <2 x i32> [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP9]], <2 x i32> [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i32> [[TMP12]], <4 x i32> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP14]]
//
v8i32 abdwo_rr_s(v8i32 a, v8i32 b) { return __builtin_kvx_abdwo(a, b, ".s"); }

// CHECK-LABEL: @abdwo_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i32> [[B:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP6]], <2 x i32> [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP9]], <2 x i32> [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i32> [[TMP12]], <4 x i32> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP14]]
//
v8i32 abdwo_rr_u(v8i32 a, v8i32 b) { return __builtin_kvx_abdwo(a, b, ".u"); }

// CHECK-LABEL: @abdwo_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 1, i32 0>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP2]], <2 x i32> <i32 1, i32 1>, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP4]], <2 x i32> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP6]], <2 x i32> <i32 1, i32 1>, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
v8i32 abdwo_ri_(v8i32 a) { v8i32 b = {1, 0, 1, 1, 0, 0, 1, 1}; return __builtin_kvx_abdwo(a, b, ""); }

// CHECK-LABEL: @abdwo_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 1, i32 0>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP2]], <2 x i32> <i32 1, i32 1>, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP4]], <2 x i32> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP6]], <2 x i32> <i32 1, i32 1>, i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
v8i32 abdwo_ri_s(v8i32 a) { v8i32 b = {1, 0, 1, 1, 0, 0, 1, 1}; return __builtin_kvx_abdwo(a, b, ".s"); }

// CHECK-LABEL: @abdwo_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 1, i32 0>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP2]], <2 x i32> <i32 1, i32 1>, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP4]], <2 x i32> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP6]], <2 x i32> <i32 1, i32 1>, i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
v8i32 abdwo_ri_u(v8i32 a) { v8i32 b = {1, 0, 1, 1, 0, 0, 1, 1}; return __builtin_kvx_abdwo(a, b, ".u"); }

// CHECK-LABEL: @abdwp_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 abdwp_rr_(v2i32 a, v2i32 b) { return __builtin_kvx_abdwp(a, b, ""); }

// CHECK-LABEL: @abdwp_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 abdwp_rr_s(v2i32 a, v2i32 b) { return __builtin_kvx_abdwp(a, b, ".s"); }

// CHECK-LABEL: @abdwp_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 abdwp_rr_u(v2i32 a, v2i32 b) { return __builtin_kvx_abdwp(a, b, ".u"); }

// CHECK-LABEL: @abdwp_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 12, i32 0>, i32 0)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 abdwp_ri_(v2i32 a) { v2i32 b = {12, 0}; return __builtin_kvx_abdwp(a, b, ""); }

// CHECK-LABEL: @abdwp_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 12, i32 0>, i32 1)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 abdwp_ri_s(v2i32 a) { v2i32 b = {12, 0}; return __builtin_kvx_abdwp(a, b, ".s"); }

// CHECK-LABEL: @abdwp_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 12, i32 0>, i32 2)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 abdwp_ri_u(v2i32 a) { v2i32 b = {12, 0}; return __builtin_kvx_abdwp(a, b, ".u"); }

// CHECK-LABEL: @abdwp_ri_at_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 12, i32 12>, i32 0)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 abdwp_ri_at_(v2i32 a) { v2i32 b = {12, 12}; return __builtin_kvx_abdwp(a, b, ""); }

// CHECK-LABEL: @abdwp_ri_at_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 12, i32 12>, i32 1)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 abdwp_ri_at_s(v2i32 a) { v2i32 b = {12, 12}; return __builtin_kvx_abdwp(a, b, ".s"); }

// CHECK-LABEL: @abdwp_ri_at_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 12, i32 12>, i32 2)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 abdwp_ri_at_u(v2i32 a) { v2i32 b = {12, 12}; return __builtin_kvx_abdwp(a, b, ".u"); }

// CHECK-LABEL: @abdwq_rr_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[B:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP6]]
//
v4i32 abdwq_rr_(v4i32 a, v4i32 b) { return __builtin_kvx_abdwq(a, b, ""); }

// CHECK-LABEL: @abdwq_rr_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[B:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP6]]
//
v4i32 abdwq_rr_s(v4i32 a, v4i32 b) { return __builtin_kvx_abdwq(a, b, ".s"); }

// CHECK-LABEL: @abdwq_rr_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[B:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP6]]
//
v4i32 abdwq_rr_u(v4i32 a, v4i32 b) { return __builtin_kvx_abdwq(a, b, ".u"); }

// CHECK-LABEL: @abdwq_ri_(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 1, i32 1>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP2]], <2 x i32> <i32 2, i32 0>, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
v4i32 abdwq_ri_(v4i32 a) { v4i32 b = {1, 1, 2, 0}; return __builtin_kvx_abdwq(a, b, ""); }

// CHECK-LABEL: @abdwq_ri_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 1, i32 1>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP2]], <2 x i32> <i32 2, i32 0>, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
v4i32 abdwq_ri_s(v4i32 a) { v4i32 b = {1, 1, 2, 0}; return __builtin_kvx_abdwq(a, b, ".s"); }

// CHECK-LABEL: @abdwq_ri_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 1, i32 1>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.abd.v2i32(<2 x i32> [[TMP2]], <2 x i32> <i32 2, i32 0>, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
v4i32 abdwq_ri_u(v4i32 a) { v4i32 b = {1, 1, 2, 0}; return __builtin_kvx_abdwq(a, b, ".u"); }

