// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-1 -O2 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -O2 -emit-llvm -o - %s | FileCheck %s
#include "vector-types.h"
// CHECK-LABEL: @avgbo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[A:%.*]], <8 x i8> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 avgbo(v8i8 a, v8i8 b) { return __builtin_kvx_avgbo(a, b, ""); }

// CHECK-LABEL: @avgbp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.avg.v2i8(<2 x i8> [[A:%.*]], <2 x i8> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 avgbp(v2i8 a, v2i8 b) { return __builtin_kvx_avgbp(a, b, ""); }

// CHECK-LABEL: @avgbq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.avg.v4i8(<4 x i8> [[A:%.*]], <4 x i8> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 avgbq(v4i8 a, v4i8 b) { return __builtin_kvx_avgbq(a, b, ""); }

// CHECK-LABEL: @avgbx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[B:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[B]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP6]]
//
v16i8 avgbx(v16i8 a, v16i8 b) { return __builtin_kvx_avgbx(a, b, ""); }

// CHECK-LABEL: @avgbv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i8> [[B:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP6]], <8 x i8> [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP9]], <8 x i8> [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP11]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> [[TMP13]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP14]]
//
v32i8 avgbv(v32i8 a, v32i8 b) { return __builtin_kvx_avgbv(a, b, ""); }

// CHECK-LABEL: @avgrbo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[A:%.*]], <8 x i8> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 avgrbo(v8i8 a, v8i8 b) { return __builtin_kvx_avgbo(a, b, ".r"); }

// CHECK-LABEL: @avgrbp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.avg.v2i8(<2 x i8> [[A:%.*]], <2 x i8> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 avgrbp(v2i8 a, v2i8 b) { return __builtin_kvx_avgbp(a, b, ".r"); }

// CHECK-LABEL: @avgrbq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.avg.v4i8(<4 x i8> [[A:%.*]], <4 x i8> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 avgrbq(v4i8 a, v4i8 b) { return __builtin_kvx_avgbq(a, b, ".r"); }

// CHECK-LABEL: @avgrbx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[B:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[B]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP6]]
//
v16i8 avgrbx(v16i8 a, v16i8 b) { return __builtin_kvx_avgbx(a, b, ".r"); }

// CHECK-LABEL: @avgrbv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i8> [[B:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP6]], <8 x i8> [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP9]], <8 x i8> [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP11]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> [[TMP13]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP14]]
//
v32i8 avgrbv(v32i8 a, v32i8 b) { return __builtin_kvx_avgbv(a, b, ".r"); }

// CHECK-LABEL: @avgubo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[A:%.*]], <8 x i8> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8u8 avgubo(v8u8 a, v8i8 b) { return __builtin_kvx_avgbo(a, b, ".u"); }

// CHECK-LABEL: @avgubp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.avg.v2i8(<2 x i8> [[A:%.*]], <2 x i8> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2u8 avgubp(v2u8 a, v2u8 b) { return __builtin_kvx_avgbp(a, b, ".u"); }

// CHECK-LABEL: @avgubq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.avg.v4i8(<4 x i8> [[A:%.*]], <4 x i8> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4u8 avgubq(v4u8 a, v4u8 b) { return __builtin_kvx_avgbq(a, b, ".u"); }

// CHECK-LABEL: @avgubx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[B:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[B]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP6]]
//
v16u8 avgubx(v16u8 a, v16u8 b) { return __builtin_kvx_avgbx(a, b, ".u"); }

// CHECK-LABEL: @avgubv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i8> [[B:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP6]], <8 x i8> [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP9]], <8 x i8> [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP11]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> [[TMP13]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP14]]
//
v32u8 avgubv(v32u8 a, v32u8 b) { return __builtin_kvx_avgbv(a, b, ".u"); }

// CHECK-LABEL: @avgrubo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[A:%.*]], <8 x i8> [[B:%.*]], i32 3)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8u8 avgrubo(v8u8 a, v8u8 b) { return __builtin_kvx_avgbo(a, b, ".ru"); }

// CHECK-LABEL: @avgrubp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.avg.v2i8(<2 x i8> [[A:%.*]], <2 x i8> [[B:%.*]], i32 3)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2u8 avgrubp(v2u8 a, v2u8 b) { return __builtin_kvx_avgbp(a, b, ".ru"); }

// CHECK-LABEL: @avgrubq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.avg.v4i8(<4 x i8> [[A:%.*]], <4 x i8> [[B:%.*]], i32 3)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4u8 avgrubq(v4u8 a, v4u8 b) { return __builtin_kvx_avgbq(a, b, ".ru"); }

// CHECK-LABEL: @avgrubx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i8> [[B:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 3)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[B]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP6]]
//
v16u8 avgrubx(v16u8 a, v16u8 b) { return __builtin_kvx_avgbx(a, b, ".ru"); }

// CHECK-LABEL: @avgrubv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i8> [[B:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> [[TMP1]], i32 3)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP3]], <8 x i8> [[TMP4]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP6]], <8 x i8> [[TMP7]], i32 3)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[B]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP9]], <8 x i8> [[TMP10]], i32 3)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <8 x i8> [[TMP2]], <8 x i8> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP11]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i8> [[TMP12]], <16 x i8> [[TMP13]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP14]]
//
v32u8 avgrubv(v32u8 a, v32u8 b) { return __builtin_kvx_avgbv(a, b, ".ru"); }

// CHECK-LABEL: @avgho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[B:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[B]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP6]]
//
v8i16 avgho(v8i16 a, v8i16 b) { return __builtin_kvx_avgho(a, b, ""); }

// CHECK-LABEL: @avghp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.avg.v2i16(<2 x i16> [[A:%.*]], <2 x i16> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 avghp(v2i16 a, v2i16 b) { return __builtin_kvx_avghp(a, b, ""); }

// CHECK-LABEL: @avghq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[A:%.*]], <4 x i16> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 avghq(v4i16 a, v4i16 b) { return __builtin_kvx_avghq(a, b, ""); }

// CHECK-LABEL: @avghx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i16> [[B:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP6]], <4 x i16> [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP9]], <4 x i16> [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i16> [[TMP12]], <8 x i16> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP14]]
//
v16i16 avghx(v16i16 a, v16i16 b) { return __builtin_kvx_avghx(a, b, ""); }

// CHECK-LABEL: @avgrho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[B:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[B]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP6]]
//
v8i16 avgrho(v8i16 a, v8i16 b) { return __builtin_kvx_avgho(a, b, ".r"); }

// CHECK-LABEL: @avgrhp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.avg.v2i16(<2 x i16> [[A:%.*]], <2 x i16> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 avgrhp(v2i16 a, v2i16 b) { return __builtin_kvx_avghp(a, b, ".r"); }

// CHECK-LABEL: @avgrhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[A:%.*]], <4 x i16> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 avgrhq(v4i16 a, v4i16 b) { return __builtin_kvx_avghq(a, b, ".r"); }

// CHECK-LABEL: @avgrhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i16> [[B:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP6]], <4 x i16> [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP9]], <4 x i16> [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i16> [[TMP12]], <8 x i16> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP14]]
//
v16i16 avgrhx(v16i16 a, v16i16 b) { return __builtin_kvx_avghx(a, b, ".r"); }

// CHECK-LABEL: @avguho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[B:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[B]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP6]]
//
v8u16 avguho(v8u16 a, v8u16 b) { return __builtin_kvx_avgho(a, b, ".u"); }

// CHECK-LABEL: @avguhp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.avg.v2i16(<2 x i16> [[A:%.*]], <2 x i16> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2u16 avguhp(v2u16 a, v2u16 b) { return __builtin_kvx_avghp(a, b, ".u"); }

// CHECK-LABEL: @avguhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[A:%.*]], <4 x i16> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4u16 avguhq(v4u16 a, v4u16 b) { return __builtin_kvx_avghq(a, b, ".u"); }

// CHECK-LABEL: @avguhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i16> [[B:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP6]], <4 x i16> [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP9]], <4 x i16> [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i16> [[TMP12]], <8 x i16> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP14]]
//
v16u16 avguhx(v16u16 a, v16u16 b) { return __builtin_kvx_avghx(a, b, ".u"); }

// CHECK-LABEL: @avgruho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[B:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 3)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[B]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP6]]
//
v8u16 avgruho(v8u16 a, v8u16 b) { return __builtin_kvx_avgho(a, b, ".ru"); }

// CHECK-LABEL: @avgruhp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.avg.v2i16(<2 x i16> [[A:%.*]], <2 x i16> [[B:%.*]], i32 3)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2u16 avgruhp(v2u16 a, v2u16 b) { return __builtin_kvx_avghp(a, b, ".ru"); }

// CHECK-LABEL: @avgruhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[A:%.*]], <4 x i16> [[B:%.*]], i32 3)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4u16 avgruhq(v4u16 a, v4u16 b) { return __builtin_kvx_avghq(a, b, ".ru"); }

// CHECK-LABEL: @avgruhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i16> [[B:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 3)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP6]], <4 x i16> [[TMP7]], i32 3)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[B]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP9]], <4 x i16> [[TMP10]], i32 3)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i16> [[TMP12]], <8 x i16> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP14]]
//
v16u16 avgruhx(v16u16 a, v16u16 b) { return __builtin_kvx_avghx(a, b, ".ru"); }

// CHECK-LABEL: @avgruwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i32> [[B:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 3)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP6]], <2 x i32> [[TMP7]], i32 3)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP9]], <2 x i32> [[TMP10]], i32 3)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i32> [[TMP12]], <4 x i32> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP14]]
//
v8u32 avgruwo(v8u32 a, v8u32 b) { return __builtin_kvx_avgwo(a, b, ".ru"); }

// CHECK-LABEL: @avgruwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], i32 3)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2u32 avgruwp(v2u32 a, v2u32 b) { return __builtin_kvx_avgwp(a, b, ".ru"); }

// CHECK-LABEL: @avgruwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[B:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 3)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP6]]
//
v4u32 avgruwq(v4u32 a, v4u32 b) { return __builtin_kvx_avgwq(a, b, ".ru"); }

// CHECK-LABEL: @avgrwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i32> [[B:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP6]], <2 x i32> [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP9]], <2 x i32> [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i32> [[TMP12]], <4 x i32> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP14]]
//
v8i32 avgrwo(v8i32 a, v8i32 b) { return __builtin_kvx_avgwo(a, b, ".r"); }

// CHECK-LABEL: @avgrwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 avgrwp(v2i32 a, v2i32 b) { return __builtin_kvx_avgwp(a, b, ".r"); }

// CHECK-LABEL: @avgrwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[B:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP6]]
//
v4i32 avgrwq(v4i32 a, v4i32 b) { return __builtin_kvx_avgwq(a, b, ".r"); }

// CHECK-LABEL: @avguwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i32> [[B:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP6]], <2 x i32> [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP9]], <2 x i32> [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i32> [[TMP12]], <4 x i32> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP14]]
//
v8u32 avguwo(v8u32 a, v8u32 b) { return __builtin_kvx_avgwo(a, b, ".u"); }

// CHECK-LABEL: @avguwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2u32 avguwp(v2u32 a, v2u32 b) { return __builtin_kvx_avgwp(a, b, ".u"); }

// CHECK-LABEL: @avguwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[B:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP6]]
//
v4u32 avguwq(v4u32 a, v4u32 b) { return __builtin_kvx_avgwq(a, b, ".u"); }

// CHECK-LABEL: @avgwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i32> [[B:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP6]], <2 x i32> [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[B]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP9]], <2 x i32> [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i32> [[TMP12]], <4 x i32> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP14]]
//
v8i32 avgwo(v8i32 a, v8i32 b) { return __builtin_kvx_avgwo(a, b, ""); }

// CHECK-LABEL: @avgwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 avgwp(v2i32 a, v2i32 b) { return __builtin_kvx_avgwp(a, b, ""); }

// CHECK-LABEL: @avgwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[B:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[B]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP6]]
//
v4i32 avgwq(v4i32 a, v4i32 b) { return __builtin_kvx_avgwq(a, b, ""); }

// CHECK-LABEL: @avgw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.avg.i32(i32 [[V1:%.*]], i32 [[V2:%.*]], i32 0)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int avgw(int v1, int v2) { return __builtin_kvx_avgw(v1, v2, ""); }

// CHECK-LABEL: @avguw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.avg.i32(i32 [[V1:%.*]], i32 [[V2:%.*]], i32 2)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int avguw(unsigned int v1, unsigned int v2) { return __builtin_kvx_avgw(v1, v2, ".u"); }

// CHECK-LABEL: @avgrw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.avg.i32(i32 [[V1:%.*]], i32 [[V2:%.*]], i32 1)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int avgrw(int v1, int v2) { return __builtin_kvx_avgw(v1, v2, ".r"); }

// CHECK-LABEL: @avgruw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.avg.i32(i32 [[V1:%.*]], i32 [[V2:%.*]], i32 3)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int avgruw(int v1, int v2) { return __builtin_kvx_avgw(v1, v2, ".ru"); }

// CHECK-LABEL: @avgbo_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 0)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 avgbo_ri(v8i8 a) { v8i8 b = {42}; return __builtin_kvx_avgbo(a, b, ""); }

// CHECK-LABEL: @avgbp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.avg.v2i8(<2 x i8> [[A:%.*]], <2 x i8> <i8 42, i8 0>, i32 0)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 avgbp_ri(v2i8 a) { v2i8 b = {42}; return __builtin_kvx_avgbp(a, b, ""); }

// CHECK-LABEL: @avgbq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.avg.v4i8(<4 x i8> [[A:%.*]], <4 x i8> <i8 42, i8 0, i8 0, i8 0>, i32 0)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 avgbq_ri(v4i8 a) { v4i8 b = {42}; return __builtin_kvx_avgbq(a, b, ""); }

// CHECK-LABEL: @avgbx_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP2]], <8 x i8> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16i8 avgbx_ri(v16i8 a) { v16i8 b = {42}; return __builtin_kvx_avgbx(a, b, ""); }

// CHECK-LABEL: @avgbv_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP2]], <8 x i8> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP4]], <8 x i8> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP6]], <8 x i8> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32i8 avgbv_ri(v32i8 a) { v32i8 b = {42}; return __builtin_kvx_avgbv(a, b, ""); }

// CHECK-LABEL: @avgrbo_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 1)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 avgrbo_ri(v8i8 a) { v8i8 b = {42}; return __builtin_kvx_avgbo(a, b, ".r"); }

// CHECK-LABEL: @avgrbp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.avg.v2i8(<2 x i8> [[A:%.*]], <2 x i8> <i8 42, i8 0>, i32 1)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 avgrbp_ri(v2i8 a) { v2i8 b = {42}; return __builtin_kvx_avgbp(a, b, ".r"); }

// CHECK-LABEL: @avgrbq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.avg.v4i8(<4 x i8> [[A:%.*]], <4 x i8> <i8 42, i8 0, i8 0, i8 0>, i32 1)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 avgrbq_ri(v4i8 a) { v4i8 b = {42}; return __builtin_kvx_avgbq(a, b, ".r"); }

// CHECK-LABEL: @avgrbx_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP2]], <8 x i8> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16i8 avgrbx_ri(v16i8 a) { v16i8 b = {42}; return __builtin_kvx_avgbx(a, b, ".r"); }

// CHECK-LABEL: @avgrbv_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP2]], <8 x i8> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP4]], <8 x i8> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP6]], <8 x i8> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32i8 avgrbv_ri(v32i8 a) { v32i8 b = {42}; return __builtin_kvx_avgbv(a, b, ".r"); }

// CHECK-LABEL: @avgubo_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 2)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8u8 avgubo_ri(v8u8 a) { v8i8 b = {42}; return __builtin_kvx_avgbo(a, b, ".u"); }

// CHECK-LABEL: @avgubp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.avg.v2i8(<2 x i8> [[A:%.*]], <2 x i8> <i8 42, i8 0>, i32 2)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2u8 avgubp_ri(v2u8 a) { v2u8 b = {42}; return __builtin_kvx_avgbp(a, b, ".u"); }

// CHECK-LABEL: @avgubq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.avg.v4i8(<4 x i8> [[A:%.*]], <4 x i8> <i8 42, i8 0, i8 0, i8 0>, i32 2)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4u8 avgubq_ri(v4u8 a) { v4u8 b = {42}; return __builtin_kvx_avgbq(a, b, ".u"); }

// CHECK-LABEL: @avgubx_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP2]], <8 x i8> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16u8 avgubx_ri(v16u8 a) { v16u8 b = {42}; return __builtin_kvx_avgbx(a, b, ".u"); }

// CHECK-LABEL: @avgubv_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP2]], <8 x i8> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP4]], <8 x i8> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP6]], <8 x i8> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32u8 avgubv_ri(v32u8 a) { v32u8 b = {42}; return __builtin_kvx_avgbv(a, b, ".u"); }

// CHECK-LABEL: @avgrubo_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[A:%.*]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 3)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8u8 avgrubo_ri(v8u8 a) { v8u8 b = {42}; return __builtin_kvx_avgbo(a, b, ".ru"); }

// CHECK-LABEL: @avgrubp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.avg.v2i8(<2 x i8> [[A:%.*]], <2 x i8> <i8 42, i8 0>, i32 3)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2u8 avgrubp_ri(v2u8 a) { v2u8 b = {42}; return __builtin_kvx_avgbp(a, b, ".ru"); }

// CHECK-LABEL: @avgrubq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.avg.v4i8(<4 x i8> [[A:%.*]], <4 x i8> <i8 42, i8 0, i8 0, i8 0>, i32 3)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4u8 avgrubq_ri(v4u8 a) { v4u8 b = {42}; return __builtin_kvx_avgbq(a, b, ".ru"); }

// CHECK-LABEL: @avgrubx_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[A:%.*]], <16 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[A]], <16 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP2]], <8 x i8> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16u8 avgrubx_ri(v16u8 a) { v16u8 b = {42}; return __builtin_kvx_avgbx(a, b, ".ru"); }

// CHECK-LABEL: @avgrubv_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[A:%.*]], <32 x i8> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP0]], <8 x i8> <i8 42, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0, i8 0>, i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP2]], <8 x i8> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP4]], <8 x i8> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[A]], <32 x i8> poison, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.avg.v8i8(<8 x i8> [[TMP6]], <8 x i8> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32u8 avgrubv_ri(v32u8 a) { v32u8 b = {42}; return __builtin_kvx_avgbv(a, b, ".ru"); }

// CHECK-LABEL: @avgho_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP2]], <4 x i16> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
v8i16 avgho_ri(v8i16 a) { v8i16 b = {42}; return __builtin_kvx_avgho(a, b, ""); }

// CHECK-LABEL: @avghp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.avg.v2i16(<2 x i16> [[A:%.*]], <2 x i16> <i16 42, i16 0>, i32 0)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 avghp_ri(v2i16 a) { v2i16 b = {42}; return __builtin_kvx_avghp(a, b, ""); }

// CHECK-LABEL: @avghq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 0)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 avghq_ri(v4i16 a) { v4i16 b = {42}; return __builtin_kvx_avghq(a, b, ""); }

// CHECK-LABEL: @avghx_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP2]], <4 x i16> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP4]], <4 x i16> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP6]], <4 x i16> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
v16i16 avghx_ri(v16i16 a) { v16i16 b = {42}; return __builtin_kvx_avghx(a, b, ""); }

// CHECK-LABEL: @avgrho_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP2]], <4 x i16> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
v8i16 avgrho_ri(v8i16 a) { v8i16 b = {42}; return __builtin_kvx_avgho(a, b, ".r"); }

// CHECK-LABEL: @avgrhp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.avg.v2i16(<2 x i16> [[A:%.*]], <2 x i16> <i16 42, i16 0>, i32 1)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 avgrhp_ri(v2i16 a) { v2i16 b = {42}; return __builtin_kvx_avghp(a, b, ".r"); }

// CHECK-LABEL: @avgrhq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 1)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 avgrhq_ri(v4i16 a) { v4i16 b = {42}; return __builtin_kvx_avghq(a, b, ".r"); }

// CHECK-LABEL: @avgrhx_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP2]], <4 x i16> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP4]], <4 x i16> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP6]], <4 x i16> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
v16i16 avgrhx_ri(v16i16 a) { v16i16 b = {42}; return __builtin_kvx_avghx(a, b, ".r"); }

// CHECK-LABEL: @avguho_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP2]], <4 x i16> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
v8u16 avguho_ri(v8u16 a) { v8u16 b = {42}; return __builtin_kvx_avgho(a, b, ".u"); }

// CHECK-LABEL: @avguhp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.avg.v2i16(<2 x i16> [[A:%.*]], <2 x i16> <i16 42, i16 0>, i32 2)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2u16 avguhp_ri(v2u16 a) { v2u16 b = {42}; return __builtin_kvx_avghp(a, b, ".u"); }

// CHECK-LABEL: @avguhq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 2)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4u16 avguhq_ri(v4u16 a) { v4u16 b = {42}; return __builtin_kvx_avghq(a, b, ".u"); }

// CHECK-LABEL: @avguhx_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP2]], <4 x i16> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP4]], <4 x i16> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP6]], <4 x i16> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
v16u16 avguhx_ri(v16u16 a) { v16u16 b = {42}; return __builtin_kvx_avghx(a, b, ".u"); }

// CHECK-LABEL: @avgruho_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP2]], <4 x i16> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
v8u16 avgruho_ri(v8u16 a) { v8u16 b = {42}; return __builtin_kvx_avgho(a, b, ".ru"); }

// CHECK-LABEL: @avgruhp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.avg.v2i16(<2 x i16> [[A:%.*]], <2 x i16> <i16 42, i16 0>, i32 3)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2u16 avgruhp_ri(v2u16 a) { v2u16 b = {42}; return __builtin_kvx_avghp(a, b, ".ru"); }

// CHECK-LABEL: @avgruhq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[A:%.*]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 3)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4u16 avgruhq_ri(v4u16 a) { v4u16 b = {42}; return __builtin_kvx_avghq(a, b, ".ru"); }

// CHECK-LABEL: @avgruhx_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP0]], <4 x i16> <i16 42, i16 0, i16 0, i16 0>, i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP2]], <4 x i16> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP4]], <4 x i16> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.avg.v4i16(<4 x i16> [[TMP6]], <4 x i16> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
v16u16 avgruhx_ri(v16u16 a) { v16u16 b = {42}; return __builtin_kvx_avghx(a, b, ".ru"); }

// CHECK-LABEL: @avgruwo_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 42, i32 0>, i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP2]], <2 x i32> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP4]], <2 x i32> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP6]], <2 x i32> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
v8u32 avgruwo_ri(v8u32 a) { v8u32 b = {42}; return __builtin_kvx_avgwo(a, b, ".ru"); }

// CHECK-LABEL: @avgruwp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 42, i32 0>, i32 3)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2u32 avgruwp_ri(v2u32 a) { v2u32 b = {42}; return __builtin_kvx_avgwp(a, b, ".ru"); }

// CHECK-LABEL: @avgruwq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 42, i32 0>, i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP2]], <2 x i32> zeroinitializer, i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
v4u32 avgruwq_ri(v4u32 a) { v4u32 b = {42}; return __builtin_kvx_avgwq(a, b, ".ru"); }

// CHECK-LABEL: @avgrwo_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 42, i32 0>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP2]], <2 x i32> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP4]], <2 x i32> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP6]], <2 x i32> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
v8i32 avgrwo_ri(v8i32 a) { v8i32 b = {42}; return __builtin_kvx_avgwo(a, b, ".r"); }

// CHECK-LABEL: @avgrwp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 42, i32 0>, i32 1)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 avgrwp_ri(v2i32 a) { v2i32 b = {42}; return __builtin_kvx_avgwp(a, b, ".r"); }

// CHECK-LABEL: @avgrwq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 42, i32 0>, i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP2]], <2 x i32> zeroinitializer, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
v4i32 avgrwq_ri(v4i32 a) { v4i32 b = {42}; return __builtin_kvx_avgwq(a, b, ".r"); }

// CHECK-LABEL: @avguwo_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 42, i32 0>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP2]], <2 x i32> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP4]], <2 x i32> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP6]], <2 x i32> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
v8u32 avguwo_ri(v8u32 a) { v8u32 b = {42}; return __builtin_kvx_avgwo(a, b, ".u"); }

// CHECK-LABEL: @avguwp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 42, i32 0>, i32 2)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2u32 avguwp_ri(v2u32 a) { v2u32 b = {42}; return __builtin_kvx_avgwp(a, b, ".u"); }

// CHECK-LABEL: @avguwq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 42, i32 0>, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP2]], <2 x i32> zeroinitializer, i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
v4u32 avguwq_ri(v4u32 a) { v4u32 b = {42}; return __builtin_kvx_avgwq(a, b, ".u"); }

// CHECK-LABEL: @avgwo_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 42, i32 0>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP2]], <2 x i32> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP4]], <2 x i32> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP6]], <2 x i32> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
v8i32 avgwo_ri(v8i32 a) { v8i32 b = {42}; return __builtin_kvx_avgwo(a, b, ""); }

// CHECK-LABEL: @avgwp_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[A:%.*]], <2 x i32> <i32 42, i32 0>, i32 0)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 avgwp_ri(v2i32 a) { v2i32 b = {42}; return __builtin_kvx_avgwp(a, b, ""); }

// CHECK-LABEL: @avgwq_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP0]], <2 x i32> <i32 42, i32 0>, i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.avg.v2i32(<2 x i32> [[TMP2]], <2 x i32> zeroinitializer, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
v4i32 avgwq_ri(v4i32 a) { v4i32 b = {42}; return __builtin_kvx_avgwq(a, b, ""); }

// CHECK-LABEL: @avgw_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.avg.i32(i32 [[V1:%.*]], i32 42, i32 0)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int avgw_ri(int v1) { return __builtin_kvx_avgw(v1, 42, ""); }

// CHECK-LABEL: @avguw_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.avg.i32(i32 [[V1:%.*]], i32 42, i32 2)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int avguw_ri(unsigned int v1) { return __builtin_kvx_avgw(v1, 42, ".u"); }

// CHECK-LABEL: @avgrw_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.avg.i32(i32 [[V1:%.*]], i32 42, i32 1)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int avgrw_ri(int v1) { return __builtin_kvx_avgw(v1, 42, ".r"); }

// CHECK-LABEL: @avgruw_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.avg.i32(i32 [[V1:%.*]], i32 42, i32 3)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
unsigned int avgruw_ri(int v1) { return __builtin_kvx_avgw(v1, 42, ".ru"); }

