// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-1 -S -O2 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -S -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @cat128(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[KVX_CAT:%.*]] = shufflevector <2 x i32> [[LO:%.*]], <2 x i32> [[HI:%.*]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[KVX_CAT]]
//
v4i32 cat128(v2i32 hi, v2i32 lo) {
    return __builtin_kvx_cat128(lo, hi);
}

// CHECK-LABEL: @cat256(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[KVX_CAT:%.*]] = shufflevector <4 x i32> [[LO:%.*]], <4 x i32> [[HI:%.*]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[KVX_CAT]]
//
v8i32 cat256(v4i32 hi, v4i32 lo) {
    return __builtin_kvx_cat256(lo, hi);
}

// CHECK-LABEL: @cat512(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[KVX_CAT:%.*]] = shufflevector <8 x i32> [[LO:%.*]], <8 x i32> [[HI:%.*]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    store <16 x i32> [[KVX_CAT]], <16 x i32>* [[AGG_RESULT:%.*]], align 32, [[TBAA2:!tbaa !.*]]
// CHECK-NEXT:    ret void
//
v16i32 cat512(v8i32 hi, v8i32 lo) {
    return __builtin_kvx_cat512(lo, hi);
}

// CHECK-LABEL: @low64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[KVX_LOW:%.*]] = shufflevector <4 x i32> [[V:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    ret <2 x i32> [[KVX_LOW]]
//
v2i32 low64(v4i32 v) {
  return __builtin_kvx_low64(v);
}

// CHECK-LABEL: @low128(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[KVX_LOW:%.*]] = shufflevector <8 x i32> [[V:%.*]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[KVX_LOW]]
//
v4i32 low128(v8i32 v) {
  return __builtin_kvx_low128(v);
}

// CHECK-LABEL: @low256(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <16 x i32>, <16 x i32>* [[TMP0:%.*]], align 32, [[TBAA2]]
// CHECK-NEXT:    [[KVX_LOW:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[KVX_LOW]]
//
v8i32 low256(v16i32 v) {
  return __builtin_kvx_low256(v);
}

// CHECK-LABEL: @high64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[KVX_HIGH:%.*]] = shufflevector <4 x i32> [[V:%.*]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    ret <2 x i32> [[KVX_HIGH]]
//
v2i32 high64(v4i32 v) {
  return __builtin_kvx_high64(v);
}

// CHECK-LABEL: @high128(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[KVX_HIGH:%.*]] = shufflevector <8 x i32> [[V:%.*]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <4 x i32> [[KVX_HIGH]]
//
v4i32 high128(v8i32 v) {
  return __builtin_kvx_high128(v);
}

// CHECK-LABEL: @high256(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <16 x i32>, <16 x i32>* [[TMP0:%.*]], align 32, [[TBAA2]]
// CHECK-NEXT:    [[KVX_HIGH:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <8 x i32> [[KVX_HIGH]]
//
v8i32 high256(v16i32 v) {
  return __builtin_kvx_high256(v);
}
