// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

typedef int V2i __attribute__((vector_size(sizeof(int) * 2)));
typedef long long V2Oi __attribute__((vector_size(sizeof(long) * 2)));
typedef short V2s __attribute__((vector_size(sizeof(short) * 2)));
typedef int V4i __attribute__((vector_size(sizeof(int) * 4)));
typedef long long V4Oi __attribute__((vector_size(sizeof(long) * 4)));
typedef short V4s __attribute__((vector_size(sizeof(short) * 4)));
typedef int V8i __attribute__((vector_size(sizeof(int) * 8)));
typedef short V8s __attribute__((vector_size(sizeof(short) * 8)));

// CHECK-LABEL: @maddxhwo_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[LHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[RHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[ACC:%.*]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i32> @llvm.kvx.maddx.v4i32(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <4 x i32> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[LHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <8 x i16> [[RHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[ACC]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i32> @llvm.kvx.maddx.v4i32(<4 x i16> [[TMP4]], <4 x i16> [[TMP5]], <4 x i32> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP8]]
//
V8i maddxhwo_s (V8s lhs, V8s rhs, V8i acc) { return __builtin_kvx_maddxhwo(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @maddxhwo_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[LHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[RHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[ACC:%.*]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i32> @llvm.kvx.maddx.v4i32(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <4 x i32> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[LHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <8 x i16> [[RHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[ACC]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i32> @llvm.kvx.maddx.v4i32(<4 x i16> [[TMP4]], <4 x i16> [[TMP5]], <4 x i32> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP8]]
//
V8i maddxhwo_su (V8s lhs, V8s rhs, V8i acc) { return __builtin_kvx_maddxhwo(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @maddxhwo_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[LHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[RHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[ACC:%.*]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i32> @llvm.kvx.maddx.v4i32(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <4 x i32> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[LHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <8 x i16> [[RHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[ACC]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i32> @llvm.kvx.maddx.v4i32(<4 x i16> [[TMP4]], <4 x i16> [[TMP5]], <4 x i32> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP8]]
//
V8i maddxhwo_u (V8s lhs, V8s rhs, V8i acc) { return __builtin_kvx_maddxhwo(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @maddxhwp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.maddx.v2i32(<2 x i16> [[LHS:%.*]], <2 x i16> [[RHS:%.*]], <2 x i32> [[ACC:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i maddxhwp_s (V2s lhs, V2s rhs, V2i acc) { return __builtin_kvx_maddxhwp(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @maddxhwp_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.maddx.v2i32(<2 x i16> [[LHS:%.*]], <2 x i16> [[RHS:%.*]], <2 x i32> [[ACC:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i maddxhwp_su (V2s lhs, V2s rhs, V2i acc) { return __builtin_kvx_maddxhwp(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @maddxhwp_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.maddx.v2i32(<2 x i16> [[LHS:%.*]], <2 x i16> [[RHS:%.*]], <2 x i32> [[ACC:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i maddxhwp_u (V2s lhs, V2s rhs, V2i acc) { return __builtin_kvx_maddxhwp(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @maddxhwq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.maddx.v4i32(<4 x i16> [[LHS:%.*]], <4 x i16> [[RHS:%.*]], <4 x i32> [[ACC:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
V4i maddxhwq_s (V4s lhs, V4s rhs, V4i acc) { return __builtin_kvx_maddxhwq(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @maddxhwq_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.maddx.v4i32(<4 x i16> [[LHS:%.*]], <4 x i16> [[RHS:%.*]], <4 x i32> [[ACC:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
V4i maddxhwq_su (V4s lhs, V4s rhs, V4i acc) { return __builtin_kvx_maddxhwq(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @maddxhwq_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.maddx.v4i32(<4 x i16> [[LHS:%.*]], <4 x i16> [[RHS:%.*]], <4 x i32> [[ACC:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
V4i maddxhwq_u (V4s lhs, V4s rhs, V4i acc) { return __builtin_kvx_maddxhwq(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @maddxwdp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.maddx.v2i64(<2 x i32> [[LHS:%.*]], <2 x i32> [[RHS:%.*]], <2 x i64> [[ACC:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
V2Oi maddxwdp_s (V2i lhs, V2i rhs, V2Oi acc) { return __builtin_kvx_maddxwdp(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @maddxwdp_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.maddx.v2i64(<2 x i32> [[LHS:%.*]], <2 x i32> [[RHS:%.*]], <2 x i64> [[ACC:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
V2Oi maddxwdp_su (V2i lhs, V2i rhs, V2Oi acc) { return __builtin_kvx_maddxwdp(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @maddxwdp_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.maddx.v2i64(<2 x i32> [[LHS:%.*]], <2 x i32> [[RHS:%.*]], <2 x i64> [[ACC:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
V2Oi maddxwdp_u (V2i lhs, V2i rhs, V2Oi acc) { return __builtin_kvx_maddxwdp(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @maddxwdq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[LHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[RHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i64> [[ACC:%.*]], <4 x i64> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i64> @llvm.kvx.maddx.v2i64(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <2 x i64> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[LHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[RHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i64> [[ACC]], <4 x i64> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i64> @llvm.kvx.maddx.v2i64(<2 x i32> [[TMP4]], <2 x i32> [[TMP5]], <2 x i64> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i64> [[TMP3]], <2 x i64> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i64> [[TMP8]]
//
V4Oi maddxwdq_s (V4i lhs, V4i rhs, V4Oi acc) { return __builtin_kvx_maddxwdq(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @maddxwdq_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[LHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[RHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i64> [[ACC:%.*]], <4 x i64> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i64> @llvm.kvx.maddx.v2i64(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <2 x i64> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[LHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[RHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i64> [[ACC]], <4 x i64> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i64> @llvm.kvx.maddx.v2i64(<2 x i32> [[TMP4]], <2 x i32> [[TMP5]], <2 x i64> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i64> [[TMP3]], <2 x i64> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i64> [[TMP8]]
//
V4Oi maddxwdq_su (V4i lhs, V4i rhs, V4Oi acc) { return __builtin_kvx_maddxwdq(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @maddxwdq_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[LHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[RHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i64> [[ACC:%.*]], <4 x i64> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i64> @llvm.kvx.maddx.v2i64(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <2 x i64> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[LHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[RHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i64> [[ACC]], <4 x i64> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i64> @llvm.kvx.maddx.v2i64(<2 x i32> [[TMP4]], <2 x i32> [[TMP5]], <2 x i64> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i64> [[TMP3]], <2 x i64> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i64> [[TMP8]]
//
V4Oi maddxwdq_u (V4i lhs, V4i rhs, V4Oi acc) { return __builtin_kvx_maddxwdq(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @msbfxhwo_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[LHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[RHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[ACC:%.*]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i32> @llvm.kvx.msbfx.v4i32(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <4 x i32> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[LHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <8 x i16> [[RHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[ACC]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i32> @llvm.kvx.msbfx.v4i32(<4 x i16> [[TMP4]], <4 x i16> [[TMP5]], <4 x i32> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP8]]
//
V8i msbfxhwo_s (V8s lhs, V8s rhs, V8i acc) { return __builtin_kvx_msbfxhwo(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @msbfxhwo_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[LHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[RHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[ACC:%.*]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i32> @llvm.kvx.msbfx.v4i32(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <4 x i32> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[LHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <8 x i16> [[RHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[ACC]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i32> @llvm.kvx.msbfx.v4i32(<4 x i16> [[TMP4]], <4 x i16> [[TMP5]], <4 x i32> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP8]]
//
V8i msbfxhwo_su (V8s lhs, V8s rhs, V8i acc) { return __builtin_kvx_msbfxhwo(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @msbfxhwo_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[LHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[RHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[ACC:%.*]], <8 x i32> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i32> @llvm.kvx.msbfx.v4i32(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], <4 x i32> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[LHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <8 x i16> [[RHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[ACC]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i32> @llvm.kvx.msbfx.v4i32(<4 x i16> [[TMP4]], <4 x i16> [[TMP5]], <4 x i32> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i32> [[TMP3]], <4 x i32> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP8]]
//
V8i msbfxhwo_u (V8s lhs, V8s rhs, V8i acc) { return __builtin_kvx_msbfxhwo(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @msbfxhwp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.msbfx.v2i32(<2 x i16> [[LHS:%.*]], <2 x i16> [[RHS:%.*]], <2 x i32> [[ACC:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i msbfxhwp_s (V2s lhs, V2s rhs, V2i acc) { return __builtin_kvx_msbfxhwp(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @msbfxhwp_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.msbfx.v2i32(<2 x i16> [[LHS:%.*]], <2 x i16> [[RHS:%.*]], <2 x i32> [[ACC:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i msbfxhwp_su (V2s lhs, V2s rhs, V2i acc) { return __builtin_kvx_msbfxhwp(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @msbfxhwp_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.msbfx.v2i32(<2 x i16> [[LHS:%.*]], <2 x i16> [[RHS:%.*]], <2 x i32> [[ACC:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i msbfxhwp_u (V2s lhs, V2s rhs, V2i acc) { return __builtin_kvx_msbfxhwp(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @msbfxhwq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.msbfx.v4i32(<4 x i16> [[LHS:%.*]], <4 x i16> [[RHS:%.*]], <4 x i32> [[ACC:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
V4i msbfxhwq_s (V4s lhs, V4s rhs, V4i acc) { return __builtin_kvx_msbfxhwq(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @msbfxhwq_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.msbfx.v4i32(<4 x i16> [[LHS:%.*]], <4 x i16> [[RHS:%.*]], <4 x i32> [[ACC:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
V4i msbfxhwq_su (V4s lhs, V4s rhs, V4i acc) { return __builtin_kvx_msbfxhwq(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @msbfxhwq_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.msbfx.v4i32(<4 x i16> [[LHS:%.*]], <4 x i16> [[RHS:%.*]], <4 x i32> [[ACC:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
V4i msbfxhwq_u (V4s lhs, V4s rhs, V4i acc) { return __builtin_kvx_msbfxhwq(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @msbfxwdp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.msbfx.v2i64(<2 x i32> [[LHS:%.*]], <2 x i32> [[RHS:%.*]], <2 x i64> [[ACC:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
V2Oi msbfxwdp_s (V2i lhs, V2i rhs, V2Oi acc) { return __builtin_kvx_msbfxwdp(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @msbfxwdp_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.msbfx.v2i64(<2 x i32> [[LHS:%.*]], <2 x i32> [[RHS:%.*]], <2 x i64> [[ACC:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
V2Oi msbfxwdp_su (V2i lhs, V2i rhs, V2Oi acc) { return __builtin_kvx_msbfxwdp(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @msbfxwdp_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.msbfx.v2i64(<2 x i32> [[LHS:%.*]], <2 x i32> [[RHS:%.*]], <2 x i64> [[ACC:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
V2Oi msbfxwdp_u (V2i lhs, V2i rhs, V2Oi acc) { return __builtin_kvx_msbfxwdp(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @msbfxwdq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[LHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[RHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i64> [[ACC:%.*]], <4 x i64> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i64> @llvm.kvx.msbfx.v2i64(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <2 x i64> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[LHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[RHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i64> [[ACC]], <4 x i64> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i64> @llvm.kvx.msbfx.v2i64(<2 x i32> [[TMP4]], <2 x i32> [[TMP5]], <2 x i64> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i64> [[TMP3]], <2 x i64> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i64> [[TMP8]]
//
V4Oi msbfxwdq_s (V4i lhs, V4i rhs, V4Oi acc) { return __builtin_kvx_msbfxwdq(lhs, rhs, acc, ".s"); }

// CHECK-LABEL: @msbfxwdq_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[LHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[RHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i64> [[ACC:%.*]], <4 x i64> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i64> @llvm.kvx.msbfx.v2i64(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <2 x i64> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[LHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[RHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i64> [[ACC]], <4 x i64> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i64> @llvm.kvx.msbfx.v2i64(<2 x i32> [[TMP4]], <2 x i32> [[TMP5]], <2 x i64> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i64> [[TMP3]], <2 x i64> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i64> [[TMP8]]
//
V4Oi msbfxwdq_su (V4i lhs, V4i rhs, V4Oi acc) { return __builtin_kvx_msbfxwdq(lhs, rhs, acc, ".su"); }

// CHECK-LABEL: @msbfxwdq_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[LHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[RHS:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i64> [[ACC:%.*]], <4 x i64> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i64> @llvm.kvx.msbfx.v2i64(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]], <2 x i64> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[LHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x i32> [[RHS]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i64> [[ACC]], <4 x i64> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i64> @llvm.kvx.msbfx.v2i64(<2 x i32> [[TMP4]], <2 x i32> [[TMP5]], <2 x i64> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i64> [[TMP3]], <2 x i64> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i64> [[TMP8]]
//
V4Oi msbfxwdq_u (V4i lhs, V4i rhs, V4Oi acc) { return __builtin_kvx_msbfxwdq(lhs, rhs, acc, ".u"); }

// CHECK-LABEL: @mulxhwo_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[LHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[RHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i32> @llvm.kvx.mulx.v4i32(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[LHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[RHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i32> @llvm.kvx.mulx.v4i32(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP6]]
//
V8i mulxhwo_s (V8s lhs, V8s rhs) { return __builtin_kvx_mulxhwo(lhs, rhs, ".s"); }

// CHECK-LABEL: @mulxhwo_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[LHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[RHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i32> @llvm.kvx.mulx.v4i32(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[LHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[RHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i32> @llvm.kvx.mulx.v4i32(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP6]]
//
V8i mulxhwo_su (V8s lhs, V8s rhs) { return __builtin_kvx_mulxhwo(lhs, rhs, ".su"); }

// CHECK-LABEL: @mulxhwo_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[LHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[RHS:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i32> @llvm.kvx.mulx.v4i32(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[LHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[RHS]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i32> @llvm.kvx.mulx.v4i32(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i32> [[TMP2]], <4 x i32> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP6]]
//
V8i mulxhwo_u (V8s lhs, V8s rhs) { return __builtin_kvx_mulxhwo(lhs, rhs, ".u"); }

// CHECK-LABEL: @mulxhwp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.mulx.v2i32(<2 x i16> [[LHS:%.*]], <2 x i16> [[RHS:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i mulxhwp_s (V2s lhs, V2s rhs) { return __builtin_kvx_mulxhwp(lhs, rhs, ".s"); }

// CHECK-LABEL: @mulxhwp_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.mulx.v2i32(<2 x i16> [[LHS:%.*]], <2 x i16> [[RHS:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i mulxhwp_su (V2s lhs, V2s rhs) { return __builtin_kvx_mulxhwp(lhs, rhs, ".su"); }

// CHECK-LABEL: @mulxhwp_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.mulx.v2i32(<2 x i16> [[LHS:%.*]], <2 x i16> [[RHS:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i mulxhwp_u (V2s lhs, V2s rhs) { return __builtin_kvx_mulxhwp(lhs, rhs, ".u"); }

// CHECK-LABEL: @mulxhwq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.mulx.v4i32(<4 x i16> [[LHS:%.*]], <4 x i16> [[RHS:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
V4i mulxhwq_s (V4s lhs, V4s rhs) { return __builtin_kvx_mulxhwq(lhs, rhs, ".s"); }

// CHECK-LABEL: @mulxhwq_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.mulx.v4i32(<4 x i16> [[LHS:%.*]], <4 x i16> [[RHS:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
V4i mulxhwq_su (V4s lhs, V4s rhs) { return __builtin_kvx_mulxhwq(lhs, rhs, ".su"); }

// CHECK-LABEL: @mulxhwq_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.mulx.v4i32(<4 x i16> [[LHS:%.*]], <4 x i16> [[RHS:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
V4i mulxhwq_u (V4s lhs, V4s rhs) { return __builtin_kvx_mulxhwq(lhs, rhs, ".u"); }

// CHECK-LABEL: @mulxwdp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.mulx.v2i64(<2 x i32> [[LHS:%.*]], <2 x i32> [[RHS:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
V2Oi mulxwdp_s (V2i lhs, V2i rhs) { return __builtin_kvx_mulxwdp(lhs, rhs, ".s"); }

// CHECK-LABEL: @mulxwdp_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.mulx.v2i64(<2 x i32> [[LHS:%.*]], <2 x i32> [[RHS:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
V2Oi mulxwdp_su (V2i lhs, V2i rhs) { return __builtin_kvx_mulxwdp(lhs, rhs, ".su"); }

// CHECK-LABEL: @mulxwdp_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.mulx.v2i64(<2 x i32> [[LHS:%.*]], <2 x i32> [[RHS:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
V2Oi mulxwdp_u (V2i lhs, V2i rhs) { return __builtin_kvx_mulxwdp(lhs, rhs, ".u"); }

// CHECK-LABEL: @mulxwdq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i64> @llvm.kvx.mulx.v4i64(<4 x i32> [[LHS:%.*]], <4 x i32> [[RHS:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i64> [[TMP0]]
//
V4Oi mulxwdq_s (V4i lhs, V4i rhs) { return __builtin_kvx_mulxwdq(lhs, rhs, ".s"); }

// CHECK-LABEL: @mulxwdq_su(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i64> @llvm.kvx.mulx.v4i64(<4 x i32> [[LHS:%.*]], <4 x i32> [[RHS:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i64> [[TMP0]]
//
V4Oi mulxwdq_su (V4i lhs, V4i rhs) { return __builtin_kvx_mulxwdq(lhs, rhs, ".su"); }

// CHECK-LABEL: @mulxwdq_u(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i64> @llvm.kvx.mulx.v4i64(<4 x i32> [[LHS:%.*]], <4 x i32> [[RHS:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i64> [[TMP0]]
//
V4Oi mulxwdq_u (V4i lhs, V4i rhs) { return __builtin_kvx_mulxwdq(lhs, rhs, ".u"); }
