// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @faddho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.kvx.fadd.v8f16(<8 x half> [[LHS:%.*]], <8 x half> [[RHS:%.*]], i32 7, i32 1)
// CHECK-NEXT:    ret <8 x half> [[TMP0]]
//
v8f16 faddho(v8f16 lhs, v8f16 rhs) {  return __builtin_kvx_faddho(lhs, rhs, ".s");}

// CHECK-LABEL: @faddhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x half> [[LHS:%.*]], <16 x half> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x half> [[RHS:%.*]], <16 x half> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x half> @llvm.kvx.fadd.v8f16(<8 x half> [[TMP0]], <8 x half> [[TMP1]], i32 7, i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x half> [[LHS]], <16 x half> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x half> [[RHS]], <16 x half> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x half> @llvm.kvx.fadd.v8f16(<8 x half> [[TMP3]], <8 x half> [[TMP4]], i32 7, i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x half> [[TMP2]], <8 x half> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x half> [[TMP6]]
//
v16f16 faddhx(v16f16 lhs, v16f16 rhs) {  return __builtin_kvx_faddhx(lhs, rhs, ".s");}

// CHECK-LABEL: @fsbfho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.kvx.fsbf.v8f16(<8 x half> [[LHS:%.*]], <8 x half> [[RHS:%.*]], i32 7, i32 1)
// CHECK-NEXT:    ret <8 x half> [[TMP0]]
//
v8f16 fsbfho(v8f16 lhs, v8f16 rhs) {  return __builtin_kvx_fsbfho(lhs, rhs, ".s");}

// CHECK-LABEL: @fsbfhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x half> [[LHS:%.*]], <16 x half> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x half> [[RHS:%.*]], <16 x half> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <8 x half> @llvm.kvx.fsbf.v8f16(<8 x half> [[TMP0]], <8 x half> [[TMP1]], i32 7, i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x half> [[LHS]], <16 x half> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x half> [[RHS]], <16 x half> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x half> @llvm.kvx.fsbf.v8f16(<8 x half> [[TMP3]], <8 x half> [[TMP4]], i32 7, i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x half> [[TMP2]], <8 x half> [[TMP5]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x half> [[TMP6]]
//
v16f16 fsbfhx(v16f16 lhs, v16f16 rhs) {  return __builtin_kvx_fsbfhx(lhs, rhs, ".s");}
