// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @ffdmdsw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call float @llvm.kvx.ffdmds.f32(<2 x float> [[A:%.*]], <2 x float> [[B:%.*]], float [[C:%.*]], i32 7, i32 0)
// CHECK-NEXT:    ret float [[TMP0]]
//
float ffdmdsw(v2f32 a, v2f32 b, float c) {
  return __builtin_kvx_ffdmdsw(a, b, c, "");
}

// CHECK-LABEL: @ffdmdswp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x float> @llvm.kvx.ffdmds.v2f32(<4 x float> [[A:%.*]], <4 x float> [[B:%.*]], <2 x float> [[C:%.*]], i32 7, i32 0)
// CHECK-NEXT:    ret <2 x float> [[TMP0]]
//
v2f32 ffdmdswp(v4f32 a, v4f32 b, v2f32 c) {
  return __builtin_kvx_ffdmdswp(a, b, c, "");
}

// CHECK-LABEL: @ffdmdswq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.ffdmds.v4f32(<8 x float> [[A:%.*]], <8 x float> [[B:%.*]], <4 x float> [[C:%.*]], i32 7, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 ffdmdswq(v8f32 a, v8f32 b, v4f32 c) {
  return __builtin_kvx_ffdmdswq(a, b, c, "");
}

// CHECK-LABEL: @ffdmdswq_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.ffdmds.v4f32(<8 x float> [[A:%.*]], <8 x float> [[B:%.*]], <4 x float> [[C:%.*]], i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 ffdmdswq_rn_s(v8f32 a, v8f32 b, v4f32 c) {
  return __builtin_kvx_ffdmdswq(a, b, c, ".rn.s");
}
