// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -target-cpu kv3-1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck --check-prefixes=ALL,CV1 %s
// RUN: %clang_cc1 -target-cpu kv3-2 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck --check-prefixes=ALL,CV2 %s

#include "vector-types.h"

// ALL-LABEL: @ffdmdaw(
// ALL-NEXT:  entry:
// ALL-NEXT:    [[TMP0:%.*]] = tail call float @llvm.kvx.ffdmda.f32(<2 x float> [[A:%.*]], <2 x float> [[B:%.*]], float [[C:%.*]], i32 7, i32 0)
// ALL-NEXT:    ret float [[TMP0]]
//
float ffdmdaw(v2f32 a, v2f32 b, float c){
    return __builtin_kvx_ffdmdaw(a, b, c, "");
}

// ALL-LABEL: @ffdmdawp(
// ALL-NEXT:  entry:
// ALL-NEXT:    [[TMP0:%.*]] = tail call <2 x float> @llvm.kvx.ffdmda.v2f32(<4 x float> [[A:%.*]], <4 x float> [[B:%.*]], <2 x float> [[C:%.*]], i32 7, i32 0)
// ALL-NEXT:    ret <2 x float> [[TMP0]]
//
v2f32 ffdmdawp(v4f32 a, v4f32 b, v2f32 c){
    return __builtin_kvx_ffdmdawp(a, b, c, "");
}

// CV1-LABEL: @ffdmdawq(
// CV1-NEXT:  entry:
// CV1-NEXT:    [[TMP0:%.*]] = shufflevector <4 x float> [[C:%.*]], <4 x float> undef, <2 x i32> <i32 0, i32 1>
// CV1-NEXT:    [[TMP1:%.*]] = shufflevector <8 x float> [[A:%.*]], <8 x float> undef, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
// CV1-NEXT:    [[TMP2:%.*]] = shufflevector <8 x float> [[B:%.*]], <8 x float> undef, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
// CV1-NEXT:    [[TMP3:%.*]] = shufflevector <4 x float> [[C]], <4 x float> undef, <2 x i32> <i32 2, i32 3>
// CV1-NEXT:    [[TMP4:%.*]] = shufflevector <8 x float> [[A]], <8 x float> undef, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
// CV1-NEXT:    [[TMP5:%.*]] = shufflevector <8 x float> [[B]], <8 x float> undef, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
// CV1-NEXT:    [[TMP6:%.*]] = tail call <2 x float> @llvm.kvx.ffdmda.v2f32(<4 x float> [[TMP1]], <4 x float> [[TMP2]], <2 x float> [[TMP0]], i32 7, i32 0)
// CV1-NEXT:    [[TMP7:%.*]] = tail call <2 x float> @llvm.kvx.ffdmda.v2f32(<4 x float> [[TMP4]], <4 x float> [[TMP5]], <2 x float> [[TMP3]], i32 7, i32 0)
// CV1-NEXT:    [[TMP8:%.*]] = shufflevector <2 x float> [[TMP6]], <2 x float> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CV1-NEXT:    ret <4 x float> [[TMP8]]
//
// CV2-LABEL: @ffdmdawq(
// CV2-NEXT:  entry:
// CV2-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.ffdmda.v4f32(<8 x float> [[A:%.*]], <8 x float> [[B:%.*]], <4 x float> [[C:%.*]], i32 7, i32 0)
// CV2-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 ffdmdawq(v8f32 a, v8f32 b, v4f32 c) {
  return __builtin_kvx_ffdmdawq(a, b, c, "");
}

// CV1-LABEL: @ffdmdawq_rn_s(
// CV1-NEXT:  entry:
// CV1-NEXT:    [[TMP0:%.*]] = shufflevector <4 x float> [[C:%.*]], <4 x float> undef, <2 x i32> <i32 0, i32 1>
// CV1-NEXT:    [[TMP1:%.*]] = shufflevector <8 x float> [[A:%.*]], <8 x float> undef, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
// CV1-NEXT:    [[TMP2:%.*]] = shufflevector <8 x float> [[B:%.*]], <8 x float> undef, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
// CV1-NEXT:    [[TMP3:%.*]] = shufflevector <4 x float> [[C]], <4 x float> undef, <2 x i32> <i32 2, i32 3>
// CV1-NEXT:    [[TMP4:%.*]] = shufflevector <8 x float> [[A]], <8 x float> undef, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
// CV1-NEXT:    [[TMP5:%.*]] = shufflevector <8 x float> [[B]], <8 x float> undef, <4 x i32> <i32 2, i32 3, i32 6, i32 7>
// CV1-NEXT:    [[TMP6:%.*]] = tail call <2 x float> @llvm.kvx.ffdmda.v2f32(<4 x float> [[TMP1]], <4 x float> [[TMP2]], <2 x float> [[TMP0]], i32 0, i32 1)
// CV1-NEXT:    [[TMP7:%.*]] = tail call <2 x float> @llvm.kvx.ffdmda.v2f32(<4 x float> [[TMP4]], <4 x float> [[TMP5]], <2 x float> [[TMP3]], i32 0, i32 1)
// CV1-NEXT:    [[TMP8:%.*]] = shufflevector <2 x float> [[TMP6]], <2 x float> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CV1-NEXT:    ret <4 x float> [[TMP8]]
//
// CV2-LABEL: @ffdmdawq_rn_s(
// CV2-NEXT:  entry:
// CV2-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.ffdmda.v4f32(<8 x float> [[A:%.*]], <8 x float> [[B:%.*]], <4 x float> [[C:%.*]], i32 0, i32 1)
// CV2-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 ffdmdawq_rn_s(v8f32 a, v8f32 b, v4f32 c) {
  return __builtin_kvx_ffdmdawq(a, b, c, ".rn.s");
}
