// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @ffdmsw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call float @llvm.kvx.ffdms.f32(<2 x float> [[A:%.*]], <2 x float> [[B:%.*]], i32 7, i32 0)
// CHECK-NEXT:    ret float [[TMP0]]
//
float ffdmsw(v2f32 a, v2f32 b) {
  return __builtin_kvx_ffdmsw(a, b, "");
}

// CHECK-LABEL: @ffdmswp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x float> @llvm.kvx.ffdms.v2f32(<4 x float> [[A:%.*]], <4 x float> [[B:%.*]], i32 7, i32 0)
// CHECK-NEXT:    ret <2 x float> [[TMP0]]
//
v2f32 ffdmswp(v4f32 a, v4f32 b, v2f32 c) {
  return __builtin_kvx_ffdmswp(a, b, "");
}

// CHECK-LABEL: @ffdmswq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.ffdms.v4f32(<8 x float> [[A:%.*]], <8 x float> [[B:%.*]], i32 7, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 ffdmswq(v8f32 a, v8f32 b) {
  return __builtin_kvx_ffdmswq(a, b, "");
}

// CHECK-LABEL: @ffdmswq_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.ffdms.v4f32(<8 x float> [[A:%.*]], <8 x float> [[B:%.*]], i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 ffdmswq_rn_s(v8f32 a, v8f32 b) {
  return __builtin_kvx_ffdmswq(a, b, ".rn.s");
}
