// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s
#include "vector-types.h"
// CHECK-LABEL: @ffmad(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call double @llvm.kvx.ffma.f64(double [[A:%.*]], double [[B:%.*]], double [[C:%.*]], i32 3, i32 0)
// CHECK-NEXT:    ret double [[TMP0]]
//
double ffmad(double a, double b, double c) { return __builtin_kvx_ffmad(a, b, c, ".rz"); }
// CHECK-LABEL: @ffmadp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x double> [[V1:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x double> [[V2:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x double> [[V3:%.*]], i64 0
// CHECK-NEXT:    [[TMP3:%.*]] = tail call double @llvm.kvx.ffma.f64(double [[TMP0]], double [[TMP1]], double [[TMP2]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x double> [[V1]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractelement <2 x double> [[V2]], i64 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <2 x double> [[V3]], i64 1
// CHECK-NEXT:    [[TMP7:%.*]] = tail call double @llvm.kvx.ffma.f64(double [[TMP4]], double [[TMP5]], double [[TMP6]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <2 x double> undef, double [[TMP3]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <2 x double> [[TMP8]], double [[TMP7]], i64 1
// CHECK-NEXT:    ret <2 x double> [[TMP9]]
//
v2f64 ffmadp(v2f64 v1, v2f64 v2, v2f64 v3) { return __builtin_kvx_ffmadp(v1, v2, v3, ".rn"); }
// CHECK-LABEL: @ffmadq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x double> [[V1:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x double> [[V2:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x double> [[V3:%.*]], i64 0
// CHECK-NEXT:    [[TMP3:%.*]] = tail call double @llvm.kvx.ffma.f64(double [[TMP0]], double [[TMP1]], double [[TMP2]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x double> [[V1]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x double> [[V2]], i64 1
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x double> [[V3]], i64 1
// CHECK-NEXT:    [[TMP7:%.*]] = tail call double @llvm.kvx.ffma.f64(double [[TMP4]], double [[TMP5]], double [[TMP6]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = extractelement <4 x double> [[V1]], i64 2
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x double> [[V2]], i64 2
// CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x double> [[V3]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = tail call double @llvm.kvx.ffma.f64(double [[TMP8]], double [[TMP9]], double [[TMP10]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = extractelement <4 x double> [[V1]], i64 3
// CHECK-NEXT:    [[TMP13:%.*]] = extractelement <4 x double> [[V2]], i64 3
// CHECK-NEXT:    [[TMP14:%.*]] = extractelement <4 x double> [[V3]], i64 3
// CHECK-NEXT:    [[TMP15:%.*]] = tail call double @llvm.kvx.ffma.f64(double [[TMP12]], double [[TMP13]], double [[TMP14]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP16:%.*]] = insertelement <4 x double> undef, double [[TMP3]], i64 0
// CHECK-NEXT:    [[TMP17:%.*]] = insertelement <4 x double> [[TMP16]], double [[TMP7]], i64 1
// CHECK-NEXT:    [[TMP18:%.*]] = insertelement <4 x double> [[TMP17]], double [[TMP11]], i64 2
// CHECK-NEXT:    [[TMP19:%.*]] = insertelement <4 x double> [[TMP18]], double [[TMP15]], i64 3
// CHECK-NEXT:    ret <4 x double> [[TMP19]]
//
v4f64 ffmadq(v4f64 v1, v4f64 v2, v4f64 v3) { return __builtin_kvx_ffmadq(v1, v2, v3, ".rn"); }
// CHECK-LABEL: @ffmah(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call half @llvm.kvx.ffma.f16(half [[A:%.*]], half [[B:%.*]], half [[C:%.*]], i32 1, i32 1)
// CHECK-NEXT:    ret half [[TMP0]]
//
half ffmah(half a, half b, half c) { return __builtin_kvx_ffmah(a, b, c, ".ru.s"); }
// CHECK-LABEL: @ffmahp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x half> @llvm.kvx.ffma.v2f16(<2 x half> [[V1:%.*]], <2 x half> [[V2:%.*]], <2 x half> [[V3:%.*]], i32 3, i32 1)
// CHECK-NEXT:    ret <2 x half> [[TMP0]]
//
v2f16 ffmahp(v2f16 v1, v2f16 v2, v2f16 v3) { return __builtin_kvx_ffmahp(v1, v2, v3, ".rz.s"); }
// CHECK-LABEL: @ffmahq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.kvx.ffma.v4f16(<4 x half> [[V1:%.*]], <4 x half> [[V2:%.*]], <4 x half> [[V3:%.*]], i32 1, i32 1)
// CHECK-NEXT:    ret <4 x half> [[TMP0]]
//
v4f16 ffmahq(v4f16 v1, v4f16 v2, v4f16 v3) { return __builtin_kvx_ffmahq(v1, v2, v3, ".ru.s"); }
// CHECK-LABEL: @ffmaw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call float @llvm.kvx.ffma.f32(float [[A:%.*]], float [[B:%.*]], float [[C:%.*]], i32 3, i32 0)
// CHECK-NEXT:    ret float [[TMP0]]
//
float ffmaw(float a, float b, float c) { return __builtin_kvx_ffmaw(a, b, c, ".rz"); }
// CHECK-LABEL: @ffmawo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x float> [[V1:%.*]], <8 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x float> [[V2:%.*]], <8 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x float> [[V3:%.*]], <8 x float> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x float> @llvm.kvx.ffma.v4f32(<4 x float> [[TMP0]], <4 x float> [[TMP1]], <4 x float> [[TMP2]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x float> [[V1]], <8 x float> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <8 x float> [[V2]], <8 x float> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x float> [[V3]], <8 x float> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x float> @llvm.kvx.ffma.v4f32(<4 x float> [[TMP4]], <4 x float> [[TMP5]], <4 x float> [[TMP6]], i32 0, i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x float> [[TMP3]], <4 x float> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x float> [[TMP8]]
//
v8f32 ffmawo(v8f32 v1, v8f32 v2, v8f32 v3) { return __builtin_kvx_ffmawo(v1, v2, v3, ".rn"); }
// CHECK-LABEL: @ffmawp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x float> @llvm.kvx.ffma.v2f32(<2 x float> [[V1:%.*]], <2 x float> [[V2:%.*]], <2 x float> [[V3:%.*]], i32 0, i32 0)
// CHECK-NEXT:    ret <2 x float> [[TMP0]]
//
v2f32 ffmawp(v2f32 v1, v2f32 v2, v2f32 v3) { return __builtin_kvx_ffmawp(v1, v2, v3, ".rn"); }
// CHECK-LABEL: @ffmawq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.ffma.v4f32(<4 x float> [[V1:%.*]], <4 x float> [[V2:%.*]], <4 x float> [[V3:%.*]], i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 ffmawq(v4f32 v1, v4f32 v2, v4f32 v3) { return __builtin_kvx_ffmawq(v1, v2, v3, ".rn"); }

// CHECK-LABEL: @ffmaho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.kvx.ffma.v8f16(<8 x half> [[V1:%.*]], <8 x half> [[V2:%.*]], <8 x half> [[V3:%.*]], i32 1, i32 1)
// CHECK-NEXT:    ret <8 x half> [[TMP0]]
//
v8f16 ffmaho(v8f16 v1, v8f16 v2, v8f16 v3) { return __builtin_kvx_ffmaho(v1, v2, v3, ".ru.s"); }
// CHECK-LABEL: @ffmahx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x half> [[V1:%.*]], <16 x half> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x half> [[V2:%.*]], <16 x half> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x half> [[V3:%.*]], <16 x half> poison, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x half> @llvm.kvx.ffma.v8f16(<8 x half> [[TMP0]], <8 x half> [[TMP1]], <8 x half> [[TMP2]], i32 1, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x half> [[V1]], <16 x half> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x half> [[V2]], <16 x half> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x half> [[V3]], <16 x half> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x half> @llvm.kvx.ffma.v8f16(<8 x half> [[TMP4]], <8 x half> [[TMP5]], <8 x half> [[TMP6]], i32 1, i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x half> [[TMP3]], <8 x half> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x half> [[TMP8]]
//
v16f16 ffmahx(v16f16 v1, v16f16 v2, v16f16 v3) { return __builtin_kvx_ffmahx(v1, v2, v3, ".ru.s"); }
//
