// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -S -O2 -emit-llvm -o - %s | FileCheck %s
#include "vector-types.h"
// CHECK-LABEL: @ffmaho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x half> @llvm.kvx.ffma.v8f16(<8 x half> [[V1:%.*]], <8 x half> [[V2:%.*]], <8 x half> [[V3:%.*]], i32 1, i32 1)
// CHECK-NEXT:    ret <8 x half> [[TMP0]]
//
v8f16 ffmaho(v8f16 v1, v8f16 v2, v8f16 v3) { return __builtin_kvx_ffmaho(v1, v2, v3, ".ru.s"); }
// CHECK-LABEL: @ffmahx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x half> [[V1:%.*]], <16 x half> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x half> [[V2:%.*]], <16 x half> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x half> [[V3:%.*]], <16 x half> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x half> @llvm.kvx.ffma.v8f16(<8 x half> [[TMP0]], <8 x half> [[TMP1]], <8 x half> [[TMP2]], i32 1, i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x half> [[V1]], <16 x half> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x half> [[V2]], <16 x half> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x half> [[V3]], <16 x half> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x half> @llvm.kvx.ffma.v8f16(<8 x half> [[TMP4]], <8 x half> [[TMP5]], <8 x half> [[TMP6]], i32 1, i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x half> [[TMP3]], <8 x half> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x half> [[TMP8]]
//
v16f16 ffmahx(v16f16 v1, v16f16 v2, v16f16 v3) { return __builtin_kvx_ffmahx(v1, v2, v3, ".ru.s"); }
//
