// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"


// CHECK-LABEL: @fmaxh(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call half @llvm.kvx.max.f16(half [[V1:%.*]], half [[V2:%.*]])
// CHECK-NEXT:    ret half [[TMP0]]
//
_Float16 fmaxh(_Float16 v1, _Float16 v2) {
  return __builtin_kvx_fmaxh(v1, v2);
}

// CHECK-LABEL: @fmaxw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call float @llvm.kvx.max.f32(float [[V1:%.*]], float [[V2:%.*]])
// CHECK-NEXT:    ret float [[TMP0]]
//
float fmaxw(float v1, float v2) {
  return __builtin_kvx_fmaxw(v1, v2);
}

// CHECK-LABEL: @fmaxd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call double @llvm.kvx.max.f64(double [[V1:%.*]], double [[V2:%.*]])
// CHECK-NEXT:    ret double [[TMP0]]
//
double fmaxd(double v1, double v2) {
  return __builtin_kvx_fmaxd(v1, v2);
}

// CHECK-LABEL: @fmaxhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.kvx.max.v4f16(<4 x half> [[V1:%.*]], <4 x half> [[V2:%.*]])
// CHECK-NEXT:    ret <4 x half> [[TMP0]]
//
v4f16 fmaxhq(v4f16 v1, v4f16 v2) {
  return __builtin_kvx_fmaxhq(v1, v2);
}

// CHECK-LABEL: @fmaxho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x half> [[V1:%.*]], <8 x half> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x half> [[V2:%.*]], <8 x half> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x half> @llvm.kvx.max.v4f16(<4 x half> [[TMP0]], <4 x half> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x half> [[V1]], <8 x half> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x half> [[V2]], <8 x half> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x half> @llvm.kvx.max.v4f16(<4 x half> [[TMP3]], <4 x half> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x half> [[TMP2]], <4 x half> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x half> [[TMP6]]
//
v8f16 fmaxho(v8f16 v1, v8f16 v2) {
  return __builtin_kvx_fmaxho(v1, v2);
}

// CHECK-LABEL: @fmaxhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x half> [[V1:%.*]], <16 x half> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x half> [[V2:%.*]], <16 x half> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x half> @llvm.kvx.max.v4f16(<4 x half> [[TMP0]], <4 x half> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x half> [[V1]], <16 x half> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x half> [[V2]], <16 x half> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x half> @llvm.kvx.max.v4f16(<4 x half> [[TMP3]], <4 x half> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x half> [[V1]], <16 x half> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x half> [[V2]], <16 x half> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x half> @llvm.kvx.max.v4f16(<4 x half> [[TMP6]], <4 x half> [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x half> [[V1]], <16 x half> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x half> [[V2]], <16 x half> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x half> @llvm.kvx.max.v4f16(<4 x half> [[TMP9]], <4 x half> [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x half> [[TMP2]], <4 x half> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x half> [[TMP8]], <4 x half> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x half> [[TMP12]], <8 x half> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x half> [[TMP14]]
//
v16f16 fmaxhx(v16f16 v1, v16f16 v2) {
  return __builtin_kvx_fmaxhx(v1, v2);
}

// CHECK-LABEL: @fmaxwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x float> @llvm.kvx.max.v2f32(<2 x float> [[V1:%.*]], <2 x float> [[V2:%.*]])
// CHECK-NEXT:    ret <2 x float> [[TMP0]]
//
v2f32 fmaxwp(v2f32 v1, v2f32 v2) {
  return __builtin_kvx_fmaxwp(v1, v2);
}

// CHECK-LABEL: @fmaxwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x float> [[V1:%.*]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x float> [[V2:%.*]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x float> @llvm.kvx.max.v2f32(<2 x float> [[TMP0]], <2 x float> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x float> [[V1]], <4 x float> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x float> [[V2]], <4 x float> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x float> @llvm.kvx.max.v2f32(<2 x float> [[TMP3]], <2 x float> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x float> [[TMP2]], <2 x float> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x float> [[TMP6]]
//
v4f32 fmaxwq(v4f32 v1, v4f32 v2) {
  return __builtin_kvx_fmaxwq(v1, v2);
}

// CHECK-LABEL: @fmaxwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x float> [[V1:%.*]], <8 x float> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x float> [[V2:%.*]], <8 x float> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x float> @llvm.kvx.max.v2f32(<2 x float> [[TMP0]], <2 x float> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x float> [[V1]], <8 x float> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x float> [[V2]], <8 x float> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x float> @llvm.kvx.max.v2f32(<2 x float> [[TMP3]], <2 x float> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x float> [[V1]], <8 x float> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x float> [[V2]], <8 x float> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x float> @llvm.kvx.max.v2f32(<2 x float> [[TMP6]], <2 x float> [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x float> [[V1]], <8 x float> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x float> [[V2]], <8 x float> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x float> @llvm.kvx.max.v2f32(<2 x float> [[TMP9]], <2 x float> [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x float> [[TMP2]], <2 x float> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x float> [[TMP8]], <2 x float> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x float> [[TMP12]], <4 x float> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x float> [[TMP14]]
//
v8f32 fmaxwo(v8f32 v1, v8f32 v2) {
  return __builtin_kvx_fmaxwo(v1, v2);
}

// CHECK-LABEL: @fmaxdp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x double> [[V1:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x double> [[V2:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call double @llvm.kvx.max.f64(double [[TMP0]], double [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x double> [[V1]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x double> [[V2]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call double @llvm.kvx.max.f64(double [[TMP3]], double [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x double> undef, double [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x double> [[TMP6]], double [[TMP5]], i64 1
// CHECK-NEXT:    ret <2 x double> [[TMP7]]
//
v2f64 fmaxdp(v2f64 v1, v2f64 v2) {
  return __builtin_kvx_fmaxdp(v1, v2);
}

// CHECK-LABEL: @fmaxdq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x double> [[V1:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x double> [[V2:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call double @llvm.kvx.max.f64(double [[TMP0]], double [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x double> [[V1]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x double> [[V2]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call double @llvm.kvx.max.f64(double [[TMP3]], double [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x double> [[V1]], i64 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x double> [[V2]], i64 2
// CHECK-NEXT:    [[TMP8:%.*]] = tail call double @llvm.kvx.max.f64(double [[TMP6]], double [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x double> [[V1]], i64 3
// CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x double> [[V2]], i64 3
// CHECK-NEXT:    [[TMP11:%.*]] = tail call double @llvm.kvx.max.f64(double [[TMP9]], double [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x double> undef, double [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP13:%.*]] = insertelement <4 x double> [[TMP12]], double [[TMP5]], i64 1
// CHECK-NEXT:    [[TMP14:%.*]] = insertelement <4 x double> [[TMP13]], double [[TMP8]], i64 2
// CHECK-NEXT:    [[TMP15:%.*]] = insertelement <4 x double> [[TMP14]], double [[TMP11]], i64 3
// CHECK-NEXT:    ret <4 x double> [[TMP15]]
//
v4f64 fmaxdq(v4f64 v1, v4f64 v2) {
  return __builtin_kvx_fmaxdq(v1, v2);
}
