// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @fminw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call float @llvm.kvx.min.f32(float [[V1:%.*]], float [[V2:%.*]])
// CHECK-NEXT:    ret float [[TMP0]]
//
float fminw(float v1, float v2) {
  return __builtin_kvx_fminw(v1, v2);
}

// CHECK-LABEL: @fmind(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call double @llvm.kvx.min.f64(double [[V1:%.*]], double [[V2:%.*]])
// CHECK-NEXT:    ret double [[TMP0]]
//
double fmind(double v1, double v2) {
  return __builtin_kvx_fmind(v1, v2);
}

// CHECK-LABEL: @fminh(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call half @llvm.kvx.min.f16(half [[V1:%.*]], half [[V2:%.*]])
// CHECK-NEXT:    ret half [[TMP0]]
//
_Float16 fminh(_Float16 v1, _Float16 v2) {
  return __builtin_kvx_fminh(v1, v2);
}

// CHECK-LABEL: @fminhp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x half> @llvm.kvx.min.v2f16(<2 x half> [[V1:%.*]], <2 x half> [[V2:%.*]])
// CHECK-NEXT:    ret <2 x half> [[TMP0]]
//
v2f16 fminhp(v2f16 v1, v2f16 v2) {
  return __builtin_kvx_fminhp(v1, v2);
}

// CHECK-LABEL: @fminhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x half> @llvm.kvx.min.v4f16(<4 x half> [[V1:%.*]], <4 x half> [[V2:%.*]])
// CHECK-NEXT:    ret <4 x half> [[TMP0]]
//
v4f16 fminhq(v4f16 v1, v4f16 v2) {
  return __builtin_kvx_fminhq(v1, v2);
}

// CHECK-LABEL: @fminho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x half> [[V1:%.*]], <8 x half> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x half> [[V2:%.*]], <8 x half> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x half> @llvm.kvx.min.v4f16(<4 x half> [[TMP0]], <4 x half> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x half> [[V1]], <8 x half> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x half> [[V2]], <8 x half> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x half> @llvm.kvx.min.v4f16(<4 x half> [[TMP3]], <4 x half> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x half> [[TMP2]], <4 x half> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x half> [[TMP6]]
//
v8f16 fminho(v8f16 v1, v8f16 v2) {
  return __builtin_kvx_fminho(v1, v2);
}

// CHECK-LABEL: @fminhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x half> [[V1:%.*]], <16 x half> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x half> [[V2:%.*]], <16 x half> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x half> @llvm.kvx.min.v4f16(<4 x half> [[TMP0]], <4 x half> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x half> [[V1]], <16 x half> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x half> [[V2]], <16 x half> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x half> @llvm.kvx.min.v4f16(<4 x half> [[TMP3]], <4 x half> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x half> [[V1]], <16 x half> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x half> [[V2]], <16 x half> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x half> @llvm.kvx.min.v4f16(<4 x half> [[TMP6]], <4 x half> [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x half> [[V1]], <16 x half> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x half> [[V2]], <16 x half> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x half> @llvm.kvx.min.v4f16(<4 x half> [[TMP9]], <4 x half> [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x half> [[TMP2]], <4 x half> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x half> [[TMP8]], <4 x half> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x half> [[TMP12]], <8 x half> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x half> [[TMP14]]
//
v16f16 fminhx(v16f16 v1, v16f16 v2) {
  return __builtin_kvx_fminhx(v1, v2);
}

// CHECK-LABEL: @fminwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x float> @llvm.kvx.min.v2f32(<2 x float> [[V1:%.*]], <2 x float> [[V2:%.*]])
// CHECK-NEXT:    ret <2 x float> [[TMP0]]
//
v2f32 fminwp(v2f32 v1, v2f32 v2) {
  return __builtin_kvx_fminwp(v1, v2);
}

// CHECK-LABEL: @fminwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x float> [[V1:%.*]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x float> [[V2:%.*]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x float> @llvm.kvx.min.v2f32(<2 x float> [[TMP0]], <2 x float> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x float> [[V1]], <4 x float> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x float> [[V2]], <4 x float> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x float> @llvm.kvx.min.v2f32(<2 x float> [[TMP3]], <2 x float> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x float> [[TMP2]], <2 x float> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x float> [[TMP6]]
//
v4f32 fminwq(v4f32 v1, v4f32 v2) {
  return __builtin_kvx_fminwq(v1, v2);
}

// CHECK-LABEL: @fminwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x float> [[V1:%.*]], <8 x float> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x float> [[V2:%.*]], <8 x float> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x float> @llvm.kvx.min.v2f32(<2 x float> [[TMP0]], <2 x float> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x float> [[V1]], <8 x float> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x float> [[V2]], <8 x float> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x float> @llvm.kvx.min.v2f32(<2 x float> [[TMP3]], <2 x float> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x float> [[V1]], <8 x float> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x float> [[V2]], <8 x float> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x float> @llvm.kvx.min.v2f32(<2 x float> [[TMP6]], <2 x float> [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x float> [[V1]], <8 x float> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x float> [[V2]], <8 x float> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x float> @llvm.kvx.min.v2f32(<2 x float> [[TMP9]], <2 x float> [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x float> [[TMP2]], <2 x float> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x float> [[TMP8]], <2 x float> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x float> [[TMP12]], <4 x float> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x float> [[TMP14]]
//
v8f32 fminwo(v8f32 v1, v8f32 v2) {
  return __builtin_kvx_fminwo(v1, v2);
}

// CHECK-LABEL: @fmindp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x double> [[V1:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <2 x double> [[V2:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call double @llvm.kvx.min.f64(double [[TMP0]], double [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <2 x double> [[V1]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <2 x double> [[V2]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call double @llvm.kvx.min.f64(double [[TMP3]], double [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = insertelement <2 x double> undef, double [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP7:%.*]] = insertelement <2 x double> [[TMP6]], double [[TMP5]], i64 1
// CHECK-NEXT:    ret <2 x double> [[TMP7]]
//
v2f64 fmindp(v2f64 v1, v2f64 v2) {
  return __builtin_kvx_fmindp(v1, v2);
}

// CHECK-LABEL: @fmindq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x double> [[V1:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x double> [[V2:%.*]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call double @llvm.kvx.min.f64(double [[TMP0]], double [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x double> [[V1]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x double> [[V2]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = tail call double @llvm.kvx.min.f64(double [[TMP3]], double [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x double> [[V1]], i64 2
// CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x double> [[V2]], i64 2
// CHECK-NEXT:    [[TMP8:%.*]] = tail call double @llvm.kvx.min.f64(double [[TMP6]], double [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x double> [[V1]], i64 3
// CHECK-NEXT:    [[TMP10:%.*]] = extractelement <4 x double> [[V2]], i64 3
// CHECK-NEXT:    [[TMP11:%.*]] = tail call double @llvm.kvx.min.f64(double [[TMP9]], double [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = insertelement <4 x double> undef, double [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP13:%.*]] = insertelement <4 x double> [[TMP12]], double [[TMP5]], i64 1
// CHECK-NEXT:    [[TMP14:%.*]] = insertelement <4 x double> [[TMP13]], double [[TMP8]], i64 2
// CHECK-NEXT:    [[TMP15:%.*]] = insertelement <4 x double> [[TMP14]], double [[TMP11]], i64 3
// CHECK-NEXT:    ret <4 x double> [[TMP15]]
//
v4f64 fmindq(v4f64 v1, v4f64 v2) {
  return __builtin_kvx_fmindq(v1, v2);
}

