// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -emit-llvm %s -O2 -o - | FileCheck %s

typedef float float4 __attribute__ ((vector_size (sizeof(float) * 4)));

// CHECK-LABEL: @fmm(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, "");
}

// CHECK-LABEL: @fmm_2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn");
}

// CHECK-LABEL: @fmma222w(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = fadd fast <4 x float> [[TMP0]], [[ACC:%.*]]
// CHECK-NEXT:    ret <4 x float> [[TMP1]]
//
float4 fmma222w(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, "");
}

// CHECK-LABEL: @fmma222w_2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = fadd fast <4 x float> [[TMP0]], [[ACC:%.*]]
// CHECK-NEXT:    ret <4 x float> [[TMP1]]
//
float4 fmma222w_2(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn");
}

// CHECK-LABEL: @fmms222w(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = fsub fast <4 x float> [[ACC:%.*]], [[TMP0]]
// CHECK-NEXT:    ret <4 x float> [[TMP1]]
//
float4 fmms222w(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, "");
}

// CHECK-LABEL: @fmms222w_2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = fsub fast <4 x float> [[ACC:%.*]], [[TMP0]]
// CHECK-NEXT:    ret <4 x float> [[TMP1]]
//
float4 fmms222w_2(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn");
}

// CHECK-LABEL: @fmm_tn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[LHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[TMP0]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    ret <4 x float> [[TMP1]]
//
float4 fmm_tn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn");
}

// CHECK-LABEL: @fmm_2_tn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[LHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[TMP0]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    ret <4 x float> [[TMP1]]
//
float4 fmm_2_tn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn");
}

// CHECK-LABEL: @fmma222w_2_tn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[LHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[TMP0]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = fadd fast <4 x float> [[TMP1]], [[ACC:%.*]]
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float4 fmma222w_2_tn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn");
}

// CHECK-LABEL: @fmms222w_2_tn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[LHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[TMP0]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = fsub fast <4 x float> [[ACC:%.*]], [[TMP1]]
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float4 fmms222w_2_tn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn");
}

// CHECK-LABEL: @fmm_nt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[RHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[TMP0]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    ret <4 x float> [[TMP1]]
//
float4 fmm_nt(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt");
}

// CHECK-LABEL: @fmm_2_nt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[RHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[TMP0]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    ret <4 x float> [[TMP1]]
//
float4 fmm_2_nt(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt");
}

// CHECK-LABEL: @fmma222w_2_nt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[RHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[TMP0]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = fadd fast <4 x float> [[TMP1]], [[ACC:%.*]]
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float4 fmma222w_2_nt(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt");
}

// CHECK-LABEL: @fmms222w_2_nt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[RHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[LHS:%.*]], <4 x float> [[TMP0]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = fsub fast <4 x float> [[ACC:%.*]], [[TMP1]]
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float4 fmms222w_2_nt(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt");
}

// CHECK-LABEL: @fmm_tt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[LHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[RHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[TMP0]], <4 x float> [[TMP1]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float4 fmm_tt(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt");
}

// CHECK-LABEL: @fmm_2_tt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[LHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[RHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[TMP0]], <4 x float> [[TMP1]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float4 fmm_2_tt(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt");
}

// CHECK-LABEL: @fmma222w_2_tt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[LHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[RHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[TMP0]], <4 x float> [[TMP1]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = fadd fast <4 x float> [[TMP2]], [[ACC:%.*]]
// CHECK-NEXT:    ret <4 x float> [[TMP3]]
//
float4 fmma222w_2_tt(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt");
}

// CHECK-LABEL: @fmms222w_2_tt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[LHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.matrix.transpose.v4f32(<4 x float> [[RHS:%.*]], i32 2, i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x float> @llvm.matrix.multiply.v4f32.v4f32.v4f32(<4 x float> [[TMP0]], <4 x float> [[TMP1]], i32 2, i32 2, i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = fsub fast <4 x float> [[ACC:%.*]], [[TMP2]]
// CHECK-NEXT:    ret <4 x float> [[TMP3]]
//
float4 fmms222w_2_tt(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt");
}

// CHECK-LABEL: @fmm_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_rn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".rn");
}

// CHECK-LABEL: @fmm_2_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_rn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn.rn");
}

// CHECK-LABEL: @fmma222w_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".rn");
}

// CHECK-LABEL: @fmma222w_2_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn.rn");
}

// CHECK-LABEL: @fmms222w_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".rn");
}

// CHECK-LABEL: @fmms222w_2_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn.rn");
}

// CHECK-LABEL: @fmm_tn_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tn_rn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rn");
}

// CHECK-LABEL: @fmm_2_tn_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tn_rn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rn");
}

// CHECK-LABEL: @fmma222w_2_tn_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tn_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn.rn");
}

// CHECK-LABEL: @fmms222w_2_tn_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tn_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn.rn");
}

// CHECK-LABEL: @fmm_nt_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_nt_rn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rn");
}

// CHECK-LABEL: @fmm_2_nt_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_nt_rn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rn");
}

// CHECK-LABEL: @fmma222w_2_nt_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_nt_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt.rn");
}

// CHECK-LABEL: @fmms222w_2_nt_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_nt_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt.rn");
}

// CHECK-LABEL: @fmm_tt_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tt_rn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rn");
}

// CHECK-LABEL: @fmm_2_tt_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tt_rn(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rn");
}

// CHECK-LABEL: @fmma222w_2_tt_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tt_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt.rn");
}

// CHECK-LABEL: @fmms222w_2_tt_rn(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tt_rn(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt.rn");
}

// CHECK-LABEL: @fmm_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_ru(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".ru");
}

// CHECK-LABEL: @fmm_2_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_ru(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn.ru");
}

// CHECK-LABEL: @fmma222w_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".ru");
}

// CHECK-LABEL: @fmma222w_2_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn.ru");
}

// CHECK-LABEL: @fmms222w_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".ru");
}

// CHECK-LABEL: @fmms222w_2_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn.ru");
}

// CHECK-LABEL: @fmm_tn_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tn_ru(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.ru");
}

// CHECK-LABEL: @fmm_2_tn_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tn_ru(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.ru");
}

// CHECK-LABEL: @fmma222w_2_tn_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tn_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn.ru");
}

// CHECK-LABEL: @fmms222w_2_tn_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tn_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn.ru");
}

// CHECK-LABEL: @fmm_nt_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_nt_ru(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.ru");
}

// CHECK-LABEL: @fmm_2_nt_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_nt_ru(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.ru");
}

// CHECK-LABEL: @fmma222w_2_nt_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_nt_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt.ru");
}

// CHECK-LABEL: @fmms222w_2_nt_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_nt_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt.ru");
}

// CHECK-LABEL: @fmm_tt_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tt_ru(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.ru");
}

// CHECK-LABEL: @fmm_2_tt_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tt_ru(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.ru");
}

// CHECK-LABEL: @fmma222w_2_tt_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tt_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt.ru");
}

// CHECK-LABEL: @fmms222w_2_tt_ru(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 1, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tt_ru(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt.ru");
}

// CHECK-LABEL: @fmm_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_rd(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".rd");
}

// CHECK-LABEL: @fmm_2_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_rd(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn.rd");
}

// CHECK-LABEL: @fmma222w_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".rd");
}

// CHECK-LABEL: @fmma222w_2_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn.rd");
}

// CHECK-LABEL: @fmms222w_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".rd");
}

// CHECK-LABEL: @fmms222w_2_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn.rd");
}

// CHECK-LABEL: @fmm_tn_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tn_rd(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rd");
}

// CHECK-LABEL: @fmm_2_tn_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tn_rd(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rd");
}

// CHECK-LABEL: @fmma222w_2_tn_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tn_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn.rd");
}

// CHECK-LABEL: @fmms222w_2_tn_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tn_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn.rd");
}

// CHECK-LABEL: @fmm_nt_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_nt_rd(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rd");
}

// CHECK-LABEL: @fmm_2_nt_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_nt_rd(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rd");
}

// CHECK-LABEL: @fmma222w_2_nt_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_nt_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt.rd");
}

// CHECK-LABEL: @fmms222w_2_nt_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_nt_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt.rd");
}

// CHECK-LABEL: @fmm_tt_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tt_rd(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rd");
}

// CHECK-LABEL: @fmm_2_tt_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tt_rd(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rd");
}

// CHECK-LABEL: @fmma222w_2_tt_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tt_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt.rd");
}

// CHECK-LABEL: @fmms222w_2_tt_rd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 2, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tt_rd(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt.rd");
}

// CHECK-LABEL: @fmm_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_rz(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".rz");
}

// CHECK-LABEL: @fmm_2_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_rz(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn.rz");
}

// CHECK-LABEL: @fmma222w_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".rz");
}

// CHECK-LABEL: @fmma222w_2_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn.rz");
}

// CHECK-LABEL: @fmms222w_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".rz");
}

// CHECK-LABEL: @fmms222w_2_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn.rz");
}

// CHECK-LABEL: @fmm_tn_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tn_rz(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rz");
}

// CHECK-LABEL: @fmm_2_tn_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tn_rz(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rz");
}

// CHECK-LABEL: @fmma222w_2_tn_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tn_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn.rz");
}

// CHECK-LABEL: @fmms222w_2_tn_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tn_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn.rz");
}

// CHECK-LABEL: @fmm_nt_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_nt_rz(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rz");
}

// CHECK-LABEL: @fmm_2_nt_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_nt_rz(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rz");
}

// CHECK-LABEL: @fmma222w_2_nt_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_nt_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt.rz");
}

// CHECK-LABEL: @fmms222w_2_nt_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_nt_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt.rz");
}

// CHECK-LABEL: @fmm_tt_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tt_rz(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rz");
}

// CHECK-LABEL: @fmm_2_tt_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tt_rz(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rz");
}

// CHECK-LABEL: @fmma222w_2_tt_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tt_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt.rz");
}

// CHECK-LABEL: @fmms222w_2_tt_rz(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 3, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tt_rz(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt.rz");
}

// CHECK-LABEL: @fmm_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".s");
}

// CHECK-LABEL: @fmm_2_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn.s");
}

// CHECK-LABEL: @fmma222w_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".s");
}

// CHECK-LABEL: @fmma222w_2_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn.s");
}

// CHECK-LABEL: @fmms222w_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".s");
}

// CHECK-LABEL: @fmms222w_2_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn.s");
}

// CHECK-LABEL: @fmm_tn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.s");
}

// CHECK-LABEL: @fmm_2_tn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.s");
}

// CHECK-LABEL: @fmma222w_2_tn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn.s");
}

// CHECK-LABEL: @fmms222w_2_tn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn.s");
}

// CHECK-LABEL: @fmm_nt_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_nt_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.s");
}

// CHECK-LABEL: @fmm_2_nt_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_nt_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.s");
}

// CHECK-LABEL: @fmma222w_2_nt_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_nt_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt.s");
}

// CHECK-LABEL: @fmms222w_2_nt_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_nt_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt.s");
}

// CHECK-LABEL: @fmm_tt_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tt_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.s");
}

// CHECK-LABEL: @fmm_2_tt_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tt_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.s");
}

// CHECK-LABEL: @fmma222w_2_tt_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tt_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt.s");
}

// CHECK-LABEL: @fmms222w_2_tt_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 7, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tt_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt.s");
}

// CHECK-LABEL: @fmm_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_rn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".rn.s");
}

// CHECK-LABEL: @fmm_2_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_rn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn.rn.s");
}

// CHECK-LABEL: @fmma222w_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".rn.s");
}

// CHECK-LABEL: @fmma222w_2_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn.rn.s");
}

// CHECK-LABEL: @fmms222w_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".rn.s");
}

// CHECK-LABEL: @fmms222w_2_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn.rn.s");
}

// CHECK-LABEL: @fmm_tn_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tn_rn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rn.s");
}

// CHECK-LABEL: @fmm_2_tn_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tn_rn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rn.s");
}

// CHECK-LABEL: @fmma222w_2_tn_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tn_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn.rn.s");
}

// CHECK-LABEL: @fmms222w_2_tn_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tn_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn.rn.s");
}

// CHECK-LABEL: @fmm_nt_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_nt_rn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rn.s");
}

// CHECK-LABEL: @fmm_2_nt_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_nt_rn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rn.s");
}

// CHECK-LABEL: @fmma222w_2_nt_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_nt_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt.rn.s");
}

// CHECK-LABEL: @fmms222w_2_nt_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_nt_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt.rn.s");
}

// CHECK-LABEL: @fmm_tt_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tt_rn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rn.s");
}

// CHECK-LABEL: @fmm_2_tt_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tt_rn_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rn.s");
}

// CHECK-LABEL: @fmma222w_2_tt_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tt_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt.rn.s");
}

// CHECK-LABEL: @fmms222w_2_tt_rn_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 0, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tt_rn_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt.rn.s");
}

// CHECK-LABEL: @fmm_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_ru_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".ru.s");
}

// CHECK-LABEL: @fmm_2_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_ru_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn.ru.s");
}

// CHECK-LABEL: @fmma222w_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".ru.s");
}

// CHECK-LABEL: @fmma222w_2_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn.ru.s");
}

// CHECK-LABEL: @fmms222w_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".ru.s");
}

// CHECK-LABEL: @fmms222w_2_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn.ru.s");
}

// CHECK-LABEL: @fmm_tn_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tn_ru_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.ru.s");
}

// CHECK-LABEL: @fmm_2_tn_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tn_ru_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.ru.s");
}

// CHECK-LABEL: @fmma222w_2_tn_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tn_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn.ru.s");
}

// CHECK-LABEL: @fmms222w_2_tn_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tn_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn.ru.s");
}

// CHECK-LABEL: @fmm_nt_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_nt_ru_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.ru.s");
}

// CHECK-LABEL: @fmm_2_nt_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_nt_ru_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.ru.s");
}

// CHECK-LABEL: @fmma222w_2_nt_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_nt_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt.ru.s");
}

// CHECK-LABEL: @fmms222w_2_nt_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_nt_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt.ru.s");
}

// CHECK-LABEL: @fmm_tt_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tt_ru_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.ru.s");
}

// CHECK-LABEL: @fmm_2_tt_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tt_ru_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.ru.s");
}

// CHECK-LABEL: @fmma222w_2_tt_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tt_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt.ru.s");
}

// CHECK-LABEL: @fmms222w_2_tt_ru_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 1, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tt_ru_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt.ru.s");
}

// CHECK-LABEL: @fmm_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_rd_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".rd.s");
}

// CHECK-LABEL: @fmm_2_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_rd_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn.rd.s");
}

// CHECK-LABEL: @fmma222w_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".rd.s");
}

// CHECK-LABEL: @fmma222w_2_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn.rd.s");
}

// CHECK-LABEL: @fmms222w_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".rd.s");
}

// CHECK-LABEL: @fmms222w_2_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn.rd.s");
}

// CHECK-LABEL: @fmm_tn_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tn_rd_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rd.s");
}

// CHECK-LABEL: @fmm_2_tn_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tn_rd_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rd.s");
}

// CHECK-LABEL: @fmma222w_2_tn_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tn_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn.rd.s");
}

// CHECK-LABEL: @fmms222w_2_tn_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tn_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn.rd.s");
}

// CHECK-LABEL: @fmm_nt_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_nt_rd_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rd.s");
}

// CHECK-LABEL: @fmm_2_nt_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_nt_rd_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rd.s");
}

// CHECK-LABEL: @fmma222w_2_nt_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_nt_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt.rd.s");
}

// CHECK-LABEL: @fmms222w_2_nt_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_nt_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt.rd.s");
}

// CHECK-LABEL: @fmm_tt_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tt_rd_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rd.s");
}

// CHECK-LABEL: @fmm_2_tt_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tt_rd_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rd.s");
}

// CHECK-LABEL: @fmma222w_2_tt_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tt_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt.rd.s");
}

// CHECK-LABEL: @fmms222w_2_tt_rd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 2, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tt_rd_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt.rd.s");
}

// CHECK-LABEL: @fmm_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_rz_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".rz.s");
}

// CHECK-LABEL: @fmm_2_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 0, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_rz_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nn.rz.s");
}

// CHECK-LABEL: @fmma222w_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".rz.s");
}

// CHECK-LABEL: @fmma222w_2_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nn.rz.s");
}

// CHECK-LABEL: @fmms222w_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".rz.s");
}

// CHECK-LABEL: @fmms222w_2_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 0, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nn.rz.s");
}

// CHECK-LABEL: @fmm_tn_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tn_rz_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rz.s");
}

// CHECK-LABEL: @fmm_2_tn_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 1, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tn_rz_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tn.rz.s");
}

// CHECK-LABEL: @fmma222w_2_tn_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tn_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tn.rz.s");
}

// CHECK-LABEL: @fmms222w_2_tn_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 1, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tn_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tn.rz.s");
}

// CHECK-LABEL: @fmm_nt_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_nt_rz_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rz.s");
}

// CHECK-LABEL: @fmm_2_nt_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 2, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_nt_rz_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".nt.rz.s");
}

// CHECK-LABEL: @fmma222w_2_nt_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_nt_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".nt.rz.s");
}

// CHECK-LABEL: @fmms222w_2_nt_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 2, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_nt_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".nt.rz.s");
}

// CHECK-LABEL: @fmm_tt_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_tt_rz_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rz.s");
}

// CHECK-LABEL: @fmm_2_tt_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], i32 3, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmm_2_tt_rz_s(float4 lhs, float4 rhs){
    return __builtin_kvx_fmm222w(lhs, rhs, ".tt.rz.s");
}

// CHECK-LABEL: @fmma222w_2_tt_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmma222w_2_tt_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmma222w(lhs, rhs, acc, ".tt.rz.s");
}

// CHECK-LABEL: @fmms222w_2_tt_rz_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms222w(<4 x float> [[LHS:%.*]], <4 x float> [[RHS:%.*]], <4 x float> [[ACC:%.*]], i32 3, i32 3, i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
float4 fmms222w_2_tt_rz_s(float4 lhs, float4 rhs, float4 acc){
    return __builtin_kvx_fmms222w(lhs, rhs, acc, ".tt.rz.s");
}
