// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @fmm212w(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmm212w(<2 x float> [[V1:%.*]], <2 x float> [[V2:%.*]], i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 fmm212w(v2f32 v1, v2f32 v2) {
  return __builtin_kvx_fmm212w(v1, v2, ".rn");
}

// CHECK-LABEL: @fmma212w(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmma212w(<2 x float> [[V1:%.*]], <2 x float> [[V2:%.*]], <4 x float> [[V3:%.*]], i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 fmma212w(v2f32 v1, v2f32 v2, v4f32 v3) {
  return __builtin_kvx_fmma212w(v1, v2, v3, ".rn");
}

// CHECK-LABEL: @fmms212w(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fmms212w(<2 x float> [[V1:%.*]], <2 x float> [[V2:%.*]], <4 x float> [[V3:%.*]], i32 0, i32 0)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 fmms212w(v2f32 v1, v2f32 v2, v4f32 v3) {
  return __builtin_kvx_fmms212w(v1, v2, v3, ".rn");
}
