// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @fwidenhw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call float @llvm.kvx.fwiden.f32(half [[X:%.*]], i32 1)
// CHECK-NEXT:    ret float [[TMP0]]
//
float fwidenhw(_Float16 x) {
  return __builtin_kvx_fwidenhw(x, ".s");
}

// CHECK-LABEL: @fwidenhwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x float> @llvm.kvx.fwiden.v2f32(<2 x half> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x float> [[TMP0]]
//
v2f32 fwidenhwp(v2f16 v) {
  return __builtin_kvx_fwidenhwp(v, ".s");
}

// CHECK-LABEL: @fwidenhwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x float> @llvm.kvx.fwiden.v4f32(<4 x half> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x float> [[TMP0]]
//
v4f32 fwidenhwq(v4f16 v) {
  return __builtin_kvx_fwidenhwq(v, ".s");
}

// CHECK-LABEL: @fwidenhwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x half> [[V:%.*]], <8 x half> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x float> @llvm.kvx.fwiden.v4f32(<4 x half> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x half> [[V]], <8 x half> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x float> @llvm.kvx.fwiden.v4f32(<4 x half> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x float> [[TMP1]], <4 x float> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x float> [[TMP4]]
//
v8f32 fwidenhwo(v8f16 v) {
  return __builtin_kvx_fwidenhwo(v, ".s");
}

// CHECK-LABEL: @fwidenwd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call double @llvm.kvx.fwiden.f64(float [[X:%.*]], i32 1)
// CHECK-NEXT:    ret double [[TMP0]]
//
double fwidenwd(float x) {
  return __builtin_kvx_fwidenwd(x, ".s");
}

// CHECK-LABEL: @fwidenwdp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x double> @llvm.kvx.fwiden.v2f64(<2 x float> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x double> [[TMP0]]
//
v2f64 fwidenwdp(v2f32 v) {
  return __builtin_kvx_fwidenwdp(v, ".s");
}

// CHECK-LABEL: @fwidenwdq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x float> [[V:%.*]], <4 x float> undef, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x double> @llvm.kvx.fwiden.v2f64(<2 x float> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x float> [[V]], <4 x float> undef, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x double> @llvm.kvx.fwiden.v2f64(<2 x float> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x double> [[TMP1]], <2 x double> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x double> [[TMP4]]
//
v4f64 fwidenwdq(v4f32 v) {
  return __builtin_kvx_fwidenwdq(v, ".s");
}
