// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-1 -S -O2 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -S -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @high64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[KVX_HIGH:%.*]] = shufflevector <4 x i32> [[V:%.*]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    ret <2 x i32> [[KVX_HIGH]]
//
v2i32 high64(v4i32 v) {
    return __builtin_kvx_high64(v);
}

// CHECK-LABEL: @high128(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[KVX_HIGH:%.*]] = shufflevector <8 x i32> [[V:%.*]], <8 x i32> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <4 x i32> [[KVX_HIGH]]
//
v4i32 high128(v8i32 v) {
    return __builtin_kvx_high128(v);
}

// CHECK-LABEL: @high256(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <16 x i32>, <16 x i32>* [[TMP0:%.*]], align 32, [[TBAA2:!tbaa !.*]]
// CHECK-NEXT:    [[KVX_HIGH:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <8 x i32> [[KVX_HIGH]]
//
v8i32 high256(v16i32 v) {
    return __builtin_kvx_high256(v);
}
