// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @sbfbo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <8 x i8> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 sbfbo(v8i8 a, v8i8 b) {
  return __builtin_kvx_sbfbo(a, b, "");
}

// CHECK-LABEL: @sbfbo_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.ssub.sat.v8i8(<8 x i8> [[B:%.*]], <8 x i8> [[A:%.*]])
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 sbfbo_s(v8i8 a, v8i8 b) {
  return __builtin_kvx_sbfbo(a, b, ".s");
}

// CHECK-LABEL: @sbfbo_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.usub.sat.v8i8(<8 x i8> [[B:%.*]], <8 x i8> [[A:%.*]])
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 sbfbo_us(v8i8 a, v8i8 b) {
  return __builtin_kvx_sbfbo(a, b, ".us");
}

// CHECK-LABEL: @sbfbx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <16 x i8> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <16 x i8> [[TMP0]]
//
v16i8 sbfbx(v16i8 a, v16i8 b) {
  return __builtin_kvx_sbfbx(a, b, "");
}

// CHECK-LABEL: @sbfbx_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <16 x i8> @llvm.ssub.sat.v16i8(<16 x i8> [[B:%.*]], <16 x i8> [[A:%.*]])
// CHECK-NEXT:    ret <16 x i8> [[TMP0]]
//
v16i8 sbfbx_s(v16i8 a, v16i8 b) {
  return __builtin_kvx_sbfbx(a, b, ".s");
}

// CHECK-LABEL: @sbfbx_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <16 x i8> @llvm.usub.sat.v16i8(<16 x i8> [[B:%.*]], <16 x i8> [[A:%.*]])
// CHECK-NEXT:    ret <16 x i8> [[TMP0]]
//
v16i8 sbfbx_us(v16i8 a, v16i8 b) {
  return __builtin_kvx_sbfbx(a, b, ".us");
}

// CHECK-LABEL: @sbfbv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <32 x i8> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32i8 sbfbv(v32i8 a, v32i8 b) {
  return __builtin_kvx_sbfbv(a, b, "");
}

// CHECK-LABEL: @sbfbv_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <32 x i8> @llvm.ssub.sat.v32i8(<32 x i8> [[B:%.*]], <32 x i8> [[A:%.*]])
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32i8 sbfbv_s(v32i8 a, v32i8 b) {
  return __builtin_kvx_sbfbv(a, b, ".s");
}

// CHECK-LABEL: @sbfbv_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <32 x i8> @llvm.usub.sat.v32i8(<32 x i8> [[B:%.*]], <32 x i8> [[A:%.*]])
// CHECK-NEXT:    ret <32 x i8> [[TMP0]]
//
v32i8 sbfbv_us(v32i8 a, v32i8 b) {
  return __builtin_kvx_sbfbv(a, b, ".us");
}

// CHECK-LABEL: @sbfhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <4 x i16> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 sbfhq(v4i16 a, v4i16 b) {
  return __builtin_kvx_sbfhq(a, b, "");
}

// CHECK-LABEL: @sbfhq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.ssub.sat.v4i16(<4 x i16> [[B:%.*]], <4 x i16> [[A:%.*]])
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 sbfhq_s(v4i16 a, v4i16 b) {
  return __builtin_kvx_sbfhq(a, b, ".s");
}

// CHECK-LABEL: @sbfhq_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.usub.sat.v4i16(<4 x i16> [[B:%.*]], <4 x i16> [[A:%.*]])
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 sbfhq_us(v4i16 a, v4i16 b) {
  return __builtin_kvx_sbfhq(a, b, ".us");
}

// CHECK-LABEL: @sbfho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <8 x i16> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <8 x i16> [[TMP0]]
//
v8i16 sbfho(v8i16 a, v8i16 b) {
  return __builtin_kvx_sbfho(a, b, "");
}

// CHECK-LABEL: @sbfho_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i16> @llvm.ssub.sat.v8i16(<8 x i16> [[B:%.*]], <8 x i16> [[A:%.*]])
// CHECK-NEXT:    ret <8 x i16> [[TMP0]]
//
v8i16 sbfho_s(v8i16 a, v8i16 b) {
  return __builtin_kvx_sbfho(a, b, ".s");
}

// CHECK-LABEL: @sbfho_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i16> @llvm.usub.sat.v8i16(<8 x i16> [[B:%.*]], <8 x i16> [[A:%.*]])
// CHECK-NEXT:    ret <8 x i16> [[TMP0]]
//
v8i16 sbfho_us(v8i16 a, v8i16 b) {
  return __builtin_kvx_sbfho(a, b, ".us");
}

// CHECK-LABEL: @sbfhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <16 x i16> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16i16 sbfhx(v16i16 a, v16i16 b) {
  return __builtin_kvx_sbfhx(a, b, "");
}

// CHECK-LABEL: @sbfhx_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <16 x i16> @llvm.ssub.sat.v16i16(<16 x i16> [[B:%.*]], <16 x i16> [[A:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16i16 sbfhx_s(v16i16 a, v16i16 b) {
  return __builtin_kvx_sbfhx(a, b, ".s");
}

// CHECK-LABEL: @sbfhx_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <16 x i16> @llvm.usub.sat.v16i16(<16 x i16> [[B:%.*]], <16 x i16> [[A:%.*]])
// CHECK-NEXT:    ret <16 x i16> [[TMP0]]
//
v16i16 sbfhx_us(v16i16 a, v16i16 b) {
  return __builtin_kvx_sbfhx(a, b, ".us");
}

// CHECK-LABEL: @sbfw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub i32 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int sbfw(int a, int b) {
  return __builtin_kvx_sbfw(a, b, "");
}

// CHECK-LABEL: @sbfw_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.ssub.sat.i32(i32 [[B:%.*]], i32 [[A:%.*]])
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int sbfw_s(int a, int b) {
  return __builtin_kvx_sbfw(a, b, ".s");
}

// CHECK-LABEL: @sbfw_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.usub.sat.i32(i32 [[B:%.*]], i32 [[A:%.*]])
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int sbfw_us(int a, int b) {
  return __builtin_kvx_sbfw(a, b, ".us");
}

// CHECK-LABEL: @sbfwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <2 x i32> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 sbfwp(v2i32 a, v2i32 b) {
  return __builtin_kvx_sbfwp(a, b, "");
}

// CHECK-LABEL: @sbfwp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.ssub.sat.v2i32(<2 x i32> [[B:%.*]], <2 x i32> [[A:%.*]])
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 sbfwp_s(v2i32 a, v2i32 b) {
  return __builtin_kvx_sbfwp(a, b, ".s");
}

// CHECK-LABEL: @sbfwp_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.usub.sat.v2i32(<2 x i32> [[B:%.*]], <2 x i32> [[A:%.*]])
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 sbfwp_us(v2i32 a, v2i32 b) {
  return __builtin_kvx_sbfwp(a, b, ".us");
}

// CHECK-LABEL: @sbfwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <4 x i32> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4i32 sbfwq(v4i32 a, v4i32 b) {
  return __builtin_kvx_sbfwq(a, b, "");
}

// CHECK-LABEL: @sbfwq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.ssub.sat.v4i32(<4 x i32> [[B:%.*]], <4 x i32> [[A:%.*]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4i32 sbfwq_s(v4i32 a, v4i32 b) {
  return __builtin_kvx_sbfwq(a, b, ".s");
}

// CHECK-LABEL: @sbfwq_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.usub.sat.v4i32(<4 x i32> [[B:%.*]], <4 x i32> [[A:%.*]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4i32 sbfwq_us(v4i32 a, v4i32 b) {
  return __builtin_kvx_sbfwq(a, b, ".us");
}

// CHECK-LABEL: @sbfwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <8 x i32> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8i32 sbfwo(v8i32 a, v8i32 b) {
  return __builtin_kvx_sbfwo(a, b, "");
}

// CHECK-LABEL: @sbfwo_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i32> @llvm.ssub.sat.v8i32(<8 x i32> [[B:%.*]], <8 x i32> [[A:%.*]])
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8i32 sbfwo_s(v8i32 a, v8i32 b) {
  return __builtin_kvx_sbfwo(a, b, ".s");
}

// CHECK-LABEL: @sbfwo_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i32> @llvm.usub.sat.v8i32(<8 x i32> [[B:%.*]], <8 x i32> [[A:%.*]])
// CHECK-NEXT:    ret <8 x i32> [[TMP0]]
//
v8i32 sbfwo_us(v8i32 a, v8i32 b) {
  return __builtin_kvx_sbfwo(a, b, ".us");
}

// CHECK-LABEL: @sbfd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub i64 [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long int sbfd(long int a, long int b) {
  return __builtin_kvx_sbfd(a, b, "");
}

// CHECK-LABEL: @sbfd_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.ssub.sat.i64(i64 [[B:%.*]], i64 [[A:%.*]])
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long int sbfd_s(long int a, long int b) {
  return __builtin_kvx_sbfd(a, b, ".s");
}

// CHECK-LABEL: @sbfd_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.usub.sat.i64(i64 [[B:%.*]], i64 [[A:%.*]])
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long int sbfd_us(long int a, long int b) {
  return __builtin_kvx_sbfd(a, b, ".us");
}

// CHECK-LABEL: @sbfdp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <2 x i64> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2i64 sbfdp(v2i64 a, v2i64 b) {
  return __builtin_kvx_sbfdp(a, b, "");
}

// CHECK-LABEL: @sbfdp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.ssub.sat.v2i64(<2 x i64> [[B:%.*]], <2 x i64> [[A:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2i64 sbfdp_s(v2i64 a, v2i64 b) {
  return __builtin_kvx_sbfdp(a, b, ".s");
}

// CHECK-LABEL: @sbfdp_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.usub.sat.v2i64(<2 x i64> [[B:%.*]], <2 x i64> [[A:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2i64 sbfdp_us(v2i64 a, v2i64 b) {
  return __builtin_kvx_sbfdp(a, b, ".us");
}

// CHECK-LABEL: @sbfdq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = sub <4 x i64> [[B:%.*]], [[A:%.*]]
// CHECK-NEXT:    ret <4 x i64> [[TMP0]]
//
v4i64 sbfdq(v4i64 a, v4i64 b) {
  return __builtin_kvx_sbfdq(a, b, "");
}

// CHECK-LABEL: @sbfdq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i64> @llvm.ssub.sat.v4i64(<4 x i64> [[B:%.*]], <4 x i64> [[A:%.*]])
// CHECK-NEXT:    ret <4 x i64> [[TMP0]]
//
v4i64 sbfdq_s(v4i64 a, v4i64 b) {
  return __builtin_kvx_sbfdq(a, b, ".s");
}

// CHECK-LABEL: @sbfdq_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i64> @llvm.usub.sat.v4i64(<4 x i64> [[B:%.*]], <4 x i64> [[A:%.*]])
// CHECK-NEXT:    ret <4 x i64> [[TMP0]]
//
v4i64 sbfdq_us(v4i64 a, v4i64 b) {
  return __builtin_kvx_sbfdq(a, b, ".us");
}
