// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @madddt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.madddt(<2 x i64> [[A:%.*]], i64 [[B:%.*]], i64 [[C:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2i64 madddt(v2i64 a, long b, long c){
    return __builtin_kvx_madddt(a, b, c);
}

// CHECK-LABEL: @maddsudt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.maddsudt(<2 x i64> [[A:%.*]], i64 [[B:%.*]], i64 [[C:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2i64 maddsudt(v2i64 a, long b, unsigned long c){
    return __builtin_kvx_maddsudt(a, b, c);
}

// CHECK-LABEL: @maddudt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.maddudt(<2 x i64> [[A:%.*]], i64 [[B:%.*]], i64 [[C:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2u64 maddudt(v2u64 a, unsigned long b, unsigned long c){
    return __builtin_kvx_maddudt(a, b, c);
}

// CHECK-LABEL: @madduzdt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.madduzdt(<2 x i64> [[A:%.*]], i64 [[B:%.*]], i64 [[C:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2u64 madduzdt(v2u64 a, unsigned long b, unsigned long c){
    return __builtin_kvx_madduzdt(a, b, c);
}

// CHECK-LABEL: @msbfdt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.msbfdt(<2 x i64> [[A:%.*]], i64 [[B:%.*]], i64 [[C:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2i64 msbfdt(v2i64 a, long b, long c){
    return __builtin_kvx_msbfdt(a, b, c);
}

// CHECK-LABEL: @msbfsudt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.msbfsudt(<2 x i64> [[A:%.*]], i64 [[B:%.*]], i64 [[C:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2i64 msbfsudt(v2i64 a, long b, unsigned long c){
    return __builtin_kvx_msbfsudt(a, b, c);
}

// CHECK-LABEL: @msbfudt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.msbfudt(<2 x i64> [[A:%.*]], i64 [[B:%.*]], i64 [[C:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2u64 msbfudt(v2u64 a, unsigned long b, unsigned long c){
    return __builtin_kvx_msbfudt(a, b, c);
}

// CHECK-LABEL: @msbfuzdt(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i64> @llvm.kvx.msbfuzdt(<2 x i64> [[A:%.*]], i64 [[B:%.*]], i64 [[C:%.*]])
// CHECK-NEXT:    ret <2 x i64> [[TMP0]]
//
v2u64 msbfuzdt(v2u64 a, unsigned long b, unsigned long c){
    return __builtin_kvx_msbfuzdt(a, b, c);
}
