// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -O2 -emit-llvm -o - %s | FileCheck %s

typedef __kvx_v4si v4;
typedef __kvx_v2si v2;

// CHECK-LABEL: @mm212w(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.mm212w(<2 x i32> [[V1:%.*]], <2 x i32> [[V2:%.*]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4 mm212w(v2 v1, v2 v2) {
  return __builtin_kvx_mm212w(v1, v2);
}

// CHECK-LABEL: @mma212w(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.mma212w(<2 x i32> [[V1:%.*]], <2 x i32> [[V2:%.*]], <4 x i32> [[A:%.*]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4 mma212w(v4 A, v2 v1, v2 v2) {
  return __builtin_kvx_mma212w(v1, v2, A);
}

// CHECK-LABEL: @mms212w(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i32> @llvm.kvx.mms212w(<2 x i32> [[V1:%.*]], <2 x i32> [[V2:%.*]], <4 x i32> [[A:%.*]])
// CHECK-NEXT:    ret <4 x i32> [[TMP0]]
//
v4 mms212w(v4 A, v2 v1, v2 v2) {
  return __builtin_kvx_mms212w(v1, v2, A);
}
