// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

typedef char V16c __attribute__((vector_size(sizeof(char) * 16)));
typedef int V16i __attribute__((vector_size(sizeof(int) * 16)));
typedef short V16s __attribute__((vector_size(sizeof(short) * 16)));
typedef char V2c __attribute__((vector_size(sizeof(char) * 2)));
typedef int V2i __attribute__((vector_size(sizeof(int) * 2)));
typedef long long V2Oi __attribute__((vector_size(sizeof(long) * 2)));
typedef short V2s __attribute__((vector_size(sizeof(short) * 2)));
typedef short V2s __attribute__((vector_size(sizeof(short) * 2)));
typedef char V32c __attribute__((vector_size(sizeof(char) * 32)));
typedef short V32s __attribute__((vector_size(sizeof(short) * 32)));
typedef char V4c __attribute__((vector_size(sizeof(char) * 4)));
typedef int V4i __attribute__((vector_size(sizeof(int) * 4)));
typedef long long V4Oi __attribute__((vector_size(sizeof(long) * 4)));
typedef short V4s __attribute__((vector_size(sizeof(short) * 4)));
typedef char V8c __attribute__((vector_size(sizeof(char) * 8)));
typedef int V8i __attribute__((vector_size(sizeof(int) * 8)));
typedef long long V8Oi __attribute__((vector_size(sizeof(long) * 8)));
typedef short V8s __attribute__((vector_size(sizeof(short) * 8)));

// CHECK-LABEL: @narrowhbx_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[V:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i8> [[TMP1]], <4 x i8> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i8> [[TMP5]], <4 x i8> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP10]]
//
V16c narrowhbx_q(V16s v) { return __builtin_kvx_narrowhbx(v, ".q"); }

// CHECK-LABEL: @narrowhbx_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[V:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i8> [[TMP1]], <4 x i8> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i8> [[TMP5]], <4 x i8> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP10]]
//
V16c narrowhbx_s(V16s v) { return __builtin_kvx_narrowhbx(v, ".s"); }

// CHECK-LABEL: @narrowhbx_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[V:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP0]], i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP2]], i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP4]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP6]], i32 3)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i8> [[TMP1]], <4 x i8> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i8> [[TMP5]], <4 x i8> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP10]]
//
V16c narrowhbx_us(V16s v) { return __builtin_kvx_narrowhbx(v, ".us"); }

// CHECK-LABEL: @narrowhbx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[V:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i8> [[TMP1]], <4 x i8> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i8> [[TMP5]], <4 x i8> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i8> [[TMP8]], <8 x i8> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP10]]
//
V16c narrowhbx(V16s v) { return __builtin_kvx_narrowhbx(v, ""); }

// CHECK-LABEL: @narrowwhx_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <16 x i32>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP3]], i32 1)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP5]], i32 1)
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 8, i32 9>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP9]], i32 1)
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 10, i32 11>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP11]], i32 1)
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 12, i32 13>
// CHECK-NEXT:    [[TMP14:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP13]], i32 1)
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 14, i32 15>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP15]], i32 1)
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> [[TMP4]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x i16> [[TMP6]], <2 x i16> [[TMP8]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <2 x i16> [[TMP10]], <2 x i16> [[TMP12]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <2 x i16> [[TMP14]], <2 x i16> [[TMP16]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <4 x i16> [[TMP17]], <4 x i16> [[TMP18]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <4 x i16> [[TMP19]], <4 x i16> [[TMP20]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <8 x i16> [[TMP21]], <8 x i16> [[TMP22]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP23]]
//
V16s narrowwhx_q(V16i v) { return __builtin_kvx_narrowwhx(v, ".q"); }

// CHECK-LABEL: @narrowwhx_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <16 x i32>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP3]], i32 2)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP5]], i32 2)
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 8, i32 9>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP9]], i32 2)
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 10, i32 11>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP11]], i32 2)
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 12, i32 13>
// CHECK-NEXT:    [[TMP14:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP13]], i32 2)
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 14, i32 15>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP15]], i32 2)
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> [[TMP4]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x i16> [[TMP6]], <2 x i16> [[TMP8]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <2 x i16> [[TMP10]], <2 x i16> [[TMP12]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <2 x i16> [[TMP14]], <2 x i16> [[TMP16]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <4 x i16> [[TMP17]], <4 x i16> [[TMP18]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <4 x i16> [[TMP19]], <4 x i16> [[TMP20]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <8 x i16> [[TMP21]], <8 x i16> [[TMP22]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP23]]
//
V16s narrowwhx_s(V16i v) { return __builtin_kvx_narrowwhx(v, ".s"); }

// CHECK-LABEL: @narrowwhx_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <16 x i32>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP1]], i32 3)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP3]], i32 3)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP5]], i32 3)
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP7]], i32 3)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 8, i32 9>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP9]], i32 3)
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 10, i32 11>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP11]], i32 3)
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 12, i32 13>
// CHECK-NEXT:    [[TMP14:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP13]], i32 3)
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 14, i32 15>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP15]], i32 3)
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> [[TMP4]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x i16> [[TMP6]], <2 x i16> [[TMP8]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <2 x i16> [[TMP10]], <2 x i16> [[TMP12]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <2 x i16> [[TMP14]], <2 x i16> [[TMP16]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <4 x i16> [[TMP17]], <4 x i16> [[TMP18]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <4 x i16> [[TMP19]], <4 x i16> [[TMP20]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <8 x i16> [[TMP21]], <8 x i16> [[TMP22]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP23]]
//
V16s narrowwhx_us(V16i v) { return __builtin_kvx_narrowwhx(v, ".us"); }

// CHECK-LABEL: @narrowwhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <16 x i32>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP5]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 8, i32 9>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP9]], i32 0)
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 10, i32 11>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP11]], i32 0)
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 12, i32 13>
// CHECK-NEXT:    [[TMP14:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP13]], i32 0)
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 14, i32 15>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP15]], i32 0)
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <2 x i16> [[TMP2]], <2 x i16> [[TMP4]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x i16> [[TMP6]], <2 x i16> [[TMP8]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <2 x i16> [[TMP10]], <2 x i16> [[TMP12]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <2 x i16> [[TMP14]], <2 x i16> [[TMP16]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <4 x i16> [[TMP17]], <4 x i16> [[TMP18]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <4 x i16> [[TMP19]], <4 x i16> [[TMP20]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <8 x i16> [[TMP21]], <8 x i16> [[TMP22]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP23]]
//
V16s narrowwhx(V16i v) { return __builtin_kvx_narrowwhx(v, ""); }

// CHECK-LABEL: @narrowhbp_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.narrowint.v2i8(<2 x i16> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
V2c narrowhbp_q(V2s v) { return __builtin_kvx_narrowhbp(v, ".q"); }

// CHECK-LABEL: @narrowhbp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.narrowint.v2i8(<2 x i16> [[V:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
V2c narrowhbp_s(V2s v) { return __builtin_kvx_narrowhbp(v, ".s"); }

// CHECK-LABEL: @narrowhbp_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.narrowint.v2i8(<2 x i16> [[V:%.*]], i32 3)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
V2c narrowhbp_us(V2s v) { return __builtin_kvx_narrowhbp(v, ".us"); }

// CHECK-LABEL: @narrowhbp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.narrowint.v2i8(<2 x i16> [[V:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
V2c narrowhbp(V2s v) { return __builtin_kvx_narrowhbp(v, ""); }

// CHECK-LABEL: @narrowdwp_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i32> undef, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i32> [[TMP4]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i32> [[TMP5]]
//
V2i narrowdwp_q(V2Oi v) { return __builtin_kvx_narrowdwp(v, ".q"); }

// CHECK-LABEL: @narrowdwp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i32> undef, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i32> [[TMP4]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i32> [[TMP5]]
//
V2i narrowdwp_s(V2Oi v) { return __builtin_kvx_narrowdwp(v, ".s"); }

// CHECK-LABEL: @narrowdwp_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP0]], i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP2]], i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i32> undef, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i32> [[TMP4]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i32> [[TMP5]]
//
V2i narrowdwp_us(V2Oi v) { return __builtin_kvx_narrowdwp(v, ".us"); }

// CHECK-LABEL: @narrowdwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i32> undef, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i32> [[TMP4]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i32> [[TMP5]]
//
V2i narrowdwp(V2Oi v) { return __builtin_kvx_narrowdwp(v, ""); }

// CHECK-LABEL: @narrowwhp_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
V2s narrowwhp_q(V2i v) { return __builtin_kvx_narrowwhp(v, ".q"); }

// CHECK-LABEL: @narrowwhp_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[V:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
V2s narrowwhp_s(V2i v) { return __builtin_kvx_narrowwhp(v, ".s"); }

// CHECK-LABEL: @narrowwhp_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[V:%.*]], i32 3)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
V2s narrowwhp_us(V2i v) { return __builtin_kvx_narrowwhp(v, ".us"); }

// CHECK-LABEL: @narrowwhp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[V:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
V2s narrowwhp(V2i v) { return __builtin_kvx_narrowwhp(v, ""); }

// CHECK-LABEL: @narrowhbv_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <32 x i16>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP3]], i32 1)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP5]], i32 1)
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 16, i32 17, i32 18, i32 19>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP9]], i32 1)
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP11]], i32 1)
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 24, i32 25, i32 26, i32 27>
// CHECK-NEXT:    [[TMP14:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP13]], i32 1)
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP15]], i32 1)
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> [[TMP4]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <4 x i8> [[TMP6]], <4 x i8> [[TMP8]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <4 x i8> [[TMP10]], <4 x i8> [[TMP12]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <4 x i8> [[TMP14]], <4 x i8> [[TMP16]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i8> [[TMP17]], <8 x i8> [[TMP18]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <8 x i8> [[TMP19]], <8 x i8> [[TMP20]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP21]], <16 x i8> [[TMP22]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP23]]
//
V32c narrowhbv_q(V32s v) { return __builtin_kvx_narrowhbv(v, ".q"); }

// CHECK-LABEL: @narrowhbv_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <32 x i16>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP3]], i32 2)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP5]], i32 2)
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 16, i32 17, i32 18, i32 19>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP9]], i32 2)
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP11]], i32 2)
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 24, i32 25, i32 26, i32 27>
// CHECK-NEXT:    [[TMP14:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP13]], i32 2)
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP15]], i32 2)
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> [[TMP4]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <4 x i8> [[TMP6]], <4 x i8> [[TMP8]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <4 x i8> [[TMP10]], <4 x i8> [[TMP12]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <4 x i8> [[TMP14]], <4 x i8> [[TMP16]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i8> [[TMP17]], <8 x i8> [[TMP18]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <8 x i8> [[TMP19]], <8 x i8> [[TMP20]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP21]], <16 x i8> [[TMP22]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP23]]
//
V32c narrowhbv_s(V32s v) { return __builtin_kvx_narrowhbv(v, ".s"); }

// CHECK-LABEL: @narrowhbv_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <32 x i16>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP1]], i32 3)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP3]], i32 3)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP5]], i32 3)
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP7]], i32 3)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 16, i32 17, i32 18, i32 19>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP9]], i32 3)
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP11]], i32 3)
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 24, i32 25, i32 26, i32 27>
// CHECK-NEXT:    [[TMP14:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP13]], i32 3)
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP15]], i32 3)
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> [[TMP4]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <4 x i8> [[TMP6]], <4 x i8> [[TMP8]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <4 x i8> [[TMP10]], <4 x i8> [[TMP12]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <4 x i8> [[TMP14]], <4 x i8> [[TMP16]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i8> [[TMP17]], <8 x i8> [[TMP18]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <8 x i8> [[TMP19]], <8 x i8> [[TMP20]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP21]], <16 x i8> [[TMP22]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP23]]
//
V32c narrowhbv_us(V32s v) { return __builtin_kvx_narrowhbv(v, ".us"); }

// CHECK-LABEL: @narrowhbv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <32 x i16>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP5]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 16, i32 17, i32 18, i32 19>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP9]], i32 0)
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP12:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP11]], i32 0)
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 24, i32 25, i32 26, i32 27>
// CHECK-NEXT:    [[TMP14:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP13]], i32 0)
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP15]], i32 0)
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> [[TMP4]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <4 x i8> [[TMP6]], <4 x i8> [[TMP8]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <4 x i8> [[TMP10]], <4 x i8> [[TMP12]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <4 x i8> [[TMP14]], <4 x i8> [[TMP16]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i8> [[TMP17]], <8 x i8> [[TMP18]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <8 x i8> [[TMP19]], <8 x i8> [[TMP20]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP21]], <16 x i8> [[TMP22]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP23]]
//
V32c narrowhbv(V32s v) { return __builtin_kvx_narrowhbv(v, ""); }

// CHECK-LABEL: @narrowhbq_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
V4c narrowhbq_q(V4s v) { return __builtin_kvx_narrowhbq(v, ".q"); }

// CHECK-LABEL: @narrowhbq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[V:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
V4c narrowhbq_s(V4s v) { return __builtin_kvx_narrowhbq(v, ".s"); }

// CHECK-LABEL: @narrowhbq_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[V:%.*]], i32 3)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
V4c narrowhbq_us(V4s v) { return __builtin_kvx_narrowhbq(v, ".us"); }

// CHECK-LABEL: @narrowhbq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[V:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
V4c narrowhbq(V4s v) { return __builtin_kvx_narrowhbq(v, ""); }

// CHECK-LABEL: @narrowdwq_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> undef, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i32> [[TMP9]], i32 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i32> [[TMP10]], i32 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i32> [[TMP11]]
//
V4i narrowdwq_q(V4Oi v) { return __builtin_kvx_narrowdwq(v, ".q"); }

// CHECK-LABEL: @narrowdwq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> undef, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i32> [[TMP9]], i32 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i32> [[TMP10]], i32 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i32> [[TMP11]]
//
V4i narrowdwq_s(V4Oi v) { return __builtin_kvx_narrowdwq(v, ".s"); }

// CHECK-LABEL: @narrowdwq_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP0]], i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP2]], i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP4]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP6]], i32 3)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> undef, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i32> [[TMP9]], i32 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i32> [[TMP10]], i32 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i32> [[TMP11]]
//
V4i narrowdwq_us(V4Oi v) { return __builtin_kvx_narrowdwq(v, ".us"); }

// CHECK-LABEL: @narrowdwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i64> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i64> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i64> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> undef, i32 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i32> [[TMP8]], i32 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i32> [[TMP9]], i32 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i32> [[TMP10]], i32 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i32> [[TMP11]]
//
V4i narrowdwq(V4Oi v) { return __builtin_kvx_narrowdwq(v, ""); }

// CHECK-LABEL: @narrowwhq_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[V:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[V]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i16> [[TMP1]], <2 x i16> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i16> [[TMP4]]
//
V4s narrowwhq_q(V4i v) { return __builtin_kvx_narrowwhq(v, ".q"); }

// CHECK-LABEL: @narrowwhq_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[V:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[V]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i16> [[TMP1]], <2 x i16> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i16> [[TMP4]]
//
V4s narrowwhq_s(V4i v) { return __builtin_kvx_narrowwhq(v, ".s"); }

// CHECK-LABEL: @narrowwhq_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[V:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP0]], i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[V]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP2]], i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i16> [[TMP1]], <2 x i16> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i16> [[TMP4]]
//
V4s narrowwhq_us(V4i v) { return __builtin_kvx_narrowwhq(v, ".us"); }

// CHECK-LABEL: @narrowwhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[V:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i32> [[V]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i16> [[TMP1]], <2 x i16> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i16> [[TMP4]]
//
V4s narrowwhq(V4i v) { return __builtin_kvx_narrowwhq(v, ""); }

// CHECK-LABEL: @narrowhbo_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[V:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i8> [[TMP1]], <4 x i8> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i8> [[TMP4]]
//
V8c narrowhbo_q(V8s v) { return __builtin_kvx_narrowhbo(v, ".q"); }

// CHECK-LABEL: @narrowhbo_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[V:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i8> [[TMP1]], <4 x i8> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i8> [[TMP4]]
//
V8c narrowhbo_s(V8s v) { return __builtin_kvx_narrowhbo(v, ".s"); }

// CHECK-LABEL: @narrowhbo_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[V:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP0]], i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP2]], i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i8> [[TMP1]], <4 x i8> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i8> [[TMP4]]
//
V8c narrowhbo_us(V8s v) { return __builtin_kvx_narrowhbo(v, ".us"); }

// CHECK-LABEL: @narrowhbo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[V:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i8> @llvm.kvx.narrowint.v4i8(<4 x i16> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i8> [[TMP1]], <4 x i8> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i8> [[TMP4]]
//
V8c narrowhbo(V8s v) { return __builtin_kvx_narrowhbo(v, ""); }

// CHECK-LABEL: @narrowdwo_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <8 x i64>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <8 x i64> [[V]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP1]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <8 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP3]], i32 1)
// CHECK-NEXT:    [[TMP5:%.*]] = extractelement <8 x i64> [[V]], i64 2
// CHECK-NEXT:    [[TMP6:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP5]], i32 1)
// CHECK-NEXT:    [[TMP7:%.*]] = extractelement <8 x i64> [[V]], i64 3
// CHECK-NEXT:    [[TMP8:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP7]], i32 1)
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <8 x i64> [[V]], i64 4
// CHECK-NEXT:    [[TMP10:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP9]], i32 1)
// CHECK-NEXT:    [[TMP11:%.*]] = extractelement <8 x i64> [[V]], i64 5
// CHECK-NEXT:    [[TMP12:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP11]], i32 1)
// CHECK-NEXT:    [[TMP13:%.*]] = extractelement <8 x i64> [[V]], i64 6
// CHECK-NEXT:    [[TMP14:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP13]], i32 1)
// CHECK-NEXT:    [[TMP15:%.*]] = extractelement <8 x i64> [[V]], i64 7
// CHECK-NEXT:    [[TMP16:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP15]], i32 1)
// CHECK-NEXT:    [[TMP17:%.*]] = insertelement <8 x i32> undef, i32 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x i32> [[TMP17]], i32 [[TMP4]], i64 1
// CHECK-NEXT:    [[TMP19:%.*]] = insertelement <8 x i32> [[TMP18]], i32 [[TMP6]], i64 2
// CHECK-NEXT:    [[TMP20:%.*]] = insertelement <8 x i32> [[TMP19]], i32 [[TMP8]], i64 3
// CHECK-NEXT:    [[TMP21:%.*]] = insertelement <8 x i32> [[TMP20]], i32 [[TMP10]], i64 4
// CHECK-NEXT:    [[TMP22:%.*]] = insertelement <8 x i32> [[TMP21]], i32 [[TMP12]], i64 5
// CHECK-NEXT:    [[TMP23:%.*]] = insertelement <8 x i32> [[TMP22]], i32 [[TMP14]], i64 6
// CHECK-NEXT:    [[TMP24:%.*]] = insertelement <8 x i32> [[TMP23]], i32 [[TMP16]], i64 7
// CHECK-NEXT:    ret <8 x i32> [[TMP24]]
//
V8i narrowdwo_q(V8Oi v) { return __builtin_kvx_narrowdwo(v, ".q"); }

// CHECK-LABEL: @narrowdwo_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <8 x i64>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <8 x i64> [[V]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP1]], i32 2)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <8 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP3]], i32 2)
// CHECK-NEXT:    [[TMP5:%.*]] = extractelement <8 x i64> [[V]], i64 2
// CHECK-NEXT:    [[TMP6:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP5]], i32 2)
// CHECK-NEXT:    [[TMP7:%.*]] = extractelement <8 x i64> [[V]], i64 3
// CHECK-NEXT:    [[TMP8:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP7]], i32 2)
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <8 x i64> [[V]], i64 4
// CHECK-NEXT:    [[TMP10:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP9]], i32 2)
// CHECK-NEXT:    [[TMP11:%.*]] = extractelement <8 x i64> [[V]], i64 5
// CHECK-NEXT:    [[TMP12:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP11]], i32 2)
// CHECK-NEXT:    [[TMP13:%.*]] = extractelement <8 x i64> [[V]], i64 6
// CHECK-NEXT:    [[TMP14:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP13]], i32 2)
// CHECK-NEXT:    [[TMP15:%.*]] = extractelement <8 x i64> [[V]], i64 7
// CHECK-NEXT:    [[TMP16:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP15]], i32 2)
// CHECK-NEXT:    [[TMP17:%.*]] = insertelement <8 x i32> undef, i32 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x i32> [[TMP17]], i32 [[TMP4]], i64 1
// CHECK-NEXT:    [[TMP19:%.*]] = insertelement <8 x i32> [[TMP18]], i32 [[TMP6]], i64 2
// CHECK-NEXT:    [[TMP20:%.*]] = insertelement <8 x i32> [[TMP19]], i32 [[TMP8]], i64 3
// CHECK-NEXT:    [[TMP21:%.*]] = insertelement <8 x i32> [[TMP20]], i32 [[TMP10]], i64 4
// CHECK-NEXT:    [[TMP22:%.*]] = insertelement <8 x i32> [[TMP21]], i32 [[TMP12]], i64 5
// CHECK-NEXT:    [[TMP23:%.*]] = insertelement <8 x i32> [[TMP22]], i32 [[TMP14]], i64 6
// CHECK-NEXT:    [[TMP24:%.*]] = insertelement <8 x i32> [[TMP23]], i32 [[TMP16]], i64 7
// CHECK-NEXT:    ret <8 x i32> [[TMP24]]
//
V8i narrowdwo_s(V8Oi v) { return __builtin_kvx_narrowdwo(v, ".s"); }

// CHECK-LABEL: @narrowdwo_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <8 x i64>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <8 x i64> [[V]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP1]], i32 3)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <8 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP3]], i32 3)
// CHECK-NEXT:    [[TMP5:%.*]] = extractelement <8 x i64> [[V]], i64 2
// CHECK-NEXT:    [[TMP6:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP5]], i32 3)
// CHECK-NEXT:    [[TMP7:%.*]] = extractelement <8 x i64> [[V]], i64 3
// CHECK-NEXT:    [[TMP8:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP7]], i32 3)
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <8 x i64> [[V]], i64 4
// CHECK-NEXT:    [[TMP10:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP9]], i32 3)
// CHECK-NEXT:    [[TMP11:%.*]] = extractelement <8 x i64> [[V]], i64 5
// CHECK-NEXT:    [[TMP12:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP11]], i32 3)
// CHECK-NEXT:    [[TMP13:%.*]] = extractelement <8 x i64> [[V]], i64 6
// CHECK-NEXT:    [[TMP14:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP13]], i32 3)
// CHECK-NEXT:    [[TMP15:%.*]] = extractelement <8 x i64> [[V]], i64 7
// CHECK-NEXT:    [[TMP16:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP15]], i32 3)
// CHECK-NEXT:    [[TMP17:%.*]] = insertelement <8 x i32> undef, i32 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x i32> [[TMP17]], i32 [[TMP4]], i64 1
// CHECK-NEXT:    [[TMP19:%.*]] = insertelement <8 x i32> [[TMP18]], i32 [[TMP6]], i64 2
// CHECK-NEXT:    [[TMP20:%.*]] = insertelement <8 x i32> [[TMP19]], i32 [[TMP8]], i64 3
// CHECK-NEXT:    [[TMP21:%.*]] = insertelement <8 x i32> [[TMP20]], i32 [[TMP10]], i64 4
// CHECK-NEXT:    [[TMP22:%.*]] = insertelement <8 x i32> [[TMP21]], i32 [[TMP12]], i64 5
// CHECK-NEXT:    [[TMP23:%.*]] = insertelement <8 x i32> [[TMP22]], i32 [[TMP14]], i64 6
// CHECK-NEXT:    [[TMP24:%.*]] = insertelement <8 x i32> [[TMP23]], i32 [[TMP16]], i64 7
// CHECK-NEXT:    ret <8 x i32> [[TMP24]]
//
V8i narrowdwo_us(V8Oi v) { return __builtin_kvx_narrowdwo(v, ".us"); }

// CHECK-LABEL: @narrowdwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <8 x i64>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractelement <8 x i64> [[V]], i64 0
// CHECK-NEXT:    [[TMP2:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP1]], i32 0)
// CHECK-NEXT:    [[TMP3:%.*]] = extractelement <8 x i64> [[V]], i64 1
// CHECK-NEXT:    [[TMP4:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP3]], i32 0)
// CHECK-NEXT:    [[TMP5:%.*]] = extractelement <8 x i64> [[V]], i64 2
// CHECK-NEXT:    [[TMP6:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP5]], i32 0)
// CHECK-NEXT:    [[TMP7:%.*]] = extractelement <8 x i64> [[V]], i64 3
// CHECK-NEXT:    [[TMP8:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP7]], i32 0)
// CHECK-NEXT:    [[TMP9:%.*]] = extractelement <8 x i64> [[V]], i64 4
// CHECK-NEXT:    [[TMP10:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP9]], i32 0)
// CHECK-NEXT:    [[TMP11:%.*]] = extractelement <8 x i64> [[V]], i64 5
// CHECK-NEXT:    [[TMP12:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP11]], i32 0)
// CHECK-NEXT:    [[TMP13:%.*]] = extractelement <8 x i64> [[V]], i64 6
// CHECK-NEXT:    [[TMP14:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP13]], i32 0)
// CHECK-NEXT:    [[TMP15:%.*]] = extractelement <8 x i64> [[V]], i64 7
// CHECK-NEXT:    [[TMP16:%.*]] = tail call i32 @llvm.kvx.narrowint.i32(i64 [[TMP15]], i32 0)
// CHECK-NEXT:    [[TMP17:%.*]] = insertelement <8 x i32> undef, i32 [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x i32> [[TMP17]], i32 [[TMP4]], i64 1
// CHECK-NEXT:    [[TMP19:%.*]] = insertelement <8 x i32> [[TMP18]], i32 [[TMP6]], i64 2
// CHECK-NEXT:    [[TMP20:%.*]] = insertelement <8 x i32> [[TMP19]], i32 [[TMP8]], i64 3
// CHECK-NEXT:    [[TMP21:%.*]] = insertelement <8 x i32> [[TMP20]], i32 [[TMP10]], i64 4
// CHECK-NEXT:    [[TMP22:%.*]] = insertelement <8 x i32> [[TMP21]], i32 [[TMP12]], i64 5
// CHECK-NEXT:    [[TMP23:%.*]] = insertelement <8 x i32> [[TMP22]], i32 [[TMP14]], i64 6
// CHECK-NEXT:    [[TMP24:%.*]] = insertelement <8 x i32> [[TMP23]], i32 [[TMP16]], i64 7
// CHECK-NEXT:    ret <8 x i32> [[TMP24]]
//
V8i narrowdwo(V8Oi v) { return __builtin_kvx_narrowdwo(v, ""); }

// CHECK-LABEL: @narrowwho_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[V:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i16> [[TMP1]], <2 x i16> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i16> [[TMP5]], <2 x i16> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP10]]
//
V8s narrowwho_q(V8i v) { return __builtin_kvx_narrowwho(v, ".q"); }

// CHECK-LABEL: @narrowwho_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[V:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i16> [[TMP1]], <2 x i16> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i16> [[TMP5]], <2 x i16> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP10]]
//
V8s narrowwho_s(V8i v) { return __builtin_kvx_narrowwho(v, ".s"); }

// CHECK-LABEL: @narrowwho_us(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[V:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP0]], i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP2]], i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP4]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP6]], i32 3)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i16> [[TMP1]], <2 x i16> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i16> [[TMP5]], <2 x i16> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP10]]
//
V8s narrowwho_us(V8i v) { return __builtin_kvx_narrowwho(v, ".us"); }

// CHECK-LABEL: @narrowwho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[V:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i16> @llvm.kvx.narrowint.v2i16(<2 x i32> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i16> [[TMP1]], <2 x i16> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i16> [[TMP5]], <2 x i16> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP10]]
//
V8s narrowwho(V8i v) { return __builtin_kvx_narrowwho(v, ""); }
