// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -emit-llvm %s -O3 -o - | FileCheck %s

// CHECK-LABEL: @scall0(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[ID:%.*]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[TMP0]] to ptr addrspace(259)
// CHECK-NEXT:    [[TMP2:%.*]] = notail call addrspace(259) i64 [[TMP1]]() #[[ATTR1:[0-9]+]]
// CHECK-NEXT:    ret i64 [[TMP2]]
//
long scall0(int id){
  return __builtin_kvx_scall(id);
}

// CHECK-LABEL: @scall1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[ID:%.*]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[TMP0]] to ptr addrspace(259)
// CHECK-NEXT:    [[TMP2:%.*]] = notail call addrspace(259) i64 [[TMP1]](i64 [[ARG1:%.*]]) #[[ATTR1]]
// CHECK-NEXT:    ret i64 [[TMP2]]
//
long scall1(int id, long arg1){
  return __builtin_kvx_scall(id, arg1);
}

// CHECK-LABEL: @scall2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[ID:%.*]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[TMP0]] to ptr addrspace(259)
// CHECK-NEXT:    [[CONV:%.*]] = sext i8 [[ARG1:%.*]] to i32
// CHECK-NEXT:    [[TMP2:%.*]] = notail call addrspace(259) i64 [[TMP1]](i32 [[CONV]], ptr [[ARG2:%.*]]) #[[ATTR1]]
// CHECK-NEXT:    ret i64 [[TMP2]]
//
long scall2(int id, char arg1, void * arg2){
  return __builtin_kvx_scall(id, arg1, arg2);
}

// CHECK-LABEL: @scall_tiny_make(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[ID:%.*]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[TMP0]] to ptr addrspace(259)
// CHECK-NEXT:    [[TMP2:%.*]] = notail call addrspace(259) i64 [[TMP1]](i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11) #[[ATTR1]]
// CHECK-NEXT:    ret i64 [[TMP2]]
//
long scall_tiny_make(int id){
  return __builtin_kvx_scall(id, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11);
}

#define SMALL_MAKE(i) ((2 << 16) + i)

// CHECK-LABEL: @scall_small_make(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[ID:%.*]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[TMP0]] to ptr addrspace(259)
// CHECK-NEXT:    [[TMP2:%.*]] = notail call addrspace(259) i64 [[TMP1]](i32 131072, i32 131073, i32 131074, i32 131075, i32 131076, i32 131077, i32 131078, i32 131079, i32 131080, i32 131081, i32 131082, i32 131083) #[[ATTR1]]
// CHECK-NEXT:    ret i64 [[TMP2]]
//
long scall_small_make(int id){
  return __builtin_kvx_scall(id, SMALL_MAKE(0), SMALL_MAKE(1), SMALL_MAKE(2),
    SMALL_MAKE(3), SMALL_MAKE(4), SMALL_MAKE(5), SMALL_MAKE(6), SMALL_MAKE(7),
    SMALL_MAKE(8), SMALL_MAKE(9), SMALL_MAKE(10), SMALL_MAKE(11));
}

#define BIG_MAKE(i) ((2l << 43) + i)

// CHECK-LABEL: @scall_big_make(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[ID:%.*]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[TMP0]] to ptr addrspace(259)
// CHECK-NEXT:    [[TMP2:%.*]] = notail call addrspace(259) i64 [[TMP1]](i64 17592186044416, i64 17592186044417, i64 17592186044418, i64 17592186044419, i64 17592186044420, i64 17592186044421, i64 17592186044422, i64 17592186044423, i64 17592186044424, i64 17592186044425, i64 17592186044426, i64 17592186044427) #[[ATTR1]]
// CHECK-NEXT:    ret i64 [[TMP2]]
//
long scall_big_make(int id){
  return __builtin_kvx_scall(id, BIG_MAKE(0), BIG_MAKE(1), BIG_MAKE(2),
    BIG_MAKE(3), BIG_MAKE(4), BIG_MAKE(5), BIG_MAKE(6), BIG_MAKE(7),
    BIG_MAKE(8), BIG_MAKE(9), BIG_MAKE(10), BIG_MAKE(11));
}

// CHECK-LABEL: @scall_then_add(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = zext i32 [[ID:%.*]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[TMP0]] to ptr addrspace(259)
// CHECK-NEXT:    [[TMP2:%.*]] = notail call addrspace(259) i64 [[TMP1]](i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11) #[[ATTR1]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i64 [[TMP2]], 42
// CHECK-NEXT:    ret i64 [[ADD]]
//
long scall_then_add(int id){
  long result = scall_tiny_make(id);
  return result + 42;
}

// CHECK-LABEL: @scall_imm(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = notail call addrspace(259) i64 inttoptr (i32 42 to ptr addrspace(259))() #[[ATTR1]]
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long scall_imm(void){
  return __builtin_kvx_scall(42);
}
