// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -target-cpu kv3-2 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @shrbos(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 0)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 shrbos (v8i8 v, unsigned sht) { return __builtin_kvx_shrbos(v, sht, ""); }

// CHECK-LABEL: @shrbos_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 1)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 shrbos_s (v8i8 v, unsigned sht) { return __builtin_kvx_shrbos(v, sht, ".a"); }

// CHECK-LABEL: @shrbos_as(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 2)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 shrbos_as (v8i8 v, unsigned sht) { return __builtin_kvx_shrbos(v, sht, ".as"); }

// CHECK-LABEL: @shrbos_r(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 3)
// CHECK-NEXT:    ret <8 x i8> [[TMP0]]
//
v8i8 shrbos_r (v8i8 v, unsigned sht) { return __builtin_kvx_shrbos(v, sht, ".r"); }

// CHECK-LABEL: @shrbps(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.shr.v2i8(<2 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 shrbps (v2i8 v, unsigned sht) { return __builtin_kvx_shrbps(v, sht, ""); }

// CHECK-LABEL: @shrbps_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.shr.v2i8(<2 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 shrbps_s (v2i8 v, unsigned sht) { return __builtin_kvx_shrbps(v, sht, ".a"); }

// CHECK-LABEL: @shrbps_as(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.shr.v2i8(<2 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 shrbps_as (v2i8 v, unsigned sht) { return __builtin_kvx_shrbps(v, sht, ".as"); }

// CHECK-LABEL: @shrbps_r(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i8> @llvm.kvx.shr.v2i8(<2 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 3)
// CHECK-NEXT:    ret <2 x i8> [[TMP0]]
//
v2i8 shrbps_r (v2i8 v, unsigned sht) { return __builtin_kvx_shrbps(v, sht, ".r"); }

// CHECK-LABEL: @shrbqs(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.shr.v4i8(<4 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 shrbqs (v4i8 v, unsigned sht) { return __builtin_kvx_shrbqs(v, sht, ""); }

// CHECK-LABEL: @shrbqs_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.shr.v4i8(<4 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 shrbqs_s (v4i8 v, unsigned sht) { return __builtin_kvx_shrbqs(v, sht, ".a"); }

// CHECK-LABEL: @shrbqs_as(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.shr.v4i8(<4 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 shrbqs_as (v4i8 v, unsigned sht) { return __builtin_kvx_shrbqs(v, sht, ".as"); }

// CHECK-LABEL: @shrbqs_r(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i8> @llvm.kvx.shr.v4i8(<4 x i8> [[V:%.*]], i32 [[SHT:%.*]], i32 3)
// CHECK-NEXT:    ret <4 x i8> [[TMP0]]
//
v4i8 shrbqs_r (v4i8 v, unsigned sht) { return __builtin_kvx_shrbqs(v, sht, ".r"); }

// CHECK-LABEL: @shrbvs(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[V:%.*]], <32 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP0]], i32 [[SHT:%.*]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP2]], i32 [[SHT]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP4]], i32 [[SHT]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP6]], i32 [[SHT]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32i8 shrbvs (v32i8 v, unsigned sht) { return __builtin_kvx_shrbvs(v, sht, ""); }

// CHECK-LABEL: @shrbvs_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[V:%.*]], <32 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP0]], i32 [[SHT:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP2]], i32 [[SHT]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP4]], i32 [[SHT]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP6]], i32 [[SHT]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32i8 shrbvs_s (v32i8 v, unsigned sht) { return __builtin_kvx_shrbvs(v, sht, ".a"); }

// CHECK-LABEL: @shrbvs_as(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[V:%.*]], <32 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP0]], i32 [[SHT:%.*]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP2]], i32 [[SHT]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP4]], i32 [[SHT]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP6]], i32 [[SHT]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32i8 shrbvs_as (v32i8 v, unsigned sht) { return __builtin_kvx_shrbvs(v, sht, ".as"); }

// CHECK-LABEL: @shrbvs_r(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[V:%.*]], <32 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP0]], i32 [[SHT:%.*]], i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP2]], i32 [[SHT]], i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP4]], i32 [[SHT]], i32 3)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> undef, <8 x i32> <i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP6]], i32 [[SHT]], i32 3)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i8> [[TMP5]], <8 x i8> [[TMP7]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i8> [[TMP8]], <16 x i8> [[TMP9]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    ret <32 x i8> [[TMP10]]
//
v32i8 shrbvs_r (v32i8 v, unsigned sht) { return __builtin_kvx_shrbvs(v, sht, ".r"); }

// CHECK-LABEL: @shrbxs(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[V:%.*]], <16 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP0]], i32 [[SHT:%.*]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP2]], i32 [[SHT]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16i8 shrbxs (v16i8 v, unsigned sht) { return __builtin_kvx_shrbxs(v, sht, ""); }

// CHECK-LABEL: @shrbxs_s(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[V:%.*]], <16 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP0]], i32 [[SHT:%.*]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP2]], i32 [[SHT]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16i8 shrbxs_s (v16i8 v, unsigned sht) { return __builtin_kvx_shrbxs(v, sht, ".a"); }

// CHECK-LABEL: @shrbxs_as(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[V:%.*]], <16 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP0]], i32 [[SHT:%.*]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP2]], i32 [[SHT]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16i8 shrbxs_as (v16i8 v, unsigned sht) { return __builtin_kvx_shrbxs(v, sht, ".as"); }

// CHECK-LABEL: @shrbxs_r(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[V:%.*]], <16 x i8> undef, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP0]], i32 [[SHT:%.*]], i32 3)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> undef, <8 x i32> <i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <8 x i8> @llvm.kvx.shr.v8i8(<8 x i8> [[TMP2]], i32 [[SHT]], i32 3)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i8> [[TMP1]], <8 x i8> [[TMP3]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i8> [[TMP4]]
//
v16i8 shrbxs_r (v16i8 v, unsigned sht) { return __builtin_kvx_shrbxs(v, sht, ".r"); }
