// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -O2 -triple kvx-kalray-cos -S -emit-llvm -target-cpu kv3-2 -o - -x c %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @stsudp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i64> [[L:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.stsu.i64(i64 [[TMP0]], i64 48879)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i64> [[L]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.stsu.i64(i64 [[TMP2]], i64 -4688547448578183441)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i64> [[TMP4]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP5]]
//
v2i64 stsudp(v2i64 l) {
  v2i64 r = {0xbeef, 0xbeeeeeefbeeeeeef};
  return __builtin_kvx_stsudp(l, r);
}

// CHECK-LABEL: @stsud_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.stsu.i64(i64 [[V:%.*]], i64 3735928559)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long stsud_ri(long v){
  return __builtin_kvx_stsud(v, 0xdeadbeef);
}

// CHECK-LABEL: @stsud_riat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.kvx.stsu.i64(i64 [[V:%.*]], i64 -2401053088876216593)
// CHECK-NEXT:    ret i64 [[TMP0]]
//
long stsud_riat(long v){
  return __builtin_kvx_stsud(v, 0xdeadbeefdeadbeef);
}

// CHECK-LABEL: @stsuw_ri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.kvx.stsu.i32(i32 [[V:%.*]], i32 17)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int stsuw_ri(int v){
  return __builtin_kvx_stsuw(v, 17);
}

// CHECK-LABEL: @stsuhp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.stsu.v2i16(<2 x i16> [[V:%.*]], <2 x i16> [[A:%.*]])
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 stsuhp(v2i16 v, v2i16 a){
  return __builtin_kvx_stsuhp(v, a);
}

// CHECK-LABEL: @stsuhpri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.stsu.v2i16(<2 x i16> [[V:%.*]], <2 x i16> <i16 150, i16 102>)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
v2i16 stsuhpri(v2i16 v){
  v2i16 a = {150, 102};
  return __builtin_kvx_stsuhp(v, a);
}


// CHECK-LABEL: @stsuhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[V:%.*]], <4 x i16> [[A:%.*]])
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 stsuhq(v4i16 v, v4i16 a){
  return __builtin_kvx_stsuhq(v, a);
}

// CHECK-LABEL: @stsuhqri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[V:%.*]], <4 x i16> <i16 15, i16 12, i16 0, i16 0>)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 stsuhqri(v4i16 v){
  v4i16 a = {15, 12, 0, 0};
  return __builtin_kvx_stsuhq(v, a);
}

// CHECK-LABEL: @stsuhqriat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[V:%.*]], <4 x i16> <i16 15, i16 12, i16 15, i16 12>)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
v4i16 stsuhqriat(v4i16 v){
  v4i16 a = {15, 12, 15, 12};
  return __builtin_kvx_stsuhq(v, a);
}

// CHECK-LABEL: @stsuho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[V:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i16> [[A:%.*]], <8 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[A]], <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP6]]
//
v8i16 stsuho(v8i16 v, v8i16 a){
  return __builtin_kvx_stsuho(v, a);
}

// CHECK-LABEL: @stsuhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[V:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <16 x i16> [[A:%.*]], <16 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP0]], <4 x i16> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP3]], <4 x i16> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP6]], <4 x i16> [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[A]], <16 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP9]], <4 x i16> [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x i16> [[TMP2]], <4 x i16> [[TMP5]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x i16> [[TMP8]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <8 x i16> [[TMP12]], <8 x i16> [[TMP13]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP14]]
//
v16i16 stsuhx(v16i16 v, v16i16 a){
  return __builtin_kvx_stsuhx(v, a);
}

// CHECK-LABEL: @stsuhv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <32 x i16>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[A:%.*]] = load <32 x i16>, ptr [[TMP1:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <32 x i16> [[A]], <32 x i16> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP2]], <4 x i16> [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i16> [[A]], <32 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP5]], <4 x i16> [[TMP6]])
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <32 x i16> [[A]], <32 x i16> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP8]], <4 x i16> [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <32 x i16> [[A]], <32 x i16> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP13:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP11]], <4 x i16> [[TMP12]])
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 16, i32 17, i32 18, i32 19>
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <32 x i16> [[A]], <32 x i16> poison, <4 x i32> <i32 16, i32 17, i32 18, i32 19>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP14]], <4 x i16> [[TMP15]])
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <32 x i16> [[A]], <32 x i16> poison, <4 x i32> <i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP19:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP17]], <4 x i16> [[TMP18]])
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 24, i32 25, i32 26, i32 27>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <32 x i16> [[A]], <32 x i16> poison, <4 x i32> <i32 24, i32 25, i32 26, i32 27>
// CHECK-NEXT:    [[TMP22:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP20]], <4 x i16> [[TMP21]])
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <32 x i16> [[V]], <32 x i16> poison, <4 x i32> <i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <32 x i16> [[A]], <32 x i16> poison, <4 x i32> <i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP25:%.*]] = tail call <4 x i16> @llvm.kvx.stsu.v4i16(<4 x i16> [[TMP23]], <4 x i16> [[TMP24]])
// CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <4 x i16> [[TMP4]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <4 x i16> [[TMP10]], <4 x i16> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <4 x i16> [[TMP16]], <4 x i16> [[TMP19]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <4 x i16> [[TMP22]], <4 x i16> [[TMP25]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP30:%.*]] = shufflevector <8 x i16> [[TMP26]], <8 x i16> [[TMP27]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP31:%.*]] = shufflevector <8 x i16> [[TMP28]], <8 x i16> [[TMP29]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP32:%.*]] = shufflevector <16 x i16> [[TMP30]], <16 x i16> [[TMP31]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    store <32 x i16> [[TMP32]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
v32i16 stsuhv(v32i16 v, v32i16 a){
  return __builtin_kvx_stsuhv(v, a);
}

// CHECK-LABEL: @stsuwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[V:%.*]], <2 x i32> [[A:%.*]])
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 stsuwp(v2i32 v, v2i32 a){
  return __builtin_kvx_stsuwp(v, a);
}

// CHECK-LABEL: @stsuwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i32> [[V:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <4 x i32> [[A:%.*]], <4 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <4 x i32> [[V]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i32> [[A]], <4 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP6]]
//
v4i32 stsuwq(v4i32 v, v4i32 a){
  return __builtin_kvx_stsuwq(v, a);
}

// CHECK-LABEL: @stsuwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i32> [[V:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <8 x i32> [[A:%.*]], <8 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP0]], <2 x i32> [[TMP1]])
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP3]], <2 x i32> [[TMP4]])
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP7:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP8:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP6]], <2 x i32> [[TMP7]])
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x i32> [[V]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i32> [[A]], <8 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP9]], <2 x i32> [[TMP10]])
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <2 x i32> [[TMP2]], <2 x i32> [[TMP5]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <2 x i32> [[TMP8]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i32> [[TMP12]], <4 x i32> [[TMP13]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP14]]
//
v8i32 stsuwo(v8i32 v, v8i32 a){
  return __builtin_kvx_stsuwo(v, a);
}

// CHECK-LABEL: @stsuwx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V:%.*]] = load <16 x i32>, ptr [[TMP0:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[A:%.*]] = load <16 x i32>, ptr [[TMP1:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP4:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP2]], <2 x i32> [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP5]], <2 x i32> [[TMP6]])
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP10:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP8]], <2 x i32> [[TMP9]])
// CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP13:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP11]], <2 x i32> [[TMP12]])
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 8, i32 9>
// CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <2 x i32> <i32 8, i32 9>
// CHECK-NEXT:    [[TMP16:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP14]], <2 x i32> [[TMP15]])
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 10, i32 11>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <2 x i32> <i32 10, i32 11>
// CHECK-NEXT:    [[TMP19:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP17]], <2 x i32> [[TMP18]])
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 12, i32 13>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <2 x i32> <i32 12, i32 13>
// CHECK-NEXT:    [[TMP22:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP20]], <2 x i32> [[TMP21]])
// CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i32> [[V]], <16 x i32> poison, <2 x i32> <i32 14, i32 15>
// CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i32> [[A]], <16 x i32> poison, <2 x i32> <i32 14, i32 15>
// CHECK-NEXT:    [[TMP25:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[TMP23]], <2 x i32> [[TMP24]])
// CHECK-NEXT:    [[TMP26:%.*]] = shufflevector <2 x i32> [[TMP4]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP27:%.*]] = shufflevector <2 x i32> [[TMP10]], <2 x i32> [[TMP13]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP28:%.*]] = shufflevector <2 x i32> [[TMP16]], <2 x i32> [[TMP19]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP29:%.*]] = shufflevector <2 x i32> [[TMP22]], <2 x i32> [[TMP25]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP30:%.*]] = shufflevector <4 x i32> [[TMP26]], <4 x i32> [[TMP27]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP31:%.*]] = shufflevector <4 x i32> [[TMP28]], <4 x i32> [[TMP29]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP32:%.*]] = shufflevector <8 x i32> [[TMP30]], <8 x i32> [[TMP31]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    store <16 x i32> [[TMP32]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
v16i32 stsuwx(v16i32 v, v16i32 a){
  return __builtin_kvx_stsuwx(v, a);
}

// CHECK-LABEL: @stsuwpri(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[V:%.*]], <2 x i32> <i32 999, i32 0>)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 stsuwpri(v2i32 v){
  v2i32 a = {999, 0};
  return __builtin_kvx_stsuwp(v, a);
}

// CHECK-LABEL: @stsuwpriat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.stsu.v2i32(<2 x i32> [[V:%.*]], <2 x i32> <i32 999, i32 999>)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
v2i32 stsuwpriat(v2i32 v){
  v2i32 a = {999, 999};
  return __builtin_kvx_stsuwp(v, a);
}
