// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -O2 -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: @errop(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.kvx.errop()
// CHECK-NEXT:    unreachable
//
void errop(void) {
  __builtin_kvx_errop();
}

// CHECK-LABEL: @trap(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.trap()
// CHECK-NEXT:    unreachable
//
void trap(void) {
  __builtin_trap();
}

// CHECK-LABEL: @rfe(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call void @llvm.kvx.rfe()
// CHECK-NEXT:    unreachable
//
void rfe(void) {
  __builtin_kvx_rfe();
}
