// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -O2 -triple kvx-kalray-cos -emit-llvm -target-cpu kv3-1 -o - -x c %s | FileCheck %s

typedef char char8 __attribute__ ((vector_size (sizeof(char) * 8)));
typedef short short4 __attribute__ ((vector_size (sizeof(short) * 4)));
typedef int int2 __attribute__ ((vector_size (sizeof(int) * 2)));

// CHECK-LABEL: @sxlbhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.sxlbhq(<8 x i8> [[V:%.*]])
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
short4 sxlbhq(char8 v){
  return __builtin_kvx_sxlbhq(v);
}

// CHECK-LABEL: @sxmbhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.sxmbhq(<8 x i8> [[V:%.*]])
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
short4 sxmbhq(char8 v){
  return __builtin_kvx_sxmbhq(v);
}

// CHECK-LABEL: @sxlhwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.sxlhwp(<4 x i16> [[V:%.*]])
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
int2 sxlhwp(short4 v){
  return __builtin_kvx_sxlhwp(v);
}

// CHECK-LABEL: @sxmhwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.sxmhwp(<4 x i16> [[V:%.*]])
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
int2 sxmhwp(short4 v){
  return __builtin_kvx_sxmhwp(v);
}
