// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

#include "vector-types.h"

// CHECK-LABEL: @fwidenhw(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = insertelement <4 x half> undef, half [[X:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call float @llvm.kvx.fwidenlhw(<4 x half> [[TMP0]], i32 1)
// CHECK-NEXT:    ret float [[TMP1]]
//
float fwidenhw(_Float16 x){
  return __builtin_kvx_fwidenhw(x, ".s");
}

// CHECK-LABEL: @fwidenhwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x float> @llvm.kvx.fwidenlhwp(<4 x half> [[V:%.*]], i32 1)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x float> @llvm.kvx.fwidenmhwp(<4 x half> [[V]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <2 x float> [[TMP0]], <2 x float> [[TMP1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
v4f32 fwidenhwq(v4f16 v){
  return __builtin_kvx_fwidenhwq(v, ".s");
}

// CHECK-LABEL: @fwidenhwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x half> [[V:%.*]], <8 x half> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x float> @llvm.kvx.fwidenlhwp(<4 x half> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = tail call <2 x float> @llvm.kvx.fwidenmhwp(<4 x half> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <2 x float> [[TMP1]], <2 x float> [[TMP2]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 undef, i32 undef, i32 undef, i32 undef>
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x half> [[V]], <8 x half> undef, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x float> @llvm.kvx.fwidenlhwp(<4 x half> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <2 x float> [[TMP5]], <2 x float> undef, <8 x i32> <i32 0, i32 1, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x float> @llvm.kvx.fwidenmhwp(<4 x half> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x float> [[TMP7]], <2 x float> undef, <8 x i32> <i32 0, i32 1, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef, i32 undef>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <8 x float> [[TMP3]], <8 x float> [[TMP6]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 undef, i32 undef>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x float> [[TMP9]], <8 x float> [[TMP8]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 8, i32 9>
// CHECK-NEXT:    ret <8 x float> [[TMP10]]
//
v8f32 fwidenhwo(v8f16 v){
  return __builtin_kvx_fwidenhwo(v, ".s");
}

// CHECK-LABEL: @fwidenwd(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = insertelement <2 x float> undef, float [[X:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call double @llvm.kvx.fwidenlwd(<2 x float> [[TMP0]], i32 1)
// CHECK-NEXT:    ret double [[TMP1]]
//
double fwidenwd(float x){
  return __builtin_kvx_fwidenwd(x, ".s");
}

// CHECK-LABEL: @fwidenwdp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call double @llvm.kvx.fwidenlwd(<2 x float> [[V:%.*]], i32 1)
// CHECK-NEXT:    [[TMP1:%.*]] = tail call double @llvm.kvx.fwidenmwd(<2 x float> [[V]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = insertelement <2 x double> undef, double [[TMP0]], i64 0
// CHECK-NEXT:    [[TMP3:%.*]] = insertelement <2 x double> [[TMP2]], double [[TMP1]], i64 1
// CHECK-NEXT:    ret <2 x double> [[TMP3]]
//
v2f64 fwidenwdp(v2f32 v){
  return __builtin_kvx_fwidenwdp(v, ".s");
}

// CHECK-LABEL: @fwidenwdq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x float> [[V:%.*]], <4 x float> undef, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call double @llvm.kvx.fwidenlwd(<2 x float> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = tail call double @llvm.kvx.fwidenmwd(<2 x float> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x double> undef, double [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <4 x double> [[TMP3]], double [[TMP2]], i64 1
// CHECK-NEXT:    [[TMP5:%.*]] = shufflevector <4 x float> [[V]], <4 x float> undef, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP6:%.*]] = tail call double @llvm.kvx.fwidenlwd(<2 x float> [[TMP5]], i32 1)
// CHECK-NEXT:    [[TMP7:%.*]] = tail call double @llvm.kvx.fwidenmwd(<2 x float> [[TMP5]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x double> [[TMP4]], double [[TMP6]], i64 2
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x double> [[TMP8]], double [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x double> [[TMP9]]
//
v4f64 fwidenwdq(v4f32 v){
  return __builtin_kvx_fwidenwdq(v, ".s");
}
