// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -S -O2 -emit-llvm -o - %s | FileCheck %s

typedef char V16c __attribute__((vector_size(sizeof(char) * 16)));
typedef int V16i __attribute__((vector_size(sizeof(int) * 16)));
typedef short V16s __attribute__((vector_size(sizeof(short) * 16)));
typedef char V2c __attribute__((vector_size(sizeof(char) * 2)));
typedef int V2i __attribute__((vector_size(sizeof(int) * 2)));
typedef long long V2Oi __attribute__((vector_size(sizeof(long) * 2)));
typedef short V2s __attribute__((vector_size(sizeof(short) * 2)));
typedef short V2s __attribute__((vector_size(sizeof(short) * 2)));
typedef char V32c __attribute__((vector_size(sizeof(char) * 32)));
typedef short V32s __attribute__((vector_size(sizeof(short) * 32)));
typedef char V4c __attribute__((vector_size(sizeof(char) * 4)));
typedef int V4i __attribute__((vector_size(sizeof(int) * 4)));
typedef long long V4Oi __attribute__((vector_size(sizeof(long) * 4)));
typedef short V4s __attribute__((vector_size(sizeof(short) * 4)));
typedef char V8c __attribute__((vector_size(sizeof(char) * 8)));
typedef int V8i __attribute__((vector_size(sizeof(int) * 8)));
typedef long long V8Oi __attribute__((vector_size(sizeof(long) * 8)));
typedef short V8s __attribute__((vector_size(sizeof(short) * 8)));

// CHECK-LABEL: @widenbho(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i8> [[V:%.*]], <8 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i8> [[V]], <8 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
V8s widenbho(V8c v) { return __builtin_kvx_widenbho(v, ""); }

// CHECK-LABEL: @widenbho_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i8> [[V:%.*]], <8 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i8> [[V]], <8 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
V8s widenbho_z(V8c v) { return __builtin_kvx_widenbho(v, ".z"); }

// CHECK-LABEL: @widenbho_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i8> [[V:%.*]], <8 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i8> [[V]], <8 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i16> [[TMP4]]
//
V8s widenbho_q(V8c v) { return __builtin_kvx_widenbho(v, ".q"); }

// CHECK-LABEL: @widenbhp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.widenint.v2i16(<2 x i8> [[V:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
V2s widenbhp(V2c v) { return __builtin_kvx_widenbhp(v, ""); }

// CHECK-LABEL: @widenbhp_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.widenint.v2i16(<2 x i8> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
V2s widenbhp_z(V2c v) { return __builtin_kvx_widenbhp(v, ".z"); }

// CHECK-LABEL: @widenbhp_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i16> @llvm.kvx.widenint.v2i16(<2 x i8> [[V:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i16> [[TMP0]]
//
V2s widenbhp_q(V2c v) { return __builtin_kvx_widenbhp(v, ".q"); }

// CHECK-LABEL: @widenbhq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[V:%.*]], i32 0)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
V4s widenbhq(V4c v) { return __builtin_kvx_widenbhq(v, ""); }

// CHECK-LABEL: @widenbhq_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
V4s widenbhq_z(V4c v) { return __builtin_kvx_widenbhq(v, ".z"); }

// CHECK-LABEL: @widenbhq_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[V:%.*]], i32 2)
// CHECK-NEXT:    ret <4 x i16> [[TMP0]]
//
V4s widenbhq_q(V4c v) { return __builtin_kvx_widenbhq(v, ".q"); }

// CHECK-LABEL: @widenbhv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[V:%.*]], <32 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 16, i32 17, i32 18, i32 19>
// CHECK-NEXT:    [[TMP9:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP8]], i32 0)
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 24, i32 25, i32 26, i32 27>
// CHECK-NEXT:    [[TMP13:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP12]], i32 0)
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP15:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP14]], i32 0)
// CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <4 x i16> [[TMP9]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <4 x i16> [[TMP13]], <4 x i16> [[TMP15]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <8 x i16> [[TMP16]], <8 x i16> [[TMP17]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i16> [[TMP18]], <8 x i16> [[TMP19]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i16> [[TMP20]], <16 x i16> [[TMP21]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    store <32 x i16> [[TMP22]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    ret void
//
V32s widenbhv(V32c v) { return __builtin_kvx_widenbhv(v, ""); }

// CHECK-LABEL: @widenbhv_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[V:%.*]], <32 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 16, i32 17, i32 18, i32 19>
// CHECK-NEXT:    [[TMP9:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP8]], i32 1)
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 24, i32 25, i32 26, i32 27>
// CHECK-NEXT:    [[TMP13:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP12]], i32 1)
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP15:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP14]], i32 1)
// CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <4 x i16> [[TMP9]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <4 x i16> [[TMP13]], <4 x i16> [[TMP15]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <8 x i16> [[TMP16]], <8 x i16> [[TMP17]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i16> [[TMP18]], <8 x i16> [[TMP19]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i16> [[TMP20]], <16 x i16> [[TMP21]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    store <32 x i16> [[TMP22]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
V32s widenbhv_z(V32c v) { return __builtin_kvx_widenbhv(v, ".z"); }

// CHECK-LABEL: @widenbhv_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <32 x i8> [[V:%.*]], <32 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 16, i32 17, i32 18, i32 19>
// CHECK-NEXT:    [[TMP9:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP8]], i32 2)
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 20, i32 21, i32 22, i32 23>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 24, i32 25, i32 26, i32 27>
// CHECK-NEXT:    [[TMP13:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP12]], i32 2)
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <32 x i8> [[V]], <32 x i8> poison, <4 x i32> <i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    [[TMP15:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP14]], i32 2)
// CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <4 x i16> [[TMP9]], <4 x i16> [[TMP11]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <4 x i16> [[TMP13]], <4 x i16> [[TMP15]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <8 x i16> [[TMP16]], <8 x i16> [[TMP17]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i16> [[TMP18]], <8 x i16> [[TMP19]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <16 x i16> [[TMP20]], <16 x i16> [[TMP21]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
// CHECK-NEXT:    store <32 x i16> [[TMP22]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
V32s widenbhv_q(V32c v) { return __builtin_kvx_widenbhv(v, ".q"); }

// CHECK-LABEL: @widenbhx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[V:%.*]], <16 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
V16s widenbhx(V16c v) { return __builtin_kvx_widenbhx(v, ""); }

// CHECK-LABEL: @widenbhx_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[V:%.*]], <16 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
V16s widenbhx_z(V16c v) { return __builtin_kvx_widenbhx(v, ".z"); }

// CHECK-LABEL: @widenbhx_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i8> [[V:%.*]], <16 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <4 x i32> <i32 8, i32 9, i32 10, i32 11>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i8> [[V]], <16 x i8> poison, <4 x i32> <i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <4 x i16> @llvm.kvx.widenint.v4i16(<4 x i8> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <4 x i16> [[TMP1]], <4 x i16> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <4 x i16> [[TMP5]], <4 x i16> [[TMP7]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <8 x i16> [[TMP8]], <8 x i16> [[TMP9]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    ret <16 x i16> [[TMP10]]
//
V16s widenbhx_q(V16c v) { return __builtin_kvx_widenbhx(v, ".q"); }

// CHECK-LABEL: @widenhwo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[V:%.*]], <8 x i16> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
V8i widenhwo(V8s v) { return __builtin_kvx_widenhwo(v, ""); }

// CHECK-LABEL: @widenhwo_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[V:%.*]], <8 x i16> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
V8i widenhwo_z(V8s v) { return __builtin_kvx_widenhwo(v, ".z"); }

// CHECK-LABEL: @widenhwo_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <8 x i16> [[V:%.*]], <8 x i16> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <8 x i16> [[V]], <8 x i16> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <4 x i32> [[TMP8]], <4 x i32> [[TMP9]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    ret <8 x i32> [[TMP10]]
//
V8i widenhwo_q(V8s v) { return __builtin_kvx_widenhwo(v, ".q"); }

// CHECK-LABEL: @widenhwp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[V:%.*]], i32 0)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i widenhwp(V2s v) { return __builtin_kvx_widenhwp(v, ""); }

// CHECK-LABEL: @widenhwp_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[V:%.*]], i32 1)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i widenhwp_z(V2s v) { return __builtin_kvx_widenhwp(v, ".z"); }

// CHECK-LABEL: @widenhwp_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[V:%.*]], i32 2)
// CHECK-NEXT:    ret <2 x i32> [[TMP0]]
//
V2i widenhwp_q(V2s v) { return __builtin_kvx_widenhwp(v, ".q"); }

// CHECK-LABEL: @widenhwq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i16> [[V:%.*]], <4 x i16> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i16> [[V]], <4 x i16> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
V4i widenhwq(V4s v) { return __builtin_kvx_widenhwq(v, ""); }

// CHECK-LABEL: @widenhwq_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i16> [[V:%.*]], <4 x i16> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i16> [[V]], <4 x i16> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
V4i widenhwq_z(V4s v) { return __builtin_kvx_widenhwq(v, ".z"); }

// CHECK-LABEL: @widenhwq_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <4 x i16> [[V:%.*]], <4 x i16> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <4 x i16> [[V]], <4 x i16> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
V4i widenhwq_q(V4s v) { return __builtin_kvx_widenhwq(v, ".q"); }

// CHECK-LABEL: @widenhwx(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[V:%.*]], <16 x i16> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 8, i32 9>
// CHECK-NEXT:    [[TMP9:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP8]], i32 0)
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 10, i32 11>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 12, i32 13>
// CHECK-NEXT:    [[TMP13:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP12]], i32 0)
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 14, i32 15>
// CHECK-NEXT:    [[TMP15:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP14]], i32 0)
// CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x i32> [[TMP9]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <2 x i32> [[TMP13]], <2 x i32> [[TMP15]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <4 x i32> [[TMP16]], <4 x i32> [[TMP17]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <4 x i32> [[TMP18]], <4 x i32> [[TMP19]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <8 x i32> [[TMP20]], <8 x i32> [[TMP21]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    store <16 x i32> [[TMP22]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
V16i widenhwx(V16s v) { return __builtin_kvx_widenhwx(v, ""); }

// CHECK-LABEL: @widenhwx_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[V:%.*]], <16 x i16> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 8, i32 9>
// CHECK-NEXT:    [[TMP9:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP8]], i32 1)
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 10, i32 11>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 12, i32 13>
// CHECK-NEXT:    [[TMP13:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP12]], i32 1)
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 14, i32 15>
// CHECK-NEXT:    [[TMP15:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP14]], i32 1)
// CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x i32> [[TMP9]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <2 x i32> [[TMP13]], <2 x i32> [[TMP15]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <4 x i32> [[TMP16]], <4 x i32> [[TMP17]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <4 x i32> [[TMP18]], <4 x i32> [[TMP19]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <8 x i32> [[TMP20]], <8 x i32> [[TMP21]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    store <16 x i32> [[TMP22]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
V16i widenhwx_z(V16s v) { return __builtin_kvx_widenhwx(v, ".z"); }

// CHECK-LABEL: @widenhwx_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <16 x i16> [[V:%.*]], <16 x i16> poison, <2 x i32> <i32 0, i32 1>
// CHECK-NEXT:    [[TMP1:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 2, i32 3>
// CHECK-NEXT:    [[TMP3:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 4, i32 5>
// CHECK-NEXT:    [[TMP5:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 6, i32 7>
// CHECK-NEXT:    [[TMP7:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 8, i32 9>
// CHECK-NEXT:    [[TMP9:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP8]], i32 2)
// CHECK-NEXT:    [[TMP10:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 10, i32 11>
// CHECK-NEXT:    [[TMP11:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 12, i32 13>
// CHECK-NEXT:    [[TMP13:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP12]], i32 2)
// CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <16 x i16> [[V]], <16 x i16> poison, <2 x i32> <i32 14, i32 15>
// CHECK-NEXT:    [[TMP15:%.*]] = tail call <2 x i32> @llvm.kvx.widenint.v2i32(<2 x i16> [[TMP14]], i32 2)
// CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <2 x i32> [[TMP1]], <2 x i32> [[TMP3]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <2 x i32> [[TMP5]], <2 x i32> [[TMP7]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <2 x i32> [[TMP9]], <2 x i32> [[TMP11]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <2 x i32> [[TMP13]], <2 x i32> [[TMP15]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <4 x i32> [[TMP16]], <4 x i32> [[TMP17]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <4 x i32> [[TMP18]], <4 x i32> [[TMP19]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
// CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <8 x i32> [[TMP20]], <8 x i32> [[TMP21]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
// CHECK-NEXT:    store <16 x i32> [[TMP22]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
V16i widenhwx_q(V16s v) { return __builtin_kvx_widenhwx(v, ".q"); }

// CHECK-LABEL: @widenwdo(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <8 x i32> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <8 x i32> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <8 x i32> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <8 x i32> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = extractelement <8 x i32> [[V]], i64 4
// CHECK-NEXT:    [[TMP9:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP8]], i32 0)
// CHECK-NEXT:    [[TMP10:%.*]] = extractelement <8 x i32> [[V]], i64 5
// CHECK-NEXT:    [[TMP11:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP10]], i32 0)
// CHECK-NEXT:    [[TMP12:%.*]] = extractelement <8 x i32> [[V]], i64 6
// CHECK-NEXT:    [[TMP13:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP12]], i32 0)
// CHECK-NEXT:    [[TMP14:%.*]] = extractelement <8 x i32> [[V]], i64 7
// CHECK-NEXT:    [[TMP15:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP14]], i32 0)
// CHECK-NEXT:    [[TMP16:%.*]] = insertelement <8 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP17:%.*]] = insertelement <8 x i64> [[TMP16]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x i64> [[TMP17]], i64 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP19:%.*]] = insertelement <8 x i64> [[TMP18]], i64 [[TMP7]], i64 3
// CHECK-NEXT:    [[TMP20:%.*]] = insertelement <8 x i64> [[TMP19]], i64 [[TMP9]], i64 4
// CHECK-NEXT:    [[TMP21:%.*]] = insertelement <8 x i64> [[TMP20]], i64 [[TMP11]], i64 5
// CHECK-NEXT:    [[TMP22:%.*]] = insertelement <8 x i64> [[TMP21]], i64 [[TMP13]], i64 6
// CHECK-NEXT:    [[TMP23:%.*]] = insertelement <8 x i64> [[TMP22]], i64 [[TMP15]], i64 7
// CHECK-NEXT:    store <8 x i64> [[TMP23]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
V8Oi widenwdo(V8i v) { return __builtin_kvx_widenwdo(v, ""); }

// CHECK-LABEL: @widenwdo_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <8 x i32> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <8 x i32> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <8 x i32> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <8 x i32> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = extractelement <8 x i32> [[V]], i64 4
// CHECK-NEXT:    [[TMP9:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP8]], i32 1)
// CHECK-NEXT:    [[TMP10:%.*]] = extractelement <8 x i32> [[V]], i64 5
// CHECK-NEXT:    [[TMP11:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP10]], i32 1)
// CHECK-NEXT:    [[TMP12:%.*]] = extractelement <8 x i32> [[V]], i64 6
// CHECK-NEXT:    [[TMP13:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP12]], i32 1)
// CHECK-NEXT:    [[TMP14:%.*]] = extractelement <8 x i32> [[V]], i64 7
// CHECK-NEXT:    [[TMP15:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP14]], i32 1)
// CHECK-NEXT:    [[TMP16:%.*]] = insertelement <8 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP17:%.*]] = insertelement <8 x i64> [[TMP16]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x i64> [[TMP17]], i64 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP19:%.*]] = insertelement <8 x i64> [[TMP18]], i64 [[TMP7]], i64 3
// CHECK-NEXT:    [[TMP20:%.*]] = insertelement <8 x i64> [[TMP19]], i64 [[TMP9]], i64 4
// CHECK-NEXT:    [[TMP21:%.*]] = insertelement <8 x i64> [[TMP20]], i64 [[TMP11]], i64 5
// CHECK-NEXT:    [[TMP22:%.*]] = insertelement <8 x i64> [[TMP21]], i64 [[TMP13]], i64 6
// CHECK-NEXT:    [[TMP23:%.*]] = insertelement <8 x i64> [[TMP22]], i64 [[TMP15]], i64 7
// CHECK-NEXT:    store <8 x i64> [[TMP23]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
V8Oi widenwdo_z(V8i v) { return __builtin_kvx_widenwdo(v, ".z"); }

// CHECK-LABEL: @widenwdo_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <8 x i32> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <8 x i32> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <8 x i32> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <8 x i32> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = extractelement <8 x i32> [[V]], i64 4
// CHECK-NEXT:    [[TMP9:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP8]], i32 2)
// CHECK-NEXT:    [[TMP10:%.*]] = extractelement <8 x i32> [[V]], i64 5
// CHECK-NEXT:    [[TMP11:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP10]], i32 2)
// CHECK-NEXT:    [[TMP12:%.*]] = extractelement <8 x i32> [[V]], i64 6
// CHECK-NEXT:    [[TMP13:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP12]], i32 2)
// CHECK-NEXT:    [[TMP14:%.*]] = extractelement <8 x i32> [[V]], i64 7
// CHECK-NEXT:    [[TMP15:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP14]], i32 2)
// CHECK-NEXT:    [[TMP16:%.*]] = insertelement <8 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP17:%.*]] = insertelement <8 x i64> [[TMP16]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x i64> [[TMP17]], i64 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP19:%.*]] = insertelement <8 x i64> [[TMP18]], i64 [[TMP7]], i64 3
// CHECK-NEXT:    [[TMP20:%.*]] = insertelement <8 x i64> [[TMP19]], i64 [[TMP9]], i64 4
// CHECK-NEXT:    [[TMP21:%.*]] = insertelement <8 x i64> [[TMP20]], i64 [[TMP11]], i64 5
// CHECK-NEXT:    [[TMP22:%.*]] = insertelement <8 x i64> [[TMP21]], i64 [[TMP13]], i64 6
// CHECK-NEXT:    [[TMP23:%.*]] = insertelement <8 x i64> [[TMP22]], i64 [[TMP15]], i64 7
// CHECK-NEXT:    store <8 x i64> [[TMP23]], ptr [[AGG_RESULT:%.*]], align 32, !tbaa [[TBAA2]]
// CHECK-NEXT:    ret void
//
V8Oi widenwdo_q(V8i v) { return __builtin_kvx_widenwdo(v, ".q"); }

// CHECK-LABEL: @widenwdp(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i32> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i32> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i64> [[TMP4]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP5]]
//
V2Oi widenwdp(V2i v) { return __builtin_kvx_widenwdp(v, ""); }

// CHECK-LABEL: @widenwdp_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i32> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i32> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i64> [[TMP4]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP5]]
//
V2Oi widenwdp_z(V2i v) { return __builtin_kvx_widenwdp(v, ".z"); }

// CHECK-LABEL: @widenwdp_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <2 x i32> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <2 x i32> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = insertelement <2 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP5:%.*]] = insertelement <2 x i64> [[TMP4]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    ret <2 x i64> [[TMP5]]
//
V2Oi widenwdp_q(V2i v) { return __builtin_kvx_widenwdp(v, ".q"); }

// CHECK-LABEL: @widenwdq(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i32> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP0]], i32 0)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i32> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP2]], i32 0)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i32> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP4]], i32 0)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i32> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP6]], i32 0)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i64> [[TMP8]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i64> [[TMP9]], i64 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i64> [[TMP10]], i64 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i64> [[TMP11]]
//
V4Oi widenwdq(V4i v) { return __builtin_kvx_widenwdq(v, ""); }

// CHECK-LABEL: @widenwdq_z(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i32> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP0]], i32 1)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i32> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP2]], i32 1)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i32> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP4]], i32 1)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i32> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP6]], i32 1)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i64> [[TMP8]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i64> [[TMP9]], i64 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i64> [[TMP10]], i64 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i64> [[TMP11]]
//
V4Oi widenwdq_z(V4i v) { return __builtin_kvx_widenwdq(v, ".z"); }

// CHECK-LABEL: @widenwdq_q(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = extractelement <4 x i32> [[V:%.*]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP0]], i32 2)
// CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i32> [[V]], i64 1
// CHECK-NEXT:    [[TMP3:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP2]], i32 2)
// CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i32> [[V]], i64 2
// CHECK-NEXT:    [[TMP5:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP4]], i32 2)
// CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x i32> [[V]], i64 3
// CHECK-NEXT:    [[TMP7:%.*]] = tail call i64 @llvm.kvx.widenint.i64(i32 [[TMP6]], i32 2)
// CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x i64> undef, i64 [[TMP1]], i64 0
// CHECK-NEXT:    [[TMP9:%.*]] = insertelement <4 x i64> [[TMP8]], i64 [[TMP3]], i64 1
// CHECK-NEXT:    [[TMP10:%.*]] = insertelement <4 x i64> [[TMP9]], i64 [[TMP5]], i64 2
// CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i64> [[TMP10]], i64 [[TMP7]], i64 3
// CHECK-NEXT:    ret <4 x i64> [[TMP11]]
//
V4Oi widenwdq_q(V4i v) { return __builtin_kvx_widenwdq(v, ".q"); }
