// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-1 -O2 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -O2 -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: @high256(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <256 x i1> @llvm.kvx.high.v256i1(<512 x i1> zeroinitializer)
// CHECK-NEXT:    store <256 x i1> [[TMP0]], ptr [[R:%.*]], align 32, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    ret void
//
void high256(__kvx_x256 *r) {
    __kvx_x512 v = __builtin_kvx_xzero512();
    *r = __builtin_kvx_xhigh256(v);
}

// CHECK-LABEL: @high512(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <512 x i1> @llvm.kvx.high.v512i1(<1024 x i1> zeroinitializer)
// CHECK-NEXT:    store <512 x i1> [[TMP0]], ptr [[R:%.*]], align 32, !tbaa [[TBAA6:![0-9]+]]
// CHECK-NEXT:    ret void
//
void high512(__kvx_x512 *r) {
    __kvx_x1024 v =__builtin_kvx_xzero1024();
    *r = __builtin_kvx_xhigh512(v);
}

// CHECK-LABEL: @high1024(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <1024 x i1> @llvm.kvx.high.v1024i1(<2048 x i1> zeroinitializer)
// CHECK-NEXT:    store <1024 x i1> [[TMP0]], ptr [[R:%.*]], align 32, !tbaa [[TBAA8:![0-9]+]]
// CHECK-NEXT:    ret void
//
void high1024(__kvx_x1024 *r) {
    __kvx_x2048 v =__builtin_kvx_xzero2048();
    *r = __builtin_kvx_xhigh1024(v);
}


// CHECK-LABEL: @xhigh2048(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call <2048 x i1> @llvm.kvx.high.v2048i1(<4096 x i1> zeroinitializer)
// CHECK-NEXT:    store <2048 x i1> [[TMP0]], ptr [[R:%.*]], align 32, !tbaa [[TBAA10:![0-9]+]]
// CHECK-NEXT:    ret void
//
void xhigh2048(__kvx_x2048 *r) {
    __kvx_x4096 v =__builtin_kvx_xzero4096();
    *r = __builtin_kvx_xhigh2048(v);
}
