// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-1 -S -O0 -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple kvx-kalray-cos -target-cpu kv3-2 -S -O0 -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: @xundef1024(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[V:%.*]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    store <1024 x i1> undef, ptr [[TMP0]], align 32
// CHECK-NEXT:    ret void
//
void xundef1024(__kvx_x1024 *v) { *v = __builtin_kvx_xundef1024(); }

// CHECK-LABEL: @xundef2048(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[V:%.*]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    store <2048 x i1> undef, ptr [[TMP0]], align 32
// CHECK-NEXT:    ret void
//
void xundef2048(__kvx_x2048 *v) { *v = __builtin_kvx_xundef2048(); }

// CHECK-LABEL: @xundef256(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[V:%.*]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    store <256 x i1> undef, ptr [[TMP0]], align 32
// CHECK-NEXT:    ret void
//
void xundef256(__kvx_x256 *v) { *v = __builtin_kvx_xundef256(); }

// CHECK-LABEL: @xundef4096(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[V:%.*]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    store <4096 x i1> undef, ptr [[TMP0]], align 32
// CHECK-NEXT:    ret void
//
void xundef4096(__kvx_x4096 *v) { *v = __builtin_kvx_xundef4096(); }

// CHECK-LABEL: @xundef512(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[V:%.*]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    store <512 x i1> undef, ptr [[TMP0]], align 32
// CHECK-NEXT:    ret void
//
void xundef512(__kvx_x512 *v) { *v = __builtin_kvx_xundef512(); }
